datenanfragen/data

companies/brooksrunning.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_brooksrunning_1666518357980%2Fcompanies%2Fbrooksrunning.json )**
=> Add 'Brooks Sports, B.V.' (community contribution)

companies/crypto.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_crypto_1655570488647%2Fcompanies%2Fcrypto.json )**
=> Add 'crypto.com' (community contribution)

companies/growbots.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_growbots_1653979672471%2Fcompanies%2Fgrowbots.json )**
=> Add 'Growbots Inc.' (community contribution)

companies/testingtime.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_testingtime_1655033454012%2Fcompanies%2Ftestingtime.json )**
=> Add 'Testingtime' (community contribution)

companies/digital-dialog-lab.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_digital-dialog-lab_1655657007264%2Fcompanies%2Fdigital-dialog-lab.json )**
=> Add 'Digital Dialog Lab GmbH' (community contribution)

companies/nodeeps.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_nodeeps_1666368810685%2Fcompanies%2Fnodeeps.json )**
=> Add 'Nodeeps - corporate hosting & service' (community contribution)

companies/sovendus-se.json, companies/sovendus.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_sovendus_1666305709478%2Fcompanies%2Fsovendus.json )**
=> Update 'Sovendus GmbH' (community contribution)

companies/skyscanner.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_skyscanner_1666103225438%2Fcompanies%2Fskyscanner.json )**
=> Update 'Skyscanner Ltd' (community contribution)

companies/idenfy.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_idenfy_1665486175758%2Fcompanies%2Fidenfy.json )**
=> Add 'idenfy' (community contribution)

companies/venntel.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_venntel_1662397509110%2Fcompanies%2Fvenntel.json )**
=> Add 'Venntel Inc.' (community contribution)

companies/gravyanalytics.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_gravyanalytics_1662397838066%2Fcompanies%2Fgravyanalytics.json )**
=> Add 'Gravy Analytics Inc.' (community contribution)

companies/telestream.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_telestream_1662357590430%2Fcompanies%2Ftelestream.json )**
=> Add 'Telestream, LLC' (community contribution)

companies/fragrantica.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_fragrantica_1661873298322%2Fcompanies%2Ffragrantica.json )**
=> Add 'Fragrantica Inc.' (community contribution)

companies/geno-media-circle.json
Add "required-elements"
and mark as "tested"
=> Update 'Geno Media Circle'

companies/united-domains.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_united-domains_1667794477164%2Fcompanies%2Funited-domains.json )**
=> Add 'united-domains AG' (community contribution)

companies/solarisbank.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_solarisbank_1666644866372%2Fcompanies%2Fsolarisbank.json )**
=> Update 'Solarisbank AG' (community contribution)

companies/haustiercastingservice.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_haustiercastingservice_1667944835259%2Fcompanies%2Fhaustiercastingservice.json )**
=> Add 'Kmedia GbR' (community contribution)

templates/nl/erasure-default.txt
=> Fix grammar error in Dutch erasure request

companies/tripadvisor.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_tripadvisor_1669555351886%2Fcompanies%2Ftripadvisor.json )**
=> Add 'Tripadvisor' (community contribution)

companies/miles-mobility.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_miles-mobility_1660145407034%2Fcompanies%2Fmiles-mobility.json )**
=> Add 'MILES Mobility GmbH' (community contribution)

companies/holidaycheck.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_holidaycheck_1669703399287%2Fcompanies%2Fholidaycheck.json )**
=> Update 'HolidayCheck AG' (community contribution)

companies/cohost.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_cohost_1669821682590%2Fcompanies%2Fcohost.json )**
=> Add 'Anti Software Software Club LLC' (community contribution)

companies/audible-de.json
PR only for the CI tests. Will merge myself.
=> Update Audible (Germany)

companies/studierendenschaft-der-johannes-gutenberg-universit-t-mainz-k-d-r.json, companies/studierendenschaft-uni-mainz
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_studierendenschaft-der-johannes-gutenberg-universit-t-mainz-k-d-r_1672401596593%2Fcompanies%2Fstudierendenschaft-der-johannes-gutenberg-universit-t-mainz-k-d-r.json )**
=> Add 'Studierendenschaft der Johannes Gutenberg-Universität Mainz K.d.ö.R.' (community contribution)

companies/worx.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_worx_1672375106974%2Fcompanies%2Fworx.json )**
=> Add 'Worx' (community contribution)

companies/fax.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_fax_1672346999724%2Fcompanies%2Ffax.json )**
=> Add 'FAX.de GmbH & Co.KG' (community contribution)

companies/organisation-uni-mainz.json, companies/uni-mainz-de.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_organisation-uni-mainz_1672400151400%2Fcompanies%2Forganisation-uni-mainz.json )**
=> Add 'Universität Mainz' (community contribution)

companies/bustedtees.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_bustedtees_1672211590344%2Fcompanies%2Fbustedtees.json )**
=> Add 'BustedTees.com' (community contribution)

companies/tvspielfilm.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_tvspielfilm_1672204040598%2Fcompanies%2Ftvspielfilm.json )**
=> Add 'TV Spielfilm' (community contribution)

companies/ipsos.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_ipsos_1671556390866%2Fcompanies%2Fipsos.json )**
=> Add 'Ipsos GmbH' (community contribution)

companies/sky-de.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_sky-de_1672276314256%2Fcompanies%2Fsky-de.json )**
=> Update 'Sky Deutschland' (community contribution)

companies/goodhood-eu.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_goodhood-eu_1672603627585%2Fcompanies%2Fgoodhood-eu.json )**
=> Update 'Good Hood GmbH' (community contribution)

companies/zendesk-international-ltd.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_zendesk-international-ltd_1671238166042%2Fcompanies%2Fzendesk-international-ltd.json )**
=> Update 'Zendesk International Ltd.' (community contribution)

companies/stroeermediabrands.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_stroeermediabrands_1667572629931%2Fcompanies%2Fstroeermediabrands.json )**
=> Update 'Ströer Media Brands GmbH' (community contribution)

companies/doctorbox.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_doctorbox_1659947488796%2Fcompanies%2Fdoctorbox.json )**
=> Update 'DoctorBox GmbH' (community contribution)

companies/proptop.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_proptop_1659984133879%2Fcompanies%2Fproptop.json )**
=> Update 'proptop GmbH' (community contribution)

companies/pfalzwerke.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_pfalzwerke_1672673789487%2Fcompanies%2Fpfalzwerke.json )**
=> Update 'PFALZWERKE AKTIENGESELLSCHAFT' (community contribution)

companies/amazon-aws.json, companies/aws-amazon.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_aws-amazon_1672925321739%2Fcompanies%2Faws-amazon.json )**
=> Add 'Amazon Web Services EMEA SARL' (community contribution)

companies/solarwinds.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_solarwinds_1674082642348%2Fcompanies%2Fsolarwinds.json )**
=> Add 'Solarwinds' (community contribution)

companies/gb-intelligence.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_gb-intelligence_1659528416588%2Fcompanies%2Fgb-intelligence.json )**
=> Update 'GB Intelligence Ltd.' (community contribution)

companies/ratepay.json, companies/tierheim-mergentheim.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_ratepay_1665074741126%2Fcompanies%2Fratepay.json )**
=> Update 'Tierheim Bad Mergentheim' (community contribution)

companies/europcar.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_europcar_1668007329617%2Fcompanies%2Feuropcar.json )**
=> Update 'EMobG Services Germany GmbH' (community contribution)

companies/gothaer.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_gothaer_1671363814894%2Fcompanies%2Fgothaer.json )**
=> Update 'Gothaer Versicherungsbank VVaG' (community contribution)

companies/firmenliste.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_firmenliste_1672918804845%2Fcompanies%2Ffirmenliste.json )**
=> Update 'Adresskontor GmbH' (community contribution)

companies/bigpoint.json
The company moved to a new office.
=> Update company Bigpoint GmbH

companies/vattenfall.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_vattenfall_1676900115694%2Fcompanies%2Fvattenfall.json )**
=> Update 'Vattenfall GmbH' (community contribution)

companies/netcologne.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_netcologne_1678221918832%2Fcompanies%2Fnetcologne.json )**
=> Update 'NetCologne Gesellschaft für Telekommunikation mbH' (community contribution)

companies/epay.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_epay_1677581828660%2Fcompanies%2Fepay.json )**
=> Update 'transact Elektronische Zahlungssysteme GmbH' (community contribution)

companies/openai.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_openai_1680369673353%2Fcompanies%2Fopenai.json )**
=> Add 'OpenAI LP' (community contribution)

companies/mxroute.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_mxroute_1681039537427%2Fcompanies%2Fmxroute.json )**
=> Update 'MXroute LLC' (community contribution)

companies/historische-s-bahn.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_historische-s-bahn_1680794936783%2Fcompanies%2Fhistorische-s-bahn.json )**
=> Update 'Historische S-Bahn e.V. (HiSB)' (community contribution)

companies/audibank.json, companies/vw-bank.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_vw-bank_1681377566188%2Fcompanies%2Fvw-bank.json )**
=> Update 'Volkswagen Financial Services AG' (community contribution)

companies/axel-springer-es.json
=> Add Spanish Axel Springer properties

companies/unstoppabledomains.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_unstoppabledomains_1682698167915%2Fcompanies%2Funstoppabledomains.json )**
=> Add 'Unstoppable Domains Inc.' (community contribution)

companies/eis-erotik.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_eis-erotik_1674558108681%2Fcompanies%2Feis-erotik.json )**
=> Update 'EIS GmbH' (community contribution)

companies/trade-republic-bank-gmbh.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_trade-republic-bank-gmbh_1673359062307%2Fcompanies%2Ftrade-republic-bank-gmbh.json )**
=> Update 'Trade Republic Bank GmbH' (community contribution)

companies/vsk-de.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_vsk-de_1681979177345%2Fcompanies%2Fvsk-de.json )**
=> Update 'Vermieterwelt GmbH' (community contribution)

companies/solarisbank.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_solarisbank_1681516695839%2Fcompanies%2Fsolarisbank.json )**
=> Update 'Solaris SE' (community contribution)

companies/infoscore.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_infoscore_1682243455081%2Fcompanies%2Finfoscore.json )**
=> Update 'infoscore Consumer Data GmbH' (community contribution)

companies/eventim.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_eventim_1673620675991%2Fcompanies%2Feventim.json )**
=> Update 'CTS EVENTIM AG & Co. KGaA' (community contribution)

companies/ewe-de.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_ewe-de_1672756875473%2Fcompanies%2Fewe-de.json )**
=> Update 'EWE AG' (community contribution)

companies/momox.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_momox_1673791385794%2Fcompanies%2Fmomox.json )**
=> Update 'momox SE' (community contribution)

companies/c-and-a.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_c-and-a_1682334961913%2Fcompanies%2Fc-and-a.json )**
=> Update 'C&A Mode GmbH & Co. KG' (community contribution)

companies/hygi-de.json, companies/hygi.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_hygi_1678798386307%2Fcompanies%2Fhygi.json )**
=> Add 'hygi.de GmbH & Co. KG' (community contribution)

templates/ro/access-default.txt
My attempt to translate data requests to 🇷🇴 Romanian. I'm not a lawyer nor work in the legal domain, but would be nice if someone coming from this domain would validate my translation.
=> 🇷🇴Romanian translation

companies/theadex.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_theadex_1687271403030%2Fcompanies%2Ftheadex.json )**
=> Update 'Virtual Minds GmbH' (community contribution)

companies/proton.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_proton_1690109842942%2Fcompanies%2Fproton.json )**
=> Update 'Proton AG' (community contribution)

companies/tiktok.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_tiktok_1691668527192%2Fcompanies%2Ftiktok.json )**
=> Update 'TikTok Technology Ltd.' (community contribution)

companies/mainova.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_mainova_1692025117258%2Fcompanies%2Fmainova.json )**
=> Add 'Mainova AG' (community contribution)

companies/getdigital.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_getdigital_1692246200570%2Fcompanies%2Fgetdigital.json )**
=> Update 'Stern & Schatz GmbH' (community contribution)

companies/lottoland.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_lottoland_1692964088296%2Fcompanies%2Flottoland.json )**
=> Update 'lottoland' (community contribution)

companies/freundlich-wohnen.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_freundlich-wohnen_1689682800341%2Fcompanies%2Ffreundlich-wohnen.json )**
=> Add 'WOGE Wohnungsgesellschaft Saarland mbH' (community contribution)

companies/schwab-versand.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_schwab-versand_1693211147978%2Fcompanies%2Fschwab-versand.json )**
=> Update 'sheego AG' (community contribution)

companies/lindnerit.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_lindnerit_1691759134237%2Fcompanies%2Flindnerit.json )**
=> Add 'Lindner IT UG (haftungsbeschränkt)' (community contribution)

companies/labor-becker.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_labor-becker_1655756687551%2Fcompanies%2Flabor-becker.json )**
=> Add 'Labor Becker MVZ GbR' (community contribution)

companies/bestwestern.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_bestwestern_1656946859530%2Fcompanies%2Fbestwestern.json )**
=> Add 'Best Western Hotels & Resorts' (community contribution)

companies/jugendwerk-altholstein.json, companies/kirchenkreis-altholstein.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_jugendwerk-altholstein_1658684244614%2Fcompanies%2Fjugendwerk-altholstein.json )**
=> Add 'Evangelisch-Lutherischer Kirchenkreis Altholstein' (community contribution)

companies/schulamt-thueringen.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_schulamt-thueringen_1657448776041%2Fcompanies%2Fschulamt-thueringen.json )**
=> Add 'Staatliches Schulamt Südthüringen' (community contribution)

companies/young-leaders.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_young-leaders_1658684436572%2Fcompanies%2Fyoung-leaders.json )**
=> Add 'young leaders GmbH' (community contribution)

companies/technische-universitaet-muenchen.json, companies/tum.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_tum_1659798352808%2Fcompanies%2Ftum.json )**
=> Add 'Technische Universität München' (community contribution)

companies/elitenetzwerk-bayern.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_elitenetzwerk-bayern_1659798530035%2Fcompanies%2Felitenetzwerk-bayern.json )**
=> Add 'Elitenetzwerk Bayern' (community contribution)

companies/uni-augsburg.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_uni-augsburg_1659798960194%2Fcompanies%2Funi-augsburg.json )**
=> Add 'Universität Augsburg' (community contribution)

companies/blutspendedienst-brk.json, companies/blutspendedienst.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_blutspendedienst_1659799452892%2Fcompanies%2Fblutspendedienst.json )**
=> Add 'Blutspendedienst des Bayerischen Roten Kreuzes gGmbH' (community contribution)

companies/flaschenpost.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_flaschenpost_1659806700893%2Fcompanies%2Fflaschenpost.json )**
=> Add 'flaschenpost SE' (community contribution)

companies/datev.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_datev_1659809300905%2Fcompanies%2Fdatev.json )**
=> Add 'DATEV eG' (community contribution)

companies/rtl-television-gmbh.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_rtl-television-gmbh_1659951732486%2Fcompanies%2Frtl-television-gmbh.json )**
=> Add 'RTL interactive GmbH' (community contribution)

companies/bw-bank.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_bw-bank_1659977660001%2Fcompanies%2Fbw-bank.json )**
=> Add 'Baden-Württembergische Bank (BW-Bank)' (community contribution)

companies/magnetikalchemy.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_magnetikalchemy_1660244258068%2Fcompanies%2Fmagnetikalchemy.json )**
=> Add 'Magnetik Alchemy' (community contribution)

companies/homeserve.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_homeserve_1661418114336%2Fcompanies%2Fhomeserve.json )**
=> Add 'HomeServe Membership Ltd' (community contribution)

companies/laolaweb-gmbh.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_laolaweb-gmbh_1658521032558%2Fcompanies%2Flaolaweb-gmbh.json )**
=> Add 'laOlaWeb GmbH' (community contribution)

companies/greenheads-onlineperformance.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_greenheads-onlineperformance_1661939929276%2Fcompanies%2Fgreenheads-onlineperformance.json )**
=> Add 'Green Heads Online-Performance GmbH' (community contribution)

companies/boerse-stuttgart.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_boerse-stuttgart_1662709928812%2Fcompanies%2Fboerse-stuttgart.json )**
=> Add 'Boerse Stuttgart GmbH' (community contribution)

companies/7mind.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_7mind_1663077976731%2Fcompanies%2F7mind.json )**
=> Add '7Mind GmbH' (community contribution)

companies/waipu-tv.json, companies/waipu.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_waipu_1663100462482%2Fcompanies%2Fwaipu.json )**
=> Add 'EXARING AG' (community contribution)

companies/datenschutzbuero.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_datenschutzbuero_1664628831930%2Fcompanies%2Fdatenschutzbuero.json )**
=> Add 'Galaxus Deutschland GmbH' (community contribution)

companies/pronovabkk.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_pronovabkk_1664629452264%2Fcompanies%2Fpronovabkk.json )**
=> Add 'Pronova BKK' (community contribution)

companies/anycoin-direct.json, companies/phoenix-payments-bv.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_phoenix-payments-bv_1665393054086%2Fcompanies%2Fphoenix-payments-bv.json )**
=> Add 'Phoenix Payments BV' (community contribution)

companies/kalendersale.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_kalendersale_1665519685127%2Fcompanies%2Fkalendersale.json )**
=> Add 'PAPIERaffin eCommerce GmbH' (community contribution)

companies/kdo.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_kdo_1666255236996%2Fcompanies%2Fkdo.json )**
=> Add 'Zweckverband Kommunale Datenverarbeitung Oldenburg (KDO)' (community contribution)

companies/rheuma-hh.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_rheuma-hh_1666366233561%2Fcompanies%2Frheuma-hh.json )**
=> Add 'MVZ Rheumatologie und Autoimmunmedizin Hamburg GmbH' (community contribution)

companies/basteln-de-buttinette.json, companies/buttinette.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_basteln-de-buttinette_1666367896318%2Fcompanies%2Fbasteln-de-buttinette.json )**
=> Add 'buttinette Textil-Versandhaus GmbH' (community contribution)

companies/dortex.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_dortex_1666368279816%2Fcompanies%2Fdortex.json )**
=> Add 'Dortex Werbung und Vertrieb mbH' (community contribution)

companies/ruhrtone.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_ruhrtone_1667469200457%2Fcompanies%2Fruhrtone.json )**
=> Add 'RUHRTONE MUSIC MANAGEMENT GMBH' (community contribution)

companies/nepatec.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_nepatec_1668533230011%2Fcompanies%2Fnepatec.json )**
=> Add 'nepatec GmbH' (community contribution)

companies/swisslife-select.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_swisslife-select_1668537009510%2Fcompanies%2Fswisslife-select.json )**
=> Add 'Swiss Life Select Deutschland GmbH' (community contribution)

companies/trendtours.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_trendtours_1669062364333%2Fcompanies%2Ftrendtours.json )**
=> Add 'Trendtours Touristik GmbH' (community contribution)

companies/uniwunder.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_uniwunder_1669281932627%2Fcompanies%2Funiwunder.json )**
=> Add 'Uniwunder GmbH' (community contribution)

companies/useartemis.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_useartemis_1669460714390%2Fcompanies%2Fuseartemis.json )**
=> Add 'useArtemis' (community contribution)

companies/schnelltestberlin.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_schnelltestberlin_1669479299041%2Fcompanies%2Fschnelltestberlin.json )**
=> Add 'WeCare Services GmbH' (community contribution)

companies/becquet.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_becquet_1669537094262%2Fcompanies%2Fbecquet.json )**
=> Add 'BECQUET, SASU' (community contribution)

companies/weightwatchers-nl.json, companies/weightwatchers.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_weightwatchers_1669552018749%2Fcompanies%2Fweightwatchers.json )**
=> Add 'WW Netherlands B.V.' (community contribution)

companies/hivesocial.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_hivesocial_1669557120723%2Fcompanies%2Fhivesocial.json )**
=> Add 'Hive Social, Inc.' (community contribution)

companies/headwayproduct.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_headwayproduct_1669629832123%2Fcompanies%2Fheadwayproduct.json )**
=> Add 'GTHW App Limited' (community contribution)

companies/nitrado.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_nitrado_1669834687821%2Fcompanies%2Fnitrado.json )**
=> Add 'marbis GmbH' (community contribution)

companies/wertgarantie.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_wertgarantie_1669836397847%2Fcompanies%2Fwertgarantie.json )**
=> Add 'Wertgarantie SE' (community contribution)

companies/planet-randy.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_planet-randy_1669939315687%2Fcompanies%2Fplanet-randy.json )**
=> Add 'Sunset Connect S.L' (community contribution)

companies/sekeymall.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_sekeymall_1670194561886%2Fcompanies%2Fsekeymall.json )**
=> Add 'Salcar GmbH' (community contribution)

companies/salo-holding-ag.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_salo-holding-ag_1670232365410%2Fcompanies%2Fsalo-holding-ag.json )**
=> Add 'Salo Holding AG' (community contribution)

companies/stopandgo.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_stopandgo_1670311559369%2Fcompanies%2Fstopandgo.json )**
=> Add 'stop+go Systemzentrale GmbH' (community contribution)

companies/uno-fluechtlingshilfe.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_uno-fluechtlingshilfe_1670418437231%2Fcompanies%2Funo-fluechtlingshilfe.json )**
=> Add 'UNO-Flüchtlingshilfe e.V.' (community contribution)

companies/asb.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_asb_1670420375482%2Fcompanies%2Fasb.json )**
=> Add 'Arbeiter-Samariter-Bund Deutschland e.V.' (community contribution)

companies/volksbank-stuttgart.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_volksbank-stuttgart_1670921217663%2Fcompanies%2Fvolksbank-stuttgart.json )**
=> Add 'Volksbank Stuttgart eG' (community contribution)

companies/sls-data.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_sls-data_1670448010305%2Fcompanies%2Fsls-data.json )**
=> Add 'SLS Data' (community contribution)

companies/vanderstorm-ventures-gmbh-co-kg.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_vanderstorm-ventures-gmbh-co-kg_1670493645622%2Fcompanies%2Fvanderstorm-ventures-gmbh-co-kg.json )**
=> Add 'Vanderstorm Ventures GmbH & Co. KG' (community contribution)

companies/niwa-gbr.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_niwa-gbr_1670910724977%2Fcompanies%2Fniwa-gbr.json )**
=> Add 'NIWA GbR' (community contribution)

companies/rootz.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_rootz_1670930234146%2Fcompanies%2Frootz.json )**
=> Add 'Rootz Ltd.' (community contribution)

companies/gommehd.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_gommehd_1671384160705%2Fcompanies%2Fgommehd.json )**
=> Add 'GommeHDnet GmbH' (community contribution)

companies/seba-swiss.json, companies/seba.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_seba_1671448274118%2Fcompanies%2Fseba.json )**
=> Add 'SEBA Bank AG' (community contribution)

companies/sygnum.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_sygnum_1671448394770%2Fcompanies%2Fsygnum.json )**
=> Add 'Sygnum Bank AG' (community contribution)

companies/rhenag.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_rhenag_1672200898571%2Fcompanies%2Frhenag.json )**
=> Add 'rhenag Rheinische Energie AG' (community contribution)

companies/sparkasse-karlsruhe.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_sparkasse-karlsruhe_1672201812975%2Fcompanies%2Fsparkasse-karlsruhe.json )**
=> Add 'Sparkasse Karlsruhe' (community contribution)

companies/isppro.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_isppro_1672208699601%2Fcompanies%2Fisppro.json )**
=> Add 'ISPpro Internet KG' (community contribution)

companies/gothaer-digital.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_gothaer-digital_1671366512407%2Fcompanies%2Fgothaer-digital.json )**
=> Add 'Gothaer Digital GmbH' (community contribution)

companies/extraenergie.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_extraenergie_1672212870902%2Fcompanies%2Fextraenergie.json )**
=> Add 'ExtraEnergie GmbH' (community contribution)

companies/ewe-vertrieb.json, companies/ewe.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_ewe_1672756758779%2Fcompanies%2Fewe.json )**
=> Add 'EWE VERTRIEB GmbH' (community contribution)

companies/kreissparkasse-ludwigsburg.json, companies/ksklb.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_ksklb_1672873119850%2Fcompanies%2Fksklb.json )**
=> Add 'Kreissparkasse Ludwigsburg' (community contribution)

companies/bundesgesundheitsministerium.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_bundesgesundheitsministerium_1672934687896%2Fcompanies%2Fbundesgesundheitsministerium.json )**
=> Add 'Bundesministerium für Gesundheit' (community contribution)

companies/staatsoper-berlin.json, companies/staatsoper-unter-den-linden.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_staatsoper-berlin_1673134120666%2Fcompanies%2Fstaatsoper-berlin.json )**
=> Add 'Staatsoper Unter den Linden' (community contribution)

companies/activeroom-gmbh.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_activeroom-gmbh_1673356907445%2Fcompanies%2Factiveroom-gmbh.json )**
=> Add 'Activeroom GmbH' (community contribution)

companies/hypovereinsbank.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_hypovereinsbank_1673388434782%2Fcompanies%2Fhypovereinsbank.json )**
=> Add 'UniCredit Bank AG' (community contribution)

companies/marcapo.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_marcapo_1673441408997%2Fcompanies%2Fmarcapo.json )**
=> Add 'marcapo GmbH' (community contribution)

companies/mvneco.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_mvneco_1673442233375%2Fcompanies%2Fmvneco.json )**
=> Add 'mvneco GmbH' (community contribution)

companies/go-ahead-bahn.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_go-ahead-bahn_1673701126951%2Fcompanies%2Fgo-ahead-bahn.json )**
=> Add 'Go-Ahead Verkehrsgesellschaft Deutschland GmbH' (community contribution)

companies/optilyz.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_optilyz_1673791562587%2Fcompanies%2Foptilyz.json )**
=> Add 'optilyz GmbH' (community contribution)

companies/adressdruck.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_adressdruck_1673791712550%2Fcompanies%2Fadressdruck.json )**
=> Add 'adressdruck.de' (community contribution)

companies/mediafinanz.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_mediafinanz_1673986215239%2Fcompanies%2Fmediafinanz.json )**
=> Add 'mediaFinanz GmbH' (community contribution)

companies/canadalife-de.json, companies/canadalife.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_canadalife_1673997085125%2Fcompanies%2Fcanadalife.json )**
=> Add 'Canada Life Assurance Europe plc' (community contribution)

companies/britishgas-co.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_britishgas-co_1674049902532%2Fcompanies%2Fbritishgas-co.json )**
=> Add 'Centrica Plc' (community contribution)

companies/masmovil.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_masmovil_1674488647334%2Fcompanies%2Fmasmovil.json )**
=> Add 'Xfera Móviles, S.A.U' (community contribution)

companies/accor-all.json, companies/all-accor.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_all-accor_1674602733947%2Fcompanies%2Fall-accor.json )**
=> Add 'Accor S.A.' (community contribution)

companies/dhl-hub-leipzig.json, companies/dhl.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_dhl_1675380125383%2Fcompanies%2Fdhl.json )**
=> Add 'DHL Hub Leipzig GmbH' (community contribution)

companies/simpleanalytics.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_simpleanalytics_1675439952848%2Fcompanies%2Fsimpleanalytics.json )**
=> Add 'Simple Analytics B.V.' (community contribution)

companies/hcaptcha.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_hcaptcha_1675440172372%2Fcompanies%2Fhcaptcha.json )**
=> Add 'Intuition Machines, Inc.' (community contribution)

companies/travelpayouts.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_travelpayouts_1675440825812%2Fcompanies%2Ftravelpayouts.json )**
=> Add 'Go Travel Un Limited' (community contribution)

companies/coinmarketcap.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_coinmarketcap_1675813787223%2Fcompanies%2Fcoinmarketcap.json )**
=> Add 'CoinMarketCap OpCo, LLC' (community contribution)

companies/companyspotter.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_companyspotter_1676188787482%2Fcompanies%2Fcompanyspotter.json )**
=> Add 'CompanySpotter' (community contribution)

companies/mmoga.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_mmoga_1676323125834%2Fcompanies%2Fmmoga.json )**
=> Add 'MMOGA Ltd.' (community contribution)

companies/anerkennung-kirche.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_anerkennung-kirche_1676488078058%2Fcompanies%2Fanerkennung-kirche.json )**
=> Add 'Unabhängige Kommission für Anerkennungsleistungen' (community contribution)

companies/greenpeace-magazin.json, companies/greenpeace-media.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_greenpeace-magazin_1676568027013%2Fcompanies%2Fgreenpeace-magazin.json )**
=> Add 'Greenpeace Media GmbH' (community contribution)

companies/official-sensitive-ltd.json, companies/official-sensitive.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_official-sensitive_1676655650311%2Fcompanies%2Fofficial-sensitive.json )**
=> Add 'Official-Sensitive Ltd.' (community contribution)

companies/ryan-jarvis-law.json, companies/ryanjarvis.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_ryanjarvis_1676655797718%2Fcompanies%2Fryanjarvis.json )**
=> Add 'Ryan Jarvis Law Ltd.' (community contribution)

companies/wattfox-gmbh.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_wattfox-gmbh_1676964874367%2Fcompanies%2Fwattfox-gmbh.json )**
=> Add 'WattFox GmbH' (community contribution)

companies/otovo.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_otovo_1676972330200%2Fcompanies%2Fotovo.json )**
=> Add 'Otovo GmbH' (community contribution)

companies/nvidia.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_nvidia_1677180724104%2Fcompanies%2Fnvidia.json )**
=> Add 'NVIDIA Corporation' (community contribution)

companies/crisp.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_crisp_1677261736771%2Fcompanies%2Fcrisp.json )**
=> Add 'Crisp IM S.A.S' (community contribution)

companies/tanzpartner-de.json, companies/tanzpartner.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_tanzpartner_1678313688448%2Fcompanies%2Ftanzpartner.json )**
=> Add 'Tanzpartner.de' (community contribution)

companies/albert-kreuz.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_albert-kreuz_1678453127363%2Fcompanies%2Falbert-kreuz.json )**
=> Add 'Albert Kreuz GmbH' (community contribution)

companies/chargebackhit.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_chargebackhit_1678522275535%2Fcompanies%2Fchargebackhit.json )**
=> Add 'Anteolink Limited' (community contribution)

companies/gfk.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_gfk_1678536913483%2Fcompanies%2Fgfk.json )**
=> Add 'GfK SE' (community contribution)

companies/gfk-gb.json, companies/gfk.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_gfk_1678537398247%2Fcompanies%2Fgfk.json )**
=> Add 'GfK UK Limited' (community contribution)

companies/owncube.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_owncube_1678619772206%2Fcompanies%2Fowncube.json )**
=> Add 'OwnCube e.U.' (community contribution)

companies/belfor-de.json, companies/belfor-deutschland-gmbh.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_belfor-deutschland-gmbh_1678784868444%2Fcompanies%2Fbelfor-deutschland-gmbh.json )**
=> Add 'BELFOR Deutschland GmbH' (community contribution)

companies/clickup.json, companies/mango-technologies-inc.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_clickup_1679318363507%2Fcompanies%2Fclickup.json )**
=> Add 'Mango Technologies, Inc.' (community contribution)

companies/uni-stuttgart.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_uni-stuttgart_1680029074122%2Fcompanies%2Funi-stuttgart.json )**
=> Add 'Universität Stuttgart' (community contribution)

companies/w2ssolutions.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_w2ssolutions_1680521149357%2Fcompanies%2Fw2ssolutions.json )**
=> Add 'W2S Solutions' (community contribution)

companies/heise-gruppe.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_heise-gruppe_1686803699857%2Fcompanies%2Fheise-gruppe.json )**
=> Add 'Heise Gruppe GmbH & Co. KG' (community contribution)

companies/superfly.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_superfly_1686835119825%2Fcompanies%2Fsuperfly.json )**
=> Add 'Superfly Air Sports Holding GmbH' (community contribution)

companies/dataxtrade.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_dataxtrade_1687270532725%2Fcompanies%2Fdataxtrade.json )**
=> Add 'dataXtrade GmbH' (community contribution)

companies/roq-ad.json, companies/roq.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_roq_1687271149943%2Fcompanies%2Froq.json )**
=> Add 'Roq.ad GmbH' (community contribution)

companies/zeotap.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_zeotap_1687271864465%2Fcompanies%2Fzeotap.json )**
=> Add 'zeotap GmbH' (community contribution)

companies/spotahome.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_spotahome_1681253178417%2Fcompanies%2Fspotahome.json )**
=> Add 'SPOTAHOME S.L.U' (community contribution)

companies/abz-zr.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_abz-zr_1682635295397%2Fcompanies%2Fabz-zr.json )**
=> Add 'ABZ Zahnärztliches Rechenzentrum für Bayern GmbH' (community contribution)

companies/softwarebilliger.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_softwarebilliger_1686584375443%2Fcompanies%2Fsoftwarebilliger.json )**
=> Add 'Antares Im- und Export GmbH' (community contribution)

companies/keseurope.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_keseurope_1686666371838%2Fcompanies%2Fkeseurope.json )**
=> Add 'KES Kulturpartner Europe Shanghai GmbH' (community contribution)

companies/deejay.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_deejay_1686723753180%2Fcompanies%2Fdeejay.json )**
=> Add 'deejay.de e.K.' (community contribution)

companies/dance-all-day.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_dance-all-day_1686734424668%2Fcompanies%2Fdance-all-day.json )**
=> Add 'Dance All Day Musicvertriebs GmbH' (community contribution)

companies/big-direkt-gesund.json, companies/big-direkt.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_big-direkt_1687280429326%2Fcompanies%2Fbig-direkt.json )**
=> Add 'BIG direkt gesund' (community contribution)

companies/tellows.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_tellows_1687465539516%2Fcompanies%2Ftellows.json )**
=> Add 'tellows UG (haftungsbeschränkt)' (community contribution)

companies/trendtest.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_trendtest_1687519469616%2Fcompanies%2Ftrendtest.json )**
=> Add 'trend.test Gesellschaft für telefonische Datenerhebung mbH' (community contribution)

companies/pr0gramm.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_pr0gramm_1687714598010%2Fcompanies%2Fpr0gramm.json )**
=> Add 'Interdimensionale Gesellschaft mbH' (community contribution)

companies/computer-erlangen.json, companies/weingarten-pc-service.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_computer-erlangen_1688322916267%2Fcompanies%2Fcomputer-erlangen.json )**
=> Add 'Weingarten PC-Service GmbH' (community contribution)

companies/enercity.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_enercity_1688470229250%2Fcompanies%2Fenercity.json )**
=> Add 'enercity AG' (community contribution)

companies/cyberhealth-gmbh.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_cyberhealth-gmbh_1688474404301%2Fcompanies%2Fcyberhealth-gmbh.json )**
=> Add 'CyberHealth GmbH' (community contribution)

companies/vultr.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_vultr_1688790873357%2Fcompanies%2Fvultr.json )**
=> Add 'The Constant Company, LLC' (community contribution)

companies/erzbistum-bamberg.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_erzbistum-bamberg_1688837157221%2Fcompanies%2Ferzbistum-bamberg.json )**
=> Add 'Erzbistum Bamberg' (community contribution)

companies/codesandbox-io.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_codesandbox-io_1688853053075%2Fcompanies%2Fcodesandbox-io.json )**
=> Add 'CodeSandbox B.V.' (community contribution)

companies/sky-gb.json, companies/sky.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_sky_1688962152767%2Fcompanies%2Fsky.json )**
=> Add 'Sky UK Limited' (community contribution)

companies/sky-ie.json, companies/sky.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_sky_1688962442040%2Fcompanies%2Fsky.json )**
=> Add 'Sky Ireland Limited' (community contribution)

companies/dgvt-erlangen.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_dgvt-erlangen_1689245584997%2Fcompanies%2Fdgvt-erlangen.json )**
=> Add 'DGVT Aus- und Weiterbildungszentrum Erlangen-Nürnberg GmbH' (community contribution)

companies/klinikum-nuernberg.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_klinikum-nuernberg_1689245953277%2Fcompanies%2Fklinikum-nuernberg.json )**
=> Add 'Klinikum Nürnberg' (community contribution)

companies/tanjastahl.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_tanjastahl_1689247664791%2Fcompanies%2Ftanjastahl.json )**
=> Add 'Psychotherapeutische Praxis Tanja Stahl' (community contribution)

companies/bezirkskliniken-mfr.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_bezirkskliniken-mfr_1689248655772%2Fcompanies%2Fbezirkskliniken-mfr.json )**
=> Add 'Bezirkskliniken Mittelfranken' (community contribution)

companies/popsure-deutschland-gmbh.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_popsure-deutschland-gmbh_1689324031336%2Fcompanies%2Fpopsure-deutschland-gmbh.json )**
=> Add 'Popsure Deutschland GmbH' (community contribution)

companies/capera-immobilien.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_capera-immobilien_1689682440960%2Fcompanies%2Fcapera-immobilien.json )**
=> Add 'CAPERA Immobilien Service GmbH' (community contribution)

companies/gbs-sls.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_gbs-sls_1689683034394%2Fcompanies%2Fgbs-sls.json )**
=> Add 'Gemeinnützige Bau- und Siedlungs-GmbH Saarlouis' (community contribution)

companies/tesla.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_tesla_1690020295555%2Fcompanies%2Ftesla.json )**
=> Add 'Tesla International B.V.' (community contribution)

companies/interrail.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_interrail_1690117664890%2Fcompanies%2Finterrail.json )**
=> Add 'Eurail B.V.' (community contribution)

companies/myunidays.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_myunidays_1690296651253%2Fcompanies%2Fmyunidays.json )**
=> Add 'Myunidays Limited' (community contribution)

companies/crunchyroll.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_crunchyroll_1690908969276%2Fcompanies%2Fcrunchyroll.json )**
=> Add 'Ellation, Inc.' (community contribution)

companies/nispa.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_nispa_1690963175723%2Fcompanies%2Fnispa.json )**
=> Add 'Niederrheinische Sparkasse RheinLippe' (community contribution)

companies/picnic.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_picnic_1691445302496%2Fcompanies%2Fpicnic.json )**
=> Add 'Picnic Technologien B.V.' (community contribution)

companies/oneplus-technology-shenzhen-co-ltd.json, companies/oneplus.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_oneplus-technology-shenzhen-co-ltd_1691609376325%2Fcompanies%2Foneplus-technology-shenzhen-co-ltd.json )**
=> Add 'OnePlus Technology (Shenzhen) Co., Ltd.' (community contribution)

companies/companyhouse-ag.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_companyhouse-ag_1692119602469%2Fcompanies%2Fcompanyhouse-ag.json )**
=> Add 'CompanyHouse AG' (community contribution)

companies/simplelogin.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_simplelogin_1692126493075%2Fcompanies%2Fsimplelogin.json )**
=> Add 'SimpleLogin SAS' (community contribution)

companies/christoph-scheiner-gymnasium-ingolstadt.json, companies/csg-in.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_csg-in_1692614359889%2Fcompanies%2Fcsg-in.json )**
=> Add 'Christoph-Scheiner-Gymnasium Ingolstadt' (community contribution)

companies/riu-hotels-und-resorts.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_riu-hotels-und-resorts_1692876493052%2Fcompanies%2Friu-hotels-und-resorts.json )**
=> Add 'RIU Hotels und Resorts' (community contribution)

companies/helvetia-de.json, companies/helvetia.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_helvetia_1692882076414%2Fcompanies%2Fhelvetia.json )**
=> Add 'Helvetia Schweizerische Versicherungsgesellschaft AG' (community contribution)

companies/kreissparkasse-goeppingen.json, companies/ksk-gp.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_ksk-gp_1692882346213%2Fcompanies%2Fksk-gp.json )**
=> Add 'Kreissparkasse Göppingen' (community contribution)

companies/rheinland-versicherungen.json, companies/rheinland-versicherungs-ag.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_rheinland-versicherungen_1692882437616%2Fcompanies%2Frheinland-versicherungen.json )**
=> Add 'RheinLand Versicherungs AG' (community contribution)

companies/bgv-de.json, companies/bgv.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_bgv_1692882865248%2Fcompanies%2Fbgv.json )**
=> Add 'BGV Badische Versicherungen' (community contribution)

companies/adressbar.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_adressbar_1692895081699%2Fcompanies%2Fadressbar.json )**
=> Add 'Fabian Wolf – Data Services' (community contribution)

companies/brose-fahrzeugteile.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_brose-fahrzeugteile_1694023984652%2Fcompanies%2Fbrose-fahrzeugteile.json )**
=> Add 'Brose Fahrzeugteile SE & Co. KG' (community contribution)

companies/jameda.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_jameda_1694097332422%2Fcompanies%2Fjameda.json )**
=> Add 'jameda GmbH' (community contribution)

companies/dreame-international-hongkong-limited.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_dreame-international-hongkong-limited_1696279524661%2Fcompanies%2Fdreame-international-hongkong-limited.json )**
=> Add 'DREAME INTERNATIONAL (HONGKONG) LIMITED' (community contribution)

companies/deutschebahnconnect.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_deutschebahnconnect_1694636954372%2Fcompanies%2Fdeutschebahnconnect.json )**
=> Add 'Deutsche Bahn Connect GmbH' (community contribution)

companies/bolt.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_bolt_1694639807918%2Fcompanies%2Fbolt.json )**
=> Add 'Bolt Operations OÜ' (community contribution)

companies/jimmyjoy.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_jimmyjoy_1694641208565%2Fcompanies%2Fjimmyjoy.json )**
=> Add 'itizi B.V.' (community contribution)

companies/flatastic-app.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_flatastic-app_1694987246267%2Fcompanies%2Fflatastic-app.json )**
=> Add 'Flatastic GmbH' (community contribution)

companies/troy-bleiben.json, companies/troy-gmbh.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_troy-bleiben_1695120795191%2Fcompanies%2Ftroy-bleiben.json )**
=> Add 'troy GmbH' (community contribution)

companies/sectigo.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_sectigo_1695154115899%2Fcompanies%2Fsectigo.json )**
=> Add 'Sectigo Limited' (community contribution)

companies/infratest-dimap.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_infratest-dimap_1695819249456%2Fcompanies%2Finfratest-dimap.json )**
=> Add 'Mantle Germany GmbH' (community contribution)

companies/utpatti.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_utpatti_1696345991950%2Fcompanies%2Futpatti.json )**
=> Add 'Utpatti GmbH' (community contribution)

companies/univativ.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_univativ_1696445081604%2Fcompanies%2Funivativ.json )**
=> Add 'univativ GmbH' (community contribution)

companies/flattr-eyeo.json, companies/flattr.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_flattr-eyeo_1696454967778%2Fcompanies%2Fflattr-eyeo.json )**
=> Add 'Flattr AB' (community contribution)

companies/mobilfunk-talk.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_mobilfunk-talk_1696503591645%2Fcompanies%2Fmobilfunk-talk.json )**
=> Add 'Telfonio GmbH & Co. KG' (community contribution)

companies/conviction-org.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_conviction-org_1676655494300%2Fcompanies%2Fconviction-org.json )**
=> Update 'Conviction' (community contribution)

companies/check24.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_check24_1673551024159%2Fcompanies%2Fcheck24.json )**
=> Update 'CHECK24 Vergleichsportal GmbH' (community contribution)

companies/radio-de.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_radio-de_1680872873224%2Fcompanies%2Fradio-de.json )**
=> Update 'radio.de GmbH' (community contribution)

companies/otto-handel.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_otto-handel_1686744717568%2Fcompanies%2Fotto-handel.json )**
=> Update 'Otto (GmbH & Co KG)' (community contribution)

companies/heise-de.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_heise-de_1686802674899%2Fcompanies%2Fheise-de.json )**
=> Update 'Heise Medien GmbH & Co. KG' (community contribution)

companies/spotify.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_spotify_1686873615388%2Fcompanies%2Fspotify.json )**
=> Update 'Spotify AB' (community contribution)

companies/stage-entertainment-de.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_stage-entertainment-de_1689778533058%2Fcompanies%2Fstage-entertainment-de.json )**
=> Update 'STAGE ENTERTAINMENT Marketing & Sales GmbH' (community contribution)

companies/lka-nds.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_lka-nds_1689921639921%2Fcompanies%2Flka-nds.json )**
=> Update 'Landeskriminalamt Niedersachsen' (community contribution)

companies/tomorrow.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_tomorrow_1690109510944%2Fcompanies%2Ftomorrow.json )**
=> Update 'Tomorrow GmbH' (community contribution)

companies/posteo.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_posteo_1690110100217%2Fcompanies%2Fposteo.json )**
=> Update 'Posteo e.K.' (community contribution)

companies/united-domains.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_united-domains_1690110368549%2Fcompanies%2Funited-domains.json )**
=> Update 'united-domains AG' (community contribution)

companies/microsoft.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_microsoft_1690913918545%2Fcompanies%2Fmicrosoft.json )**
=> Update 'Microsoft Ireland Operations Ltd.' (community contribution)

companies/marley-spoon.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_marley-spoon_1691428283363%2Fcompanies%2Fmarley-spoon.json )**
=> Update 'Marley Spoon SE' (community contribution)

companies/eurowings.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_eurowings_1691867570173%2Fcompanies%2Feurowings.json )**
=> Update 'Eurowings GmbH' (community contribution)

companies/tellja.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_tellja_1691985900652%2Fcompanies%2Ftellja.json )**
=> Update 'Tellja GmbH' (community contribution)

companies/herdt.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_herdt_1692256071947%2Fcompanies%2Fherdt.json )**
=> Update 'HERDT-Verlag für Bildungsmedien GmbH' (community contribution)

companies/tvinfo.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_tvinfo_1692398405801%2Fcompanies%2Ftvinfo.json )**
=> Update 'TVinfo Internet GmbH' (community contribution)

companies/basler-versicherungen.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_basler-versicherungen_1692881802200%2Fcompanies%2Fbasler-versicherungen.json )**
=> Update 'Baloise Versicherungen' (community contribution)

companies/xing.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_xing_1692882588992%2Fcompanies%2Fxing.json )**
=> Update 'NEW WORK SE' (community contribution)

companies/ingenico-eu.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_ingenico-eu_1693558342144%2Fcompanies%2Fingenico-eu.json )**
=> Update 'INGENICO' (community contribution)

companies/bw-bank.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_bw-bank_1694188342887%2Fcompanies%2Fbw-bank.json )**
=> Update 'Baden-Württembergische Bank (BW-Bank)' (community contribution)

companies/acxiom.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_acxiom_1694193699654%2Fcompanies%2Facxiom.json )**
=> Update 'Acxiom Deutschland GmbH' (community contribution)

companies/ebay-kleinanzeigen-gmbh.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_ebay-kleinanzeigen-gmbh_1694443055194%2Fcompanies%2Febay-kleinanzeigen-gmbh.json )**
=> Update 'kleinanzeigen.de GmbH' (community contribution)

companies/mcm-init-com.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_mcm-init-com_1694983529547%2Fcompanies%2Fmcm-init-com.json )**
=> Update 'mcm.init UG (haftungsbeschränkt)' (community contribution)

companies/studydrive.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_studydrive_1694635433173%2Fcompanies%2Fstudydrive.json )**
=> Update 'Studydrive GmbH' (community contribution)

companies/voiscooterscom.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_voiscooterscom_1694637951776%2Fcompanies%2Fvoiscooterscom.json )**
=> Update 'Voi Technology AB' (community contribution)

companies/shein.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_shein_1695583741723%2Fcompanies%2Fshein.json )**
=> Update 'Infinite Styles Ecommerce Co., Ltd.' (community contribution)

companies/dance-all-day.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_dance-all-day_1695705680244%2Fcompanies%2Fdance-all-day.json )**
=> Update 'Dance All Day Musicvertriebs GmbH' (community contribution)

companies/elv.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_elv_1696545241273%2Fcompanies%2Felv.json )**
=> Update 'ELV Elektronik AG' (community contribution)

companies/orf.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_orf_1696810115202%2Fcompanies%2Forf.json )**
=> Update 'Österreichischer Rundfunk (ORF)' (community contribution)

companies/tier-mobility-de.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_tier-mobility-de_1696850644903%2Fcompanies%2Ftier-mobility-de.json )**
=> Update 'Tier Mobility SE' (community contribution)

companies/debeka.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_debeka_1697652995849%2Fcompanies%2Fdebeka.json )**
=> Update 'Debeka-Gruppe' (community contribution)

companies/klinikum-ingolstadt.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_klinikum-ingolstadt_1696789867161%2Fcompanies%2Fklinikum-ingolstadt.json )**
=> Add 'Klinikum Ingolstadt GmbH' (community contribution)

companies/rmv.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_rmv_1697550751027%2Fcompanies%2Frmv.json )**
=> Add 'Rhein-Main-Verkehrsverbund GmbH' (community contribution)

companies/fr.json, companies/frankfurter-rundschau.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_fr_1697551101939%2Fcompanies%2Ffr.json )**
=> Add 'Frankfurter Rundschau GmbH' (community contribution)

companies/mannheimer-morgen.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_mannheimer-morgen_1697551500770%2Fcompanies%2Fmannheimer-morgen.json )**
=> Add 'Mannheimer Morgen Großdruckerei und Verlag GmbH' (community contribution)

companies/oekotest.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_oekotest_1697553027567%2Fcompanies%2Foekotest.json )**
=> Add 'ÖKO-TEST GmbH & Co. KG' (community contribution)

companies/stiftung-warentest.json, companies/test.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_test_1697553135065%2Fcompanies%2Ftest.json )**
=> Add 'Stiftung Warentest' (community contribution)

companies/medikompass.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_medikompass_1697570522226%2Fcompanies%2Fmedikompass.json )**
=> Add 'MediKompass GmbH' (community contribution)

companies/veja-faire-trade-sarl.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_veja-faire-trade-sarl_1697571737570%2Fcompanies%2Fveja-faire-trade-sarl.json )**
=> Add 'Veja Faire Trade SARL' (community contribution)

companies/triodos.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_triodos_1697572324699%2Fcompanies%2Ftriodos.json )**
=> Add 'Triodos Bank N.V. Deutschland' (community contribution)

companies/cineplex.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_cineplex_1697573489571%2Fcompanies%2Fcineplex.json )**
=> Add 'CINEPLEX Deutschland GmbH & Co. KG' (community contribution)

companies/fielmann-de.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_fielmann-de_1695826538035%2Fcompanies%2Ffielmann-de.json )**
=> Update 'Fielmann AG' (community contribution)

companies/gov.json, companies/ministry-of-justice-gb.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_gov_1688957754265%2Fcompanies%2Fgov.json )**
=> Add 'Ministry of Justice' (community contribution)

companies/dwp-gov-uk.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_dwp-gov-uk_1688958522262%2Fcompanies%2Fdwp-gov-uk.json )**
=> Update 'Department for Work and Pensions' (community contribution)

companies/hmrc-gb.json, companies/hmrc-gov.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_hmrc-gov_1688959133395%2Fcompanies%2Fhmrc-gov.json )**
=> Add 'HM Revenue and Customs' (community contribution)

companies/socialsecurity-gov.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_socialsecurity-gov_1688959905326%2Fcompanies%2Fsocialsecurity-gov.json )**
=> Add 'Social Security Scotland' (community contribution)

companies/gmp-police.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_gmp-police_1690584924316%2Fcompanies%2Fgmp-police.json )**
=> Update 'Chief Constable Greater Manchester Police' (community contribution)

companies/revolut-com.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_revolut-com_1691665957761%2Fcompanies%2Frevolut-com.json )**
=> Update 'Revolut Ltd.' (community contribution)

companies/sedo-de.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_sedo-de_1696241278263%2Fcompanies%2Fsedo-de.json )**
=> Update 'Sedo GmbH' (community contribution)

companies/hp-store.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_hp-store_1697311594738%2Fcompanies%2Fhp-store.json )**
=> Update 'HP Deutschland GmbH' (community contribution)

companies/saturn-shop.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_saturn-shop_1697356608166%2Fcompanies%2Fsaturn-shop.json )**
=> Update 'Saturn.de' (community contribution)

companies/congstar.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_congstar_1697472429430%2Fcompanies%2Fcongstar.json )**
=> Update 'congstar' (community contribution)

companies/adeccogroup.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_adeccogroup_1697647227001%2Fcompanies%2Fadeccogroup.json )**
=> Add 'Adecco Group Germany' (community contribution)

companies/snuffstore-de.json, companies/snuffstore.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_snuffstore_1697792734476%2Fcompanies%2Fsnuffstore.json )**
=> Add 'Stratton Oakmont Innovations oü' (community contribution)

companies/job4you.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_job4you_1697830702461%2Fcompanies%2Fjob4you.json )**
=> Add 'Job4You Software KG' (community contribution)

companies/volksbank-eisenberg.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_volksbank-eisenberg_1698406666877%2Fcompanies%2Fvolksbank-eisenberg.json )**
=> Update 'Volksbank Eisenberg eG' (community contribution)

companies/ethikbank.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_ethikbank_1698406798625%2Fcompanies%2Fethikbank.json )**
=> Add 'EthikBank eG, Zwgndl. der Volksbank Eisenberg eG' (community contribution)

companies/odgersberndtson.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_odgersberndtson_1698826417275%2Fcompanies%2Fodgersberndtson.json )**
=> Add 'Odgers Berndtson' (community contribution)

companies/data-factory.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_data-factory_1698828982668%2Fcompanies%2Fdata-factory.json )**
=> Add ':data factory GmbH' (community contribution)

companies/samsung.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_samsung_1698976760139%2Fcompanies%2Fsamsung.json )**
=> Add 'Samsung Electronics (UK) Limited' (community contribution)

companies/dtv-verlag.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_dtv-verlag_1699121318020%2Fcompanies%2Fdtv-verlag.json )**
=> Update 'dtv Verlagsgesellschaft mbH & Co. KG' (community contribution)

companies/twitter.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_twitter_1699454535361%2Fcompanies%2Ftwitter.json )**
=> Update 'Twitter International Unlimited Company' (community contribution)

companies/humblebundle.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_humblebundle_1700128799763%2Fcompanies%2Fhumblebundle.json )**
=> Update 'Humble Bundle, Inc.' (community contribution)

companies/kinderaerzte-im-netz.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_kinderaerzte-im-netz_1700150561404%2Fcompanies%2Fkinderaerzte-im-netz.json )**
=> Add 'Dr. med. univ. Michael Torbahn Facharzt für Kinder- und Jugendmedizin' (community contribution)

companies/conrad.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_conrad_1700375215234%2Fcompanies%2Fconrad.json )**
=> Update 'Conrad Electronic SE' (community contribution)

companies/jacques-wein-depot.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_jacques-wein-depot_1700653349275%2Fcompanies%2Fjacques-wein-depot.json )**
=> Add 'Jacques’ Wein-Depot Wein-Einzelhandel GmbH' (community contribution)

companies/finya.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_finya_1704020101967%2Fcompanies%2Ffinya.json )**
=> Update 'Finya GmbH & Co. KG' (community contribution)

companies/post-at.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_post-at_1704513445949%2Fcompanies%2Fpost-at.json )**
=> Update 'Österreichische Post AG' (community contribution)

companies/openai-ireland-limited.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_openai-ireland-limited_1703458676444%2Fcompanies%2Fopenai-ireland-limited.json )**
=> Add 'OpenAI Ireland Limited' (community contribution)

companies/fibonaccicode.json, companies/jafari-consulting-gmb-h.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_fibonaccicode_1704628663149%2Fcompanies%2Ffibonaccicode.json )**
=> Add 'Jafari Consulting GmbH' (community contribution)

companies/wolt-com.json, companies/wolt-de.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_wolt-de_1704886656237%2Fcompanies%2Fwolt-de.json )**
=> Update 'Wolt Enterprises Oy' (community contribution)

companies/easypark-gmbh.json, companies/easypark.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_easypark_1704926358540%2Fcompanies%2Feasypark.json )**
=> Add 'Easypark GmbH' (community contribution)

companies/cls-computer.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_cls-computer_1706606181410%2Fcompanies%2Fcls-computer.json )**
=> Add 'CLS Computer' (community contribution)

companies/bs-energy.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_bs-energy_1706782241595%2Fcompanies%2Fbs-energy.json )**
=> Update 'Braunschweiger Versorgungs-AG & Co. KG (BS|ENERGY)' (community contribution)

companies/proaesthetic.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_proaesthetic_1708674422388%2Fcompanies%2Fproaesthetic.json )**
=> Add 'Heidelberger Klinik für plastische und kosmetische Chirurgie proaesthetic GmbH' (community contribution)

companies/orf-beitrag.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_orf-beitrag_1708375471018%2Fcompanies%2Forf-beitrag.json )**
=> Add 'ORF-Beitrags Service GmbH (OBS)' (community contribution)

companies/neu-de.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_neu-de_1700382186532%2Fcompanies%2Fneu-de.json )**
=> Update 'NEU.DE GmbH' (community contribution)

companies/datenschutz-planb-ruhr-de.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_datenschutz-planb-ruhr-de_1700729984486%2Fcompanies%2Fdatenschutz-planb-ruhr-de.json )**
=> Add 'PLANB Ruhr e.V.' (community contribution)

companies/ticketmaster-de.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_ticketmaster-de_1712661377917%2Fcompanies%2Fticketmaster-de.json )**
=> Update 'Ticketmaster GmbH' (community contribution)

companies/ibm.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_ibm_1701340795877%2Fcompanies%2Fibm.json )**
=> Update 'IBM International Group B.V.' (community contribution)

companies/proaesthetic.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_proaesthetic_1709040277524%2Fcompanies%2Fproaesthetic.json )**
=> Update 'Heidelberger Klinik für plastische und kosmetische Chirurgie proaesthetic GmbH' (community contribution)

companies/ebay-de.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_ebay-de_1709460964882%2Fcompanies%2Febay-de.json )**
=> Update 'eBay GmbH' (community contribution)

companies/provinzial-versicherung.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_provinzial-versicherung_1710929841185%2Fcompanies%2Fprovinzial-versicherung.json )**
=> Update 'Westfälische Provinzial Versicherung AG' (community contribution)

companies/brandmarkt.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_brandmarkt_1711008836641%2Fcompanies%2Fbrandmarkt.json )**
=> Update 'Brandmarkt-Outlet' (community contribution)

companies/eprimo.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_eprimo_1711452253410%2Fcompanies%2Feprimo.json )**
=> Update 'eprimo GmbH' (community contribution)

companies/fti-touristik.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_fti-touristik_1712061487955%2Fcompanies%2Ffti-touristik.json )**
=> Update 'FTI Touristik GmbH' (community contribution)

companies/netbank.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_netbank_1713650577043%2Fcompanies%2Fnetbank.json )**
=> Update 'netbank' (community contribution)

companies/freenet-de.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_freenet-de_1700213381879%2Fcompanies%2Ffreenet-de.json )**
=> Update 'freenet.de GmbH' (community contribution)

companies/merton-council.json, companies/merton-gov.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_merton-gov_1700274629675%2Fcompanies%2Fmerton-gov.json )**
=> Add 'Merton Council' (community contribution)

companies/lovoo.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_lovoo_1700573375969%2Fcompanies%2Flovoo.json )**
=> Add 'LOOVO' (community contribution)

companies/goertz.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_goertz_1700853922447%2Fcompanies%2Fgoertz.json )**
=> Add 'Görtz Retail GmbH' (community contribution)

companies/emil-energie.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_emil-energie_1700897803788%2Fcompanies%2Femil-energie.json )**
=> Add 'emil energie GmbH' (community contribution)

companies/mtgmbh.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_mtgmbh_1701082877440%2Fcompanies%2Fmtgmbh.json )**
=> Add 'MTG Miettreuhandgesellschaft mbH' (community contribution)

companies/supreme-me.json, companies/supreme.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_supreme_1701531004869%2Fcompanies%2Fsupreme.json )**
=> Add 'Supreme Media AG' (community contribution)

companies/infynd.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_infynd_1702467682788%2Fcompanies%2Finfynd.json )**
=> Add 'InFynd' (community contribution)

companies/tebio.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_tebio_1703456916282%2Fcompanies%2Ftebio.json )**
=> Add 'Tebio GmbH' (community contribution)

companies/mymiglia.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_mymiglia_1703781152432%2Fcompanies%2Fmymiglia.json )**
=> Add 'Italia Loyalty S.p.A.' (community contribution)

companies/antec-servicepool.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_antec-servicepool_1705152834508%2Fcompanies%2Fantec-servicepool.json )**
=> Add 'ANTEC Servicepool GmbH' (community contribution)

companies/bitmaster-online.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_bitmaster-online_1702228169849%2Fcompanies%2Fbitmaster-online.json )**
=> Update 'Bitmaster Online B.V.' (community contribution)

companies/autohero-com.json, companies/autohero.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_autohero_1707071896114%2Fcompanies%2Fautohero.json )**
=> Add 'Autohero GmbH' (community contribution)

companies/leuchtturm1917.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_leuchtturm1917_1708198736402%2Fcompanies%2Fleuchtturm1917.json )**
=> Add 'LEUCHTTURM GRUPPE GMBH & CO. KG' (community contribution)

companies/oculuscom.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_oculuscom_1714127420584%2Fcompanies%2Foculuscom.json )**
=> Update 'Meta Platforms Ireland Ltd.' (community contribution)

companies/pp-trading.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_pp-trading_1707925265418%2Fcompanies%2Fpp-trading.json )**
=> Add 'PP-Trading' (community contribution)

companies/interhyp.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_interhyp_1708931195221%2Fcompanies%2Finterhyp.json )**
=> Add 'Interhyp AG' (community contribution)

companies/milanote.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_milanote_1709197983650%2Fcompanies%2Fmilanote.json )**
=> Add 'Milanote Pty Ltd' (community contribution)

companies/prixtel.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_prixtel_1709243496049%2Fcompanies%2Fprixtel.json )**
=> Add 'Prixtel SAS' (community contribution)

companies/leroy-merlin.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_leroy-merlin_1709247235194%2Fcompanies%2Fleroy-merlin.json )**
=> Add 'Leroy Merlin' (community contribution)

companies/carfax.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_carfax_1710035411938%2Fcompanies%2Fcarfax.json )**
=> Add 'CARFAX Europe GmbH' (community contribution)

companies/mega-io.json, companies/mega.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_mega_1710036389187%2Fcompanies%2Fmega.json )**
=> Add 'Mega Limited' (community contribution)

companies/mullvad.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_mullvad_1710037002798%2Fcompanies%2Fmullvad.json )**
=> Add 'Mullvad VPN AB' (community contribution)

companies/von-poll.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_von-poll_1710166386061%2Fcompanies%2Fvon-poll.json )**
=> Add 'von Poll Immobilien GmbH' (community contribution)

companies/laserteile4you.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_laserteile4you_1710359086309%2Fcompanies%2Flaserteile4you.json )**
=> Add 'H.P. Kaysser GmbH + Co. KG' (community contribution)

companies/weltsparen.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_weltsparen_1710857337005%2Fcompanies%2Fweltsparen.json )**
=> Add 'Weltsparen' (community contribution)

companies/primastrom.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_primastrom_1711302063703%2Fcompanies%2Fprimastrom.json )**
=> Add 'primastrom GmbH' (community contribution)

companies/camelactive.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_camelactive_1711483086232%2Fcompanies%2Fcamelactive.json )**
=> Add 'Bültel Worldwide Fashion GmbH & Co. KG' (community contribution)

companies/drawboard.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_drawboard_1711497331522%2Fcompanies%2Fdrawboard.json )**
=> Add 'Drawboard Pty Ltd.' (community contribution)

companies/digitalcourage.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_digitalcourage_1712591559685%2Fcompanies%2Fdigitalcourage.json )**
=> Add 'Digitalcourage e.V.' (community contribution)

companies/sony-music-entertainment-germany.json, companies/sonymusic.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_sonymusic_1712648766616%2Fcompanies%2Fsonymusic.json )**
=> Add 'Sony Music Entertainment Germany' (community contribution)

companies/eyesandmore.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_eyesandmore_1712728587413%2Fcompanies%2Feyesandmore.json )**
=> Add 'eyes and more GmbH' (community contribution)

companies/bazaarofmagic.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_bazaarofmagic_1712995294107%2Fcompanies%2Fbazaarofmagic.json )**
=> Add 'Bazaar of Magic' (community contribution)

companies/opentable-de.json, companies/opentable-inc.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_opentable-inc_1713105340034%2Fcompanies%2Fopentable-inc.json )**
=> Add 'OpenTable GmbH' (community contribution)

companies/tricount.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_tricount_1713436763507%2Fcompanies%2Ftricount.json )**
=> Add 'Tricount S.A.' (community contribution)

companies/napster.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_napster_1713441001864%2Fcompanies%2Fnapster.json )**
=> Add 'Napster Luxembourg S.a.r.l.' (community contribution)

companies/elisabeth-von-thadden-schule.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_elisabeth-von-thadden-schule_1713651442890%2Fcompanies%2Felisabeth-von-thadden-schule.json )**
=> Add 'Elisabeth-von-Thadden-Schule' (community contribution)

companies/stats-fm.json, companies/stats.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_stats_1714841622743%2Fcompanies%2Fstats.json )**
=> Add 'StatsFM B.V.' (community contribution)

companies/suno-com.json, companies/suno.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_suno_1714895255133%2Fcompanies%2Fsuno.json )**
=> Add 'Suno, Inc.' (community contribution)

companies/stadtverwaltung-erfurt.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_stadtverwaltung-erfurt_1715029253838%2Fcompanies%2Fstadtverwaltung-erfurt.json )**
=> Add 'Stadtverwaltung Erfurt' (community contribution)

companies/secure-splitwise.json, companies/splitwise.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_secure-splitwise_1715963676253%2Fcompanies%2Fsecure-splitwise.json )**
=> Add 'Splitwise Inc.' (community contribution)

companies/utiq.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_utiq_1715965908129%2Fcompanies%2Futiq.json )**
=> Add 'Utiq SA/NV' (community contribution)

companies/atala.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_atala_1715973660431%2Fcompanies%2Fatala.json )**
=> Add 'Atala GmbH & Co. Fliesen- und Sanitärhandel KG' (community contribution)

companies/uber.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_uber_1716032785534%2Fcompanies%2Fuber.json )**
=> Add 'Uber Technologies Inc.' (community contribution)

companies/addconti.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_addconti_1721151650406%2Fcompanies%2Faddconti.json )**
=> Update 'Add Conti GmbH' (community contribution)

companies/egentic.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_egentic_1719741299049%2Fcompanies%2Fegentic.json )**
=> Update 'eGENTIC GmbH' (community contribution)

companies/uestra.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_uestra_1730030320151%2Fcompanies%2Fuestra.json )**
=> Update 'ÜSTRA Hannoversche Verkehrsbetriebe Aktiengesellschaft' (community contribution)

companies/zarenga.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_zarenga_1729712789062%2Fcompanies%2Fzarenga.json )**
=> Update 'Zarenga GmbH' (community contribution)

companies/snuffstore-de.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_snuffstore-de_1728640727707%2Fcompanies%2Fsnuffstore-de.json )**
=> Update 'Stratton Oakmont Innovations oü' (community contribution)

companies/freelancermap.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_freelancermap_1727776353724%2Fcompanies%2Ffreelancermap.json )**
=> Update 'freelancermap GmbH' (community contribution)

companies/klarmobil.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_klarmobil_1725910034465%2Fcompanies%2Fklarmobil.json )**
=> Update 'klarmobil GmbH' (community contribution)

companies/netflix.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_netflix_1728909858247%2Fcompanies%2Fnetflix.json )**
=> Update 'Netflix International B.V.' (community contribution)

companies/primastrom.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_primastrom_1728229416357%2Fcompanies%2Fprimastrom.json )**
=> Update 'primastrom GmbH' (community contribution)

companies/bumble.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_bumble_1725210366094%2Fcompanies%2Fbumble.json )**
=> Update 'Bumble Group' (community contribution)

companies/open-knowledge-foundation-deutschland-ev.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_open-knowledge-foundation-deutschland-ev_1724853729918%2Fcompanies%2Fopen-knowledge-foundation-deutschland-ev.json )**
=> Update 'Open Knowledge Foundation Deutschland e.V.' (community contribution)

companies/stats-fm.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_stats-fm_1724324114832%2Fcompanies%2Fstats-fm.json )**
=> Update 'StatsFM B.V.' (community contribution)

companies/skyhire.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_skyhire_1716409601114%2Fcompanies%2Fskyhire.json )**
=> Add 'SkyHire GmbH' (community contribution)

companies/wm-beautysystems.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_wm-beautysystems_1716549989396%2Fcompanies%2Fwm-beautysystems.json )**
=> Add 'WM BEAUTYSYSTEMS AG & Co. KG' (community contribution)

companies/caritas-erzbistum-koeln.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_caritas-erzbistum-koeln_1716968902830%2Fcompanies%2Fcaritas-erzbistum-koeln.json )**
=> Add 'Sozialdienst Katholischer Frauen Rhein-Erft-Kreis e.V.' (community contribution)

companies/maxdome.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_maxdome_1717783044300%2Fcompanies%2Fmaxdome.json )**
=> Update '7TV Joint Venture GmbH' (community contribution)

companies/c24-bank-gmbh.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_c24-bank-gmbh_1724905452537%2Fcompanies%2Fc24-bank-gmbh.json )**
=> Add 'C24 Bank GmbH' (community contribution)

companies/stoelting-gruppe.json
**Edit in: [company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_stoelting-gruppe_1730581564674%2Fcompanies%2Fstoelting-gruppe.json), [data editor](https://data-editor.datenanfragen.de/#/review/2896)[^1]**
=> Add 'Stölting Service Group GmbH' (community contribution)

companies/wws-security.json
**Edit in: [company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_wws-security_1730581188645%2Fcompanies%2Fwws-security.json), [data editor](https://data-editor.datenanfragen.de/#/review/2895)[^1]**
=> Add 'Westfälischer Wachschutz GmbH & Co. KG' (community contribution)

companies/monkee.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_monkee_1718093507557%2Fcompanies%2Fmonkee.json )**
=> Add 'Monkee GmbH' (community contribution)

companies/stadtverwaltung-weimar.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_stadtverwaltung-weimar_1724698905338%2Fcompanies%2Fstadtverwaltung-weimar.json )**
=> Add 'Stadtverwaltung Weimar' (community contribution)

companies/sophien-und-hufeland-klinikum-ggmbh.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_sophien-und-hufeland-klinikum-ggmbh_1724699452363%2Fcompanies%2Fsophien-und-hufeland-klinikum-ggmbh.json )**
=> Add 'Sophien- und Hufeland-Klinikum gGmbH' (community contribution)

companies/reddit.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_reddit_1709684671909%2Fcompanies%2Freddit.json )**
=> Update 'Reddit Netherlands B.V.' (community contribution)

companies/iserv.json
**Edit in: [company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_iserv_1730911132684%2Fcompanies%2Fiserv.json), [data editor](https://data-editor.datenanfragen.de/#/review/2907)[^1]**
=> Update 'IServ GmbH' (community contribution)

companies/samsung-electronics-gmbh.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_samsung-electronics-gmbh_1717170473067%2Fcompanies%2Fsamsung-electronics-gmbh.json )**
=> Add 'Samsung Electronics GmbH' (community contribution)

companies/pullandbear-de.json, companies/pullandbear.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_pullandbear_1718718875461%2Fcompanies%2Fpullandbear.json )**
=> Add 'PULL & BEAR Deutschland B.V. & Co. KG' (community contribution)

companies/ups.json
**Edit in: [company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_ups_1730920063854%2Fcompanies%2Fups.json), [data editor](https://data-editor.datenanfragen.de/#/review/2913)[^1]**
=> Update 'UPS Europe SA' (community contribution)

companies/aadia.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_aadia_1708068521314%2Fcompanies%2Faadia.json )**
=> Add 'Confer UG' (community contribution)

companies/notion.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_notion_1724342567848%2Fcompanies%2Fnotion.json )**
=> Add 'Notion Labs, Inc.' (community contribution)

companies/klm.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_klm_1724325895456%2Fcompanies%2Fklm.json )**
=> Add 'KLM Royal Dutch Airlines' (community contribution)

companies/kaspersky.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_kaspersky_1720991665386%2Fcompanies%2Fkaspersky.json )**
=> Add 'Kaspersky Labs GmbH' (community contribution)

companies/maginteractive.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_maginteractive_1709742142553%2Fcompanies%2Fmaginteractive.json )**
=> Add 'MAG Interactive AB' (community contribution)

companies/samsung.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_samsung_1727817300346%2Fcompanies%2Fsamsung.json )**
=> Update 'Samsung Electronics (UK) Limited' (community contribution)

companies/deepl-se.json, companies/deepl.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_deepl-se_1728249771800%2Fcompanies%2Fdeepl-se.json )**
=> Add 'DeepL SE' (community contribution)

companies/bsw-vg.json
**Edit in: [company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_bsw-vg_1730913783439%2Fcompanies%2Fbsw-vg.json), [data editor](https://data-editor.datenanfragen.de/#/review/2912)[^1]**
=> Add 'Bündnis Sahra Wagenknecht – Vernunft und Gerechtigkeit' (community contribution)

companies/time-for-kids.json
**Edit in: [company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_time-for-kids_1730913439362%2Fcompanies%2Ftime-for-kids.json), [data editor](https://data-editor.datenanfragen.de/#/review/2911)[^1]**
=> Add 'TIME for kids Informationstechnologien GmbH' (community contribution)

companies/afd.json
**Edit in: [company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_afd_1730913207963%2Fcompanies%2Fafd.json), [data editor](https://data-editor.datenanfragen.de/#/review/2910)[^1]**
=> Update '„Alternative für Deutschland“ (AfD)' (community contribution)

companies/aktion-deutschland-hilft.json
**Edit in: [company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_aktion-deutschland-hilft_1731769090859%2Fcompanies%2Faktion-deutschland-hilft.json), [data editor](https://data-editor.datenanfragen.de/#/review/2920)[^1]**
=> Add 'Aktion Deutschland Hilft e. V.' (community contribution)

companies/id5.json
**Edit in: [company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_id5_1732025737084%2Fcompanies%2Fid5.json), [data editor](https://data-editor.datenanfragen.de/#/review/2923)[^1]**
=> Add 'ID5 Technology Ltd.' (community contribution)

companies/adagio.json
**Edit in: [company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_adagio_1732194085938%2Fcompanies%2Fadagio.json), [data editor](https://data-editor.datenanfragen.de/#/review/2926)[^1]**
=> Add 'Onfocus SAS' (community contribution)

companies/pubmatic.json
**Edit in: [company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_pubmatic_1732619654866%2Fcompanies%2Fpubmatic.json), [data editor](https://data-editor.datenanfragen.de/#/review/2935)[^1]**
=> Add 'PubMatic GmbH' (community contribution)

companies/yoc-ag.json, companies/yoc.json
**Edit in: [company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_yoc_1732870764716%2Fcompanies%2Fyoc.json), [data editor](https://data-editor.datenanfragen.de/#/review/2937)[^1]**
=> Add 'YOC AG' (community contribution)

companies/sovrn.json
**Edit in: [company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_sovrn_1732873614882%2Fcompanies%2Fsovrn.json), [data editor](https://data-editor.datenanfragen.de/#/review/2938)[^1]**
=> Update 'Sovrn Holdings, Inc.' (community contribution)

companies/nortonlifelock.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_nortonlifelock_1721901411936%2Fcompanies%2Fnortonlifelock.json )**
=> Update 'NortonLifeLock Ireland Limited' (community contribution)

companies/gutefrage-net.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_gutefrage-net_1724904602149%2Fcompanies%2Fgutefrage-net.json )**
=> Update 'gutefrage.net GmbH' (community contribution)

companies/rocketreach.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_rocketreach_1726869483807%2Fcompanies%2Frocketreach.json )**
=> Update 'RocketReach' (community contribution)

companies/kfzteile24-de.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_kfzteile24-de_1729580013830%2Fcompanies%2Fkfzteile24-de.json )**
=> Update 'kfzteile24 GmbH' (community contribution)

companies/all-travel-marketing.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_all-travel-marketing_1730134997515%2Fcompanies%2Fall-travel-marketing.json )**
=> Update 'All Travel Marketing GmbH' (community contribution)

companies/franzis.json
**Edit in: [company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_franzis_1732204640362%2Fcompanies%2Ffranzis.json), [data editor](https://data-editor.datenanfragen.de/#/review/2928)[^1]**
=> Update 'FRANZIS GmbH' (community contribution)

companies/verti.json
**Edit in: [company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_verti_1733624069912%2Fcompanies%2Fverti.json), [data editor](https://data-editor.datenanfragen.de/#/review/2948)[^1]**
=> Update 'Verti Versicherung AG' (community contribution)

companies/medicoreports.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_medicoreports_1716792642046%2Fcompanies%2Fmedicoreports.json )**
=> Add 'Medqon Limited' (community contribution)

companies/runalyze.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_runalyze_1716967096463%2Fcompanies%2Frunalyze.json )**
=> Add 'Runalyze GmbH' (community contribution)

companies/jaksch-partner.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_jaksch-partner_1720030967236%2Fcompanies%2Fjaksch-partner.json )**
=> Add 'JAKSCH & PARTNER - Jaksch Research GmbH' (community contribution)

companies/sharethrough.json
**Edit in: [company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_sharethrough_1734520776878%2Fcompanies%2Fsharethrough.json), [data editor](https://data-editor.datenanfragen.de/#/review/2954)[^1]**
=> Add 'Sharethrough Inc.' (community contribution)

companies/datarade.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_datarade_1722793786802%2Fcompanies%2Fdatarade.json )**
=> Add 'Datarade GmbH' (community contribution)

companies/payback.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_payback_1725132221915%2Fcompanies%2Fpayback.json )**
=> Update 'PAYBACK GmbH' (community contribution)

companies/mastercard-eu.json
**Edit in: [company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_mastercard-eu_1738650547006%2Fcompanies%2Fmastercard-eu.json), [data editor](https://data-editor.datenanfragen.de/#/review/3000)[^1]**
=> Update 'Mastercard Europe SA' (community contribution)

companies/mtch-technology.json
**Edit in: [company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_mtch-technology_1738761057929%2Fcompanies%2Fmtch-technology.json), [data editor](https://data-editor.datenanfragen.de/#/review/3003)[^1]**
=> Update 'MTCH Technology Services Limited' (community contribution)

companies/demcon-life-sciences-health-enschede-b-v.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_demcon-life-sciences-health-enschede-b-v_1718730763964%2Fcompanies%2Fdemcon-life-sciences-health-enschede-b-v.json )**
=> Add 'DEMCON management & support B.V.' (community contribution)

companies/shimano.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_shimano_1724821825617%2Fcompanies%2Fshimano.json )**
=> Add 'Shimano Europe B.V.' (community contribution)

companies/only-fans.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_only-fans_1724686701237%2Fcompanies%2Fonly-fans.json )**
=> Add 'Fenix International Limited' (community contribution)

companies/canon-deutschland.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_canon-deutschland_1725136444275%2Fcompanies%2Fcanon-deutschland.json )**
=> Add 'Canon Deutschland' (community contribution)

companies/epson-europe-b-v.json, companies/epson-europe.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_epson-europe-b-v_1725136698328%2Fcompanies%2Fepson-europe-b-v.json )**
=> Add 'Epson Europe B.V.' (community contribution)

companies/carl-zeiss-ag.json, companies/carl-zeiss.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_carl-zeiss-ag_1725479632417%2Fcompanies%2Fcarl-zeiss-ag.json )**
=> Add 'Carl Zeiss AG' (community contribution)

companies/ticket-io.json
**Edit in: [company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_ticket-io_1734907438560%2Fcompanies%2Fticket-io.json), [data editor](https://data-editor.datenanfragen.de/#/review/2957)[^1]**
=> Update 'Ticket i/O GmbH' (community contribution)

companies/radissonhotels.json
**Edit in: [company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_radissonhotels_1732230110683%2Fcompanies%2Fradissonhotels.json), [data editor](https://data-editor.datenanfragen.de/#/review/2931)[^1]**
=> Add 'Radisson Hotel Group' (community contribution)

companies/pg-de.json, companies/procter-gamble-p-g.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_procter-gamble-p-g_1725462202499%2Fcompanies%2Fprocter-gamble-p-g.json )**
=> Add 'Procter & Gamble Service GmbH' (community contribution)

companies/advanced-micro-devices-inc.json, companies/amd.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_advanced-micro-devices-inc_1725132771224%2Fcompanies%2Fadvanced-micro-devices-inc.json )**
=> Add 'Advanced Micro Devices Inc.' (community contribution)

companies/redsift.json
**Edit in: [company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_redsift_1739136580592%2Fcompanies%2Fredsift.json), [data editor](https://data-editor.datenanfragen.de/#/review/3008)[^1]**
=> Update 'Redsift Limited' (community contribution)

companies/gamblizard.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_gamblizard_1721656862540%2Fcompanies%2Fgamblizard.json )**
=> Add 'Gamblizard' (community contribution)

companies/stadtwerke-weimar-stadtversorgungs-gmbh.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_stadtwerke-weimar-stadtversorgungs-gmbh_1724698713068%2Fcompanies%2Fstadtwerke-weimar-stadtversorgungs-gmbh.json )**
=> Add 'Stadtwerke Weimar Stadtversorgungs-GmbH' (community contribution)

companies/ardmed-medical-supplies-gmbh-co-kg.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_ardmed-medical-supplies-gmbh-co-kg_1724586823060%2Fcompanies%2Fardmed-medical-supplies-gmbh-co-kg.json )**
=> Add 'ARDMED Medical Supplies GmbH & Co. KG' (community contribution)

companies/swe-stadtwerke-erfurt-gmbh.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_swe-stadtwerke-erfurt-gmbh_1724698837142%2Fcompanies%2Fswe-stadtwerke-erfurt-gmbh.json )**
=> Add 'SWE Stadtwerke Erfurt GmbH' (community contribution)

companies/deutsche-lebens-rettungs-gesellschaft-dlrg.json, companies/dlrg-de.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_deutsche-lebens-rettungs-gesellschaft-dlrg_1724699947266%2Fcompanies%2Fdeutsche-lebens-rettungs-gesellschaft-dlrg.json )**
=> Add 'Deutsche Lebens-Rettungs-Gesellschaft (DLRG)' (community contribution)

companies/cube.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_cube_1724821926891%2Fcompanies%2Fcube.json )**
=> Add 'Pending System GmbH & Co. KG' (community contribution)

companies/chip-de.json, companies/chip.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_chip_1724853113958%2Fcompanies%2Fchip.json )**
=> Add 'BurdaForward GmbH' (community contribution)

companies/gessgroup-de.json, companies/gessgroup.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_gessgroup_1720977183759%2Fcompanies%2Fgessgroup.json )**
=> Add 'GESS Gesellschaft für Software in der Sozialforschung mbH' (community contribution)

companies/amboss-gmbh.json, companies/amboss-se.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_amboss-gmbh_1724905220429%2Fcompanies%2Famboss-gmbh.json )**
=> Add 'AMBOSS SE' (community contribution)

companies/emeraldhost.json
**Edit in: [company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_emeraldhost_1741873209112%2Fcompanies%2Femeraldhost.json), [data editor](https://data-editor.datenanfragen.de/#/review/3044)[^1]**
=> Update 'EmeraldHost UG (haftungsbeschränkt)' (community contribution)

companies/exotargets.json
Fixes https://github.com/datenanfragen/data/issues/3045 and also updates the source URL regarding data protection.
=> fix: 'eXotargets Data Network GmbH' data

companies/happycar.json
**Edit in: [company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_happycar_1739527302089%2Fcompanies%2Fhappycar.json), [data editor](https://data-editor.datenanfragen.de/#/review/3015)[^1]**
=> Update 'HAPPYCAR GmbH' (community contribution)

companies/strassenverkehrsabteilung-bs.json
**Edit in: [company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_strassenverkehrsabteilung-bs_1733622560363%2Fcompanies%2Fstrassenverkehrsabteilung-bs.json), [data editor](https://data-editor.datenanfragen.de/#/review/2946)[^1]**
=> Update 'Stadt Braunschweig, Straßenverkehrsabteilung' (community contribution)

companies/komoot.json
**Edit in: [company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_komoot_1742584056800%2Fcompanies%2Fkomoot.json), [data editor](https://data-editor.datenanfragen.de/#/review/3056)[^1]**
=> Add 'komoot GmbH' (community contribution)

companies/berry2b-gmbh.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_berry2b-gmbh_1725137583507%2Fcompanies%2Fberry2b-gmbh.json )**
=> Add 'Berry2b GmbH' (community contribution)

companies/vidaxl-de.json, companies/vidaxl.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_vidaxl_1720696804767%2Fcompanies%2Fvidaxl.json )**
=> Add 'vidaXL marketplace Europe B.V.' (community contribution)

companies/ikano-bank-de.json
**Edit in: [company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_ikano-bank-de_1737548044174%2Fcompanies%2Fikano-bank-de.json), [data editor](https://data-editor.datenanfragen.de/#/review/2981)[^1]**
=> Update 'Ikano Bank AB (publ), Zweigniederlassung Deutschland' (community contribution)

companies/beyerdynamic.json
**Edit in: [company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_beyerdynamic_1737993869471%2Fcompanies%2Fbeyerdynamic.json), [data editor](https://data-editor.datenanfragen.de/#/review/2991)[^1]**
=> Update 'beyerdynamic GmbH & Co. KG' (community contribution)

companies/leuchtturm1917.json
**Edit in: [company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_leuchtturm1917_1738156246685%2Fcompanies%2Fleuchtturm1917.json), [data editor](https://data-editor.datenanfragen.de/#/review/2993)[^1]**
=> Update 'LEUCHTTURM GRUPPE GMBH & CO. KG' (community contribution)

companies/eu-worx-com.json
**Edit in: [company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_eu-worx-com_1739295757670%2Fcompanies%2Feu-worx-com.json), [data editor](https://data-editor.datenanfragen.de/#/review/3011)[^1]**
=> Update 'Positec Germany GmbH' (community contribution)

companies/schufa.json
**Edit in: [company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_schufa_1741268859079%2Fcompanies%2Fschufa.json), [data editor](https://data-editor.datenanfragen.de/#/review/3031)[^1]**
=> Update 'SCHUFA Holding AG' (community contribution)

companies/bolt.json
**Edit in: [company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_bolt_1741602941499%2Fcompanies%2Fbolt.json), [data editor](https://data-editor.datenanfragen.de/#/review/3036)[^1]**
=> Add 'Bolt Technology OÜ' (community contribution)

companies/goto.json
**Edit in: [company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_goto_1740843180735%2Fcompanies%2Fgoto.json), [data editor](https://data-editor.datenanfragen.de/#/review/3030)[^1]**
=> Add 'GoTo Technologies Ireland Unlimited Company' (community contribution)

companies/segway.json
**Edit in: [company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_segway_1742980022285%2Fcompanies%2Fsegway.json), [data editor](https://data-editor.datenanfragen.de/#/review/3058)[^1]**
=> Add 'Segway Europe BV' (community contribution)

companies/seamless.json
**Edit in: [company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_seamless_1743106809499%2Fcompanies%2Fseamless.json), [data editor](https://data-editor.datenanfragen.de/#/review/3066)[^1]**
=> Add 'Seamless.AI' (community contribution)

companies/transdev.json
**Edit in: [company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_transdev_1743706105070%2Fcompanies%2Ftransdev.json), [data editor](https://data-editor.datenanfragen.de/#/review/3070)[^1]**
=> Update 'Transdev Vertrieb GmbH' (community contribution)

companies/cosmosdirekt.json
**Edit in: [company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_cosmosdirekt_1743667585239%2Fcompanies%2Fcosmosdirekt.json), [data editor](https://data-editor.datenanfragen.de/#/review/3069)[^1]**
=> Update 'CosmosDirekt' (community contribution)

companies/faz.json
**Edit in: [company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_faz_1744201340802%2Fcompanies%2Ffaz.json), [data editor](https://data-editor.datenanfragen.de/#/review/3073)[^1]**
=> Update 'Frankfurter Allgemeine Zeitung GmbH' (community contribution)

companies/kirchengemeinde-st-barbara-in-wittmar.json
**Edit in: [company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_kirchengemeinde-st-barbara-in-wittmar_1745776791584%2Fcompanies%2Fkirchengemeinde-st-barbara-in-wittmar.json), [data editor](https://data-editor.datenanfragen.de/#/review/3081)[^1]**
=> Update 'Kirchengemeinde St. Barbara in Wittmar' (community contribution)

companies/viactiv.json
**Edit in: [company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_viactiv_1745993661551%2Fcompanies%2Fviactiv.json), [data editor](https://data-editor.datenanfragen.de/#/review/3085)[^1]**
=> Update 'VIACTIV Krankenkasse' (community contribution)

companies/energiekompass-hamburg.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_energiekompass-hamburg_1723128001002%2Fcompanies%2Fenergiekompass-hamburg.json )**
=> Add 'Energiekompass Hamburg UG (haftungsbeschränkt)' (community contribution)

companies/bildungswerk-f-r-gesundheitsberufe-e-v.json, companies/bildungswerk-fuer-gesundheitsberufe-erfurt.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_bildungswerk-f-r-gesundheitsberufe-e-v_1724699239161%2Fcompanies%2Fbildungswerk-f-r-gesundheitsberufe-e-v.json )**
=> Add 'Bildungswerk für Gesundheitsberufe gGmbH' (community contribution)

companies/th-ringer-landtag.json, companies/thueringer-landtag.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_th-ringer-landtag_1724822349745%2Fcompanies%2Fth-ringer-landtag.json )**
=> Add 'Thüringer Landtag' (community contribution)

companies/landespolizei-th-ringen.json, companies/landespolizeidirektion-thueringen.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_landespolizei-th-ringen_1724853234722%2Fcompanies%2Flandespolizei-th-ringen.json )**
=> Add 'Landespolizeidirektion Thüringen' (community contribution)

companies/aldi-s-d-dienstleistungs-se-co-ohg.json, companies/aldi-sued-dienstleistungs-se-co-ohg.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_aldi-s-d-dienstleistungs-se-co-ohg_1724853330067%2Fcompanies%2Faldi-s-d-dienstleistungs-se-co-ohg.json )**
=> Add 'ALDI SÜD Dienstleistungs-SE & Co. oHG' (community contribution)

companies/aldi-nord-deutschland-stiftung-co-kg.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_aldi-nord-deutschland-stiftung-co-kg_1724853375897%2Fcompanies%2Faldi-nord-deutschland-stiftung-co-kg.json )**
=> Add 'ALDI Nord Deutschland Stiftung & Co. KG' (community contribution)

companies/doccheck-com.json, companies/doccheck.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_doccheck_1724905096087%2Fcompanies%2Fdoccheck.json )**
=> Add 'DocCheck Community GmbH' (community contribution)

companies/unfallkasse-brandenburg.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_unfallkasse-brandenburg_1725136962415%2Fcompanies%2Funfallkasse-brandenburg.json )**
=> Add 'Unfallkasse Brandenburg' (community contribution)

companies/krotus-computer-de.json, companies/krotus-computer-gmbh.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_krotus-computer-gmbh_1725132570109%2Fcompanies%2Fkrotus-computer-gmbh.json )**
=> Add 'Krotus Computer GmbH' (community contribution)

companies/preisvergleich-internet-services-ag.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_preisvergleich-internet-services-ag_1725464985243%2Fcompanies%2Fpreisvergleich-internet-services-ag.json )**
=> Add 'Preisvergleich Internet Services AG' (community contribution)

companies/comdirect.json
**Edit in: [company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_comdirect_1746885714207%2Fcompanies%2Fcomdirect.json), [data editor](https://data-editor.datenanfragen.de/#/review/3102)[^1]**
=> Update 'comdirect' (community contribution)

companies/adyen-de.json
**Edit in: [company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_adyen-de_1746626300534%2Fcompanies%2Fadyen-de.json), [data editor](https://data-editor.datenanfragen.de/#/review/3095)[^1]**
=> Update 'Adyen N.V.' (community contribution)

companies/deutsche-bahn-ag.json
**Edit in: [company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_deutsche-bahn-ag_1746606579302%2Fcompanies%2Fdeutsche-bahn-ag.json), [data editor](https://data-editor.datenanfragen.de/#/review/3093)[^1]**
=> Update 'Deutsche Bahn AG' (community contribution)

companies/digital-dialog-lab.json
**Edit in: [company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_digital-dialog-lab_1748864067477%2Fcompanies%2Fdigital-dialog-lab.json), [data editor](https://data-editor.datenanfragen.de/#/review/3126)[^1]**
=> Update 'Digital Dialog Lab GmbH' (community contribution)

companies/meetic-nl.json
**Edit in: [company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_meetic-nl_1749122298079%2Fcompanies%2Fmeetic-nl.json), [data editor](https://data-editor.datenanfragen.de/#/review/3127)[^1]**
=> Update 'Meetic SAS' (community contribution)

companies/witt-weiden.json
**Edit in: [company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_witt-weiden_1749316439401%2Fcompanies%2Fwitt-weiden.json), [data editor](https://data-editor.datenanfragen.de/#/review/3129)[^1]**
=> Update 'Josef WITT GmbH' (community contribution)

companies/frankonia-handels-gmbh-co-kg.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_frankonia-handels-gmbh-co-kg_1725132374490%2Fcompanies%2Ffrankonia-handels-gmbh-co-kg.json )**
=> Add 'Frankonia Handels GmbH & Co. KG' (community contribution)

companies/wetterdienst.json
**Edit in: [company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_wetterdienst_1750418124108%2Fcompanies%2Fwetterdienst.json), [data editor](https://data-editor.datenanfragen.de/#/review/3137)[^1]**
=> Add 'Wetterdienst.de - Wetter- und Klimaberatung' (community contribution)

companies/wetter.json
**Edit in: [company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_wetter_1750417764074%2Fcompanies%2Fwetter.json), [data editor](https://data-editor.datenanfragen.de/#/review/3134)[^1]**
=> Add 'wetter.com GmbH' (community contribution)

companies/accuweather-inc.json
**Edit in: [company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_accuweather-inc_1750418399472%2Fcompanies%2Faccuweather-inc.json), [data editor](https://data-editor.datenanfragen.de/#/review/3139)[^1]**
=> Add 'AccuWeather, Inc.' (community contribution)

companies/shop-apotheke-com.json
**Edit in: [company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_shop-apotheke-com_1752583968923%2Fcompanies%2Fshop-apotheke-com.json), [data editor](https://data-editor.datenanfragen.de/#/review/3151)[^1]**
=> Update 'Shop-Apotheke B.V.' (community contribution)

companies/deutsche-gesetzliche-unfallversicherung-e-v.json, companies/dguv-de.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_deutsche-gesetzliche-unfallversicherung-e-v_1725170654488%2Fcompanies%2Fdeutsche-gesetzliche-unfallversicherung-e-v.json )**
=> Add 'Deutsche Gesetzliche Unfallversicherung e.V.' (community contribution)

companies/vr-bank-mitte-eg.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_vr-bank-mitte-eg_1724877464060%2Fcompanies%2Fvr-bank-mitte-eg.json )**
=> Add 'VR-Bank Mitte eG' (community contribution)

companies/airlineassessmentprep.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_airlineassessmentprep_1722352322374%2Fcompanies%2Fairlineassessmentprep.json )**
=> Add 'Airline Assessment Prep' (community contribution)

companies/netcup.json
**Edit in: [company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_netcup_1753946572807%2Fcompanies%2Fnetcup.json), [data editor](https://data-editor.datenanfragen.de/#/review/3176)[^1]**
=> Update 'netcup GmbH' (community contribution)

companies/datenschutzbuero.json, companies/digitec-ch.json
**Edit in: [company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_datenschutzbuero_1754648374787%2Fcompanies%2Fdatenschutzbuero.json), [data editor](https://data-editor.datenanfragen.de/#/review/3184)[^1]**
=> Add 'Digitec Galaxus AG'; Update 'Galaxus Deutschland GmbH' (community contribution)

companies/th-ringer-schulportal-tsp.json, companies/thillm-de.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_th-ringer-schulportal-tsp_1725458625619%2Fcompanies%2Fth-ringer-schulportal-tsp.json )**
=> Add 'Thüringer Institut für Lehrerfortbildung, Lehrplanentwicklung und Medien (ThILLM)' (community contribution)

companies/sparkasse-mittelth-ringen.json, companies/sparkasse-mittelthueringen.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_sparkasse-mittelth-ringen_1725117053064%2Fcompanies%2Fsparkasse-mittelth-ringen.json )**
=> Add 'Sparkasse Mittelthüringen' (community contribution)

companies/disney.json
**Edit in: [company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_disney_1756455031848%2Fcompanies%2Fdisney.json), [data editor](https://data-editor.datenanfragen.de/#/review/3208)[^1]**
=> Update 'The Walt Disney Company Limited' (community contribution)
