- companies/efficientip-com.json
On their privacy statement, privacy@efficientip.com is listed as the
email address. However, when trying to send an email to that address,
you get a "Delivery Status Notification (Failure)" notification.
> Change invalid email of EfficientIP, SAS

- companies/mi-com.json
I copied the previous web link in browser but it returned a '403' Forbidden error. So updated it with the www prefix for the data record of the link to be functional.
> #349 Updated the web link of xiaomi

- companies/ifttt.json
The email in the terms is "IFTTT@gdpr-rep.com".
However, when sending a request to that email, you get the
following reply:
"We don't monitor emails sent directly to this email address, and
we won't be able to respond to this email."
Therefore, I've added the more general email address that can also
be found in the sources.
> Fix email of IFTTT Inc.

- companies/4sigma
Added 4sigma GmbH which provides telephone and digital health service support to i.a. health insurance companies. The Siemens Betriebskrankenkasse (SBK) uses 4sigma GmbH to organize appointments for a suitable doctor for their customers.
> Add 4sigma GmbH

- companies/barmeniade.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22barmeniade%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22insurance%22%5D%2C%22name%22%3A%22Barmenia%20Versicherungen%20a.%20G.%22%2C%22runs%22%3A%5B%22Barmenia%20Allgemeine%20Versicherungs-AG%22%2C%22Barmenia%20Krankenversicherung%20AG%22%2C%22Barmenia%20Lebensversicherung%20a.%20G.%22%5D%2C%22address%22%3A%22Barmenia-Allee%201%5Cn42119%20Wuppertal%5CnDeutschland%22%2C%22phone%22%3A%220202%20438-00%22%2C%22email%22%3A%22datenschutz%40barmenia.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.barmenia.de%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.barmenia.de%2Fdeu%2Fbde_privat%2Fdatenschutz.xhtml%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata …
> New company suggestion: 'Barmenia Versicherungen a. G.'

- companies/digitrust.json
Change DigiTrust Email Address to point to the new IAB support Email.
Fix #465
> [DigiTrust] Update email address

- test-records.js
It checked for `}\\n`, but only states that the file doesn't end with a newline on fail. Confused me for a second in #729.
> Clarify newline fail string

- companies/volkswagen-ag.json
Hello!
I've collected information about the Volkswagen Group (aka Volkswagen AG) & generated the JSON file via the webtool. The main source of info: "https://datenschutz.volkswagen.de/". Also, perhaps the "slug" would be better if named as volkswagen-group or volkswagen-ag? Let me know your thoughts.
> Add "Volkswagen"

- companies/beitragsservice.json
They currently do have the problem that their mail server does not support SSL/TLS. I'm going to fill a complaint.
However, they at least referred me to their contact form, which is quite nice, actually.
They do also have a special one for art. 15 requests, but as Datenanfragen.de also allows other requests, I've used this one. The other one would be:
https://www.rundfunkbeitrag.de/der_rundfunkbeitrag/beitragsservice/datenschutz/datenauskunft/index_ger.html
> Add web form for Beitragsservice

- companies/bitel.json
- companies/stadtwerke-bielefeld.json
- companies/technische-werke-osning.json
- companies/two.json
T.W.O. and Stadtwerke Bielefeld are utility companies. BITel is a telco.
I'm unsure about the super short slug for T.W.O. ("two"), but it's not yet used. Alternatively "two-de" or "technische-werke-osning" could be used.
> Add BITel, T.W.O. and Stadtwerke Bielefeld

- companies/shoop.json
Shoop is a German cashback company. You can earn cashback by purchasing things through their partners.
I'm not sure about two things:
- Is "finance" the right category? I couldn't find another cashback company in the database.
- Do I use the DPO or the generic "datenschutz@" e-mail? I would prefer the DPO, but it's a individual person and this goes against datenanfragens guidelines ("Please make sure that there is no personal data in your record. This means no names in the address and no emails that include names, either.")
> Add "Shoop Germany GmbH"

- companies/g2a.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22g2a%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22entertainment%22%5D%2C%22name%22%3A%22G2A.COM%20Limited%22%2C%22address%22%3A%22DPO%5CnG2A.COM%20Limited%5Cn31%2FF%2C%20Tower%20Two%2C%5CnTimes%20Square%2C%5Cn1%20Matheson%20Street%2C%5CnCauseway%20Bay%2C%5CnHong%20Kong%22%2C%22email%22%3A%22dpo%40g2a.com%22%2C%22web%22%3A%22https%3A%2F%2Fg2a.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.g2a.com%2Fprivacy-policy%3F___store%3Denglish%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F768%22%5D%2C%22needs-id-document%22%3Afalse%2C%22suggested-transport-medium%22%3A%22email%22%2C%22quality%22%3A%22verified%22%7D)**
> Add 'G2A.COM Limited' (community contribution)

- companies/starz.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22starz%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22name%22%3A%22StarzPlay%20Direct%20UK%20Limited%22%2C%22address%22%3A%22StarzPlay%20Direct%20UK%20Limited%2C%5Cn45%20Mortimer%20Street%2C%5CnLondon%2C%20W1W%208HJ%2C%5CnUnited%20Kingdom%22%2C%22email%22%3A%22privacy%40starz.com%22%2C%22web%22%3A%22https%3A%2F%2Fstarz.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.starz.com%2Fgb%2Fen%2Fprivacy%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F770%22%5D%2C%22needs-id-document%22%3Afalse%2C%22suggested-transport-medium%22%3A%22email%22%2C%22quality%22%3A%22verified%22%7D)**
> Add 'StarzPlay Direct UK Limited' (community contribution)

- schema.json
This makes the tooltip a bit more useful.
This is the old one:
If you don't have the technical knowledge you might be confused why this is wrong. 
If we don't want something like this in the schema we could change the suggest-UI.
> Explicitly state that the protocol is needed in the schema

- companies/barcov-de.json
- companies/corona-anmeldung.json
Small problem with BarCov:
The "verantwortliche Stelle " is given with name in the [PP](https://barcov.id/privacypolicy) and has a completly different address than the [company](https://barcov.id/impressum) itself. 
How do we make sure that letters arrive without storing the name in this repo?
> Added corona-anmeldung and BarCov

- companies/blendle.json
Added online news platform blendle.com. See also: https://en.wikipedia.org/wiki/Blendle
> Add 'Blendle B.V.'

- companies/chasedebt-co.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22chasedebt-co%22%2C%22relevant-countries%22%3A%5B%22gb%22%5D%2C%22categories%22%3A%5B%22finance%22%5D%2C%22name%22%3A%22Chase%20Debt%20Ltd%22%2C%22address%22%3A%221st%20Floor%2C%2054%20Watling%20Street%20Radlett%2C%20Hertfordshire%22%2C%22phone%22%3A%220203%20780%207141%22%2C%22email%22%3A%22%20info%40chasedebt.co.uk%22%2C%22web%22%3A%22https%3A%2F%2Fchasedebt.co.uk%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fchasedebt.co.uk%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F821%22%5D%2C%22needs-id-document%22%3Atrue%2C%22suggested-transport-medium%22%3A%22email%22%2C%22comments%22%3A%5B%22Chase%20Debt%20will%20provide%20you%20all%20the%20services%20you%20ne …
> Add 'Chase Debt Ltd' (community contribution)

- companies/suedspa-de.json
- companies/suedspa.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22suedspa%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22finance%22%5D%2C%22name%22%3A%22S%C3%BCdtiroler%20Sparkasse%20AG%20Niederlassung%20M%C3%BCnchen%22%2C%22address%22%3A%22Gai%C3%9Facher%20Stra%C3%9Fe%2018%5Cn81371%20M%C3%BCnchen%22%2C%22phone%22%3A%22%2B49%2089%2059944350%22%2C%22fax%22%3A%22%2B49%2089%20599443599%22%2C%22email%22%3A%22datenschutz%40suedspa.de%20%22%2C%22web%22%3A%22https%3A%2F%2Fwww.suedspa.de%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.suedspa.de%2Fde%2Finformation%2Fdatenschutz%2F6-0.html%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F830%22%5D%2C%22quality%22%3A%22verified%22%7D)**
> Add 'Südtiroler Sparkasse AG Niederlassung München' (community contribution)

- companies/playstation-com.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22playstation-com%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22entertainment%22%5D%2C%22name%22%3A%22Sony%20Interactive%20Entertainment%20Europe%20Limited%22%2C%22runs%22%3A%5B%22My%20Playstation%22%2C%22PlayStation%20Network%22%2C%22Sony%20Interactive%20Entertainment%20Network%20Europe%20Limited%22%5D%2C%22address%22%3A%2210%20Great%20Marlborough%20Street%5CnLondon%5CnW1F%207LP%5CnUnited%20Kingdom%22%2C%22email%22%3A%22siee.dpo%40sony.com%22%2C%22web%22%3A%22https%3A%2F%2Fwww.playstation.com%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.playstation.com%2Flegal%2Fprivacy-policy%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues …
> Update 'Sony Interactive Entertainment Europe Limited' (community contribution)

- companies/steam.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22steam%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22entertainment%22%5D%2C%22name%22%3A%22Valve%20GmbH%22%2C%22runs%22%3A%5B%22Steam%20(store.steampowered.com)%22%2C%22Valve%20Corporation%22%2C%22Valve%20S.a.r.l.%22%5D%2C%22address%22%3A%22R%C3%B6dingsmarkt%209%5Cn20354%20Hamburg%5CnGermany%22%2C%22email%22%3A%22questions%40valvesoftware.com%22%2C%22web%22%3A%22https%3A%2F%2Fwww.valvesoftware.com%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fstore.steampowered.com%2Fprivacy_agreement%2F%22%2C%22https%3A%2F%2Fwww.valvesoftware.com%2Fcontact%2F%22%2C%22https%3A%2F%2Fwww.privacyshield.gov%2Fparticipant%3Fid%3Da2zt0000000TO5UAAW%26status%3DActive%22%2 …
> Update 'Valve GmbH' (community contribution)

- companies/bongacams-com.json
- companies/chaturbate-com.json
- companies/duodecad-it-services.json
- companies/ebay-kleinanzeigen-gmbh.json
- companies/stroeer-digital-publishing.json
- Add bongacams, duodecad, stöer, ebay-kleinanzeigen, and chaturbate
> Add companies to cover Alexa Top 25 sites in germany

- companies/gameloft.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22gameloft%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22entertainment%22%5D%2C%22name%22%3A%22Gameloft%20SE%22%2C%22address%22%3A%2214%20rue%20Auber%5Cn75009%20Paris%22%2C%22phone%22%3A%22%2B33%201%2053%2016%2020%2040%22%2C%22email%22%3A%22DataProtectionSupport%40gameloft.com%22%2C%22web%22%3A%22https%3A%2F%2Fwww.gameloft.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.gameloft.com%2Fde%2Fprivacy-notice%22%2C%22https%3A%2F%2Fwww.gameloft.com%2Fde%2Finformation%2Flegal-notices%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F892%22%5D%2C%22quality%22%3A%22verified%22%7D)**
> Add 'Gameloft SE' (community contribution)

- companies/stripe-inc.json
- companies/stripe.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22stripe-inc%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22finance%22%5D%2C%22name%22%3A%22Stripe%20Inc.%22%2C%22address%22%3A%22510%20Townsend%20Street%5CnSan%20Francisco%5CnCA%2094103%5CnUSA%22%2C%22email%22%3A%22privacy%40stripe.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fstripe.com%2Fde%2Fprivacy%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F888%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22quality%22%3A%22verified%22%7D)**
> Add 'Stripe Inc.' (community contribution)

- companies/limburg-net.json
- companies/limburg.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22limburg%22%2C%22relevant-countries%22%3A%5B%22be%22%5D%2C%22categories%22%3A%5B%22utility%22%5D%2C%22name%22%3A%22Limburg.net%22%2C%22address%22%3A%22Gouverneur%20Verwilghensingel%2032%5Cn3500%20Hasselt%22%2C%22phone%22%3A%22011%2F28.89.89%22%2C%22email%22%3A%22privacy%40limburg.net%22%2C%22web%22%3A%22https%3A%2F%2Flimburg.net%22%2C%22sources%22%3A%5B%22https%3A%2F%2Flimburg.net%2Fprivacyverklaring%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F908%22%5D%2C%22quality%22%3A%22verified%22%7D)**
> Add 'Limburg.net' (community contribution)

- companies/formula1.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22formula1%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22entertainment%22%5D%2C%22name%22%3A%22Formula%20One%20Digital%20Media%20Limited%22%2C%22runs%22%3A%5B%22Formula%201%22%2C%22F1%20TV%22%5D%2C%22address%22%3A%22No.2%20St.%20James%E2%80%99s%20Market%2C%20London%2C%20SW1Y%204AH%2C%20England%22%2C%22email%22%3A%22general%40en.formula1.com%22%2C%22web%22%3A%22https%3A%2F%2Fwww.formula1.com%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Faccount.formula1.com%2F%23%2Fen%2Fprivacy-policy%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F913%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22quality%22%3A%22verified%22%7D)**
> Add 'Formula One Digital Media Limited' (community contribution)

- companies/autobahn.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22autobahn%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22public%20body%22%5D%2C%22name%22%3A%22Die%20Autobahn%20GmbH%20des%20Bundes%22%2C%22address%22%3A%22Die%20Autobahn%20GmbH%20des%20Bundes%5CnFriedrichstra%C3%9Fe%2071%5Cn10117%20Berlin%22%2C%22fax%22%3A%22%2B49%2030%20403680810%22%2C%22email%22%3A%22datenschutz%40autobahn.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.autobahn.de%22%2C%22sources%22%3A%5B%22www.autobahn.de%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F927%22%5D%2C%22quality%22%3A%22verified%22%7D)**
> Add 'Die Autobahn GmbH des Bundes' (community contribution)

- companies/facebook.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22facebook%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22entertainment%22%2C%22social%20media%22%5D%2C%22name%22%3A%22Facebook%20Ireland%20Ltd.%22%2C%22runs%22%3A%5B%22Facebook%2C%20Inc.%22%5D%2C%22address%22%3A%224%20Grand%20Canal%20Square%5CnGrand%20Canal%20Harbour%5CnDublin%202%5CnIreland%22%2C%22phone%22%3A%22%2B1%20650%20543%204800%22%2C%22fax%22%3A%22%2B1%20650%20543%205349%22%2C%22web%22%3A%22https%3A%2F%2Fwww.facebook.com%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.facebook.com%2Fprivacy%2Fexplanation%22%2C%22https%3A%2F%2Fwww.facebook.com%2Flegal%2Fterms%22%2C%22https%3A%2F%2Fwww.privacyshield.gov%2Fparticipant%3Fid%3Da2zt0000000GnywA …
> Update 'Facebook Ireland Ltd.' (community contribution)

- companies/a-thinking-ape-entertainment-ltd.json
- companies/a-thinking-ape.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22a-thinking-ape-entertainment-ltd%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22entertainment%22%5D%2C%22name%22%3A%22%20A%20Thinking%20Ape%20Entertainment%20Ltd.%22%2C%22runs%22%3A%5B%22Party%20in%20my%20Dorm%22%2C%22Kingdoms%20of%20Heckfire%22%2C%22Kingdoms%20at%20War%22%2C%22Casino%20X%22%5D%2C%22address%22%3A%22%23200%E2%80%931132%20Alberni%20St.%5CnVancouver%2C%20BC%2C%20Canada%5CnV6E%201A5%22%2C%22email%22%3A%22support%40athinkingape.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fathinkingape.com%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F938%22%5D%2C%22quality%22%3A%22verified%22%7D)**
> Add ' A Thinking Ape Entertainment Ltd.' (community contribution)

- companies/bbc.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22bbc%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22entertainment%22%5D%2C%22name%22%3A%22British%20Broadcasting%20Corporation%20(BBC)%22%2C%22runs%22%3A%5B%22BBC%20Media%20Applications%20Technologies%20Limited%22%2C%221943%20Berlin%20Blitz%20(VR%20Experience)%22%5D%2C%22address%22%3A%22BC2%20A4%5Cn201%20Wood%20Lane%5CnLondon%20W12%207TP%5CnUnited%20Kingdom%22%2C%22email%22%3A%22dataprotection%40bbc.com%22%2C%22web%22%3A%22https%3A%2F%2Fwww.bbc.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.bbc.co.uk%2Fusingthebbc%2Fprivacy%2Fprivacy-policy%2F%22%2C%22https%3A%2F%2Fstore.steampowered.com%2Fapp%2F513490%2F1943_Berlin_Blitz%2F%22%2C%22https%3A%2F% …
> Update 'British Broadcasting Corporation (BBC)' (community contribution)

- companies/valimail.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22valimail%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22utility%22%5D%2C%22name%22%3A%22Valimail%20Inc.%22%2C%22address%22%3A%22Valimail%20Inc.%5Cn180%20Montgomery%20Street%2C%2020th%20Floor%5CnSan%20Francisco%20CA%2094104%5CnUnited%20States%20of%20America%22%2C%22email%22%3A%22privacy%40valimail.com%22%2C%22web%22%3A%22https%3A%2F%2Fwww.valimail.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.valimail.com%2Fprivacy%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F993%22%5D%2C%22needs-id-document%22%3Afalse%2C%22quality%22%3A%22verified%22%7D)**
> Add 'Valimail Inc.' (community contribution)

- companies/wallwisher-inc.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22wallwisher-inc%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22name%22%3A%22Wallwisher%2C%20Inc.%22%2C%22runs%22%3A%5B%22padlet.com%22%5D%2C%22address%22%3A%22981%20Mission%20St%5CnSan%20Francisco%2C%20CA%2094103%5CnUSA%22%2C%22email%22%3A%22hello%40padlet.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fpadlet.com%2Fabout%2Fprivacy%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1030%22%5D%2C%22quality%22%3A%22verified%22%7D)**
> Add 'Wallwisher, Inc.' (community contribution)

- companies/app-fahrschulcard.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22app-fahrschulcard%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22name%22%3A%22Deutscher%20Fahrschulverlag%20GmbH%22%2C%22address%22%3A%22Luise-Ullrich-Stra%C3%9Fe%208%5Cn82031%20Gr%C3%BCnwald%5CnDeutschland%22%2C%22email%22%3A%22datenschutz%40d-fv.de%22%2C%22web%22%3A%22https%3A%2F%2Fapp.fahrschulcard.de%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fapp.fahrschulcard.de%2Fimprint%22%2C%22https%3A%2F%2Fapp.fahrschulcard.de%2Fprivacy%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1051%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22quality%22%3A%22verified%22%7D)**
> Add 'Deutscher Fahrschulverlag GmbH' (community contribution)

- companies/elsevier.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22elsevier%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22school%22%5D%2C%22name%22%3A%22Elsevier%22%2C%22address%22%3A%22Data%20Protection%20Officer%5CnElsevier%20Limited%5CnThe%20Boulevard%5CnLangford%20Lane%5CnKidlington%5CnOxford%20OX5%201GB%5CnUnited%20Kingdom%22%2C%22email%22%3A%22DPO%40elsevier.com%22%2C%22web%22%3A%22https%3A%2F%2Fwww.elsevier.com%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.elsevier.com%2Flegal%2Fprivacy-policy-de-de%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1057%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22quality%22%3A%22verified%22%7D)**
> Add 'Elsevier' (community contribution)

- companies/gloeckle.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22gloeckle%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22ads%22%5D%2C%22name%22%3A%22Staatliche%20Lotterie-Einnahme%20Gl%C3%B6ckle%20KG%22%2C%22address%22%3A%22zu%20Hd.%20Datenschutzbeauftragter%5CnDaimlerstra%C3%9Fe%2086%5Cn70372%20Stuttgart%22%2C%22phone%22%3A%2207119541620%22%2C%22fax%22%3A%2207319541309%22%2C%22email%22%3A%22datenschutz%40gloeckle.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.gloeckle.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.gloeckle.de%2Fdatenschutz%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1063%22%5D%2C%22quality%22%3A%22verified%22%7D)**
> Add 'Staatliche Lotterie-Einnahme Glöckle KG' (community contribution)

- companies/cio-institute.json
- companies/gb-intelligence.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22cio-institute%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22ads%22%2C%22school%22%5D%2C%22name%22%3A%22GB%20Intelligence%20Ltd%22%2C%22runs%22%3A%5B%22Global%20CIO%20Institute%22%5D%2C%22address%22%3A%228-10%20Griffin%20Street%5CnNewport%20NP20%201GL%22%2C%22email%22%3A%22marketing%40cio-institute.com%22%2C%22web%22%3A%22https%3A%2F%2Fwww.cio-institute.com%22%2C%22sources%22%3A%5B%22website%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1078%22%5D%2C%22quality%22%3A%22verified%22%7D)**
> Add 'GB Intelligence Ltd' (community contribution)

- companies/dzvhae.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22dzvhae%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22health%22%5D%2C%22name%22%3A%22Deutscher%20Zentralverein%20hom%C3%B6opathischer%20%C3%84rzte%20e.V.%22%2C%22address%22%3A%22Deutscher%20Zentralverein%20hom%C3%B6opathischer%20%C3%84rzte%20e.V.%5CnDatenschutzbeauftragter%5CnAxel-Springer-Str.%2054%20B%5Cn10117%20Berlin%22%2C%22email%22%3A%22datenschutz%40dzvhae.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.dzvhae.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.dzvhae.de%2Fdatenschutz%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1103%22%5D%2C%22needs-id-document%22%3Afalse%2C%22suggested-transport-medium%22%3A%22email%22%2C%22qu …
> Add 'Deutscher Zentralverein homöopathischer Ärzte e.V.' (community contribution)

- companies/sooner.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22sooner%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22entertainment%22%5D%2C%22name%22%3A%22ContentScope%20GmbH%22%2C%22runs%22%3A%5B%22Sooner%20(sooner.de)%22%5D%2C%22address%22%3A%22Alte%20Jakobstra%C3%9Fe%2076%5Cn10179%20Berlin%5CnDeutschland%22%2C%22phone%22%3A%22%2B49%2030%2097004330%22%2C%22fax%22%3A%22%2B49%2030%2097004331%22%2C%22email%22%3A%22privacy%40sooner.de%22%2C%22web%22%3A%22https%3A%2F%2Fsooner.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fsooner.de%2Frechtliches%2F%22%2C%22https%3A%2F%2Fsooner.de%2Fimpressum%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1117%22%5D%2C%22suggested-transport-medium%22%3A%22email …
> Add 'ContentScope GmbH' (community contribution)

- schema.json
This will also "fix" the missing translations in the suggest form:
> Schema: Remove overseas territories that aren't actually countries

- companies/sendinblue.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22sendinblue%22%2C%22relevant-countries%22%3A%5B%22fr%22%2C%22de%22%5D%2C%22name%22%3A%22sendinblue.com%22%2C%22address%22%3A%22Address%3A%20K%C3%B6penicker%20Str.%20126%2C%2010179%20Berlin%2C%20Germany%22%2C%22web%22%3A%22https%3A%2F%2Fwww.sendinblue.com%2Fabout%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.sendinblue.com%2Fabout%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1135%22%5D%2C%22comments%22%3A%5B%22Competitor%20to%20Mailchimp%2C%20handles%20massive%20marketing%20campaign%20databases%22%5D%2C%22quality%22%3A%22verified%22%7D)**
> Add 'sendinblue.com' (community contribution)

- companies/discord.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22discord%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22social%20media%22%5D%2C%22name%22%3A%22Discord%2C%20Inc.%22%2C%22address%22%3A%22444%20De%20Haro%20Street%5CnSuite%20%23200%5CnSan%20Francisco%5CnCA%2094107%5CnUnited%20States%20of%20America%22%2C%22email%22%3A%22privacy%40discord.com%22%2C%22web%22%3A%22https%3A%2F%2Fdiscord.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fdiscord.com%2Fprivacy%22%2C%22https%3A%2F%2Fwww.bloomberg.com%2Fresearch%2Fstocks%2Fprivate%2Fsnapshot.asp%3FprivcapId%3D243221325%22%2C%22https%3A%2F%2Fdiscord.com%2Fterms%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1159%22%5D%2C%22request-language%2 …
> Update 'Discord, Inc.' (community contribution)

- companies/taxfix.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22taxfix%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22finance%22%5D%2C%22name%22%3A%22Taxfix%20GmbH%22%2C%22address%22%3A%22Karl-Liebknecht-Str.%2034%5Cn10178%20Berlin%22%2C%22phone%22%3A%22%2B49%2030%2092106949%22%2C%22email%22%3A%22privacy%40taxfix.de%22%2C%22web%22%3A%22https%3A%2F%2Ftaxfix.de%22%2C%22sources%22%3A%5B%22privacy%40taxfix.de%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1163%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22quality%22%3A%22verified%22%7D)**
> Add 'Taxfix GmbH' (community contribution)

- companies/faber-lotto.json
- companies/faber.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22faber%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22ads%22%5D%2C%22name%22%3A%22FABER%20Lotto%20GmbH%20%26%20Co.%20KG%22%2C%22address%22%3A%22Markstra%C3%9Fe%2079%5Cn44801%20Bochum%5CnDeutschland%20%22%2C%22email%22%3A%22datenschutz%40faber.de.%22%2C%22web%22%3A%22https%3A%2F%2Fwww.faber.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.faber.de%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1181%22%5D%2C%22needs-id-document%22%3Afalse%2C%22suggested-transport-medium%22%3A%22email%22%2C%22quality%22%3A%22verified%22%7D)**
> Add 'FABER Lotto GmbH & Co. KG' (community contribution)

- schema.json
The regex allowed trailing spaces before. I've also escaped the point in the 'ext.'-clause.
> more precise fax and phone regex

- companies/infovergleich99.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22infovergleich99%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22name%22%3A%22INFOVERGLEICH99%20UG%22%2C%22address%22%3A%22Zimmerstra%C3%9Fe%2078%5Cn10117%20Berlin%22%2C%22phone%22%3A%22%2B49%2030%20255583655%22%2C%22email%22%3A%22datenschutz%40infovergleich99.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.infovergleich99.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.infovergleich99.de%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1206%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22comments%22%3A%5B%22Rufen%20pauschal%20bei%20Leuten%20an%2C%20erz%C3%A4hlen%20was%20von%20Spartarifen%2C%20verlangen%20nach%20der%20Z%C3%A4hlernummer%20und% …
> Add 'INFOVERGLEICH99 UG' (community contribution)

- companies/hannoversche.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22hannoversche%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22insurance%22%5D%2C%22name%22%3A%22Hannoversche%20Le%C2%ADbens%C2%ADver%C2%ADsiche%C2%ADrung%20AG%22%2C%22address%22%3A%22Hannoversche%20Lebens%C2%ADversicherung%20AG%5CnVHV-Platz%201%5CnD-30177%20Hannover%22%2C%22phone%22%3A%220511%2F9565-0%22%2C%22fax%22%3A%220511%2F9565-666%22%2C%22email%22%3A%22service%40hannoversche.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.hannoversche.de%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.hannoversche.de%2Fdatenschutz%2Fallgemeine-informationen%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1213%22%5D%2C%22quality%22%3A%22verified% …
> Add 'Hannoversche Le­bens­ver­siche­rung AG' (community contribution)

- companies/basler-versicherungen.json
- companies/basler.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22basler%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22insurance%22%5D%2C%22name%22%3A%22Basler%20Sachversicherungs-AG%20und%20Basler%20Lebensversicherungs-AG%22%2C%22address%22%3A%22Basler%20Stra%C3%9Fe%204%5Cn61352%20Bad%20Homburg%22%2C%22phone%22%3A%22%2B49%206172%201254600%22%2C%22fax%22%3A%22%2B49%206172%201254056%22%2C%22email%22%3A%22datenschutz%40basler.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.basler.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.basler.de%2Fde%2Fueber-uns%2Fdatenschutz.html%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1239%22%5D%2C%22quality%22%3A%22verified%22%7D)**
> Add 'Basler Sachversicherungs-AG und Basler Lebensversicherungs-AG' (community contribution)

- companies/sat1.json
- companies/sat1de.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22sat1%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22entertainment%22%5D%2C%22name%22%3A%22ProSiebenSat.1%20Digital%20GmbH%22%2C%22runs%22%3A%5B%22https%3A%2F%2Fwww.7pass.de%22%5D%2C%22address%22%3A%22ProSiebenSat.1%20Digital%20GmbH%5CnDatenschutzbeauftragter%5CnMedienallee%204%5CnD-85774%20Unterf%C3%B6hring%22%2C%22phone%22%3A%22%2B49%2089%20950710%22%2C%22email%22%3A%22datenschutz%40sat1.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.sat1.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.sat1.de%2Fservice%2Fagb%2Fdatenschutz%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1241%22%5D%2C%22comments%22%3A%5B%22Vermutlich%20%20ist%20die …
> Add 'ProSiebenSat.1 Digital GmbH' (community contribution)

- companies/gartentraum.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22gartentraum%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22commerce%22%2C%22ads%22%5D%2C%22name%22%3A%22Gartentraum.de%22%2C%22address%22%3A%22Rudolst%C3%A4dter%20Str.%2039%5Cn07745%5CnJena%5CnGermany%22%2C%22web%22%3A%22https%3A%2F%2Fwww.gartentraum.de%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.gartentraum.de%2FImpressum%22%2C%22https%3A%2F%2Fwww.gartentraum.de%2Fdatenschutzbestimmungen%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1249%22%5D%2C%22quality%22%3A%22verified%22%7D)**
> Add 'Gartentraum.de' (community contribution)

- companies/hamburg.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22hamburg%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22name%22%3A%22hamburg.de%20GmbH%20%26%20Co.%20KG%22%2C%22address%22%3A%22Rothenbaumchaussee%2080b%5Cn20148%20Hamburg%22%2C%22email%22%3A%22datenschutz%40hamburg.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.hamburg.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.hamburg.de%2Fdatenschutz%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1253%22%5D%2C%22comments%22%3A%5B%22Bei%20der%20Bearbeitung%20kann%20es%20m%C3%B6glich%20sein%2C%20dass%20der%20Betreiber%20um%20einen%20Identit%C3%A4tsnachweis%20bittet.%20Dieses%20ergibt%20sich%20im%20Einzelfall.%22%5D%2C%22quality%22%3A%22verified%22%7D)**
> Add 'hamburg.de GmbH & Co. KG' (community contribution)

- companies/videobuster.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22videobuster%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22entertainment%22%5D%2C%22name%22%3A%22Netleih%20GmbH%20%26%20Co.%20KG%22%2C%22address%22%3A%22Johann-Zincken-Stra%C3%9Fe%206%5Cn38723%20Seesen%5CnDeutschland%22%2C%22phone%22%3A%22%2B49%205381%2074929898%22%2C%22email%22%3A%22datenschutz%40videobuster.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.videobuster.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.videobuster.de%2Fdatenschutz%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1254%22%5D%2C%22comments%22%3A%5B%22Externer%20Datenschutzbeauftragter%3A%5CnHerr%20Markus%20Strauss%5Cntacticx%20Consulting%20GmbH%5CnWalbecker …
> Add 'Netleih GmbH & Co. KG' (community contribution)

- companies/buhl-de.json
- companies/buhl.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22buhl%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22name%22%3A%22Buhl%20Data%20Service%20GmbH%22%2C%22address%22%3A%22Am%20Siebertsweiher%203%2F5%5Cn57290%20Neunkirchen%22%2C%22fax%22%3A%22%2B49%202735%2077619%22%2C%22email%22%3A%22datenschutz%40buhl-data.com%22%2C%22web%22%3A%22https%3A%2F%2Fwww.buhl.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.buhl.de%2Fdatenschutz%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1260%22%5D%2C%22comments%22%3A%5B%22Eine%20Anfrage%20per%20Email%20er%C3%B6ffnet%20ein%20Ticket%20beim%20Kundenservice.%20Die%20Zustellung%20der%20Askunft%20erfolgt%20auf%20dem%20Postweg.%22%5D%2C%22quality%22%3A%22verified%22%7D)**
> Add 'Buhl Data Service GmbH' (community contribution)

- companies/sparkasse-hannover.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22sparkasse-hannover%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22name%22%3A%22Sparkasse%20Sparkasse%22%2C%22address%22%3A%22Raschplatz%204%5Cn30161%20Hannover%5CnDeutschland%22%2C%22email%22%3A%22datenschutzbeauftragter%40sparkasse-hannover.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.sparkasse-hannover.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.sparkasse-hannover.de%2Fde%2Fhome%2Ftoolbar%2Fdatenschutz.html%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1271%22%5D%2C%22quality%22%3A%22verified%22%7D)**
> Add 'Sparkasse Sparkasse' (community contribution)

- companies/pearson.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22pearson%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22name%22%3A%22Pearson%20Deutschland%20GmbH%22%2C%22address%22%3A%22St.-Martin-Stra%C3%9Fe%2082%5Cn81541%20M%C3%BCnchen%5CnDeutschland%22%2C%22phone%22%3A%22%2B49%2089%20954597420%22%2C%22fax%22%3A%22%2B49%2089%20954597429%22%2C%22web%22%3A%22https%3A%2F%2Fwww.pearson.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.pearson.de%2Fdatenschutz%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1263%22%5D%2C%22comments%22%3A%5B%22Externer%20Datenschutzbeauftragter%3A%5Cn%5CnDr.%20Felix%20Wittern%2C%20Fieldfisher%20(Germany)%20LLP%5CnAm%20Sandtorkai%2068%5Cn20457%20Hamburg%5Cn%5CnE-Mail%3A%20Datenschutz. …
> Add 'Pearson Deutschland GmbH' (community contribution)

- companies/shop-hannover96.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22shop-hannover96%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22commerce%22%5D%2C%22name%22%3A%22Hannover%2096%20Sales%20%26%20Service%20GmbH%20%26%20Co.KG%22%2C%22address%22%3A%22Robert-Enke-Str.%201%5Cn30169%20Hannover%22%2C%22phone%22%3A%22%2B49%20511%209690096%22%2C%22fax%22%3A%22%2B49%20511%2096900796%22%2C%22email%22%3A%22datenschutz%40hannover96.de%22%2C%22web%22%3A%22https%3A%2F%2Fshop.hannover96.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fshop.hannover96.de%2Fdatenschutzerklaerung%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1311%22%5D%2C%22quality%22%3A%22verified%22%7D)**
> Add 'Hannover 96 Sales & Service GmbH & Co.KG' (community contribution)

- companies/giga-de.json
- companies/giga.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22giga%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22name%22%3A%22GIGA.de%22%2C%22address%22%3A%22%E2%84%85%20Str%C3%B6er%20Media%20Brands%20GmbH%5CnTorstra%C3%9Fe%2049%5Cn10119%20Berlin-Mitte%22%2C%22email%22%3A%22datenschutz-giga%40stroeermediabrands.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.giga.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.giga.de%2Finfo%2Fimpressum%22%2C%22https%3A%2F%2Fwww.giga.de%2Fdatenschutz%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1337%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22comments%22%3A%5B%22Alternative%20E-Mail-Adresse%3A%20smb-datenschutzbeauftragter%40stroeer.de%22%5D%2C%22quality%22%3A%2 …
> Add 'GIGA.de' (community contribution)

- companies/onlinetvrecorder.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22onlinetvrecorder%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22entertainment%22%5D%2C%22name%22%3A%22Internet%20TV%20AG%22%2C%22runs%22%3A%5B%22onlinetvrecorder.com%22%5D%2C%22address%22%3A%22306%20Victoria%20House%5Cn361%20Victoria%5CnSeychelles%5Cn%5Cn%22%2C%22phone%22%3A%22%2B1%20510%20984%205218%22%2C%22email%22%3A%22webmaster%40onlinetvrecorder.com%22%2C%22web%22%3A%22http%3A%2F%2Fwww.onlinetvrecorder.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.onlinetvrecorder.com%2Fv2%2Fcontact%2Fgdpr%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1350%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22comments%22%3A%5B …
> Add 'Internet TV AG' (community contribution)

- supervisory-authorities/derf.json
- supervisory-authorities/derfdw.json
- supervisory-authorities/derfhr.json
- supervisory-authorities/derfmdr.json
- supervisory-authorities/derfndr.json
- supervisory-authorities/derfrb.json
- supervisory-authorities/derfrbb.json
- supervisory-authorities/derfswr.json
Fixes #1126 
- `supervisory-authorities/derf.json`
responsible for BR (Bayerischer Rundfunk), SR (Saarländischer Rundfunk), WDR (Westdeutscher Rundfunk), Deutschlandradio, ZDF (Zweites Deutsches Fernsehen)
- `supervisory-authorities/derfdw.json`
responsible for Deutsche Welle
- `supervisory-authorities/derfhr.json`
responsible for HR (Hessischer Rundfunk)
- `supervisory-authorities/derfmdr.json`
responsible for MDR (Mitteldeutscher Rundfunk)
- `supervisory-authorities/derfndr.json`
responsible for NDR (Norddeutscher Rundfunk)
- `supervisory-authorities/derfrbb.json`
responsible for RBB (Rundfunk Berlin-Brandenburg)
- `supervisory-authorities/derfswr.json`
responsible for SWR (Südwestrundfunk)
> Add Rundfunkdatenschutzbeauftragte (public broadcasting SVAs)

- templates/nl/objection-default.txt
- templates/nl/rectification-default.txt
I've translated the objection and rectification template to the Dutch language.
I've kept the wording consistent between the other Dutch translations. Although I believe that the email greeting "Aan wie het aanbelangt:" isn't correct, I kept it for consistency. If this is something that can be changed I'm willing to do so in a seperate pull request.
[This Quora question](https://nl.quora.com/Hoe-zeg-ik-to-whom-it-may-concern-in-het-Nederlands) goes a bit more in depth. It states that in Flanders (a part of Belgium), it would be considered normal, but in the Netherlands it "absolutely wouldn't be". We don't have a perfect translation for this phrase, although something like "Aan wie het aangaat" might be better. Perhaps it's better to raise a seperate issue for this.
> Translate objection and rectification template to Dutch

- companies/facebook.json
Added few verified products run by Facebook, which don't even have their separate schema, and also added the relevant authentic source for the same.
> Updated 'Facebook' company schema

- src/test-records.ts
This otherwise produces empty lines which causes Reviewdog's JSON
parsing to fail.
> Reviewdog: Only log if there are actual results

- companies/proxalto-lv.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22proxalto-lv%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22insurance%22%5D%2C%22name%22%3A%22Proxalto%20Lebensversicherung%20AG%22%2C%22runs%22%3A%5B%22hat%20die%20Vetr%C3%A4ge%20von%20Generali%20Lebensversicherung%20%C3%BCbernommen%22%5D%2C%22address%22%3A%22Adenauerring%207%5Cn81737%20M%C3%BCnchen%22%2C%22phone%22%3A%22022841080%22%2C%22fax%22%3A%22022841081550%22%2C%22email%22%3A%22datenschutz%40viridium-gruppe.com%22%2C%22web%22%3A%22https%3A%2F%2Fwww.proxalto-lv.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.proxalto-lv.de%2Fdatenschutzbestimmungen%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1550%22%5D%2C%22quali …
> Add 'Proxalto Lebensversicherung AG' (community contribution)

- companies/schwaebisch-hall.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22schwaebisch-hall%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22finance%22%5D%2C%22name%22%3A%22Schw%C3%A4bisch%20Hall%20Kreditservice%20GmbH%22%2C%22address%22%3A%22Team%20Datenschutz%5CnCrailsheimer%20Stra%C3%9Fe%2052%5Cn74523%20Schw%C3%A4bisch%20Hall%5CnDEUTSCHLAND%22%2C%22phone%22%3A%220791464812%22%2C%22fax%22%3A%220791462628%22%2C%22email%22%3A%22datenschutzbeauftragter-SHG%40schwaebisch-hall.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.schwaebisch-hall.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.schwaebisch-hall.de%2Fsicherheit-und-datenschutz.html%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1555%22%5D%2C%22suggest …
> Add 'Schwäbisch Hall Kreditservice GmbH' (community contribution)

- companies/rechargecom.json
There are conflicting sources for the address: https://www.recharge.com/de/AGB
Google Maps says the one in Amsterdam is correct.
Also, they say they will ask for identification documents:
> In diesen Fällen können wir Sie um eine Kopie Ihres Ausweisdokuments oder Ihres Reisepasses bitten. Wenn Sie uns eine Kopie Ihres Ausweises oder Reisepasses schicken, schwärzen Sie bitte das Foto, die MLZ (maschinenlesbare Zone, den Streifen mit den Zahlen, der sich unten auf Ihrem Reisepass befindet), die Passnummer sowie Ihre Bürgerdienste-Nummer. 
I will test that and I will be happy to complain if neccessary.
> Add Recharge.com International B.V.

- supervisory-authorities/deberlbdi.json
Apparently the PGP-key (and the link to it *sigh*) for the Berlin BfDI changed.
> New PGP-key for Berlin BfDI

- companies/aseag.json
- package.json
- src/test-records.ts
- yarn.lock
Seems like they removed/broke their TypeScript types between releases.
We now need to use the DefinitelyTyped ones.
See also: markedjs/marked#2364
> Fixes #1692: Fix broken marked import

- deploy-typesense.js
- package.json
- src/deploy-typesense.ts
- yarn.lock
I have updated our Typesense server to the newest version (0.22.2). The client in `website` still works (though we should also update to gain advantage of the new features). But the deploy script needs to be updated as the import endpoint now returns a JSONL of `{ success: bool }` objects instead of a single `{ success: bool, num_imported: number }` object. We won't be able to deploy until this is merged.
While we're at it, this PR also:
* Uses the Typesense lib for the import endpoint (previously, we manually POSTed to the endpoint as the older Typesense lib didn't support that feature yet.
* Gets rid of our horrible `intifySlug()` hack that I thought we needed but luckily don't actually (see #1209).
* Converts the deploy script to TypeScript in line with what we did for the test script. …
> Update deploy script for Typesense 0.22.2

- src/deploy-typesense.ts
With these, "all inkl" will now match "all-inkl" for example, which it previously didn't. See the Typesense issue for more details: https://github.com/typesense/typesense/issues/122#issuecomment-907489433
I used the following script to collect candidates for the characters:
```js
const glob = require('glob');
const path = require('path');
const chars = [
...new Set(
glob
.sync(`./companies/*.json`)
.map((file) => require(path.resolve(file)))
.map((obj) => obj.name.split('').filter(
(c) => !c.match(/\p{Letter}|\p{Number}/gu)
))
.flat()
),
];
console.log(chars);
```
> Set token separators for Typesense

- companies/lekker.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_lekker_1646312647173%2Fcompanies%2Flekker.json )**
> Add 'lekker Energie GmbH' (community contribution)

- companies/crifbuergel.json
…apparently…
Also they have changed nearly everything (even their headquarter?), only the phone number stayed the same.
See https://www.crif.de/pr-events/pressemitteilungen/2021/november/04/crifbuergel-heisst-jetzt-crif-informationsdienstleister-positioniert-sich-als-partner-fuer-digital-customer-journey-management/
> CRIFBÜRGEL has been rebranded to CRIF

- templates/nl/access-default.txt
- templates/nl/access-tracking.txt
- templates/nl/admonition.txt
- templates/nl/complaint.txt
- templates/nl/erasure-default.txt
- templates/nl/objection-default.txt
- templates/nl/rectification-default.txt
I personally think that using 'Hoogachtend' as a closing sentence is outdated. Even in formal emails, I never see people using 'Hoogachtend' anymore.
I propose changing it to the more common closing sentence "Met vriendelijke groet" which translates to "With kind regards". According to the Dutch site taaladvies.net, [both options are acceptable](https://taaladvies.net/met-vriendelijke-groeten-of-hoogachtend/). Taaladvies.net mentions that with the greeting we're currently using (Geachte), both options are acceptable.
> Change closing sentence to 'Met vriendelijke groet,'

- .circleci/config.yml
CircleCI has been complaining for quite a while (e.g. in https://app.circleci.com/pipelines/github/datenanfragen/data/4938/workflows/0f379abf-0e82-4271-b1c4-57df15373d68/jobs/5945):
> You’re using a deprecated Docker convenience image. Upgrade to a next-gen Docker convenience image.
While we're at it, I've also switched to Node 18 (instead of 14) in CI. Main advantage: Unhandled promise rejections cause a non-zero exit code in that version, which we definitely want, especially in CI.
I have not increased the `engines` value in the `package.json` since everything still works just fine with Node 14.
> Circle: Upgrade Docker image

- companies/der-touristik.json
- companies/dertour.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_dertour_1661378469593%2Fcompanies%2Fdertour.json )**
> Add 'DER Touristik Deutschland GmbH' (community contribution)

- companies/corona-schnelltest-hamburg.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_corona-schnelltest-hamburg_1666367222728%2Fcompanies%2Fcorona-schnelltest-hamburg.json )**
> Add 'Corona Schnelltest Hamburg UG (haftungsbeschränkt)' (community contribution)

- companies/freshworks.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_freshworks_1675030461638%2Fcompanies%2Ffreshworks.json )**
> Add 'Freshworks Inc.' (community contribution)

- companies/privilegiosencompras.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_privilegiosencompras_1677257573444%2Fcompanies%2Fprivilegiosencompras.json )**
> Add 'Webloyalty Sàrl.' (community contribution)

- companies/big-click.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_big-click_1679967355272%2Fcompanies%2Fbig-click.json )**
> Add 'BigClick GmbH & Co.KG' (community contribution)

- companies/mysociety.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_mysociety_1687223791640%2Fcompanies%2Fmysociety.json )**
> Add 'mySociety Limited' (community contribution)

- companies/fnp.json
- companies/frankfurter-societaets-medien.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_fnp_1697551374988%2Fcompanies%2Ffnp.json )**
> Add 'Frankfurter Societäts-Medien GmbH' (community contribution)

- companies/lufthansa-airplus-servicekarten-gmbh.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_lufthansa-airplus-servicekarten-gmbh_1703458456047%2Fcompanies%2Flufthansa-airplus-servicekarten-gmbh.json )**
> Add 'Lufthansa AirPlus Servicekarten GmbH' (community contribution)

- companies/hey-com.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_hey-com_1717345098213%2Fcompanies%2Fhey-com.json )**
> Add 'HEYCOM GmbH & Co. KG' (community contribution)

- companies/thueringer-allgemeine.json
**Edit in: [company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_thueringer-allgemeine_1743105811128%2Fcompanies%2Fthueringer-allgemeine.json), [data editor](https://data-editor.datenanfragen.de/#/review/3065)[^1]**
> Add 'Thüringer Allgemeine' (community contribution)
