datenanfragen/data

- templates/de/admonition.txt
- templates/de/complaint.txt
- templates/en/admonition.txt
- templates/en/complaint.txt
I added these rudimentary templates I want to use in the generator on da.de. Please check them thoroughly and feel free to completely trash them.
> Added admonition and complaint templates

- companies/bild-de.json
- companies/br-de.json
- companies/datenanfragen.json
- companies/deutschewelle.json
- companies/deutschlandradio.json
- companies/faz.json
- companies/focus-magazin.json
- companies/focus-online-de.json
- companies/handelsblatt.json
- companies/hr-de.json
- companies/mdr.json
- companies/morgenpost.json
- companies/n-tv-de.json
- companies/ndr.json
- companies/radio-bremen.json
- companies/rbb.json
- companies/spiegel-de.json
- companies/sr-de.json
- companies/stern-de.json
- companies/sueddeutsche.json
- companies/swr.json
- companies/t3n.json
- companies/tagesspiegel.json
- companies/wdr.json
- companies/welt-de.json
- companies/zeit-de.json
Inspired by these lists:
* https://www.kadaza.de/news
* https://t3n.de/news/t3n-usability-eyequant-eyetracking-555003/
Also adds most (all?) German public broadcasting institutions. Oh yeah, and us.
As always, no squashing please.
> Add several German news outlets

- companies/alba.json
- companies/apple.json
- companies/audibkk.json
- companies/buenting.json
- companies/bufferapp.json
- companies/deutsche-bahn.json
- companies/fiverr.json
- companies/hootsuite.json
- companies/huawei.json
- companies/minicar-bs.json
- companies/n26-bank.json
- companies/nanu-nana.json
- companies/oeffentliche.json
- companies/planoly.json
- companies/vero.json
- companies/vw-bank.json
Nothing special (or exciting), just some (unrelated) additions and fixes.
The usual stuff applies.
> Various additions and fixes

- templates/nl/access-default.txt
> Add dutch `access-default` template

- companies/adfirehealth.json
- companies/alikeaudience.json
- companies/appreciate-mobi.json
- companies/branch-io.json
- companies/cuebiq.json
- companies/dataplusmath.json
- companies/factual.json
- companies/freckleiot.json
- companies/fysical.json
- companies/ninthdecimal.json
- companies/revealmobile.json
- companies/safegraph.json
- companies/truedata-co.json
- companies/ubimo.json
> Add remaining NAI companies

- companies/adcolony.json
- companies/connatix.json
- companies/innity.json
- companies/mediavine.json
- companies/omnicommediagroup.json
- companies/quotient-com.json
- companies/revcontent.json
> Add betterads.org companies

- templates/it/access-default.txt
> Add italian 'access-default' template

- companies/stadt-goettingen.json
Because of a recent request I added the city of Göttingen
> Add Stadt Göttingen to the database

- templates/es/access-default.txt
- templates/es/access-tracking.txt
- templates/es/admonition.txt
I translated some templates to Spanish. I plan to translate the rest of them in the next days.
> Add Spanish translations for some templates

- templates/fr/admonition.txt
Translation for french for the admonition file.
Let me know if something isn't okay :)
Issue #230
> admonition french translation

- templates/fr/access-default.txt
- templates/fr/access-tracking.txt
- translate `access-tracking.txt` to french
- added french acronym for GDPR to `access-default.txt` and `access-tracking.txt`
> Translate access-tracking.txt to french

- README.md
Typos:
• 'specifc' corrected to 'specific'
• 'directy' to 'directly'
• 'Universial' to 'Universal'
• 'informaton' to 'information'
Errors:
• 'We invite you contribute' corrected to 'We invite you to contribute'
• removed an extra 'be' (appearing twice consecutively)
> Corrected 4 typos and 3 Grammatical Errors

- companies/b3fuerthde.json
Created using https://company-json.netlify.com
> Add B3-Fürth

- templates/de/objection-default.txt
- templates/en/objection-default.txt
Inspired by datenanfragen/website#65.
> Add objection templates

- companies/tarifhaus-de.json
> Add Tarifhaus AG

- companies/stiftung-drja-de.json
* Add Stiftung deutsch-russischer Jugendaustausch gGmbH
> Add Stiftung deutsch-russischer Jugendaustausch gGmbH

- companies/egentic.json
* Update email address
* update outdated source URLs
> Update eGENTIC GmbH information

- companies/openpetition-de.json
> Add openPetition gGmbH

- companies/intelligent-apps.json
> Add Intelligent Apps GmbH

- companies/synnexcorp-com.json
> Add SYNNEX Corporation

- companies/zarenga-com.json
> Add Zarenga GmbH

- templates/es/access-default.txt
- templates/es/access-tracking.txt
- templates/es/admonition.txt
- templates/es/complaint.txt
- templates/es/erasure-default.txt
- templates/es/rectification-default.txt
* Improve grammar
* Translate untranslated text
* Fix typos
* Fix spelling of "artículo"
* Change "compañía" to "empresa"
* Remove unnecessary spaces
> Improve Spanish translation

- templates/it/objection-default.txt
> Translate objection-default in Italian

- companies/mp-newmedia-com.json
> Add M,P,NEWMEDIA, GmbH

- companies/sift-com.json
> Add Sift Science, Inc.

- companies/rsvg-de.json
> Add Rhein-Sieg-Verkehrsgesellschaft mbH

- companies/flux-fail.json
- companies/mcm-init-com.json
- companies/nianticlabs-com.json
- companies/owncloud-com.json
- companies/wire-com.json
* Add Wire Swiss GmbH
* Add flux.fail UG (haftungsbeschränkt) & Co. Betriebs KG
* Add mcm.init UG (haftungsbeschränkt)
* Add Niantic, Inc.
* Add ownCloud GmbH
> Add companies/organisations

- companies/adp-com.json
- companies/bit4coin-net.json
- companies/revolut-com.json
- companies/rewe-group-com.json
* Add ADP, LLC (closes #395)
* Add bit4coin BV (closes #397)
* Add Revolut Ltd. (closes #401)
* Add REWE-ZENTRALFINANZ eG
> Add ADP, bit4coin, Revolut, REWE-ZENTRALFINANZ

- companies/dannemann-com.json
- companies/kivuto-com.json
* Add Kivuto Solutions Inc. (closes #408)
* Add DANNEMANN EL NOBLE CIGARRO GmbH (closes #405)
> Add Kivuto, Dannemann

- companies/apothekerschmitt-de.json
- companies/corp-bandsintown-com.json
- companies/fielmann-de.json
- companies/ihre-ahornapotheke-de.json
- companies/leopold-apotheke-nbg-de.json
* Add Fielmann AG
* Add Bandsintown, LLC
* Add Leopold-Apotheke, Helene Worowski e.K. (closes #414)
* Add St. Leonhard Apotheke, Roland Schmitt e.K (closes #415)
* Add Apotheker Stefan Schmid e. K. (closes #416)
> Add Fielmann, Bandsintown, and a few pharmacies

- companies/caseking.json
- companies/innogames.json
- companies/suse.json
- companies/traviangames.json
- Add SUSE Software Solutions Germany GmbH
- Add Caseking GmbH
- Add InnoGames GmbH
- Add Travian Games GmbH
> Add SUSE, Travian, InnoGames and Caseking

- companies/readdle
- companies/wework
- Add Readdle
- Add WeWork International Ltd.
> Add Readdle and WeWork International Ltd.

- companies/caseking.json
- companies/cdprojekt.json
- companies/fashionid.json
- companies/logitech.json
- companies/peekundcloppenburg.json
- companies/rocketchat.json
- companies/signal-messenger.json
- companies/threema.json
- Add Logitech Europe S.A.
- Add CD PROJEKT S.A.
- Add Fashion ID GmbH & Co. KG
- Add Peek & Cloppenburg KG
- Add Rocket.Chat Technologies Corp.
- Add Signal Messenger LLC.
- Add Threema GmbH
I was not able to find telephone and fax numbers for some companies. Feel free to add missing parts.
> Added some more social media, gaming and fashion companies

- companies/ghm-de.json
I am not quite sure if _relevant countries_ should be _all_ or just _de_, but since the company runs the **"Internationale** Handwerksmesse" I thought it would be apropriate to choose _all_ here.
What do you think @baltpeter?
> Add Gesellschaft für Handwerksmessen mbH (GHM)

- companies/shutterstock.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22shutterstock%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22name%22%3A%22shutterstock%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F694%22%5D%7D)**
> New company suggestion: 'shutterstock'

- companies/pharmacie-lafayette-toulouse.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22pharmacie-lafayette-toulouse%22%2C%22relevant-countries%22%3A%5B%22fr%22%5D%2C%22categories%22%3A%5B%22health%22%5D%2C%22name%22%3A%22Pharmacie%20Lafayette%20Toulouse%22%2C%22address%22%3A%2235%20rue%20Lafayette%5Cn31000%20Toulouse%5Cn%22%2C%22phone%22%3A%22%2B33%205%2034%2045%2058%2080%22%2C%22email%22%3A%22contact%40pharmacielafayettetoulouse.com%22%2C%22needs-id-document%22%3Atrue%2C%22suggested-transport-medium%22%3A%22email%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F693%22%5D%7D)**
> New company suggestion: 'Pharmacie Lafayette Toulouse'

- companies/travelodge.json
- companies/travelodgecouk.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22travelodgecouk%22%2C%22relevant-countries%22%3A%5B%22gb%22%5D%2C%22categories%22%3A%5B%22travel%22%5D%2C%22name%22%3A%22Travelodge%22%2C%22address%22%3A%22Data%20Protection%20Officer%5CnTravelodge%20Hotels%20Ltd%5CnSleepy%20Hollow%5CnAylesbury%20Road%5CnThame%5CnOxfordshire%5CnOX9%203AT%22%2C%22email%22%3A%22datacontroller%40travelodge.co.uk%22%2C%22web%22%3A%22https%3A%2F%2Fwww.travelodge.co.uk%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.travelodge.co.uk%2Fabout%2Fprivacy-policy%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F692%22%5D%2C%22required-elements%22%3A%5B%7B%22type%22%3A%22name%22%7D%5D%2C%22needs-id-document%22%3Afalse%2C%22suggested-trans …
> New company suggestion: 'Travelodge'

- companies/moemax.json
- companies/moemaxde.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22moemaxde%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22commerce%22%2C%22ads%22%2Cnull%5D%2C%22name%22%3A%22M%C3%B6max%22%2C%22address%22%3A%22m%C3%B6max%20Deutschland%20GmbH%5CnMergentheimerstr.%2059%2C%2097084%20W%C3%BCrzburg%5CnDeutschland%22%2C%22phone%22%3A%22%2B49%20931%2025092299900%22%2C%22fax%22%3A%22%2B49%2089%2051056299900%22%2C%22email%22%3A%22info%40moemax.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.moemax.de%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.moemax.de%2Fc%2Fimpressum%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F703%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%7D)**
> New company suggestion: 'Mömax'

- companies/hostrado.json
- companies/hostradocom.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22hostradocom%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5Bnull%5D%2C%22name%22%3A%22hostrado.com%22%2C%22address%22%3A%22Manuel%20Schnitzer%5CnMartin-Luther-Stra%C3%9Fe%2027%5Cn91207%20Lauf%20a.d.%20Pegnitz%5CnDeutschland%22%2C%22phone%22%3A%22%2B49%20176%2047612688%22%2C%22email%22%3A%22info%40hostrado.com%22%2C%22web%22%3A%22https%3A%2F%2Fwww.hostrado.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.hostrado.com%2Fde%2Fimpressum%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F706%22%5D%2C%22required-elements%22%3A%5B%7B%22desc%22%3A%22Name%22%2C%22type%22%3A%22name%22%7D%2C%7B%22desc%22%3A%22Adresse%22%2C%22type%22%3A%22address%22 …
> New company suggestion: 'hostrado.com'

- companies/grape-io.json
- companies/grapeio.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22grapeio%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22telecommunication%22%5D%2C%22name%22%3A%22UberGrape%20GmbH%22%2C%22address%22%3A%22Lange%20Gasse%2076%2F18%5Cn1080%20Vienna%2C%20AT%22%2C%22phone%22%3A%22%2B43%20680%202205255%22%2C%22email%22%3A%22support%40chatgrape.com%22%2C%22web%22%3A%22https%3A%2F%2Fwww.grape.io%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.grape.io%2Fprivacy%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F707%22%5D%2C%22required-elements%22%3A%5B%7B%22desc%22%3A%22Name%22%2C%22type%22%3A%22name%22%7D%2C%7B%22desc%22%3A%22Address%22%2C%22type%22%3A%22address%22%7D%5D%2C%22suggested-transport-medium%22 …
> New company suggestion: 'UberGrape GmbH'

- companies/bethesda.json
- companies/bethesdanet.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22bethesdanet%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22entertainment%22%5D%2C%22name%22%3A%22ZeniMax%20Media%20Inc.%22%2C%22runs%22%3A%5B%22Bethesda%22%5D%2C%22address%22%3A%22ZeniMax%20Media%20Inc.%5CnAttn%3A%20ZeniMax%20Customer%20Service%2FPrivacy%5Cn1370%20Piccard%20Drive%5CnRockville%2C%20Maryland%2020850%20USA%22%2C%22email%22%3A%22privacy%40support.zenimax.com%22%2C%22web%22%3A%22https%3A%2F%2Fbethesda.net%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fbethesda.net%2Fen%2Fdocument%2Fprivacy-policy%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F712%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22quality%22%3A% …
> New company suggestion: 'ZeniMax Media Inc.'

- companies/firmenliste.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22firmenliste%22%2C%22relevant-countries%22%3A%5B%22de%22%2C%22at%22%2C%22gb%22%2C%22ch%22%5D%2C%22categories%22%3A%5B%22addresses%22%2C%22ads%22%5D%2C%22name%22%3A%22Adresskontor%20Gmbh%20%22%2C%22address%22%3A%22Am%20H%C3%B6fel%201%22%2C%22phone%22%3A%22004915118761813%22%2C%22email%22%3A%22support%40firmenliste.net%22%2C%22web%22%3A%22https%3A%2F%2Fwww.firmenliste.net%22%2C%22suggested-transport-medium%22%3A%22email%22%2C%22quality%22%3A%22verified%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F715%22%5D%7D)**
> New company suggestion: 'Adresskontor Gmbh '

- companies/ecolog-international.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22ecolog-international%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22health%22%5D%2C%22name%22%3A%22%20Ecolog%20International%20FZE%22%2C%22runs%22%3A%5B%22Ecolog%20Deutschland%20GmbH%22%5D%2C%22address%22%3A%22In%20der%20Steele%2014%20%5Cn40599%20D%C3%BCsseldorf%5CnDeutschland%22%2C%22email%22%3A%22dpo%40ecolog-international.com%22%2C%22web%22%3A%22http%3A%2F%2Fecolog-international.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.ecocare.center%2Fdatenschutzerklaerung%2F%22%2C%22https%3A%2F%2Fecolog-international.com%2Facceptable-use-policy%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F714%22%5D%2C%22required-elements%22%3A% …
> New company suggestion: ' Ecolog International FZE'

- companies/csl-computer.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22csl-computer%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22commerce%22%5D%2C%22name%22%3A%22CSL-Computer%20GmbH%20%26%20Co.%20KG%22%2C%22address%22%3A%22Sokelantstra%C3%9Fe%2033-35%5Cn30165%20Hannover%22%2C%22phone%22%3A%22%2B49%20511%2076900100%22%2C%22fax%22%3A%22%2B49%20511%2076900199%22%2C%22email%22%3A%22datenschutz%40csl-computer.com%22%2C%22web%22%3A%22http%3A%2F%2Fwww.csl-computer.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.csl-computer.com%2Fdatenschutz%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F719%22%5D%2C%22quality%22%3A%22verified%22%7D)**
> Add 'CSL-Computer GmbH & Co. KG' (community contribution)

- companies/deezer.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22deezer%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22entertainment%22%5D%2C%22name%22%3A%22Deezer%22%2C%22address%22%3A%2224%20rue%20de%20Calais%2075009%20Paris%20%E2%80%93%20FRANKREICH%20%22%2C%22phone%22%3A%22%2B33%201%2084%2025%2025%2000%22%2C%22email%22%3A%22privacy%40deezer.com%22%2C%22web%22%3A%22http%3A%2F%2Fwww.deezer.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.deezer.com%2Flegal%2Flegal%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F718%22%5D%2C%22quality%22%3A%22verified%22%7D)**
> Add 'Deezer' (community contribution)

- companies/volksbank-plochingen.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22volksbank-plochingen%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22name%22%3A%22Volksbank%20Plochingen%20eG%22%2C%22address%22%3A%22Volksbank%20Plochingen%20eG%2C%20Am%20Fischbrunnen%208%20%2C%2073207%20Plochingen%5CnTel.%3A%2007153%20706%E2%80%930%20%2C%20Fax%3A%2007153%20706%E2%80%93146%22%2C%22email%22%3A%22datenschutz%40volksbank-plochingen.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.volksbank-plochingen.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.volksbank-plochingen.de%2Fservice%2Frechtliche-hinweise%2Fdatenschutzhinweis-zur-website.html%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F734%22%5D%2C%22quality%22%3A%22verified%22%7D)**
> Add 'Volksbank Plochingen eG' (community contribution)

- companies/sparda-west.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22sparda-west%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22finance%22%5D%2C%22name%22%3A%22Sparda-Bank%20West%20eG%22%2C%22runs%22%3A%5B%22Sparda-Bank%20M%C3%BCnster%20(ehem.)%22%5D%2C%22address%22%3A%22Ludwig-Erhard-Allee%2015%5CnDeutschland%22%2C%22phone%22%3A%22%2B49%20211%2023932393%22%2C%22fax%22%3A%22%2B49%20211%20239329494%22%2C%22email%22%3A%22datenschutz%40sparda-west.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.sparda-west.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.sparda-west.de%2Fdatenschutz.html%22%2C%22https%3A%2F%2Fwww.sparda-west.de%2Finternetauftritt%2Fglobale-inhaltsseiten%2Fnachricht-pressemitteilung_9280.html%22%2C%22https%3A% …
> Add 'Sparda-Bank West eG' (community contribution)

- companies/nibcdirect.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22nibcdirect%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22finance%22%5D%2C%22name%22%3A%22NIBC%20Bank%20N.V.%22%2C%22address%22%3A%22Neue%20Mainzer%20Stra%C3%9Fe%2052%5Cn60311%20Frankfurt%20am%20Main%5CnDeutschland%22%2C%22email%22%3A%22datenschutz%40nibcdirect.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.nibcdirect.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.nibcdirect.de%2Fservices%2Fsicherheit%2F%231435%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F737%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22comments%22%3A%5B%22Es%20gibt%20zwei%20verschiedene%20Mails%20f%C3%BCr%20die%20NIBC%2C%20siehe%20Quelle.%22%5D%2C%22 …
> Add 'NIBC Bank N.V.' (community contribution)

- companies/bvg.json
- companies/deutsche-bahn.json
- companies/sbahn-berlin.json
- companies/vbb.json
BVG is the main public transport provider in Berlin complemented by the S-Bahn Berlin GmbH. The VBB is the transport association for public transport in Berlin and Brandenburg.
> Adding BVG, VBB and S-Bahn Berlin. Updated DB

- companies/holvi.json
Holvi is a Payment Institution authorised and regulated by the Financial Supervisory Authority of Finland.
> Add 'Holvi Payment Services Oy'

- companies/comdirect.json
regulatorikcomdirect [at] comdirect.de replied
> Gerne möchten wir Ihr Anliegen schnell und umfassend klären. Zu Ihrer eigenen Sicherheit benötigen wir Ihre eindeutige Identifizierung. Senden Sie uns Ihren Auftrag bitte aus dem Persönlichen Bereich Ihrer Kontoverbindung. Klicken Sie hierfür nach dem Login auf Hilfe & Service. Anschließend scrollen Sie bis zur Überschrift "Allgemeine Kontaktdaten“. Wählen Sie nun "Kontaktformular für Kunden“ und dann "Kontaktformular“. Füllen Sie das Formular aus und schicken Sie uns Ihre Nachricht. Nutzen Sie nicht die Antwortfunktion dieser E-Mail und senden Sie die E-Mail nicht aus einer App Ihres mobilen Endgerätes. 
> Alternativ stehen Ihnen unsere Kundenbetreuer telefonisch rund um die Uhr gerne zur Verfügung. Halten Sie hierfür Ihre Zugangsdaten …
> Add restriction/comment for Comdirect

- companies/amazon-de.json
From their response:
> Wir haben Ihr Konto überprüft und dabei festgestellt, dass unter Ihrer Email Adresse keine Daten vorhanden sind.
> 
> Den Großteil Ihrer Daten können Sie sofort online über Ihr Amazon-Konto abrufen. Klicken Sie dazu einfach auf den Reiter "Mein Konto".
> 
> Sie können in Ihrem Konto Ihre personenbezogenen Daten bei Bedarf auch ändern oder aktualisieren.
> 
> Wenn Sie personenbezogene Daten benötigen, können Sie sich in Ihrem Konto anmelden, um Ihre Identität zu bestätigen und Ihre Anfrage zu stellen. Sie können diese Anfrage über die Seite "Meine Daten anfordern" in Ihrem Amazon-Kundenkonto einreichen, nachdem Sie sich angemeldet haben:
> 
> https://amazon.de/gp/privacycentral/dsar/preview.html
>
> […]
> [a huge list of opt-out settings]
> Add account link for Amazon EU

- companies/1plus-agency.json
- companies/3dhubs.json
- companies/4wave.json
- companies/abebooks.json
> Updated some records

- companies/adroll.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22adroll%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22ads%22%5D%2C%22name%22%3A%22AdRoll%20Advertising%20Ltd.%22%2C%22address%22%3A%22Level%206%5Cn1%2C%20Burlington%20Plaza%5CnBurlington%20Road%5CnDublin%204%5CnIreland%22%2C%22email%22%3A%22dpo%40nextroll.com%22%2C%22web%22%3A%22https%3A%2F%2Fwww.adroll.com%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.adrollgroup.com%2Fprivacy%22%2C%22https%3A%2F%2Fwww.nextroll.com%2Fprivacy%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F753%22%5D%2C%22custom-access-template%22%3A%22access-tracking%22%2C%22suggested-transport-medium%22%3A%22email%22%2C%22quality%22%3A%22verified%22%7D)**
> Update 'adroll' (community contribution)

- companies/viessmann.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22viessmann%22%2C%22relevant-countries%22%3A%5B%22de%22%2C%22all%22%5D%2C%22name%22%3A%22Viessmann%20Werke%20GmbH%20%26%20Co.%20KG%22%2C%22runs%22%3A%5B%22Viessmann%20Deutschland%20GmbH%22%2C%22Viessmann%20Climate%20Solutions%20Berlin%20GmbH%22%2C%22Viessmann%20IT%20Service%20GmbH%22%2C%22Viessmann%20PV%20%2B%20E%20GmbH%22%2C%22Digital%20Energy%20Solutions%20GmbH%20%26%20Co.%20KG%22%5D%2C%22address%22%3A%22Viessmannstra%C3%9Fe%201%5Cn35108%20Allendorf%20(Eder)%22%2C%22phone%22%3A%22%2B49%206452%20700%22%2C%22fax%22%3A%22%2B49%206452%20702780%22%2C%22email%22%3A%22info%40viessmann.com%22%2C%22web%22%3A%22https%3A%2F%2Fwww.viessmann.de%2F%22%2C%22sources%22%3A%5B%22https%3A%2F% …
> Add 'Viessmann Werke GmbH & Co. KG' (community contribution)

- companies/mediainformationsystems.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22mediainformationsystems%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22ads%22%5D%2C%22name%22%3A%22Media%20Information%20Systems%20Deutschland%20GmbH%22%2C%22address%22%3A%22Bavariaring%2016%5Cn80336%20M%C3%BCnchen%5CnBundesrepublik%20Deutschland%5Cn%22%2C%22phone%22%3A%22%2B49%2089%20121400858%22%2C%22email%22%3A%22datenschutz%40mismail.de%22%2C%22web%22%3A%22https%3A%2F%2Fmediainformationsystems.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fmediainformationsystems.de%2Fdatenschutz.html%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F760%22%5D%2C%22quality%22%3A%22verified%22%7D)**
> Add 'Media Information Systems Deutschland GmbH' (community contribution)

- companies/marketwing.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22marketwing%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22name%22%3A%22marketwing%20GmbH%22%2C%22address%22%3A%22Steinriede%205a%5Cn30827%20Garbsen%22%2C%22phone%22%3A%22%2B49%205131%20452250%22%2C%22fax%22%3A%22%2B49%205131%204522520%22%2C%22email%22%3A%22datenschutz%40marketwing.de%22%2C%22web%22%3A%22https%3A%2F%2Fmarketwing.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fmarketwing.de%2Fdatenschutzerklaerung%2F%22%2C%22https%3A%2F%2Fmarketwing.de%2Fimpressum%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F765%22%5D%2C%22quality%22%3A%22verified%22%7D)**
> Add 'marketwing GmbH' (community contribution)

- companies/justwatch.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22justwatch%22%2C%22relevant-countries%22%3A%5B%22de%22%2C%22all%22%5D%2C%22categories%22%3A%5B%22entertainment%22%2C%22ads%22%5D%2C%22name%22%3A%22JustWatch%20GmbH%22%2C%22address%22%3A%22Boxhagener%20Str.%2018%5CnDE%20-%2010245%20Berlin%22%2C%22email%22%3A%22data-police%40justwatch.com%22%2C%22web%22%3A%22https%3A%2F%2Fwww.justwatch.com%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.justwatch.com%2Fde%2FImpressum%22%2C%22https%3A%2F%2Fwww.justwatch.com%2Fde%2Fprivacy-policy%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F767%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22quality%22%3A%22verified%22%7D)**
> Add 'JustWatch GmbH' (community contribution)

- companies/likee.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22likee%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22entertainment%22%2C%22social%20media%22%5D%2C%22name%22%3A%22Bigo%20Technology%20Pte.%20Ltd.%22%2C%22runs%22%3A%5B%22Likee%22%2C%22LIKE%20Video%20(formerly)%22%5D%2C%22address%22%3A%2230%20Pasir%20Panjang%20Road%20%23%2015-31A%5CnMapletree%20Business%20City%5CnSingapore%20117440%22%2C%22phone%22%3A%22%2B1%20829%20205%208342%22%2C%22email%22%3A%22likeeaffairs%40bigo.sg%22%2C%22web%22%3A%22https%3A%2F%2Flikee.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Flikee.com%2Fprivacy%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F539%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdat …
> Update 'likee' (community contribution)

- companies/schober.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22schober%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22addresses%22%5D%2C%22name%22%3A%22Schober%20Information%20Group%20Deutschland%20GmbH%22%2C%22address%22%3A%22Meisenweg%2037%5Cn70771%20Leinfelden-Echterdingen%5CnDeutschland%22%2C%22phone%22%3A%22%2B49%207156%203040%22%2C%22fax%22%3A%22%2B49%207156%20304283%22%2C%22email%22%3A%22datenschutz%40schober.de%22%2C%22web%22%3A%22https%3A%2F%2Fschober.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fschober.de%2Fdatenschutz%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F775%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22comments%22%3A%5B%22Haben%20laut%20eigenen%20Angaben …
> Update 'schober' (community contribution)

- companies/woltlab.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22woltlab%22%2C%22relevant-countries%22%3A%5B%22de%22%2C%22at%22%2C%22ch%22%5D%2C%22name%22%3A%22WoltLab%20GmbH%22%2C%22address%22%3A%22Nedlitzer%20Str.%2027B%5Cn14469%20Potsdam%5CnDeutschland%22%2C%22phone%22%3A%220331%2096784338%22%2C%22email%22%3A%22woltlab%40woltlab.com%22%2C%22web%22%3A%22https%3A%2F%2Fwww.woltlab.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.woltlab.com%2Fde%2Flegal-notice%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F776%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22quality%22%3A%22verified%22%7D)**
> Add 'WoltLab GmbH' (community contribution)

- templates/it/access-default.txt
- templates/it/access-tracking.txt
- templates/it/admonition.txt
- templates/it/erasure-default.txt
- templates/it/objection-default.txt
- templates/it/rectification-default.txt
- Update Italian templates with clearer information as requested in #229
- Capitalize some incorrectly lowercase words
> Make templates clearer (IT)

- companies/consorsfinanz.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22consorsfinanz%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22finance%22%2C%22insurance%22%5D%2C%22name%22%3A%22BNP%20Paribas%20S.A.%20Niederlassung%20Deutschland%22%2C%22runs%22%3A%5B%22Consors%20Finanz%22%2C%22Commerz%20Finanz%20(ehemals)%22%2C%22Consorsbank%22%2C%22DAB%20BNP%20Paribas%22%2C%22BNP%20Paribas%20Wealth%20Management%22%2C%22BNP%20Paribas%20Corporate%20%26%20Institutional%20Banking%22%2C%22BNP%20Paribas%20Securities%20Services%22%5D%2C%22address%22%3A%22Europa-Allee%2012%5Cn60327%20Frankfurt%20am%20Main%5CnDeutschland%22%2C%22phone%22%3A%22%2B49%2069%2071930%22%2C%22fax%22%3A%22%2B49%20203%2034695409%22%2C%22email%22%3A%22gdpr.desk.ci …
> Update 'BNP Paribas S.A. Niederlassung Deutschland' (community contribution)

- companies/bunq.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22bunq%22%2C%22relevant-countries%22%3A%5B%22de%22%2C%22it%22%2C%22gb%22%2C%22es%22%2C%22fr%22%2C%22pt%22%5D%2C%22categories%22%3A%5B%22finance%22%5D%2C%22name%22%3A%22bunq%20B.V.%20%22%2C%22address%22%3A%22Naritaweg%20131-133%5Cn1043%20BS%20Amsterdam%5CnNL%22%2C%22email%22%3A%22privacy%40bunq.com%22%2C%22web%22%3A%22https%3A%2F%2Fwww.bunq.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.bunq.com%2Fterms%22%2C%22https%3A%2F%2Fwww.bunq.com%2Fde%2Fprivacy%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F778%22%5D%2C%22required-elements%22%3A%5B%7B%22desc%22%3A%22Adress%22%2C%22type%22%3A%22address%22%2C%22optional%22%3Afalse%7D%2C%7B%22desc%22%3A%22Phone%22%2C%2 …
> Add 'bunq B.V. ' (community contribution)

- companies/untappd.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22untappd%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22social%20media%22%2C%22commerce%22%5D%2C%22name%22%3A%22Untappd%2C%20Inc.%22%2C%22runs%22%3A%5B%22Untappd%22%2C%22Untappd%20for%20Business%22%2C%22Untappd%20Store%22%5D%2C%22address%22%3A%2221%20S%20Front%20St%20%5CnWilmington%2C%20NC%5CnU.S.A.%20%22%2C%22email%22%3A%22gdpr%40untappd.com%22%2C%22web%22%3A%22https%3A%2F%2Funtappd.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Funtappd.com%2Fprivacy%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F779%22%5D%2C%22required-elements%22%3A%5B%7B%22desc%22%3A%22E-Mail%22%2C%22type%22%3A%22email%22%2C%22optional%22%3Afalse%7D%5D%2C%22nee …
> Add 'Untappd, Inc.' (community contribution)

- companies/union-investment.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22union-investment%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22finance%22%5D%2C%22name%22%3A%22Union%20Investment%20Gruppe%22%2C%22runs%22%3A%5B%22Union%20Investment%20Privatfonds%20GmbH%22%2C%22Union%20Investment%20Real%20Estate%20GmbH%22%2C%22Union%20Investment%20Service%20Bank%20AG%22%2C%22Quoniam%20Asset%20Management%20GmbH%22%2C%22Union%20Investment%20Institutional%20GmbH%22%2C%22Union%20Investment%20Institutional%20Property%20GmbH%22%2C%22UIR%20Verwaltungsgesellschaft%20mbH%22%2C%22Union%20IT-Services%20GmbH%22%2C%22Union%20Service-Gesellschaft%20mbH%22%2C%22VisualVest%20GmbH%22%5D%2C%22address%22%3A%22Wei%C3%9Ffrauenstra%C3%9Fe%207%5Cn6031 …
> Add 'Union Investment Gruppe' (community contribution)

- companies/baer-schuhe.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22baer-schuhe%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22commerce%22%5D%2C%22name%22%3A%22B%C3%84R%20GmbH%22%2C%22address%22%3A%22Pleidelsheimer%20Stra%C3%9Fe%2015%5Cn74321%20Bietigheim-Bissingen%22%2C%22phone%22%3A%2207142956610%22%2C%22fax%22%3A%2207142956622%22%2C%22email%22%3A%22kundenbetreuung%40baer-schuhe.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.baer-schuhe.de%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.baer-schuhe.de%2Frechtliches-impressum%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F793%22%5D%2C%22needs-id-document%22%3Afalse%2C%22suggested-transport-medium%22%3A%22letter%22%2C%22quality%22%3A%22verified%22%7 …
> Add 'BÄR GmbH' (community contribution)

- companies/we-conect.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22we-conect%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22ads%22%2C%22social%20media%22%2C%22commerce%22%5D%2C%22name%22%3A%22we.CONECT%20Global%20Leaders%20GmbH%22%2C%22runs%22%3A%5B%22scaleup%20360%22%2C%22we.CONECT%20DISCOVER%22%5D%2C%22address%22%3A%22Reichenberger%20Str.%20124%5Cn10999%20Berlin%5CnDeutschland%22%2C%22phone%22%3A%22%2B49%2030%2052107030%22%2C%22fax%22%3A%22%2B49%2030%20521070330%22%2C%22email%22%3A%22info%40we-conect.com%22%2C%22web%22%3A%22https%3A%2F%2Fwww.we-conect.com%2Fde%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fprivacy.we-conect.com%22%2C%22https%3A%2F%2Fprivacy.we-conect.com%2Fdata-privacy%2F%22%2C%22https%3A%2F%2Fpr …
> Add 'we.CONECT Global Leaders GmbH' (community contribution)

- templates/nl/erasure-default.txt
I had to do this earlier, because this is one of the most important letters.
> Translate erasure to Dutch

- companies/itzehoer.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22itzehoer%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22insurance%22%5D%2C%22name%22%3A%22itzehoer%22%2C%22address%22%3A%22Itzehoer%20Versicherung%2FBrandgilde%20von%201691%20Versicherungsverein%20a.G.%5Cn%5CnItzehoer%20Platz%5Cn%5Cn25521%20Itzehoe%22%2C%22fax%22%3A%22%2B49%204821%207738888%22%2C%22email%22%3A%22datenschutz%40itzehoer.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.itzehoer.de%2Fdatenschutz%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F805%22%5D%2C%22needs-id-document%22%3Afalse%2C%22suggested-transport-medium%22%3A%22letter%22%2C%22quality%22%3A%22verified%22%7D)**
> Add 'itzehoer' (community contribution)

- companies/hagengrote.json
Added mail order business/online shop "Hagen Grote GmbH".
Tested GDPR request successfully about 2 years ago.
> Add 'Hagen Grote GmbH'

- companies/baaderbank.json
- companies/scalablecapital.json
Added fintech/asset manager "Scalable Capital Vermögensverwaltung GmbH" and bank "Baader Bank AG".
> Add 'Scalable Capital' and 'Baader Bank'

- companies/nhi2.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22nhi2%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22telecommunication%22%2C%22ads%22%5D%2C%22name%22%3A%22nhi%C2%B2%20AG%20Interviews%20International%22%2C%22address%22%3A%22%20Am%20Metternicher%20Hof%2015%5Cn%2053111%20Bonn%22%2C%22phone%22%3A%22%2B49%20228%20201780%22%2C%22fax%22%3A%22%2B49%20228%202017878%22%2C%22email%22%3A%22ds-beauftragter%40nhi2.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.nhi2.de%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.nhi2.de%2Fprivacy%22%2C%22https%3A%2F%2Fwww.nhi2.de%2Fimpress%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F791%22%5D%2C%22required-elements%22%3A%5B%7B%22desc%22%3A%22Name%22%2C%22typ …
> Add 'nhi² AG Interviews International' (community contribution)

- companies/eastbankclub.json
Added 'East Bank Club The Fitness Factory GmbH'. Operator of gyms/fitness studios in Berlin and Brandenburg (Germany) under brand name "SUPERFIT".
Tested GDPR request successfully about 2 years ago.
> Add 'East Bank Club The Fitness Factory GmbH'

- companies/m-net.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22m-net%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22name%22%3A%22M-net%20Telekommunikations%20GmbH%22%2C%22address%22%3A%22Frankfurter%20Ring%20158%5Cn80807%20M%C3%BCnchen%22%2C%22phone%22%3A%22089452000%22%2C%22fax%22%3A%220894520045%22%2C%22email%22%3A%22info%40m-net.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.m-net.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.m-net.de%2Frechtliches%2Fimpressum%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F797%22%5D%2C%22quality%22%3A%22verified%22%7D)**
> Add 'M-net Telekommunikations GmbH' (community contribution)

- companies/renault-bank-direkt.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22renault-bank-direkt%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22finance%22%5D%2C%22name%22%3A%22%20Renault%20Bank%20direkt%22%2C%22address%22%3A%22RCI%20Banque%20S.A.%20Niederlassung%20Deutschland%5CnJagenbergstra%C3%9Fe%201%5Cn41468%20Neuss%22%2C%22phone%22%3A%22%2B49%202131%20401040%22%2C%22email%22%3A%22renault-bank-direkt%40rcibanque.com%20%22%2C%22web%22%3A%22https%3A%2F%2Fwww.renault-bank-direkt.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.renault-bank-direkt.de%2Fhilfe-informationen%2Fdatenschutz.html%22%2C%22https%3A%2F%2Fwww.renault-bank-direkt.de%2Fhilfe-informationen%2Fimpressum.html%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfrage …
> Add ' Renault Bank direkt' (community contribution)

- companies/unitedbase.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22unitedbase%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22name%22%3A%22unitedbase%20Vertriebsgesellschaft%20mbH%22%2C%22address%22%3A%22Kurf%C3%BCrstendamm%20199%5CnD-10719%20Berlin%22%2C%22phone%22%3A%22%2B49%2030%2088715770%22%2C%22fax%22%3A%22%2B49%2030%20887157720%22%2C%22email%22%3A%22info%40unitedbase.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.unitedbase.de%22%2C%22sources%22%3A%5B%22Impressum%20www.unitedbase.de%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F813%22%5D%2C%22quality%22%3A%22verified%22%7D)**
> Add 'unitedbase Vertriebsgesellschaft mbH' (community contribution)

- companies/figuya.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22figuya%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22commerce%22%5D%2C%22name%22%3A%22Figuya%20GmbH%22%2C%22address%22%3A%22Wolfener%20Str%2036%5CnHaus%20R%2BS%5Cn12681Berlin%5CnDeutschland%22%2C%22phone%22%3A%22%2B49%2030%20577011989%22%2C%22fax%22%3A%22%2B49%2030%20577011987%22%2C%22email%22%3A%22kontakt%40figuya.de%22%2C%22web%22%3A%22https%3A%2F%2Ffiguya.com%22%2C%22needs-id-document%22%3Atrue%2C%22quality%22%3A%22verified%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F817%22%5D%7D)**
> Add 'Figuya GmbH' (community contribution)

- companies/arvato-bertelsmann.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22arvato-bertelsmann%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22collection%20agency%22%5D%2C%22name%22%3A%22Bertelsmann%20SE%20%26%20Co.%20KGaA%22%2C%22address%22%3A%22Carl-Bertelsmann-Stra%C3%9Fe%20270%5Cn33311%20G%C3%BCtersloh%5CnDeutschland%22%2C%22phone%22%3A%22%2B49%205241%205276000%22%2C%22fax%22%3A%22%2B49%205241%205276001%22%2C%22email%22%3A%22datenschutz%40bertelsmann.de%22%2C%22web%22%3A%22https%3A%2F%2Ffinance.arvato.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Ffinance.arvato.com%2Fde%2Fueber-arvato%2Fimpressum.html%22%2C%22https%3A%2F%2Ffinance.arvato.com%2Fde%2Fueber-arvato%2Fdatenschutz.html%22%2C%22https%3A%2F%2Fwww.biifund.com%2F …
> Update 'Bertelsmann SE & Co. KGaA' (community contribution)

- companies/kleiderkreisel-de.json
- companies/vinted-uab-cz.json
- companies/vinted-uab-lt.json
- companies/vinted-uab-pl.json
- companies/vinted-uab-uk.json
- companies/vinted-uab.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22kleiderkreisel-de%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22addresses%22%5D%2C%22name%22%3A%22kleiderkreisel.de%22%2C%22runs%22%3A%5B%22mamikreisel.de%22%5D%2C%22address%22%3A%22Wallstra%C3%9Fe%2065%5Cn10179%20Berlin%22%2C%22email%22%3A%22legal%40kleiderkreisel.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.kleiderkreisel.de%2Fimpressum%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F801%22%5D%2C%22quality%22%3A%22verified%22%7D)**
> Add 'kleiderkreisel.de' (community contribution)

- companies/natwest.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22natwest%22%2C%22relevant-countries%22%3A%5B%22gb%22%5D%2C%22categories%22%3A%5B%22finance%22%5D%2C%22name%22%3A%22NatWest%20Group%20plc%20%22%2C%22runs%22%3A%5B%22Natwest%22%2C%22National%20Westminster%20Bank%20Plc%22%5D%2C%22address%22%3A%22NatWest%2C%20%5CnSubject%20Access%20Requests%2C%20%5CnManchester%20Mailroom%2C%5Cn1%20Hardman%20Boulevard%2C%20%5CnManchester%2C%20M3%203AQ%5CnUnited%20Kingdom%22%2C%22phone%22%3A%22%2B44%20345%20788%208444%22%2C%22web%22%3A%22https%3A%2F%2Fwww.natwest.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fpersonal.natwest.com%2Fpersonal%2Fprivacy-policy.html%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F824%22%5D%2C%22required …
> Add 'NatWest Group plc ' (community contribution)

- companies/opelbank-de.json
- companies/opelbank.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22opelbank%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22name%22%3A%22Opel%20Bank%20S.A.%20Niederlassung%20Deutschland%22%2C%22address%22%3A%22Mainzer%20Stra%C3%9Fe%20190%5Cn65428%20R%C3%BCsselsheim%20am%20Main%22%2C%22phone%22%3A%22%2B49%206142%20878878%22%2C%22email%22%3A%22datenschutzbeauftragte%40opelfinance.com%22%2C%22web%22%3A%22https%3A%2F%2Fwww.opelbank.de%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.opelbank.de%2Fdatenschutz%2F%22%2C%22https%3A%2F%2Fwww.opelbank.de%2Fimpressum%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F827%22%5D%2C%22quality%22%3A%22verified%22%7D)**
> Add 'Opel Bank S.A. Niederlassung Deutschland' (community contribution)

- companies/pfalzwerke.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22pfalzwerke%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22utility%22%5D%2C%22name%22%3A%22PFALZWERKE%20AKTIENGESELLSCHAFT%22%2C%22runs%22%3A%5B%22123energie%22%2C%22ALDI%20Gr%C3%BCnstrom%22%5D%2C%22address%22%3A%22Kurf%C3%BCrstenstra%C3%9Fe%2029%5Cn67061%20Ludwigshafen%5CnDeutschland%22%2C%22phone%22%3A%22%2B49%20621%20570572585%22%2C%22fax%22%3A%22%2B49%20621%205853388%22%2C%22email%22%3A%22datenschutz%40pfalzwerke.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.pfalzwerke.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.pfalzwerke.de%2Fdatenschutz%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F834%22%5D%2C%22required-elements%22%3A%5B% …
> Add 'PFALZWERKE AKTIENGESELLSCHAFT' (community contribution)

- companies/arkoselabs.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22arkoselabs%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22utility%22%2C%22ads%22%5D%2C%22name%22%3A%22Arkose%20Labs%2C%20Inc.%22%2C%22address%22%3A%22250%20Montgomery%20St%5CnLvl%2010%5CnSan%20Francisco%20%5CnUSA%22%2C%22email%22%3A%22GDPR%40arkoselabs.com%22%2C%22web%22%3A%22https%3A%2F%2Fwww.arkoselabs.com%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Farkoselabs.atlassian.net%2Fwiki%2Fspaces%2FLEG%2Fpages%2F1146946%2FPrivacy%2BPolicy%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F839%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22quality%22%3A%22verified%22%7D)**
> Add 'Arkose Labs, Inc.' (community contribution)

- companies/abis.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22abis%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22addresses%22%5D%2C%22name%22%3A%22ABIS%20GmbH%22%2C%22address%22%3A%22Lyoner%20Str.%2020%5Cn60528%20Frankfurt%20am%20Main%5CnDeutschland%22%2C%22phone%22%3A%22%2B49%2069%207920090%22%2C%22fax%22%3A%22%2B49%2069%2079200920%22%2C%22email%22%3A%22datenschutz%40abis-online.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.abis-online.de%2Fdatenschutz%2Fdatenschutzanfrage%2F%22%2C%22https%3A%2F%2Fwww.abis-online.de%2Fkontakt%2Fimpressum%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F812%22%5D%2C%22required-elements%22%3A%5B%7B%22desc%22%3A%22Name%22%2C%22type%22%3A%22name%22%7D%2C%7 …
> Update 'ABIS GmbH' (community contribution)

- companies/academia-edu.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22academia-edu%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22school%22%5D%2C%22name%22%3A%22academia.edu%22%2C%22address%22%3A%22Academia%5Cn580%20California%20Street%5CnNo.%20400%5CnSan%20Francisco%2C%20CA%2094104%22%2C%22sources%22%3A%5B%22academia.edu%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F837%22%5D%2C%22quality%22%3A%22verified%22%7D)**
> Add 'academia.edu' (community contribution)

- companies/concordia-sozialprojekte.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22concordia-sozialprojekte%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22nonprofit%22%5D%2C%22name%22%3A%22CONCORDIA%20Sozialprojekte%20Stiftung%20Deutschland%22%2C%22address%22%3A%22Hohnerstra%C3%9Fe%2025%5Cn70469%20Stuttgart%22%2C%22phone%22%3A%22%2B49%20711%2080630070%22%2C%22email%22%3A%22stiftung%40concordia-sozialprojekte.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.concordia-sozialprojekte.de%2Fwillkommen%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.concordia-sozialprojekte.de%2Fdatenschutz%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F835%22%5D%2C%22quality%22%3A%22verified%22%7D)**
> Add 'CONCORDIA Sozialprojekte Stiftung Deutschland' (community contribution)

- companies/starlink-germany-gmbh.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22starlink-germany-gmbh%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22telecommunication%22%5D%2C%22name%22%3A%22Starlink%20Germany%20GmbH%20%22%2C%22address%22%3A%22Mainzer%20Landstr.%2049%5Cn60329%20Frankfurt%20am%20Main%5CnDeutschland%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.handelsregisterbekanntmachungen.de%2Fskripte%2Fhrb.php%3Frb_id%3D731652%26land_abk%3Dhe%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F838%22%5D%2C%22quality%22%3A%22verified%22%7D)**
> Add 'Starlink Germany GmbH ' (community contribution)

- companies/palantir.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22palantir%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5Bnull%5D%2C%22name%22%3A%22palantir%22%2C%22address%22%3A%22Palantir%20Technologies%20Inc.%5CnAttention%3A%20Legal%20Department%2C%20Privacy%20Statement%20Issues%5Cn100%20Hamilton%20Ave.%2C%20Suite%20300%5CnPalo%20Alto%2C%20CA%2094301%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.palantir.com%2Fprivacy-and-security%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F836%22%5D%2C%22quality%22%3A%22verified%22%7D)**
> Add 'palantir' (community contribution)

- companies/biontech.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22biontech%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22health%22%5D%2C%22name%22%3A%22BioNTech%20SE%22%2C%22address%22%3A%22An%20der%20Goldgrube%2012%5Cn55131%20Mainz%5CnDeutschland%22%2C%22phone%22%3A%22%2B49%206131%2090841030%22%2C%22email%22%3A%22data.privacy%40biontech.de%22%2C%22web%22%3A%22https%3A%2F%2Fbiontech.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fbiontech.de%2Fdata-privacy-policy%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F833%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22quality%22%3A%22verified%22%7D)**
> Add 'BioNTech SE' (community contribution)

- companies/sparda-hessen.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22sparda-hessen%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5Bnull%5D%2C%22name%22%3A%22Sparda-Bank%20Hessen%20eG%22%2C%22address%22%3A%22Datenschutzbeauftragte(r)%5CnOsloer%20Stra%C3%9Fe%202%5Cn60327%20Frankfurt%20am%20Main%22%2C%22phone%22%3A%22%20069%20%2F%207537%20%E2%80%93%20500%22%2C%22fax%22%3A%22069%20%2F%207537%20%E2%80%93%209500%22%2C%22email%22%3A%22datenschutz%40sparda-hessen.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.sparda-hessen.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.sparda-hessen.de%2Fdatenschutz.html%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F856%22%5D%2C%22needs-id-document%22%3Afalse%2C%22quality%22%3A%2 …
> Add 'Sparda-Bank Hessen eG' (community contribution)

- companies/imgur.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22imgur%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22social%20media%22%2C%22entertainment%22%5D%2C%22name%22%3A%22Imgur%20Inc.%22%2C%22address%22%3A%22600%20California%20St.%2C%20%5CnFloor%2011%2C%20San%20Francisco%20%5CnCA%2094018-2727.%20%5CnUnited%20States%20of%20America%22%2C%22email%22%3A%22privacy%40imgur.com%22%2C%22web%22%3A%22https%3A%2F%2Fimgur.com%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fimgur.com%2Fprivacy%22%2C%22https%3A%2F%2Fimgur.com%2Ftos%22%2C%22https%3A%2F%2Fwww.bloomberg.com%2Fresearch%2Fstocks%2Fprivate%2Fsnapshot.asp%3Fprivcapid%3D252810438%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F275%22%2C%22htt …
> Update 'Imgur Inc.' (community contribution)

- companies/mediainformationsystems.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22mediainformationsystems%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22addresses%22%5D%2C%22name%22%3A%22Media%20Information%20Systems%20Deutschland%20GmbH%22%2C%22address%22%3A%22Bavariaring%2016%5CnD-80336%20M%C3%BCnchen%5Cn%22%2C%22phone%22%3A%22%2B49%2089%20121400858%22%2C%22email%22%3A%22datenschutz%40mismail.de%22%2C%22web%22%3A%22https%3A%2F%2Fmediainformationsystems.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fmediainformationsystems.de%2Fdatenschutz.html%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F851%22%5D%2C%22required-elements%22%3A%5B%7B%22desc%22%3A%22Vor-%20und%20Nachname%20sind%20neben%20der%20Anschrift%20zur%20 …
> Update 'Media Information Systems Deutschland GmbH' (community contribution)

- companies/aufstehen.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22aufstehen%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22political%20party%22%5D%2C%22name%22%3A%22Aufstehen%20Tr%C3%A4gerverein%20e.V.%22%2C%22address%22%3A%22Friedrichstra%C3%9Fe%20171%5Cn10117%20Berlin%5CnDeutschland%22%2C%22phone%22%3A%22%2B49%20171%205545350%22%2C%22email%22%3A%22datenschutz%40aufstehen.de%22%2C%22web%22%3A%22https%3A%2F%2Faufstehen.de%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Faufstehen.de%2Fweb%2Fdatenschutz%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F852%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22quality%22%3A%22verified%22%7D)**
> Add 'Aufstehen Trägerverein e.V.' (community contribution)

- companies/bwi.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22bwi%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22public%20body%22%5D%2C%22name%22%3A%22BWI%20GmbH%22%2C%22runs%22%3A%5B%22BwMessenger%22%5D%2C%22address%22%3A%22Auf%20dem%20Steinb%C3%BCchel%2022%5Cn53340%20Meckenheim%5CnDeutschland%22%2C%22phone%22%3A%22%2B49%202225%2098814529%22%2C%22email%22%3A%22datenschutzbeauftragter%40bwi.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.bwi.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.bwi.de%2Fdatenschutz%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F853%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22quality%22%3A%22verified%22%7D)**
> Add 'BWI GmbH' (community contribution)

- companies/sparkasse.json
- companies/suedtiroler-sparkasse.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22sparkasse%22%2C%22relevant-countries%22%3A%5B%22it%22%2C%22at%22%2C%22ch%22%5D%2C%22categories%22%3A%5B%22finance%22%5D%2C%22name%22%3A%22S%C3%BCdtiroler%20Sparkasse%20AG%22%2C%22address%22%3A%22Sparkassenstra%C3%9Fe%2012%5Cn39100%20BOZEN%5CnItaly%22%2C%22phone%22%3A%22%2B39%20840%20052%20052%22%2C%22email%22%3A%22privacy.crbz%40sparkasse.it%22%2C%22web%22%3A%22https%3A%2F%2Fwww.sparkasse.it%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.sparkasse.it%2Fde%2Fprivacy%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F831%22%5D%2C%22comments%22%3A%5B%22Ich%20hab%20mal%20assumed%2C%20dass%20CH%20und%20AT%20auch%20relevant%20sind%2C%20weil%20die%20Seite%20auch%20a …
> Add 'Südtiroler Sparkasse AG' (community contribution)

- companies/jetbrains-com.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22jetbrains-com%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22name%22%3A%22JetBrains%20s.r.o.%22%2C%22runs%22%3A%5B%22IntelliJ%20Software%20s.r.o.%20(formerly)%22%5D%2C%22address%22%3A%22Kav%C4%8D%C3%AD%20Hory%20Office%20Park%5CnNa%20h%C5%99ebenech%20II%201718%2F10%5CnPraha%204%20-%20Nusle%20-%20140%2000%5CnCzech%20Republic%22%2C%22phone%22%3A%22%2B420%20241%20722%20501%22%2C%22fax%22%3A%22%2B420%20241%20722%20540%22%2C%22email%22%3A%22privacy%40jetbrains.com%22%2C%22web%22%3A%22https%3A%2F%2Fwww.jetbrains.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.jetbrains.com%2Fcompany%2Fcontacts%2F%23headquarters-international-sales%22%2C%22https%3A%2F%2Fwww.jetbrains.com%2Fc …
> Update 'JetBrains s.r.o.' (community contribution)

- companies/ikk-classic.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22ikk-classic%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22name%22%3A%22IKK%20Classic%20%22%2C%22address%22%3A%22Tannenstr.%204%20b%2C%2001099%20Dresden%20%22%2C%22email%22%3A%22datenschutz%40ikk-classic.de%22%2C%22quality%22%3A%22verified%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F862%22%5D%7D)**
> Add 'IKK Classic ' (community contribution)

- companies/beyerdynamic.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22beyerdynamic%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22entertainment%22%5D%2C%22name%22%3A%22beyerdynamic%20GmbH%20%26%20Co.%20KG%22%2C%22address%22%3A%22c%2Fo%20WFC%20IT%20GmbH%5CnPflastergasse%205%5Cn74889%20Sinsheim%5CnDeutschland%22%2C%22phone%22%3A%22%2B49%207261%2094520202%22%2C%22email%22%3A%22datenschutz%40wfc-it.com%22%2C%22web%22%3A%22https%3A%2F%2Fwww.beyerdynamic.de%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.beyerdynamic.de%2Frechtliche-informationen%2Fdatenschutzerklaerung%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F861%22%5D%2C%22quality%22%3A%22verified%22%7D)**
> Add 'beyerdynamic GmbH & Co. KG' (community contribution)

- companies/dak-de.json
- companies/dak.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22dak%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22health%22%5D%2C%22name%22%3A%22service%40dak.de%22%2C%22runs%22%3A%5Bnull%5D%2C%22address%22%3A%22DAK-Gesundheit%5CnNagelsweg%2027%20-%2031%5Cn20097%20Hamburg%22%2C%22phone%22%3A%22040-236%2048%2055-0%22%2C%22email%22%3A%22service%40dak.de%22%2C%22web%22%3A%22https%3A%2F%2Fdak.de%2F%22%2C%22needs-id-document%22%3Afalse%2C%22suggested-transport-medium%22%3A%22email%22%2C%22quality%22%3A%22verified%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F866%22%5D%7D)**
> Add 'service@dak.de' (community contribution)

- companies/bankofscotland-de.json
- companies/bankofscotland.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22bankofscotland%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22finance%22%5D%2C%22name%22%3A%22Lloyds%20Bank%20GmbH%22%2C%22runs%22%3A%5B%22Bank%20of%20Scotland%22%5D%2C%22address%22%3A%22Karl-Liebknecht-Stra%C3%9Fe%205%5Cn10178%20Berlin%22%2C%22phone%22%3A%22%2B49%2030%202804280%22%2C%22email%22%3A%22kundenservice%40bankofscotland.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.bankofscotland.de%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.bankofscotland.de%2Fdatenschutz%22%2C%22https%3A%2F%2Fwww.bankofscotland.de%2Fdam%2Fjcr%3A7c02f359-ff51-455f-ae21-8750de70f7a8%2Fdatenschutzinformation.pdf%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fp …
> Add 'Lloyds Bank GmbH' (community contribution)

- companies/digitalmedialine.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22digitalmedialine%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22social%20media%22%5D%2C%22name%22%3A%22Digital%20Media%20Line%22%2C%22address%22%3A%22Number%207%2C%20J-2%20Block%2C%20Wapda%20Town%2C%20Lahore%2C%20Pakistan%22%2C%22phone%22%3A%2203004246680%22%2C%22email%22%3A%22info%40digitalmedialine.com%22%2C%22web%22%3A%22https%3A%2F%2Fdigitalmedialine.com%2F%22%2C%22quality%22%3A%22verified%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F857%22%5D%7D)**
> Add 'Digital Media Line' (community contribution)

- companies/kinderkrankenhaus-altonaer.json
- companies/kinderkrankenhaus.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22kinderkrankenhaus%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22health%22%5D%2C%22name%22%3A%22AKK%20Altonaer%20Kinderkrankenhaus%20gGmbH%20(AKK)%22%2C%22runs%22%3A%5B%22AKK%20Altonaer%20Kinderkrankenhaus%20gGmbH%20(AKK)%22%5D%2C%22address%22%3A%22Bleickenallee%2038%5Cn22763%20Hamburg%5CnDeutschland%22%2C%22phone%22%3A%22%2B49%2040%20889080%22%2C%22fax%22%3A%22%2B49%2040%2088908366%22%2C%22email%22%3A%22datenschutz%40kinderkrankenhaus.net%22%2C%22web%22%3A%22https%3A%2F%2Fwww.kinderkrankenhaus.net%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.kinderkrankenhaus.net%2Fdatenschutz.html%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F …
> Add 'AKK Altonaer Kinderkrankenhaus gGmbH (AKK)' (community contribution)

- companies/abihome.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22abihome%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22ads%22%2C%22school%22%2C%22commerce%22%5D%2C%22name%22%3A%22Abihome%20GmbH%22%2C%22address%22%3A%22c%2Fo%20ANKA%20Rechtsanwaltsgesellschaft%20mbH%5CnKaninenbergh%C3%B6he%2050%5Cn45136%20Essen%5CnDeutschland%22%2C%22phone%22%3A%220800%20-%203%2077%2022%2044%22%2C%22email%22%3A%22datenschutz%40abihome.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.abihome.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.abihome.de%2Fdatenschutz%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F848%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22quality%22%3A%22verified%22%7D)**
> Add 'Abihome GmbH' (community contribution)

- companies/vk.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22vk%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22social%20media%22%5D%2C%22name%22%3A%22LLC%20%5C%22V%20Kontakte%5C%22%22%2C%22address%22%3A%22LLC%20%5C%22V%20Kontakte%5C%22%5Cn1-N%2C%20bld.%2012-14%2C%20Lit.%20A%2C%20Khersonskaya%20st.%5Cn191024%20St.%20Petersburg%5CnRussia%22%2C%22email%22%3A%22dpo%40corp.my.com%22%2C%22web%22%3A%22https%3A%2F%2Fvk.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fvk.com%2Fprivacy%2Feu%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F855%22%5D%2C%22required-elements%22%3A%5B%7B%22desc%22%3A%22Link%20to%20profile%20page%22%2C%22type%22%3A%22input%22%2C%22optional%22%3Afalse%7D%2C%7B%22desc%22%3A%22Em …
> Add 'LLC "V Kontakte"' (community contribution)

- companies/luca-app.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22luca-app%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22health%22%2C%22commerce%22%5D%2C%22name%22%3A%22%20culture4life%20GmbH%22%2C%22runs%22%3A%5B%22luca%22%5D%2C%22address%22%3A%22Charlottenstra%C3%9Fe%2059%5Cn10117%20Berlin%5CnDeutschland%22%2C%22phone%22%3A%22%2B49%2030%2022183850%22%2C%22email%22%3A%22dataprivacy%40culture4life.de%22%2C%22web%22%3A%22https%3A%2F%2Fluca-app.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fluca-app.de%2Fapp-privacy-policy%2F%22%2C%22https%3A%2F%2Fluca-app.de%2Fimprint%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F867%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22quality%22%3A%22v …
> Add ' culture4life GmbH' (community contribution)

- companies/coinbase.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22coinbase%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22finance%22%5D%2C%22name%22%3A%22Coinbase%20Ireland%2C%20Limited%22%2C%22address%22%3A%2270%20Sir%20John%20Rogerson's%20Quay%5CnDublin%202%5CnIreland%20%22%2C%22email%22%3A%22dpo%40coinbase.com%22%2C%22web%22%3A%22https%3A%2F%2Fwww.coinbase.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.coinbase.com%2Flegal%2Fprivacy%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F870%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22quality%22%3A%22verified%22%7D)**
> Add 'Coinbase Ireland, Limited' (community contribution)

- companies/b4bpayments.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22b4bpayments%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22finance%22%5D%2C%22name%22%3A%22B4BPayments%22%2C%22address%22%3A%22Europe%20%E2%80%93%20PO%20Box%2076256%2C%20London%2C%20SW1P%209NU%20USA%20%E2%80%93%20B4B%20Payments%2C%20275%20Grove%20Street%2C%20Suite%202-400%20Newton%2C%20MA%2002466%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.b4bpayments.com%2Fprepaid%2Fprivacy%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F872%22%5D%2C%22quality%22%3A%22verified%22%7D)**
> Add 'B4BPayments' (community contribution)

- companies/quantyoo.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22quantyoo%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22ads%22%5D%2C%22name%22%3A%22quantyoo%22%2C%22address%22%3A%22QUANTYOO%20GmbH%20%26%20Co.%20KG%5CnTrautenwolfstra%C3%9Fe%203%5Cn80802%20M%C3%BCnchen%22%2C%22email%22%3A%22privacy%40quantyoo.de%22%2C%22web%22%3A%22https%3A%2F%2Fquantyoo.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fquantyoo.de%2Fdatenschutz%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F876%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22quality%22%3A%22verified%22%7D)**
> Add 'quantyoo' (community contribution)

- companies/autodesk.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22autodesk%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22name%22%3A%22Autodesk%22%2C%22quality%22%3A%22verified%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F873%22%5D%7D)**
> Add 'Autodesk' (community contribution)

- companies/tutanota.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22tutanota%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22telecommunication%22%5D%2C%22name%22%3A%22Tutao%20GmbH%22%2C%22runs%22%3A%5Bnull%2C%22Tutanota%22%5D%2C%22address%22%3A%22Deisterstr.%2017a%5Cn30449%20Hannover%5CnDeutschland%22%2C%22phone%22%3A%22%2B49%20511%202028010%22%2C%22fax%22%3A%22%2B49%20511%2020280119%22%2C%22email%22%3A%22hello%40tutao.de%22%2C%22web%22%3A%22https%3A%2F%2Ftutanota.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Ftutanota.com%2Fprivacy%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F875%22%5D%2C%22quality%22%3A%22verified%22%7D)**
> Add 'Tutao GmbH' (community contribution)

- companies/aerzte-ohne-grenzen.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22aerzte-ohne-grenzen%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22nonprofit%22%2C%22health%22%5D%2C%22name%22%3A%22%C3%84rzte%20ohne%20Grenzen%20e.%20V.%22%2C%22address%22%3A%22Am%20K%C3%B6llnischen%20Park%201%5Cn10179%20Berlin%5Cn%22%2C%22phone%22%3A%22%2B49%2030%207001300%22%2C%22fax%22%3A%22%2B49%2030%20700130340%22%2C%22email%22%3A%22datenschutz%40berlin.msf.org%22%2C%22web%22%3A%22https%3A%2F%2Fwww.aerzte-ohne-grenzen.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.aerzte-ohne-grenzen.de%2Fdatenschutz-und-datensicherheit%22%2C%22https%3A%2F%2Fwww.aerzte-ohne-grenzen.de%2Fdatenschutzbeauftrager%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen …
> Add 'Ärzte ohne Grenzen e. V.' (community contribution)

- companies/pvz-pressevertriebszentrale.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22pvz-pressevertriebszentrale%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22name%22%3A%22PVZ%20Pressevertriebszentrale%20GmbH%20%26%20Co.%20KG%22%2C%22address%22%3A%22Bahndamm%209%5Cn23617%20Stockelsdorf%5CnDeutschland%22%2C%22phone%22%3A%22%2B49%20451%204906600%22%2C%22fax%22%3A%22%2B49%20451%204906670%22%2C%22email%22%3A%22datenschutz%40pvz.digital%22%2C%22web%22%3A%22https%3A%2F%2Fwww.pvz.digital%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.pvz.digital%2Fimpressum%22%2C%22https%3A%2F%2Fwww.pvz.digital%2Fdatenschutz%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F881%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22quality%22%3A%22verified% …
> Update 'PVZ Pressevertriebszentrale GmbH & Co. KG' (community contribution)

- companies/bbs5-bs.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22bbs5-bs%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22school%22%2C%22public%20body%22%5D%2C%22name%22%3A%22Berufsbildende%20Schule%20V%20der%20Stadt%20Braunschweig%22%2C%22address%22%3A%22Kastanienallee%2071%5Cn38102%20Braunschweig%5CnDeutschland%20%22%2C%22phone%22%3A%22%2B49%20531%204707950%22%2C%22fax%22%3A%22%2B49%20531%204707989%22%2C%22email%22%3A%22datenschutz%40bbs5-bs.de%22%2C%22web%22%3A%22https%3A%2F%2Fbbs5bs.de%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fbbs5bs.de%2Fkontakt%2Fdatenschutz%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F880%22%5D%2C%22request-language%22%3A%22de%22%2C%22suggested-transport-medium%22% …
> Update 'Berufsbildende Schule V der Stadt Braunschweig' (community contribution)

- companies/socialdeal-nl.json
- companies/socialdeal.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22socialdeal%22%2C%22relevant-countries%22%3A%5B%22nl%22%5D%2C%22categories%22%3A%5B%22travel%22%5D%2C%22name%22%3A%22Social%20Deal%22%2C%22address%22%3A%22Magistratenlaan%2070%5Cn's-Hertogenbosch%205223MD%5CnNoord-Brabant%22%2C%22email%22%3A%22privacy%40socialdeal.nl%22%2C%22web%22%3A%22https%3A%2F%2Fsocialdeal.nl%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.socialdeal.nl%2Fprivacy-policy%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F840%22%5D%2C%22needs-id-document%22%3Afalse%2C%22suggested-transport-medium%22%3A%22email%22%2C%22quality%22%3A%22verified%22%7D)**
> Add 'Social Deal' (community contribution)

- companies/klinikum-stuttgart.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22klinikum-stuttgart%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22health%22%5D%2C%22name%22%3A%22Klinikum%20Stuttgart%22%2C%22address%22%3A%22Kriegsbergstra%C3%9Fe%2060%5Cn70174%20Stuttgart%22%2C%22phone%22%3A%220711%20278-01%22%2C%22email%22%3A%22info%40klinikum-stuttgart.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.klinikum-stuttgart.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.klinikum-stuttgart.de%2Fdatenschutz%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F884%22%5D%2C%22quality%22%3A%22verified%22%7D)**
> Add 'Klinikum Stuttgart' (community contribution)

- companies/crefopay.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22crefopay%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22finance%22%5D%2C%22name%22%3A%22CrefoPayment%20GmbH%20%26%20Co.%20KG%22%2C%22address%22%3A%22Schlo%C3%9Fstra%C3%9Fe%2020%2C%2012163%20Berlin%2C%20Deutschland%22%2C%22phone%22%3A%2200%2049%2030%20221847200%22%2C%22email%22%3A%22info%40crefopay.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.crefopay.de%2F%22%2C%22quality%22%3A%22verified%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F885%22%5D%7D)**
> Add 'CrefoPayment GmbH & Co. KG' (community contribution)

- companies/afterpay.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22afterpay%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22finance%22%5D%2C%22name%22%3A%22Arvato%20Payment%20Solutions%20GmbH%22%2C%22runs%22%3A%5B%22Afterpay%22%5D%2C%22address%22%3A%22G%C3%BCtersloher%20Str.%20123%5Cn33415%20Verl%5CnDeutschland%22%2C%22phone%22%3A%22%2B49%205241%208043441%22%2C%22email%22%3A%22datenschutz%40afterpay.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.afterpay.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.afterpay.de%2Fdatenschutz%22%2C%22https%3A%2F%2Fwww.afterpay.de%2Fimpressum%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F887%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22quality%22%3A%22v …
> Add 'Arvato Payment Solutions GmbH' (community contribution)

- companies/freenet-tv.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22freenet-tv%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22entertainment%22%5D%2C%22name%22%3A%22freenet%20TV%22%2C%22address%22%3A%22MEDIA%20BROADCAST%20GmbH%2C%20Erna-Scheffler-Strasse%201%2C%2051103%20K%C3%B6ln%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.freenet.tv%2Fdatenschutzhinweise%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F890%22%5D%2C%22quality%22%3A%22verified%22%7D)**
> Add 'freenet TV' (community contribution)

- companies/unwirednetworks.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22unwirednetworks%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22telecommunication%22%2C%22travel%22%5D%2C%22name%22%3A%22https%3A%2F%2Funwirednetworks.net%22%2C%22address%22%3A%22Gonzagagasse%2011%2F25%5Cn1010%20Wien%5Cn%C3%96sterreich%22%2C%22phone%22%3A%22%2B43%201%209962051%22%2C%22email%22%3A%22privacy%40unwired.at%22%2C%22web%22%3A%22https%3A%2F%2Funwirednetworks.net%22%2C%22sources%22%3A%5B%22https%3A%2F%2Funwirednetworks.net%2Fservice%2Fdatenschutz%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F891%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22comments%22%3A%5B%22Alternative%2C%20deutsche%20Telefonnummer%3 …
> Add 'https://unwirednetworks.net' (community contribution)

- companies/reddit.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22reddit%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22social%20media%22%5D%2C%22name%22%3A%22Reddit%2C%20Inc.%22%2C%22address%22%3A%22520%203rd%20Street%5CnSan%20Francisco%5CnCA%2094107%5CnUnited%20States%20of%20America%22%2C%22email%22%3A%22eurepresentative%40reddit.com%22%2C%22web%22%3A%22https%3A%2F%2Fwww.reddit.com%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.redditinc.com%2Fpolicies%2Fprivacy-policy%22%2C%22https%3A%2F%2Fwww.bloomberg.com%2Fprofiles%2Fcompanies%2F0893288D%3AUS-reddit-inc%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F669%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F893%22%5D%2C%22re …
> Update 'Reddit, Inc.' (community contribution)

- companies/fyfeweb.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22fyfeweb%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22telecommunication%22%5D%2C%22name%22%3A%22FyfeWeb%20Ltd%22%2C%22runs%22%3A%5B%22FyfeWeb%20Hosting%22%2C%22FyfeWeb%20Hosting%20Services%22%5D%2C%22address%22%3A%22FyfeWeb%20Ltd%5CnAttn%3A%20Data%20Protection%5CnAshfield%20Park%5CnNewcastle%20upon%20Tyne%5CnUnited%20Kingdom%22%2C%22email%22%3A%22dpo%40fyfeweb.com%22%2C%22web%22%3A%22https%3A%2F%2Ffyfeweb.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Ffyfeweb.com%2Flegal%2Fprivacy-policy%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F897%22%5D%2C%22required-elements%22%3A%5B%7B%22desc%22%3A%22Full%20Name%22%2C%22type%22%3A%22n …
> Add 'FyfeWeb Ltd' (community contribution)

- companies/x-tract-io.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22x-tract-io%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22social%20media%22%5D%2C%22name%22%3A%22X-tract.io%22%2C%22address%22%3A%2248%20Wall%20Street%5Cn11th%20floor%5CnNY%2010005%5CnUSA%22%2C%22phone%22%3A%22%2B1%20212%20918%204456%22%2C%22email%22%3A%22support%40xtract.io%22%2C%22web%22%3A%22https%3A%2F%2Fwww.xtract.io%2Fsolutions%2Fonline-reputation-management%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.xtract.io%2Fcontact-us%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F583%22%2C%22https%3A%2F%2Fwww.xtract.io%2Fprivacy-policy%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F900%22%5D%2C%22quality%22%3A%2 …
> Update 'X-tract.io' (community contribution)

- companies/oracle.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22oracle%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22ads%22%5D%2C%22name%22%3A%22Oracle%20Corporation%22%2C%22address%22%3A%2210%20Van%20de%20Graaff%20Drive%5CnBurlington%5CnMA%2001803%5CnUnited%20States%20of%20America%22%2C%22phone%22%3A%22%2B1%20650%20506%207000%22%2C%22email%22%3A%22mail%40legislator.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.oracle.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.oracle.com%2Flegal%2Fprivacy%2Fservices-privacy-policy.html%22%2C%22https%3A%2F%2Fwww.oracle.com%2Fcorporate%2Fcontact%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F906%22%5D%2C%22request-language%22%3A%22en%22%2C%22custom-access …
> Update 'Oracle Corporation' (community contribution)

- companies/mvg-de.json
- companies/mvg.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22mvg%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22utility%22%5D%2C%22name%22%3A%22M%C3%BCnchner%20Verkehrsgesellschaft%20mbH%20(MVG)%22%2C%22address%22%3A%22Emmy-Noether-Stra%C3%9Fe%202%5Cn80992%20M%C3%BCnchen%22%2C%22phone%22%3A%22%2B49%2089%2021910%22%2C%22fax%22%3A%22%2B49%2089%202191703386%22%2C%22email%22%3A%22datenschutz%40swm.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.mvg.de%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.mvg.de%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F910%22%5D%2C%22needs-id-document%22%3Afalse%2C%22suggested-transport-medium%22%3A%22email%22%2C%22quality%22%3A%22verified%22%7D)**
> Add 'Münchner Verkehrsgesellschaft mbH (MVG)' (community contribution)

- companies/mvv-muenchen.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22mvv-muenchen%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22utility%22%5D%2C%22name%22%3A%22M%C3%BCnchner%20Verkehrs-%20und%20Tarifverbund%20GmbH%20(MVV)%22%2C%22address%22%3A%22Thierschstra%C3%9Fe%202%20%20%20%5Cn80538%20M%C3%BCnchen%22%2C%22phone%22%3A%22%2B49%2089%20210330%22%2C%22fax%22%3A%22%2B49%2089%2021033282%22%2C%22email%22%3A%22Datenschutz%40mvv-muenchen.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.mvv-muenchen.de%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.mvv-muenchen.de%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F911%22%5D%2C%22needs-id-document%22%3Afalse%2C%22suggested-transport-medium%22%3A%22email%22%2C%22 …
> Add 'Münchner Verkehrs- und Tarifverbund GmbH (MVV)' (community contribution)

- companies/hawesko.json
full name: "Hanseatisches Wein- und Sekt-Kontor Hawesko GmbH"
> Add Hawesko GmbH

- companies/moshbit.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22moshbit%22%2C%22relevant-countries%22%3A%5B%22at%22%5D%2C%22categories%22%3A%5B%22school%22%5D%2C%22name%22%3A%22Moshbit%20GmbH%22%2C%22runs%22%3A%5B%22Studo%22%5D%2C%22address%22%3A%22Joanneumring%203%20%5Cn8010%20Graz%5Cn%C3%96sterreich%22%2C%22phone%22%3A%22%2B43%20664%208351081%22%2C%22email%22%3A%22datenschutz%40moshbit.com%22%2C%22web%22%3A%22https%3A%2F%2Fmoshbit.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fmoshbit.com%2Flegalnotice.html%22%2C%22https%3A%2F%2Fstudo.co%2Fimpressum%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F206%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F916%22%5D%2C%22suggested-transport-medium%22%3A%22emai …
> Update 'Moshbit GmbH' (community contribution)

- companies/vk.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22vk%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22social%20media%22%5D%2C%22name%22%3A%22LLC%20%5C%22V%20Kontakte%5C%22%22%2C%22address%22%3A%221-N%2C%20bld.%2012-14%2C%20Lit.%20A%2C%20Khersonskaya%20st.%5Cn191024%20St.%20Petersburg%5CnRussia%22%2C%22email%22%3A%22dpo%40corp.my.com%22%2C%22web%22%3A%22https%3A%2F%2Fvk.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fvk.com%2Fprivacy%2Feu%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F855%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F924%22%5D%2C%22required-elements%22%3A%5B%7B%22desc%22%3A%22Name%22%2C%22type%22%3A%22name%22%7D%2C%7B%22desc%22%3A%22Link%20to%20pro …
> Update 'LLC "V Kontakte"' (community contribution)

- companies/bedirect.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22bedirect%22%2C%22relevant-countries%22%3A%5B%22de%22%2C%22at%22%5D%2C%22categories%22%3A%5B%22addresses%22%5D%2C%22name%22%3A%22beDirect%20GmbH%20%26%20Co.%20KG%22%2C%22runs%22%3A%5B%22beAddress.de%22%5D%2C%22address%22%3A%22Carl-Bertelsmann-Str.%20105%20%E2%80%93%20107%5Cn33311%20G%C3%BCtersloh%5CnDeutschland%22%2C%22phone%22%3A%22%2B49%205241%208045600%22%2C%22fax%22%3A%22%2B49%205241%208045699%22%2C%22email%22%3A%22datenschutz%40bedirect.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.bedirect-online.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.bedirect-online.de%2Fde%2Fdatenschutz%2F%22%2C%22https%3A%2F%2Fwww.bedirect-online.de%2Fde%2Fdatenschutz-dialogmarketing%2F%22%2C%22 …
> Update 'beDirect GmbH & Co. KG' (community contribution)

- companies/pkgator.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22pkgator%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22commerce%22%5D%2C%22name%22%3A%22Pk%20Gator%22%2C%22address%22%3A%22Valencia%20Mall%2C%20Sunrise%20Road%2C%20Valencia%20Town%2C%20Lahore%2C%20Pakistan.%22%2C%22phone%22%3A%2203004235757%22%2C%22email%22%3A%22bilalahmaad012%40gmail.com%22%2C%22web%22%3A%22https%3A%2F%2Fwww.pkgator.com%2F%22%2C%22sources%22%3A%5B%22online%20Shopping%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F882%22%5D%2C%22needs-id-document%22%3Afalse%2C%22suggested-transport-medium%22%3A%22email%22%2C%22quality%22%3A%22verified%22%7D)**
> Add 'Pk Gator' (community contribution)

- companies/babista.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22babista%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22commerce%22%5D%2C%22name%22%3A%22Babista%22%2C%22address%22%3A%22c%2Fo%20K-Mail%20Order%20GmbH%20%26%20Co%20KG%5CnSachsenstr.%2023%5Cn75177%20Pforzheim%5CnDeutschland%22%2C%22phone%22%3A%2201805%20%2F%2043%2063%2036%22%2C%22email%22%3A%22datenschutz%40babista.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.babista.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.babista.de%2Fk%2Fdatenschutz%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F917%22%5D%2C%22comments%22%3A%5B%22%5C%22*(14%20Cent%2FMinute%20inkl.%20MwSt.%20a.d.%20Festnetz%3B%20Mobilfunk%2C%20max.%2042%20Cent%2FMinute%20in …
> Add 'Babista' (community contribution)

- companies/epay.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22epay%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22finance%22%5D%2C%22name%22%3A%22transact%20Elektronische%20Zahlungssysteme%20GmbH%20dba.%20epay%22%2C%22address%22%3A%22Fraunhoferstr.%2010%5Cn82152%20Martinsried%5CnDeutschland%22%2C%22phone%22%3A%22%2B49%2089%208996430%22%2C%22email%22%3A%22info%40epay.de%22%2C%22web%22%3A%22https%3A%2F%2Fepay.de%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fepay.de%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F918%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22quality%22%3A%22verified%22%7D)**
> Add 'transact Elektronische Zahlungssysteme GmbH dba. epay' (community contribution)

- companies/wb-fernstudium.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22wb-fernstudium%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22name%22%3A%22Wilhelm%20B%C3%BCchner%20Hochschule%22%2C%22address%22%3A%22Hilpertstra%C3%9Fe%2031%5Cn64295%20Darmstadt%22%2C%22phone%22%3A%22%2B49%206151%203842404%22%2C%22fax%22%3A%22%2B49%206151%203842401%22%2C%22email%22%3A%22datenschutz%40wb-fernstudium.de%22%2C%22web%22%3A%22https%3A%2F%2Fwb-fernstudium.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.wb-fernstudium.de%2Fdatenschutz.html%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F928%22%5D%2C%22needs-id-document%22%3Afalse%2C%22suggested-transport-medium%22%3A%22letter%22%2C%22quality%22%3A%22verified%22%7D)**
> Add 'Wilhelm Büchner Hochschule' (community contribution)

- companies/fairphone.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22fairphone%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22telecommunication%22%2C%22commerce%22%5D%2C%22name%22%3A%22Fairphone%20B.V.%22%2C%22address%22%3A%22Jollemanhof%2017%5Cn1019%20GW%20Amsterdam%5CnThe%20Netherlands%22%2C%22phone%22%3A%22%2B31%2020%20788%204400%22%2C%22email%22%3A%22privacy%40fairphone.com%22%2C%22web%22%3A%22https%3A%2F%2Fwww.fairphone.com%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.fairphone.com%2Fen%2Flegal%2Ffairphone-privacy-policy%2F%22%2C%22https%3A%2F%2Fwww.fairphone.com%2Fen%2Flegal%2Fimpressum%2F%3Fref%3Dfooter%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F932%22%5D%2C%22suggested-transport-me …
> Add 'Fairphone B.V.' (community contribution)

- companies/twingle.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22twingle%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22finance%22%5D%2C%22name%22%3A%22twingle%20GmbH%22%2C%22address%22%3A%22Prinzenallee%2074%5Cn13357%20Berlin%5CnDeutschland%22%2C%22phone%22%3A%22%2B49%2030%2098323777%22%2C%22email%22%3A%22info%40twingle.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.twingle.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.twingle.de%2Fdatenschutz%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F931%22%5D%2C%22quality%22%3A%22verified%22%7D)**
> Add 'twingle GmbH' (community contribution)

- companies/sachsenlotto.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22sachsenlotto%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22commerce%22%5D%2C%22name%22%3A%22S%C3%A4chsische%20Lotto-GmbH%22%2C%22address%22%3A%22Oststra%C3%9Fe%20105%5Cn04299%20Leipzig%22%2C%22phone%22%3A%22%2B49%20341%2086700%22%2C%22email%22%3A%22datenschutz%40sachsenlotto.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.sachsenlotto.de%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.sachsenlotto.de%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F933%22%5D%2C%22needs-id-document%22%3Afalse%2C%22quality%22%3A%22verified%22%7D)**
> Add 'Sächsische Lotto-GmbH' (community contribution)

- companies/instagram.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22instagram%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22entertainment%22%2C%22social%20media%22%5D%2C%22name%22%3A%22Instagram%22%2C%22address%22%3A%22c%2Fo%20Facebook%20Ireland%20Ltd.%5Cn4%20Grand%20Canal%20Square%5CnGrand%20Canal%20Harbour%5CnDublin%202%5CnIreland%20%22%2C%22fax%22%3A%22%2B1%20650%20543%205340%22%2C%22web%22%3A%22https%3A%2F%2Fwww.instagram.com%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fhelp.instagram.com%2F519522125107875%22%2C%22https%3A%2F%2Fhelp.instagram.com%2Fcontact%2F163695614321277%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F93%22%2C%22https%3A%2F%2Fhelp.instagram.com%2F581066165581870%22%2C%22 …
> Update 'Instagram' (community contribution)

- companies/morganstanley.json
> Add Morgan Stanley

- companies/heinlein-support-de.json
- companies/posteo.json
- companies/proton-technologies.json
- companies/soverin.json
- companies/startmail.json
- Updated quality and required elements for Heinlein
- Added Posteo
- Added Proton Technologies
- Added Soverin
- Added StartMail
- Tested and added required elements for Tutanota
> Adding secure email providers

- companies/joinclubhouse.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22joinclubhouse%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22name%22%3A%22Alpha%20Exploration%20Co.%2C%20Inc%22%2C%22runs%22%3A%5B%22Clubhouse%22%5D%2C%22address%22%3A%22%3F%22%2C%22email%22%3A%22support%40alphaexplorationco.com%22%2C%22web%22%3A%22https%3A%2F%2Fwww.joinclubhouse.com%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.notion.so%2FPrivacy-Policy-cd4b415950204a46819478b31f6ce14f%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F934%22%5D%2C%22quality%22%3A%22verified%22%7D)**
> Add 'Alpha Exploration Co., Inc' (community contribution)

- companies/joinclubhouse.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22joinclubhouse%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22social%20media%22%5D%2C%22name%22%3A%22Alpha%20Exploration%20Co.%2C%20Inc%22%2C%22runs%22%3A%5B%22Clubhouse%22%5D%2C%22address%22%3A%225335%20Lawton%20Avenue%5CnOakland%5CnCalifornia%2094618%5CnUnited%20States%20of%20America%22%2C%22email%22%3A%22support%40alphaexplorationco.com%22%2C%22web%22%3A%22https%3A%2F%2Fwww.joinclubhouse.com%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.notion.so%2FPrivacy-Policy-cd4b415950204a46819478b31f6ce14f%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F934%22%2C%22https%3A%2F%2Fbusinesssearch.sos.ca.gov%2FDocument%2FRetrievePDF%3FId%3D …
> Update 'Alpha Exploration Co., Inc' (community contribution)

- companies/printpeter.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22printpeter%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22ads%22%2C%22commerce%22%5D%2C%22name%22%3A%22PlusPeter%20GmbH%22%2C%22runs%22%3A%5B%22PlusPeter%20(www.pluspeter.com)%22%5D%2C%22address%22%3A%22Chausseestra%C3%9Fe%2084%5Cn10115%20Berlin%5CnDeutschland%22%2C%22phone%22%3A%22%2B49%2030%20555798821%22%2C%22email%22%3A%22datenschutz%40charly.education%22%2C%22web%22%3A%22https%3A%2F%2Fwww.charly.education%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.charly.education%2Fdatenschutz%22%2C%22https%3A%2F%2Fwww.charly.education%2Fimprint%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F950%22%5D%2C%22required-elements%22%3A%5B%7B%22 …
> Update 'PlusPeter GmbH' (community contribution)

- companies/gas-de.json
- companies/gas.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22gas%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22utility%22%5D%2C%22name%22%3A%22gas.de%20Versorgungsgesellschaft%20mbH%22%2C%22address%22%3A%22Girmes-Kreuz-Str.%2055%5Cn41564%20Kaarst%5CnDeutschland%22%2C%22email%22%3A%22datenschutz%40gas.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.gas.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.gas.de%2Fdatenschutz.html%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F955%22%5D%2C%22required-elements%22%3A%5B%7B%22desc%22%3A%22Name%22%2C%22type%22%3A%22name%22%2C%22optional%22%3Afalse%7D%2C%7B%22desc%22%3A%22E-Mail-Adresse%22%2C%22type%22%3A%22email%22%2C%22optional%22%3Atrue%7D%2C%7B%22desc%2 …
> Add 'gas.de Versorgungsgesellschaft mbH' (community contribution)

- companies/stw-uni-heidelberg.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22stw-uni-heidelberg%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22public%20body%22%2C%22school%22%5D%2C%22name%22%3A%22Studierendenwerk%20Heidelberg%20A%C3%B6R%22%2C%22address%22%3A%22Marstallhof%201%5Cn69117%20Heidelberg%5CnDeutschland%22%2C%22phone%22%3A%2206221%2054-5400%22%2C%22fax%22%3A%2206221%2054-5401%22%2C%22email%22%3A%22dsb%40stw.uni-heidelberg.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.stw.uni-heidelberg.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.stw.uni-heidelberg.de%2Fde%2Fimpressum%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F943%22%5D%2C%22required-elements%22%3A%5B%7B%22desc%22%3A%22E-Mail-Adresse%22%2C%22ty …
> Add 'Studierendenwerk Heidelberg AöR' (community contribution)

- templates/es/access-default.txt
- templates/es/access-tracking.txt
- templates/es/admonition.txt
- templates/es/complaint.txt
- templates/es/erasure-default.txt
- templates/es/objection-default.txt
- templates/es/rectification-default.txt
They have been tested locally on dev environment
> Spanish updates

- companies/intercom-com.json
- companies/intercom.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22intercom%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22telecommunication%22%5D%2C%22name%22%3A%22Intercom%20R%26D%20Unlimited%20Company%22%2C%22address%22%3A%222nd%20Floor%5CnStephen%20Court%5Cn18-21%20Saint%20Stephen's%20Green%5CnDublin%202%5CnIreland%22%2C%22email%22%3A%22legal%40intercom.com%22%2C%22web%22%3A%22https%3A%2F%2Fwww.intercom.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.intercom.com%2Flegal%2Fprivacy%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F944%22%5D%2C%22required-elements%22%3A%5B%7B%22desc%22%3A%22Name%22%2C%22type%22%3A%22name%22%7D%2C%7B%22desc%22%3A%22E-Mail%20Address%22%2C%22type%22%3A%22email%22% …
> Add 'Intercom R&D Unlimited Company' (community contribution)

- companies/kontist.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22kontist%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22finance%22%5D%2C%22name%22%3A%22Kontist%20GmbH%22%2C%22address%22%3A%22Kastanienallee%2098B%5Cn10435%20Berlin%5CnGermany%22%2C%22phone%22%3A%22%2B49%2030%2031198600%22%2C%22email%22%3A%22support%40kontist.com%22%2C%22web%22%3A%22https%3A%2F%2Fkontist.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fkontist.com%2Fimprint%2F%22%2C%22https%3A%2F%2Fkontist.com%2Fprivacy%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F945%22%5D%2C%22required-elements%22%3A%5B%7B%22desc%22%3A%22Name%22%2C%22type%22%3A%22name%22%2C%22optional%22%3Afalse%7D%2C%7B%22desc%22%3A%22E-Mail-Adresse%22%2C%22t …
> Add 'Kontist GmbH' (community contribution)

- companies/memolife.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22memolife%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22commerce%22%5D%2C%22name%22%3A%22memo%20AG%22%2C%22runs%22%3A%5B%22https%3A%2F%2Fwww.memo.de%2F%22%2C%22https%3A%2F%2Fwww.memo-werbeartikel.de%2F%22%2C%22https%3A%2F%2Fwww.memoworld.de%2F%22%2C%22https%3A%2F%2Fwww.memolife.de%2F%22%5D%2C%22address%22%3A%22Am%20Biotop%206%5Cn97259%20Greu%C3%9Fenheim%22%2C%22phone%22%3A%22%2B49%209369%20905600%22%2C%22fax%22%3A%22%2B49%209369%20905307%22%2C%22email%22%3A%22info%40memolife.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.memolife.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.memolife.de%2Fdatenschutz%22%2C%22https%3A%2F%2Fwww.memolife.de%2Fimpressum%2 …
> Add 'memo AG' (community contribution)

- companies/autocode.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22autocode%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22telecommunication%22%5D%2C%22name%22%3A%22Polybit%20Inc.%22%2C%22runs%22%3A%5B%22Autocode%22%5D%2C%22address%22%3A%222390%2030th%20Ave.%5CnSan%20Francisco%20CA%2094116%22%2C%22email%22%3A%22support%40autocode.com%22%2C%22web%22%3A%22https%3A%2F%2Fautocode.com%22%2C%22required-elements%22%3A%5B%7B%22desc%22%3A%22Name%22%2C%22type%22%3A%22name%22%7D%2C%7B%22desc%22%3A%22E-Mail%20address%22%2C%22type%22%3A%22email%22%7D%5D%2C%22quality%22%3A%22verified%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F947%22%5D%7D)**
> Add 'Polybit Inc.' (community contribution)

- companies/flotte-berlin.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22flotte-berlin%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22nonprofit%22%5D%2C%22name%22%3A%22Allgemeiner%20Deutscher%20Fahrrad-Club%20Berlin%20e.V.%22%2C%22runs%22%3A%5B%22fLotte%20Berlin%22%5D%2C%22address%22%3A%22Yorckstra%C3%9Fe%2025%5Cn10965%20Berlin%5CnDeutschland%22%2C%22phone%22%3A%22%2B49%2030%204484724%22%2C%22fax%22%3A%22%2B49%2030%2044340520%22%2C%22email%22%3A%22kontakt%40adfc-berlin.de%22%2C%22web%22%3A%22https%3A%2F%2Fflotte-berlin.de%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fflotte-berlin.de%2Fdatenschutzerklaerung%2F%22%2C%22https%3A%2F%2Fflotte-berlin.de%2Fueber-uns%2Fimpressum%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfrag …
> Add 'Allgemeiner Deutscher Fahrrad-Club Berlin e.V.' (community contribution)

- companies/musescore-bvba.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22musescore-bvba%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22entertainment%22%5D%2C%22name%22%3A%22MuseScore%20BVBA%22%2C%22address%22%3A%22Octaaf%20Soudanstraat%2022%5CnSint-Denijs-Westrem%2C%209051%5CnBelgium%22%2C%22email%22%3A%22privacy%40musescore.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fmusescore.com%2Flegal%2Fprivacy%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F953%22%5D%2C%22required-elements%22%3A%5B%7B%22desc%22%3A%22Name%22%2C%22type%22%3A%22name%22%7D%2C%7B%22desc%22%3A%22E-Mail%20address%22%2C%22type%22%3A%22email%22%7D%5D%2C%22quality%22%3A%22verified%22%7D)**
> Add 'MuseScore BVBA' (community contribution)

- companies/berliner-sparkasse.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22berliner-sparkasse%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22finance%22%5D%2C%22name%22%3A%22Berliner%20Sparkasse%22%2C%22address%22%3A%22Alexanderplatz%202%5Cn10178%20Berlin%5CnDeutschland%22%2C%22phone%22%3A%22%2B49%2030%2086986969%22%2C%22fax%22%3A%22%2B49%2030%208696941369%22%2C%22email%22%3A%22datenschutz%40berliner-sparkasse.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.berliner-sparkasse.de%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.berliner-sparkasse.de%2Fde%2Fhome%2Ftoolbar%2Fdatenschutz.html%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F966%22%5D%2C%22quality%22%3A%22verified%22%7D)**
> Add 'Berliner Sparkasse' (community contribution)

- companies/denns-biomarkt.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22denns-biomarkt%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22commerce%22%5D%2C%22name%22%3A%22denn's%20Biomarkt%20GmbH%22%2C%22address%22%3A%22Hofer%20Str.%2011%5Cn95183%20T%C3%B6pen%22%2C%22phone%22%3A%2209295%2018-0%22%2C%22email%22%3A%22datenschutz%40denns.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.denns-biomarkt.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.denns-biomarkt.de%2Fueber-uns%2Fimpressum%2F%22%2C%22https%3A%2F%2Fwww.denns-biomarkt.de%2Fueber-uns%2Fdatenschutz%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F948%22%5D%2C%22required-elements%22%3A%5B%7B%22desc%22%3A%22Name%22%2C%22type%22%3A%22name%22%2C%22optional …
> Add 'denn's Biomarkt GmbH' (community contribution)

- companies/sauberenergie.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22sauberenergie%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22utility%22%5D%2C%22name%22%3A%22SE%20SAUBER%20ENERGIE%20GmbH%20%26%20Co.%20KG%22%2C%22address%22%3A%22Bachstra%C3%9Fe%203%5Cn53721%20Siegburg%5CnDeutschland%22%2C%22phone%22%3A%220800-11%2022%20999%22%2C%22fax%22%3A%2202241-107%20485%22%2C%22email%22%3A%22kundenservice%40sauberenergie.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.sauberenergie.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.sauberenergie.de%2Fdatenschutz%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F954%22%5D%2C%22required-elements%22%3A%5B%7B%22desc%22%3A%22Name%22%2C%22type%22%3A%22name%22%7D%2C%7B%22desc …
> Add 'SE SAUBER ENERGIE GmbH & Co. KG' (community contribution)

- companies/vestiairecollective.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22vestiairecollective%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22commerce%22%5D%2C%22name%22%3A%22Vestiaire%20Collective%22%2C%22address%22%3A%22255%20boulevard%20Pereire%2075017%20Paris%20-%20FRANCE%22%2C%22web%22%3A%22https%3A%2F%2Fwww.vestiairecollective.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Ffr.vestiairecollective.com%2Fa-propos%2Fcontact%2F%22%2C%22https%3A%2F%2Ffr.vestiairecollective.com%2Fpolitique-de-confidentialite%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F956%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22quality%22%3A%22verified%22%7D)**
> Add 'Vestiaire Collective' (community contribution)

- README.md
originally from Benni in the Matrix chat
> README: add part about the request language

- companies/datenanfragen.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22datenanfragen%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22nonprofit%22%5D%2C%22name%22%3A%22Datenanfragen.de%20e.%20V.%22%2C%22runs%22%3A%5B%22Datenanfragen.de%22%2C%22datarequests.org%22%2C%22pedidodedados.org%22%2C%22demandetesdonnees.fr%22%2C%22htsolicituddedatos.es%22%5D%2C%22address%22%3A%22Schreinerweg%206%5Cn38126%20Braunschweig%5CnDeutschland%22%2C%22phone%22%3A%22%2B49%20531%2020929935%22%2C%22fax%22%3A%22%2B49%20531%2020929936%22%2C%22email%22%3A%22datenschutz%40datenanfragen.de%22%2C%22pgp-fingerprint%22%3A%22CC13%20973A%20F8FD%2011D1%204D94%20%2098A8%200269%2092F0%20CF2C%20BB2E%22%2C%22pgp-url%22%3A%22https%3A%2F%2Fwww.datenanfrage …
> Update 'Datenanfragen.de e. V.' (community contribution)

- companies/mymuesli.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22mymuesli%22%2C%22relevant-countries%22%3A%5B%22de%22%2C%22ch%22%2C%22nl%22%2C%22be%22%2C%22gb%22%2C%22se%22%2C%22pl%22%2C%22fr%22%2C%22at%22%5D%2C%22categories%22%3A%5B%22commerce%22%5D%2C%22name%22%3A%22mymuesli%20GmbH%22%2C%22address%22%3A%22Sailerw%C3%B6hr%2016%5Cn94032%20Passau%5CnGermany%22%2C%22phone%22%3A%22%2B49%20851%2020426699%22%2C%22fax%22%3A%22%2B49%20851%2020426693%22%2C%22email%22%3A%22dataprotection%40mymuesli.com%22%2C%22web%22%3A%22https%3A%2F%2Fwww.mymuesli.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.mymuesli.com%2Fdatenschutz%22%2C%22https%3A%2F%2Fwww.mymuesli.com%2Fimpressum%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F952%22%5D …
> Add 'mymuesli GmbH' (community contribution)

- companies/samedi-de.json
- companies/samedi.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22samedi%22%2C%22relevant-countries%22%3A%5B%22de%22%2C%22at%22%2C%22ch%22%5D%2C%22categories%22%3A%5B%22health%22%5D%2C%22name%22%3A%22samedi%20GmbH%22%2C%22runs%22%3A%5B%22www.samedi.de%22%2C%22patient.samedi.de%22%5D%2C%22address%22%3A%22Rigaer%20Stra%C3%9Fe%2044%5Cn10247%20Berlin%22%2C%22phone%22%3A%22030%202123%200707%200%22%2C%22fax%22%3A%22030%202123%200707%209%22%2C%22email%22%3A%22datenschutz%40samedi.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.samedi.de%22%2C%22sources%22%3A%5B%22Erfahrung%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F972%22%5D%2C%22needs-id-document%22%3Atrue%2C%22suggested-transport-medium%22%3A%22email%22%2C%22quality%22%3A%22veri …
> Add 'samedi GmbH' (community contribution)

- companies/uni-heidelberg.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22uni-heidelberg%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22public%20body%22%2C%22school%22%5D%2C%22name%22%3A%22Universit%C3%A4t%20Heidelberg%22%2C%22address%22%3A%22Grabengasse%201%5Cn69117%20Heidelberg%5CnDeutschland%22%2C%22phone%22%3A%22%2B49%206221%205412070%22%2C%22email%22%3A%22datenschutz%40uni-heidelberg.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.uni-heidelberg.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.uni-heidelberg.de%2Fde%2Fdatenschutzerklaerung%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F942%22%5D%2C%22quality%22%3A%22verified%22%7D)**
> Add 'Universität Heidelberg' (community contribution)

- companies/casamoda.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22casamoda%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22commerce%22%5D%2C%22name%22%3A%22CASAMODA%20Heinrich%20Katt%20GmbH%20%26%20Co.%20KG%22%2C%22runs%22%3A%5B%22venti.com%22%5D%2C%22address%22%3A%22Gutenbergstra%C3%9Fe%207%5Cn26135%20Oldenburg%5CnDeutschland%22%2C%22phone%22%3A%2204412066456%22%2C%22fax%22%3A%2204412066111%22%2C%22email%22%3A%22onlineshop%40venti.com%22%2C%22web%22%3A%22https%3A%2F%2Fwww.casamoda.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.venti.com%2Fde%2Fde%2Fdatenschutz%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F940%22%5D%2C%22required-elements%22%3A%5B%7B%22desc%22%3A%22E-Mail-Adresse%22%2C%22type …
> Add 'CASAMODA Heinrich Katt GmbH & Co. KG' (community contribution)

- companies/heidelberg.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22heidelberg%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22public%20body%22%5D%2C%22name%22%3A%22Stadt%20Heidelberg%22%2C%22runs%22%3A%5B%22heidelberg.de%22%5D%2C%22address%22%3A%22Marktplatz%2010%2C%2069117%20Heidelberg%22%2C%22phone%22%3A%2206221%2058-10580%22%2C%22fax%22%3A%2206221%2058-10900%22%2C%22email%22%3A%22stadt%40heidelberg.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.heidelberg.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.heidelberg.de%2Fhd%2FHD%2Fservice%2Fimpressum.html%22%2C%22https%3A%2F%2Fwww.heidelberg.de%2Fsite%2FHeidelberg_ROOT%2Fnode%2F234767%2Findex.html%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F941%22%5 …
> Add 'Stadt Heidelberg' (community contribution)

- companies/trafficplex.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22trafficplex%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22name%22%3A%22TrafficPlex%20GmbH%22%2C%22runs%22%3A%5B%22lima-city%22%2C%22bitbackup%22%5D%2C%22address%22%3A%22Konsul-Smidt-Str.%2090%5Cn28217%20Bremen%22%2C%22phone%22%3A%220421%20-%2040%2089%2094%205-0%22%2C%22fax%22%3A%220421%20-%2040%2089%2094%205-9%22%2C%22email%22%3A%22info%40trafficplex.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.trafficplex.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.trafficplex.de%2Fabout_us.html%23impressum%22%2C%22https%3A%2F%2Fwww.lima-city.de%2Fjuristisches%23datenschutzerklaerung%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F949%22%5D%2C%22quality%22%3A%22verif …
> Add 'TrafficPlex GmbH' (community contribution)

- companies/zendesk-international-ltd.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22zendesk-international-ltd%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22telecommunication%22%5D%2C%22name%22%3A%22Zendesk%20International%20Ltd.%22%2C%22address%22%3A%22Rachel%20Tobin%2C%20AGC%2C%20EMEA%20%26%20Global%20Privacy%20Counsel%2C%20Zendesk%20International%20Ltd.%5Cn55%20Charlemont%20Place%5CnSaint%20Kevin%E2%80%99s%5CnDublin%2C%20D02%20F985%5CnIreland%22%2C%22email%22%3A%22privacy%40zendesk.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.zendesk.de%2Fcompany%2Fcustomers-partners%2Fprivacy-policy%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F951%22%5D%2C%22required-elements%22%3A%5B%7B%22desc%22%3A%22Name%22%2C%2 …
> Add 'Zendesk International Ltd.' (community contribution)

- companies/calcuso.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22calcuso%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22commerce%22%5D%2C%22name%22%3A%22CALCUSO%20GmbH%22%2C%22address%22%3A%22Hans-B%C3%B6ckler-Str.%2012%5Cn40764%20Langenfeld%5CnDeutschland%22%2C%22phone%22%3A%22%2B49%202173%209608884%22%2C%22email%22%3A%22anja.hildebrand%40calcuso.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.calcuso.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.calcuso.de%2Fdatenschutz%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F967%22%5D%2C%22quality%22%3A%22verified%22%7D)**
> Add 'CALCUSO GmbH' (community contribution)

- companies/hermann-bosch-inkasso.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22hermann-bosch-inkasso%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22collection%20agency%22%5D%2C%22name%22%3A%22Hermann%20Bosch%20Inkasso%20und%20Beratung%20GmbH%20%26%20Co.%20KG%22%2C%22address%22%3A%22zu%20Hd.%20Frau%20Kranhold%5CnAugsburger%20Str.%2010%5Cn99091%20Erfurt%5CnDeutschland%22%2C%22phone%22%3A%2203%2061%2026%2024%2018%20-%200%22%2C%22fax%22%3A%2203%2061%2026%2024%2018%20-%2013%22%2C%22email%22%3A%22datenschutz%40hermann-bosch-inkasso.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.hermann-bosch-inkasso.de%22%2C%22sources%22%3A%5B%22Internet%2C%20%C3%B6ffentliche%20Daten%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F973%2 …
> Add 'Hermann Bosch Inkasso und Beratung GmbH & Co. KG' (community contribution)

- companies/teamviewer.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22teamviewer%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22telecommunication%22%5D%2C%22name%22%3A%22TeamViewer%20AG%22%2C%22address%22%3A%22Bahnhofsplatz%202%2C%2073033%20G%C3%B6ppingen%22%2C%22email%22%3A%22privacy%40teamviewer.com%22%2C%22web%22%3A%22https%3A%2F%2Fwww.teamviewer.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.teamviewer.com%2Fde%2Fdatenschutzerklaerung%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F977%22%5D%2C%22needs-id-document%22%3Afalse%2C%22comments%22%3A%5B%22Achtung%3A%20Neben%20der%20TeamViewer%20AG%20existiert%20noch%20die%20TeamViewer%20Germany%20GmbH%2C%20vergleiche%20%23976.%20Inwiefern%20diese%20 …
> Add 'TeamViewer AG' (community contribution)

- companies/vhv-versicherung.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22vhv-versicherung%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22insurance%22%2Cnull%5D%2C%22name%22%3A%22VHV%20Versicherung%22%2C%22address%22%3A%22Constantin%20Str.%2090%5CnHannover%2C%2030177%22%2C%22phone%22%3A%2205119075%22%2C%22suggested-transport-medium%22%3A%22email%22%2C%22quality%22%3A%22verified%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F978%22%5D%7D)**
> Add 'VHV Versicherung' (community contribution)

- companies/reishunger.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22reishunger%22%2C%22relevant-countries%22%3A%5B%22de%22%2C%22ch%22%2C%22at%22%5D%2C%22categories%22%3A%5B%22commerce%22%5D%2C%22name%22%3A%22Reishunger%20GmbH%22%2C%22address%22%3A%22Am%20Waller%20Freihafen%201%5Cn28217%20Bremen%5CnGermany%22%2C%22phone%22%3A%22%2B49%20421%2020802491%22%2C%22fax%22%3A%22%2B49%20421%2020802128%22%2C%22email%22%3A%22datenschutz%40reishunger.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.reishunger.de%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.reishunger.de%2Fdatenschutz%233-datenschutzbeauftragter%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F982%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22quality%22%3A%22veri …
> Add 'Reishunger GmbH' (community contribution)

- companies/smartbroker.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22smartbroker%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22finance%22%5D%2C%22name%22%3A%22wallstreet%3Aonline%20capital%20AG%22%2C%22runs%22%3A%5B%22Smartbroker%22%5D%2C%22address%22%3A%22zu%20Hd.%20Abteilung%20Datenschutz%5CnMichaelkirchstr.%2017%2F18%5Cn10179%20Berlin%5CnDeutschland%22%2C%22phone%22%3A%22%2B49%2030%20275776200%22%2C%22fax%22%3A%22%2B49%2030%20275776415%22%2C%22email%22%3A%22datenschutzbeauftragter%40wo-capital.de%22%2C%22web%22%3A%22https%3A%2F%2Fsmartbroker.de%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fsmartbroker.de%2Fdatenschutz.php%22%2C%22https%3A%2F%2Fsmartbroker.de%2Fimpressum.php%22%2C%22https%3A%2F%2Fgithub.com%2Fdate …
> Add 'wallstreet:online capital AG' (community contribution)

- companies/adressmonster.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22adressmonster%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22addresses%22%2C%22ads%22%5D%2C%22name%22%3A%22B2B%20Monster%20UG%20haftungsbeschr%C3%A4nkt%22%2C%22runs%22%3A%5B%22adressmonster.de%22%5D%2C%22address%22%3A%22%5CnB2B%20Monster%5CnUG%20haftungsbeschr%C3%A4nkt%5CnAm%20Mantel%204%5Cn76646%20Bruchsal%5CnB2B%20Monster%20Logo%5Cn%22%2C%22phone%22%3A%2207251%2032%2066%20873%22%2C%22email%22%3A%22support%40adressmosnter.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.adressmonster.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fadressmonster.de%2Fimpressum%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F984%22%5D%2C%22needs-id-document%22 …
> Add 'B2B Monster UG haftungsbeschränkt' (community contribution)

- companies/firmenhai.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22firmenhai%22%2C%22relevant-countries%22%3A%5B%22at%22%5D%2C%22categories%22%3A%5B%22ads%22%2C%22addresses%22%5D%2C%22name%22%3A%22Talenthai%20e.U.%22%2C%22runs%22%3A%5B%22firmenhai.at%22%2C%22talenthai.at%22%5D%2C%22address%22%3A%22Talenthai%20e.U.%5CnBenjamin%20Hadodo%2C%20B.Sc.%5CnSoftwarepark%2021%20%2F%201%20%2F%202.1%2C%5CnA%20%E2%80%93%204232%20Hagenberg%20im%20M%C3%BChlkreis%2C%5Cn%C3%96sterreich%22%2C%22phone%22%3A%22%2B43%20720%20518180%22%2C%22email%22%3A%22office%40firmenhai.at%22%2C%22web%22%3A%22https%3A%2F%2Ffirmenhai.at%22%2C%22sources%22%3A%5B%22https%3A%2F%2Ffirmenhai.at%2Fdatenschutzerklaerung%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull% …
> Add 'Talenthai e.U.' (community contribution)

- companies/b2b-datenbank-de.json
- companies/b2b-datenbank.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22b2b-datenbank%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22name%22%3A%22b2b-datenbank.de%22%2C%22runs%22%3A%5B%22https%3A%2F%2Fb2b-datenbank.de%22%5D%2C%22address%22%3A%22Spaqi%20Einzelunternehmen%5CnPascal%20Spaq%5CnBramfelder%20Drift%2011%5Cn22175%20Hamburg%22%2C%22phone%22%3A%22%2B49%204109%202690225%22%2C%22email%22%3A%22info%40b2b-datenbank.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.b2b-datenbank.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.b2b-datenbank.de%2Fdatenschutz%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F987%22%5D%2C%22needs-id-document%22%3Afalse%2C%22suggested-transport-medium%22%3A%22email%22%2C%22quality%22%3A%22verified%2 …
> Add 'b2b-datenbank.de' (community contribution)

- companies/pepsico-de.json
- companies/pepsico.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22pepsico%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22commerce%22%5D%2C%22name%22%3A%22PepsiCo%20Deutschland%20GmbH%20%22%2C%22runs%22%3A%5B%22rockstarenergydrink.de%22%2C%22PepsiCo%2C%20Inc.%22%5D%2C%22address%22%3A%22Hugenottenallee%20173%5Cn63263%20Neu-Isenburg%5CnGermany%20%22%2C%22phone%22%3A%22%2B49%206102%207490%22%2C%22fax%22%3A%22%2B49%206102%20749200%22%2C%22email%22%3A%22europe.privacy%40pepsico.com%22%2C%22web%22%3A%22https%3A%2F%2Fwww.pepsico.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fpepsicoprivacypolicy.com%2Fde%22%2C%22https%3A%2F%2Fwww.pepsico.de%2Fimpressum%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F989%22 …
> Add 'PepsiCo Deutschland GmbH ' (community contribution)

- companies/lmu-klinikum.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22lmu-klinikum%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22health%22%5D%2C%22name%22%3A%22Klinikum%20der%20Universit%C3%A4t%20M%C3%BCnchen%22%2C%22address%22%3A%22Marchioninistra%C3%9Fe%2015%5Cn81377%20M%C3%BCnchen%22%2C%22phone%22%3A%22089%20%2F%204400%20-%2058454%22%2C%22fax%22%3A%22089%20%2F%204400%20-%2055192%22%2C%22email%22%3A%22datenschutz%40med.uni-muenchen.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.lmu-klinikum.de%2Fdata_safety%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.lmu-klinikum.de%2Fdata_safety%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1008%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22quality%22 …
> Add 'Klinikum der Universität München' (community contribution)

- companies/panic.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22panic%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22entertainment%22%5D%2C%22name%22%3A%22Panic%20Inc.%22%2C%22runs%22%3A%5B%22Coda%22%2C%22Nova%22%2C%22Transmit%22%2C%22Prompt%22%2C%22Firewatch%22%2C%22Untitled%20Goose%20Game%22%2C%22Playdate%22%5D%2C%22address%22%3A%22315%20SW%2011th%20Ave%5Cn4th%20Floor%5CnPortland%2C%20OR%2097205%5CnUnited%20States%20of%20America%22%2C%22phone%22%3A%22%2B1%20503%20224%203451%22%2C%22email%22%3A%22gdpr%40panic.com%22%2C%22web%22%3A%22https%3A%2F%2Fpanic.com%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fpanic.com%2Fprivacy%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F957%22%5D%2C%22require …
> Update 'Panic Inc.' (community contribution)

- companies/digineo.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22digineo%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22name%22%3A%22Digineo%20GmbH%22%2C%22runs%22%3A%5B%22selbstauskunft.net%22%5D%2C%22address%22%3A%22Fahrenheitstr.%2015%5Cn28359%20Bremen%5CnDeutschland%22%2C%22phone%22%3A%22%200421%20167%2066%20090%22%2C%22fax%22%3A%220421%20167%2066%20099%22%2C%22email%22%3A%22datenschutz%40digineo.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.digineo.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fselbstauskunft.net%2Fdatenschutz%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1003%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22quality%22%3A%22verified%22%7D)**
> Add 'Digineo GmbH' (community contribution)

- companies/pwc-de.json
- companies/pwc.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22pwc%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22finance%22%5D%2C%22name%22%3A%22PricewaterhouseCoopers%20GmbH%20Wirtschaftspr%C3%BCfungsgesellschaft%20(PWC)%22%2C%22address%22%3A%22Friedrich-Ebert-Anlage%2035-37%5Cn60327%20Frankfurt%20am%20Main%22%2C%22phone%22%3A%22%2B49%2069%2095850%22%2C%22email%22%3A%22DE_Datenschutz%40pwc.com%22%2C%22web%22%3A%22https%3A%2F%2Fwww.pwc.de%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.pwc.de%2Fde%2Fdatenschutzerklaerung.html%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F992%22%5D%2C%22required-elements%22%3A%5B%7B%22desc%22%3A%22Geburtsdatum%22%2C%22type%22%3A%22birthdate%22%2C%22optional …
> Add 'PricewaterhouseCoopers GmbH Wirtschaftsprüfungsgesellschaft (PWC)' (community contribution)

- companies/hostpoint.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22hostpoint%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22telecommunication%22%5D%2C%22name%22%3A%22Hostpoint%20AG%22%2C%22address%22%3A%22Neue%20Jonastrasse%2060%5Cn8640%20Rapperswil-Jona%5CnSwitzerland%22%2C%22phone%22%3A%22%2B41%2055%20220%2063%2010%22%2C%22fax%22%3A%22%2B41%20844%20090%20909%22%2C%22email%22%3A%22privacy%40hostpoint.ch%22%2C%22web%22%3A%22https%3A%2F%2Fwww.hostpoint.ch%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.hostpoint.ch%2Fen%2Fhostpoint%2Fcontact-gtc.html%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F997%22%5D%2C%22required-elements%22%3A%5B%7B%22desc%22%3A%22Email%20(Hostpoint%20ID)%22%2C%22type%22%3A …
> Add 'Hostpoint AG' (community contribution)

- companies/ra-kodiak.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22ra-kodiak%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22collection%20agency%22%5D%2C%22name%22%3A%22KODIAK%20Rechtsanwaltsgesellschaft%20mbH%22%2C%22address%22%3A%22Normannenweg%2030%5Cn20537%20Hamburg%22%2C%22phone%22%3A%22040%2083509%200101%22%2C%22fax%22%3A%22040%2025317%205219%22%2C%22email%22%3A%22info%40ra-kodiak.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.ra-kodiak.de%22%2C%22sources%22%3A%5B%22Internet%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F994%22%5D%2C%22quality%22%3A%22verified%22%7D)**
> Add 'KODIAK Rechtsanwaltsgesellschaft mbH' (community contribution)

- companies/dispo.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22dispo%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22entertainment%22%5D%2C%22name%22%3A%22Dispo%2C%20Inc%22%2C%22address%22%3A%222720%20Neilson%20Way%20%235131%5CnSanta%20Monica%20CA%2090405%5CnUnited%20States%20of%20America%22%2C%22email%22%3A%22support%40dispo.fun%22%2C%22web%22%3A%22https%3A%2F%2Fdispo.fun%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fdispo.fun%2Fprivacy.html%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1000%22%5D%2C%22required-elements%22%3A%5B%7B%22desc%22%3A%22Name%22%2C%22type%22%3A%22name%22%2C%22optional%22%3Afalse%7D%2C%7B%22desc%22%3A%22Email%22%2C%22type%22%3A%22email%22%2C%22optional%22%3Afalse%7D% …
> Add 'Dispo, Inc' (community contribution)

- companies/cdu-bw.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22cdu-bw%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22political%20party%22%5D%2C%22name%22%3A%22CDU-Landesverband%20Baden-W%C3%BCrttemberg%22%2C%22address%22%3A%22Union%20Betriebs-GmbH%5CnEgermannstr.%202%5Cn53359%20Rheinbach%5CnDeutschland%22%2C%22phone%22%3A%22%2B49%2030%2022070570%22%2C%22fax%22%3A%22%2B49%202226%20802111%22%2C%22email%22%3A%22datenschutz%40ubgnet.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.cdu-bw.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.cdu-bw.de%2Fimpressum%2F%22%2C%22https%3A%2F%2Fwww.ubgnet.de%2Fdatenschutzerklaerung%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1001%22%5D%2C%22quality%22%3A%22verifie …
> Add 'CDU-Landesverband Baden-Württemberg' (community contribution)

- companies/permodo.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22permodo%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22ads%22%5D%2C%22name%22%3A%22%20Permodo%20GmbH%22%2C%22address%22%3A%22Derendorfer%20Allee%206c%5Cn40476%20D%C3%BCsseldorf%22%2C%22phone%22%3A%22%2B49%2089%20413240264%22%2C%22email%22%3A%22privacy%40permodo.com%22%2C%22web%22%3A%22https%3A%2F%2Fpermodo.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fpermodo.com%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1004%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22quality%22%3A%22verified%22%7D)**
> Add ' Permodo GmbH' (community contribution)

- companies/vgwort.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22vgwort%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22ads%22%5D%2C%22name%22%3A%22%20Verwertungsgesellschaft%20WORT%20(VG%20WORT)%22%2C%22address%22%3A%22Untere%20Weidenstra%C3%9Fe%205%5Cn81543%20M%C3%BCnchen%22%2C%22phone%22%3A%22%2B49%2089%20514120%22%2C%22fax%22%3A%22%2B49%2089%205141258%22%2C%22email%22%3A%22datenschutz%40vgwort.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.vgwort.de%2Fhilfsseiten%2Fdatenschutz.html%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.vgwort.de%2Fhilfsseiten%2Fdatenschutz.html%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1005%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22quality%22%3A%22ve …
> Add ' Verwertungsgesellschaft WORT (VG WORT)' (community contribution)

- companies/login-rtbmarket.json
- companies/rtbmarkt.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22login-rtbmarket%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22ads%22%5D%2C%22name%22%3A%22EASYmedia%20GmbH%22%2C%22address%22%3A%22L%C3%B6hner%20Str.%2012d%5Cn44652%20Herne%22%2C%22email%22%3A%22info%40easymedia-gmbh.de%22%2C%22web%22%3A%22https%3A%2F%2Flogin.rtbmarket.com%2Fgdpr%22%2C%22sources%22%3A%5B%22https%3A%2F%2Flogin.rtbmarket.com%2Fgdpr%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1006%22%5D%2C%22quality%22%3A%22verified%22%7D)**
> Add 'EASYmedia GmbH' (community contribution)

- companies/docsity.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22docsity%22%2C%22relevant-countries%22%3A%5B%22fr%22%2C%22it%22%5D%2C%22categories%22%3A%5B%22commerce%22%5D%2C%22name%22%3A%22Docsity%22%2C%22runs%22%3A%5B%22Koofers%22%5D%2C%22address%22%3A%22Via%20Leonardo%20da%20Vinci%2C%2016%20-%2010126%20Torino%22%2C%22phone%22%3A%22011%206938436%22%2C%22email%22%3A%22dpo%40docsity.com%22%2C%22web%22%3A%22https%3A%2F%2Fwww.docsity.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.docsity.com%2Ffr%2Fpag%2Fprivacy%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1007%22%5D%2C%22needs-id-document%22%3Afalse%2C%22suggested-transport-medium%22%3A%22email%22%2C%22quality%22%3A%22verified%22%7D)**
> Add 'Docsity' (community contribution)

- companies/hd-toner.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22hd-toner%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22commerce%22%2C%22ads%22%5D%2C%22name%22%3A%22TRENSCO%20GmbH%20%26%20Co.%20KG%22%2C%22runs%22%3A%5B%22HD%20Toner%22%5D%2C%22address%22%3A%22TRENSCO%20GmbH%20%26%20Co.%20KG%5CnAm%20Funkturm%209a%5Cn29525%20Uelzen%22%2C%22phone%22%3A%220581%203893276%22%2C%22fax%22%3A%220581%203893275%22%2C%22email%22%3A%22info%40hd-toner.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.hd-toner.de%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.hd-toner.de%2FImpressum%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1009%22%5D%2C%22quality%22%3A%22verified%22%7D)**
> Add 'TRENSCO GmbH & Co. KG' (community contribution)

- companies/vivalu.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22vivalu%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22ads%22%5D%2C%22name%22%3A%22VIVALU%20GmbH%22%2C%22address%22%3A%22Kaistr.%204%5Cn40221%20D%C3%BCsseldorf%5CnDeutschland%22%2C%22phone%22%3A%22%2B49%20211%207817520%22%2C%22fax%22%3A%22%2B49%20211%2078175299%22%2C%22email%22%3A%22datenschutz%40vivalu.com%22%2C%22web%22%3A%22https%3A%2F%2Fwww.vivalu.com%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.vivalu.com%2Fdatenschutz%2F%22%2C%22https%3A%2F%2Fwww.vivalu.com%2Fimpressum%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1013%22%5D%2C%22custom-access-template%22%3A%22access-tracking%22%2C%22suggested-transport-medium%22%3A% …
> Update 'VIVALU GmbH' (community contribution)

- companies/luca-app.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22luca-app%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22health%22%2C%22commerce%22%5D%2C%22name%22%3A%22culture4life%20GmbH%22%2C%22runs%22%3A%5B%22Kontakttagebuch%20luca%22%5D%2C%22address%22%3A%22Charlottenstra%C3%9Fe%2059%5Cn10117%20Berlin%5CnDeutschland%22%2C%22phone%22%3A%22%2B49%2030%2022183850%22%2C%22email%22%3A%22privacy%40culture4life.de%22%2C%22web%22%3A%22https%3A%2F%2Fluca-app.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fluca-app.de%2Fapp-privacy-policy%2F%22%2C%22https%3A%2F%2Fluca-app.de%2Fimprint%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F867%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1 …
> Update 'culture4life GmbH' (community contribution)

- companies/fintiba.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22fintiba%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22finance%22%2C%22school%22%5D%2C%22name%22%3A%22Fintiba%20GmbH%22%2C%22address%22%3A%22Baseler%20Stra%C3%9Fe%2035-37%5Cn60329%20Frankfurt%20am%20Main%5CnGermany%22%2C%22phone%22%3A%22%2B49%2069%2012006206620%22%2C%22email%22%3A%22privacy%40fintiba.com%22%2C%22web%22%3A%22https%3A%2F%2Fwww.fintiba.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.fintiba.com%2Fdocuments%2FAgreement_DataProtectionNotice_Fintiba.pdf%3Fx54750%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1026%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22quality%22%3A%22verified%22%7D)**
> Add 'Fintiba GmbH' (community contribution)

- companies/dominos-de.json
- companies/dominos.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22dominos%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22utility%22%5D%2C%22name%22%3A%22Domino%E2%80%99s%20Pizza%20Deutschland%20GmbH%22%2C%22address%22%3A%22Am%20Sandtorkai%2075-77%5Cn20457%20Hamburg%22%2C%22phone%22%3A%22%2B49%2040%204502330%22%2C%22email%22%3A%22datenschutz%40dominos.de%22%2C%22web%22%3A%22https%3A%2F%2Fdominos.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.dominos.de%2Fdatenschutz%22%2C%22https%3A%2F%2Fwww.dominos.de%2Fimpressum%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1018%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22quality%22%3A%22verified%22%7D)**
> Add 'Domino’s Pizza Deutschland GmbH' (community contribution)

- companies/flyeralarm-gmbh.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22flyeralarm-gmbh%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22name%22%3A%22FLYERALARM%20GmbH%22%2C%22runs%22%3A%5B%22flyeralarm.com%22%5D%2C%22address%22%3A%22Alfred-Nobel-Str.%2018%5Cn97080%20W%C3%BCrzburg%5CnDeutschland%22%2C%22phone%22%3A%22%2B49%20931%20465840%22%2C%22fax%22%3A%22%2B49%20931%20465841080%22%2C%22email%22%3A%22datenschutz%40flyeralarm.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.flyeralarm.com%2Fde%2Fcontent%2Findex%2Fopen%2Fid%2F23%2Fdatenschutzerklaerung.html%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1033%22%5D%2C%22quality%22%3A%22verified%22%7D)**
> Add 'FLYERALARM GmbH' (community contribution)

- companies/bitmaster-online.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22bitmaster-online%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22name%22%3A%22bitmaster%22%2C%22address%22%3A%22Plotterweg%2031%5Cn3821BB%20Amersfoort%5CnThe%20Netherlands%22%2C%22phone%22%3A%22%2B31%2085%20400%200176%22%2C%22email%22%3A%22support%40bitmaster-online.com%22%2C%22web%22%3A%22https%3A%2F%2Fbitmaster-online.com%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fbitmaster-online.com%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1019%22%5D%2C%22quality%22%3A%22verified%22%7D)**
> Add 'bitmaster' (community contribution)

- companies/qnc-gmbh.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22qnc-gmbh%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22name%22%3A%22QNC%20GmbH%22%2C%22runs%22%3A%5B%22frag-einen-anwalt.de%22%2C%22123recht.de%22%5D%2C%22address%22%3A%22c%2Fo%20Notix%20Datenschutz%20GmbH%5CnSchwarzer%20B%C3%A4r%204%5Cn30449%20Hannover%5CnDeutschland%22%2C%22phone%22%3A%22%2B49%20511%201222458%22%2C%22fax%22%3A%22%2B49%20511%2012356739%22%2C%22email%22%3A%22datenschutz%40qnc.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.frag-einen-anwalt.de%2Finfo.asp%3Fid%3Ddatenschutz%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1029%22%5D%2C%22quality%22%3A%22verified%22%7D)**
> Add 'QNC GmbH' (community contribution)

- companies/ihd-kredit.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22ihd-kredit%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22collection%20agency%22%2C%22credit%20agency%22%5D%2C%22name%22%3A%22IHD%20Gesellschaft%20f%C3%BCr%20Kredit-%20und%20Forderungsmanagement%20mbH%22%2C%22address%22%3A%22Augustinusstra%C3%9Fe%2011b%5Cn50226%20Frechen%5CnDeutschland%22%2C%22phone%22%3A%22%2B49%202234%2096420%22%2C%22fax%22%3A%22%2B49%202234%20964213%22%2C%22email%22%3A%22datenschutz%40ihd.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.ihd.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.ihd.de%2Fimpressum%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1038%22%5D%2C%22required-elements%22%3A%5B%7B%22desc%22%3A%22Na …
> Update 'IHD Gesellschaft für Kredit- und Forderungsmanagement mbH' (community contribution)

- companies/123greetings.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22123greetings%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22social%20media%22%5D%2C%22name%22%3A%22123Greetings.com%20Inc.%22%2C%22address%22%3A%22123Greetings.com%2C%20Inc.%5Cn255%20Executive%20Drive%2C%20Suite%20400%2C%5CnPlainview%2C%20New%20York%20NY-11803%3B%22%2C%22fax%22%3A%22%2B1%20212%20202%204738%22%2C%22email%22%3A%22privacy%40123greetings-inc.com%22%2C%22web%22%3A%22https%3A%2F%2Fwww.123greetings.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.123greetings.com%2Fprivacy_policy.html%22%2C%22https%3A%2F%2Fwww.123greetings.com%2Fterms_of_use.html%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1025%22%5D%2C%22needs-id-d …
> Add '123Greetings.com Inc.' (community contribution)

- companies/bildung-und-begabung.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22bildung-und-begabung%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22nonprofit%22%2C%22school%22%5D%2C%22name%22%3A%22Bildung%20%26%20Begabung%22%2C%22runs%22%3A%5B%22Sch%C3%BClerakademie%22%5D%2C%22address%22%3A%22Bildung%20%26%20Begabung%20gemeinn%C3%BCtzige%20GmbH%5CnKortrijker%20Stra%C3%9Fe%201%5Cn53177%20Bonn%22%2C%22phone%22%3A%22%2B49%20228%20959150%22%2C%22fax%22%3A%22%2B49%20228%209591519%22%2C%22email%22%3A%22info%40bildung-und-begabung.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.bildung-und-begabung.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.deutsche-schuelerakademie.de%2Fdatenschutzerklaerung%22%2C%22https%3A%2F%2Fwww.bildung-und-bega …
> Add 'Bildung & Begabung' (community contribution)

- companies/bodendirect.json
- companies/jp-boden.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22bodendirect%22%2C%22relevant-countries%22%3A%5B%22de%22%2C%22nl%22%2C%22gb%22%5D%2C%22categories%22%3A%5B%22commerce%22%5D%2C%22name%22%3A%22J.%20P.%20Boden%20(Netherlands)%20B.V.%22%2C%22address%22%3A%22Konnetlaantje%204%2C%5Cn1435HW%2C%5CnRijsenhout%22%2C%22phone%22%3A%220800%20000%203265%22%2C%22email%22%3A%22kundenbetreuung%40bodendirect.de%22%2C%22web%22%3A%22https%3A%2F%2Fbodendirect.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.bodendirect.de%2Fde-de%2Fimpressum%2Fdatenschutzerklarung%23Footer%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1021%22%5D%2C%22quality%22%3A%22verified%22%7D)**
> Add 'J. P. Boden (Netherlands) B.V.' (community contribution)

- companies/biber.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22biber%22%2C%22relevant-countries%22%3A%5B%22de%22%2C%22at%22%5D%2C%22categories%22%3A%5B%22commerce%22%5D%2C%22name%22%3A%22Biber%20Umweltprodukte%20Versand%20GmbH%22%2C%22address%22%3A%22Biber%20Umweltprodukte%20Versand%20GmbH%20F%C3%A4rbergasse%2013%5Cn6850%20Dornbirn%5Cn%C3%96sterreich%22%2C%22phone%22%3A%22%2B43%205572%202078200%22%2C%22email%22%3A%22datenschutz%40biber.com%22%2C%22web%22%3A%22https%3A%2F%2Fbiber.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.biber.com%2Fshop%2Fdatenschutz%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1022%22%5D%2C%22quality%22%3A%22verified%22%7D)**
> Add 'Biber Umweltprodukte Versand GmbH' (community contribution)

- companies/activeleads-se.json
- companies/activeleads.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22activeleads%22%2C%22relevant-countries%22%3A%5B%22se%22%5D%2C%22categories%22%3A%5B%22telecommunication%22%2C%22addresses%22%5D%2C%22name%22%3A%22Active%20Leads%20AB%22%2C%22address%22%3A%22V%C3%A4stmannagatan%2066%5CnS-113%2025%20Stockholm%5CnSWEDEN%22%2C%22phone%22%3A%22%2B46%2073%20997%2060%2069%22%2C%22email%22%3A%22hej%40ActiveLeads.se%22%2C%22web%22%3A%22https%3A%2F%2Fwww.activeleads.se%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.activeleads.se%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1028%22%5D%2C%22needs-id-document%22%3Afalse%2C%22suggested-transport-medium%22%3A%22email%22%2C%22quality%22%3A%22verified%22%7D)**
> Add 'Active Leads AB' (community contribution)

- companies/learnship.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22learnship%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22school%22%5D%2C%22name%22%3A%22Learnship%20Networks%20GmbH%22%2C%22address%22%3A%22Stolberger%20Str.%20374%5CnD-50933%20K%C3%B6ln%22%2C%22phone%22%3A%22%2B49%20221%2013062820%22%2C%22email%22%3A%22support%40learnship.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.learnship.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.learnship.com%22%2C%22https%3A%2F%2Fwww.northdata.com%2FLearnship%2BNetworks%2BGmbH%2C%2BK%25C3%25B6ln%2FHRB%2B61591%22%2C%22https%3A%2F%2Fwww.linkedin.com%2Fcompany%2Flearnship%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1034%22%5D%2C%22suggested-transpor …
> Add 'Learnship Networks GmbH' (community contribution)

- companies/suedkurier.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22suedkurier%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22name%22%3A%22S%C3%BCdkurier%22%2C%22address%22%3A%22S%C3%9CDKURIER%20GmbH%20Medienhaus%5CnMax-Stromeyer-Str.%20178%5Cn78467%20Konstanz%5CnDeutschland%22%2C%22email%22%3A%22datenschutz%40s%C3%BCdkurier.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.suedkurier.de%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.suedkurier.de%2Fservices%2Fagb%2Fdatenschutzerklaerung%3Bart1370803%2C10581762%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1036%22%5D%2C%22required-elements%22%3A%5B%7B%22desc%22%3A%22Name%3A%22%2C%22type%22%3A%22name%22%7D%2C%7B%22desc%22%3A%22E-Mail%20Addresse%3A%22%2C%22type%22%3A%22email%2 …
> Add 'Südkurier' (community contribution)

- companies/surreylofts-co.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22surreylofts-co%22%2C%22relevant-countries%22%3A%5B%22gb%22%5D%2C%22categories%22%3A%5B%22insurance%22%5D%2C%22name%22%3A%22Surrey%20Lofts%20Group%20Limited%22%2C%22address%22%3A%22317%20Molesey%20Road%2C%20Walton%20On%20Thames%2C%20Surrey%22%2C%22phone%22%3A%2201932%20269002%22%2C%22email%22%3A%22sales%40surreylofts.co.uk%22%2C%22web%22%3A%22https%3A%2F%2Fwww.surreylofts.co.uk%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.surreylofts.co.uk%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1037%22%5D%2C%22quality%22%3A%22verified%22%7D)**
> Add 'Surrey Lofts Group Limited' (community contribution)

- companies/mapcite.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22mapcite%22%2C%22relevant-countries%22%3A%5B%22gb%22%5D%2C%22categories%22%3A%5B%22school%22%5D%2C%22name%22%3A%22excel%20maps%22%2C%22address%22%3A%22Sunrise%20Parkway%20Milton%20Keynes%22%2C%22phone%22%3A%2201604981704%22%2C%22email%22%3A%22vinhcity2097%40gmail.com%22%2C%22web%22%3A%22https%3A%2F%2Fwww.mapcite.com%2Fexcel-addin%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.mapcite.com%2Fexcel-addin%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1039%22%5D%2C%22quality%22%3A%22verified%22%7D)**
> Add 'excel maps' (community contribution)

- companies/nfumutual-co.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22nfumutual-co%22%2C%22relevant-countries%22%3A%5B%22gb%22%5D%2C%22categories%22%3A%5B%22insurance%22%5D%2C%22name%22%3A%22NFU%20Mutual%22%2C%22address%22%3A%22NFU%20Mutual%2C%20Tiddington%20Road%2C%20Stratford-upon-Avon%2C%20Warwickshire%2C%20CV37%207BJ%22%2C%22phone%22%3A%220800%20072%200168%22%2C%22web%22%3A%22https%3A%2F%2Fwww.nfumutual.co.uk%22%2C%22quality%22%3A%22verified%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1011%22%5D%7D)**
> Add 'NFU Mutual' (community contribution)

- companies/barkandrock.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22barkandrock%22%2C%22relevant-countries%22%3A%5B%22gb%22%5D%2C%22categories%22%3A%5B%22school%22%5D%2C%22name%22%3A%22Bark%20%26%20Rock%22%2C%22address%22%3A%22Pool%20Close%20Unit%201%2C%20Delf%20House%20West%20Molesey%2C%20Surrey%20KT8%202HW%2C%20GB%22%2C%22phone%22%3A%22%2B44%2020%203968%202090%22%2C%22email%22%3A%22hello%40barkandrock.com%22%2C%22web%22%3A%22https%3A%2F%2Fwww.barkandrock.com%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.barkandrock.com%2Fblogs%2Fnews%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1045%22%5D%2C%22quality%22%3A%22verified%22%7D)**
> Add 'Bark & Rock' (community contribution)

- companies/csob.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22csob%22%2C%22relevant-countries%22%3A%5B%22cz%22%5D%2C%22categories%22%3A%5B%22finance%22%2C%22credit%20agency%22%5D%2C%22name%22%3A%22%C4%8Ceskoslovensk%C3%A1%20obchodn%C3%AD%20banka%2C%20a.s.%22%2C%22runs%22%3A%5B%22%C4%8CSOB%22%5D%2C%22address%22%3A%22Radlick%C3%A1%20333%2F150%5Cn150%2057%2C%20Praha%205%5CnCzech%20Republic%22%2C%22phone%22%3A%22%2B420%20800%20023%20003%22%2C%22email%22%3A%22osobni-data%40csob.cz%22%2C%22web%22%3A%22https%3A%2F%2Fwww.csob.cz%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.csob.cz%2Fportal%2Fcontacts%22%2C%22https%3A%2F%2Fwww.csob.cz%2Fportal%2Fcsob%2Fabout-the-csob-group%22%2C%22https%3A%2F%2Fwww.csob.cz%2Fportal%2Fen%2Fcsob%2Fprotection- …
> Add 'Československá obchodní banka, a.s.' (community contribution)

- companies/hcc-gmbh.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22hcc-gmbh%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22ads%22%5D%2C%22name%22%3A%22HCC%20GmbH%22%2C%22address%22%3A%22Airport%20Center%20(Haus%20C)%2C%5CnFlughafenstra%C3%9Fe%2052a%5Cn%5Cn22335%20Hamburg%22%2C%22fax%22%3A%22%2B49%2040%2053299100%22%2C%22email%22%3A%22info-hcc%40email.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.hcc-gmbh.net%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.hcc-gmbh.net%2Fimpressum%22%2C%22https%3A%2F%2Fwww.hcc-gmbh.net%2Fdatenschutz%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1052%22%5D%2C%22suggested-transport-medium%22%3A%22fax%22%2C%22quality%22%3A%22verified%22%7D)**
> Add 'HCC GmbH' (community contribution)

- companies/umweltbank.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22umweltbank%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22finance%22%5D%2C%22name%22%3A%22UmweltBank%20AG%22%2C%22address%22%3A%22Laufertorgraben%206%5Cn90489%20N%C3%BCrnberg%5CnDeutschland%22%2C%22phone%22%3A%22%2B49%20911%2053082020%22%2C%22fax%22%3A%22%2B49%20911%205308129%22%2C%22email%22%3A%22datenschutz%40umweltbank.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.umweltbank.de%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.umweltbank.de%2Fdatenschutz%22%2C%22https%3A%2F%2Fwww.umweltbank.de%2Fimpressum%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1054%22%5D%2C%22quality%22%3A%22verified%22%7D)**
> Add 'UmweltBank AG' (community contribution)

- companies/wirecloud.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22wirecloud%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22telecommunication%22%5D%2C%22name%22%3A%22WIRECLOUD%22%2C%22address%22%3A%22Im%20Mediapark%205%5Cn50670%20K%C3%B6n%5CnDeutschland%22%2C%22phone%22%3A%220221%2099999936%20%22%2C%22fax%22%3A%220221%2099999937%22%2C%22email%22%3A%22beratung%40wirecloud.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.wirecloud.de%2F%22%2C%22suggested-transport-medium%22%3A%22email%22%2C%22quality%22%3A%22verified%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1055%22%5D%7D)**
> Add 'WIRECLOUD' (community contribution)

- companies/sfr.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22sfr%22%2C%22relevant-countries%22%3A%5B%22fr%22%5D%2C%22categories%22%3A%5B%22telecommunication%22%5D%2C%22name%22%3A%22SFR%22%2C%22runs%22%3A%5B%22Red%20by%20SFR%22%5D%2C%22address%22%3A%22Service%20client%20SFR%20Donn%C3%A9es%20personnelles%20%20%5CnTSA%2010101%20-%2069947%20LYON%20CEDEX%2020%22%2C%22web%22%3A%22https%3A%2F%2Fwww.sfr.fr%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fassistance.sfr.fr%2Fnc%2Facces-a-vos-donnees-personnelles.html%22%2C%22https%3A%2F%2Fwww.sfr.fr%2Fpolitique-de-protection-des-donnees-personnelles.html%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1064%22%5D%2C%22needs-id-document%22%3Atrue%2C%22suggested-transport-medium%22%3A%2 …
> Add 'SFR' (community contribution)

- companies/futuraemedia.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22futuraemedia%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22name%22%3A%22Futurae%20Media%20Ltd%22%2C%22address%22%3A%22Kemp%20House%20City%20Road%2C%20152%20%E2%80%93%20160%5CnLondon%2C%20England%2C%20EC1V%202NX%5Cn%22%2C%22phone%22%3A%22%2B44%207451%20204362%22%2C%22email%22%3A%22info%40futuraemedia.com%22%2C%22web%22%3A%22https%3A%2F%2Fwww.futuraemedia.com%22%2C%22sources%22%3A%5B%22www.futuraemedia.com%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1069%22%5D%2C%22quality%22%3A%22verified%22%7D)**
> Add 'Futurae Media Ltd' (community contribution)

- companies/doctorbox.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22doctorbox%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22health%22%5D%2C%22name%22%3A%22DoctorBox%20GmbH%22%2C%22address%22%3A%22DoctorBox%20GmbH%5CnKnesebeckstr.%2059-61%5Cn10719%20Berlin%20%22%2C%22phone%22%3A%22%2B49%2030%2034045468%22%2C%22web%22%3A%22https%3A%2F%2Fwww.doctorbox.de%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.doctorbox.de%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1070%22%5D%2C%22quality%22%3A%22verified%22%7D)**
> Add 'DoctorBox GmbH' (community contribution)

- companies/concora.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22concora%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22name%22%3A%22concora%22%2C%22address%22%3A%2213010%20Morris%20Road%20Building%201%2C%20Suite%20650%20Alpharetta%2C%20Ga%2030004%22%2C%22phone%22%3A%228774369031%22%2C%22email%22%3A%22concora678%40gmail.com%22%2C%22web%22%3A%22https%3A%2F%2Fconcora.com%22%2C%22quality%22%3A%22verified%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1062%22%5D%7D)**
> Add 'concora' (community contribution)

- companies/hireright.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22hireright%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22name%22%3A%22HireRight%22%2C%22address%22%3A%223349%20Michelson%20Drive%2C%20%5CnSuite%20150%2C%20%5CnIrvine%2C%20%5CnCA%2092612%5CnUSA%22%2C%22phone%22%3A%22%2B44%20808%20196%202039%22%2C%22email%22%3A%22%20dpo%40hireright.com%22%2C%22web%22%3A%22https%3A%2F%2Fwww.hireright.com%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.hireright.com%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1065%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22quality%22%3A%22verified%22%7D)**
> Add 'HireRight' (community contribution)

- companies/ubisoft.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22ubisoft%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22entertainment%22%2C%22social%20media%22%5D%2C%22name%22%3A%22Ubisoft%20Entertainment%20SA%22%2C%22runs%22%3A%5B%22Ubisoft%20EMEA%20SAS%22%2C%22Ubisoft%20GmbH%22%2C%22Ubisoft%20Nordic%20A%2FS%22%2C%22Ubisoft%2C%20S.A.%22%2C%22Ubisoft%20P%2FL%22%2C%22Ubisoft%20Blue%20Byte%20GmbH%22%5D%2C%22address%22%3A%2217%20avenue%20Henri%20Fr%C3%A9ville%5Cn35200%20Rennes%5CnFrance%22%2C%22email%22%3A%22https%3A%2F%2Fsupport.ubi.com%2Ffaqs%2F35367%2FReviewing-the-data-that-Ubisoft-holds-about-me%2F%22%2C%22web%22%3A%22https%3A%2F%2Fwww.ubisoft.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Flegal.ubi.com%2FLega …
> Update 'Ubisoft Entertainment SA' (community contribution)

- companies/ikano-bank-de.json
- companies/ikano-bank-dk.json
- companies/ikano-bank-fi.json
- companies/ikano-bank-pl.json
- companies/ikano-bank.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22ikano-bank%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22finance%22%5D%2C%22name%22%3A%22Ikano%20Bank%22%2C%22runs%22%3A%5B%22Forderungsmanagement%22%5D%2C%22address%22%3A%22Postfach%20420162%5Cn65102%20Wiesbaden%22%2C%22phone%22%3A%2206122%20999240%22%2C%22fax%22%3A%2206122%20999241%22%2C%22quality%22%3A%22verified%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1056%22%5D%7D)**
> Add 'Ikano Bank' (community contribution)

- companies/123greetings.json
- companies/appsumo.json
- companies/cloudapp.json
- companies/quora.json
- companies/zoho.json
Adding a couple more companies + updating some
> March batch

- companies/spezi-haus-de.json
- companies/spezialit-ten-haus-g-schulteis-gmbh.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22spezialit-ten-haus-g-schulteis-gmbh%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22ads%22%5D%2C%22name%22%3A%22Spezialit%C3%A4ten-Haus%20G.%20Schulteis%20GmbH%22%2C%22address%22%3A%22Spezialit%C3%A4ten-Haus%20G.%20Schulteis%20GmbH%5Cnz.Hdn.%20Abteilung%20Datenschut%5CnBachstra%C3%9Fe%2022%20%5Cn52066%20Aachen%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.spezi-haus.de%2Fdatenschutzerklaerung%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1084%22%5D%2C%22required-elements%22%3A%5B%7B%22desc%22%3A%22Werbung%22%2C%22type%22%3A%22address%22%7D%5D%2C%22quality%22%3A%22verified%22%7D)**
> Add 'Spezialitäten-Haus G. Schulteis GmbH' (community contribution)

- companies/bfs-health-finance.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22bfs-health-finance%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22credit%20agency%22%5D%2C%22name%22%3A%22BFS%20health%20finance%20GmbH%22%2C%22address%22%3A%22Carl-Bertelsmann-Stra%C3%9Fe%20270%5Cn33311%20G%C3%BCtersloh%5CnDeutschland%22%2C%22phone%22%3A%22%2B49%20800%204473254%22%2C%22fax%22%3A%22%2B49%20231%20945362888%22%2C%22email%22%3A%22datenschutz%40meinebfs.de%22%2C%22web%22%3A%22https%3A%2F%2Fmeinebfs.de%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fmeinebfs.de%2Fdatenschutz%2F%22%2C%22https%3A%2F%2Fmeinebfs.de%2Fimpressum%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1061%22%5D%2C%22needs-id-document%22%3Atrue%2C%22s …
> Update 'BFS health finance GmbH' (community contribution)

- companies/fiddiam-sa.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22fiddiam-sa%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22ads%22%5D%2C%22name%22%3A%22Fiddiam%20SA%22%2C%22address%22%3A%22Fiddiam%20SA%20%5Cn25%2C%20Rue%20des%20Bruy%C3%A8res%20%5CnL-1274%20Howald%22%2C%22phone%22%3A%22%2B352%2026%2019%2068%2011%22%2C%22email%22%3A%22contact%40fiddiam.net%22%2C%22sources%22%3A%5B%22Registergericht%3A%20Stadt%20Luxemburg%20%7C%20Registernummer%3A%20RCS%20B%2044695%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1076%22%5D%2C%22needs-id-document%22%3Afalse%2C%22suggested-transport-medium%22%3A%22email%22%2C%22quality%22%3A%22verified%22%7D)**
> Add 'Fiddiam SA' (community contribution)

- companies/onesource.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22onesource%22%2C%22relevant-countries%22%3A%5B%22be%22%2C%22nl%22%2C%22gb%22%5D%2C%22name%22%3A%22One%20Source%20Consulting%20B.V.%22%2C%22runs%22%3A%5B%22TELVEL%20IT%20Solutions%20Pvt%20Ltd.%22%2C%22One%20Source%20Consulting%20SPRL.%22%2C%22One%20Source%20Consulting%20Limited%22%5D%2C%22address%22%3A%22Bezoekadres%20Flight%20Forum%2040%5Cn5657DB%20Eindhoven%22%2C%22phone%22%3A%22%2B31%2040%20808%201192%22%2C%22email%22%3A%22info%40onesource.nl%22%2C%22web%22%3A%22https%3A%2F%2Fwww.onesource.one%2F%22%2C%22needs-id-document%22%3Afalse%2C%22suggested-transport-medium%22%3A%22email%22%2C%22quality%22%3A%22verified%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fgithub.com%2Fdatenanfr …
> Add 'One Source Consulting B.V.' (community contribution)

- companies/globalme-net.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22globalme-net%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22name%22%3A%22Summa%20Linguae%20Technologies%22%2C%22address%22%3A%221008%20Homer%20Street%20%23310%20%5CnVancouver%5CnBC%20V6B%202X1%5CnCanada%22%2C%22phone%22%3A%22%2B1%20855%20438%205106%22%2C%22email%22%3A%22office_us%40summalinguae.com%22%2C%22web%22%3A%22https%3A%2F%2Fsummalinguae.com%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F187%22%2C%22https%3A%2F%2Fsummalinguae.com%2Fprivacy-policy%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1080%22%5D%2C%22quality%22%3A%22verified%22%7D)**
> Update 'Summa Linguae Technologies' (community contribution)

- companies/scaleway.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22scaleway%22%2C%22relevant-countries%22%3A%5B%22fr%22%5D%2C%22categories%22%3A%5B%22telecommunication%22%5D%2C%22name%22%3A%22Scaleway%22%2C%22address%22%3A%22SCALEWAY%5CnInformatique%20et%20Libert%C3%A9s%5Cn75371%20Paris%20Cedex%2008%5CnFRANCE%22%2C%22phone%22%3A%22%2B33%201%2084%2013%2000%2000%22%2C%22fax%22%3A%22%2B33%20899%2019%2037%2075%22%2C%22email%22%3A%22privacy%40scaleway.com%22%2C%22web%22%3A%22https%3A%2F%2Fwww.scaleway.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.scaleway.com%2Ffr%2Fconditions%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1086%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22quality%22%3A%22verified%22%7D)**
> Add 'Scaleway' (community contribution)

- companies/digital-pressence.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22digital-pressence%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22ads%22%5D%2C%22name%22%3A%22digital%20pressence%20GmbH%22%2C%22address%22%3A%22Enzianstra%C3%9Fe%202%5CnD-82319%20Starnberg%22%2C%22phone%22%3A%22n.a.%22%2C%22email%22%3A%22d.berghof%40digital-pressence.de%22%2C%22web%22%3A%22https%3A%2F%2Fdigital-pressence.de%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fdigital-pressence.de%2Fdatenschutz%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1087%22%5D%2C%22needs-id-document%22%3Afalse%2C%22suggested-transport-medium%22%3A%22email%22%2C%22quality%22%3A%22verified%22%7D)**
> Add 'digital pressence GmbH' (community contribution)

- companies/muehlenkreiskliniken.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22muehlenkreiskliniken%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22health%22%5D%2C%22name%22%3A%22M%C3%BChlenkreiskliniken%22%2C%22address%22%3A%22M%C3%BChlenkreiskliniken%20A%C3%B6R%5CnHans-Nolte-Stra%C3%9Fe%201%5Cn32429%20Minden%22%2C%22phone%22%3A%220571%2F7900%22%2C%22fax%22%3A%220571%2F790292929%22%2C%22email%22%3A%22info%40muehlenkreiskliniken.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.muehlenkreiskliniken.de%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.muehlenkreiskliniken.de%2Fmkk%2Fimpressum.html%23datenschutz%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1088%22%5D%2C%22quality%22%3A%22verified%22%7D)**
> Add 'Mühlenkreiskliniken' (community contribution)

- companies/vivacom.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22vivacom%22%2C%22relevant-countries%22%3A%5B%22bg%22%5D%2C%22categories%22%3A%5B%22telecommunication%22%5D%2C%22name%22%3A%22Vivacom%22%2C%22address%22%3A%22VIVACOM%20Headquarters%20%5Cn115%20I%2C%20Tsarigradsko%20chaussee%20blvd.%2C%20%5Cn1784%20Sofia%2C%20%5CnBulgaria%22%2C%22phone%22%3A%22%2B359%202%20949%206079%22%2C%22email%22%3A%22dpo%40vivacom.bg%22%2C%22web%22%3A%22https%3A%2F%2Fwww.vivacom.bg%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.vivacom.bg%2Fbg%2Ffiles%2F7639-politika-za-poveritelnost.pdf%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1090%22%5D%2C%22needs-id-document%22%3Atrue%2C%22suggested-transport-medium%22%3A%22email%22%2C%22commen …
> Add 'Vivacom' (community contribution)

- companies/elyflowers-co.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22elyflowers-co%22%2C%22relevant-countries%22%3A%5B%22gb%22%5D%2C%22categories%22%3A%5B%22entertainment%22%5D%2C%22name%22%3A%22Garden%20Gate%20Flowers%20Ely%20Ltd%22%2C%22address%22%3A%2230%20St.%20Mary's%20Street%2C%20Ely%2C%20Cambridgeshire%22%2C%22phone%22%3A%2201353%20663%20888%22%2C%22email%22%3A%22shop%40elyflowers.co.uk%22%2C%22web%22%3A%22https%3A%2F%2Fwww.elyflowers.co.uk%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.elyflowers.co.uk%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1094%22%5D%2C%22quality%22%3A%22verified%22%7D)**
> Add 'Garden Gate Flowers Ely Ltd' (community contribution)

- companies/bitcoinsuisse.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22bitcoinsuisse%22%2C%22relevant-countries%22%3A%5B%22de%22%2C%22at%22%2C%22ch%22%5D%2C%22categories%22%3A%5B%22finance%22%5D%2C%22name%22%3A%22Bitcoin%20Suisse%22%2C%22address%22%3A%22Internationale%20E-Mail%3A%20dataprotection%40bitcoinsuisse.com%22%2C%22email%22%3A%22philipp.mittelberger%40bwb.li%22%2C%22web%22%3A%22https%3A%2F%2Fwww.bitcoinsuisse.com%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Ffiles.bitcoinsuisse.com%2Fassets%2Fpdf%2Fdata_protection_policy.pdf%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1035%22%5D%2C%22quality%22%3A%22verified%22%7D)**
> Add 'Bitcoin Suisse' (community contribution)

- companies/goldgas.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22goldgas%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22utility%22%5D%2C%22name%22%3A%22goldgas%20GmbH%22%2C%22address%22%3A%22Ginnheimer%20Stra%C3%9Fe%204%5Cn65760%20Eschborn%22%2C%22email%22%3A%22info%40goldgas.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.goldgas.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.goldgas.de%2Fservice%2Fkontakt%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1102%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22quality%22%3A%22verified%22%7D)**
> Add 'goldgas GmbH' (community contribution)

- companies/domoguide.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22domoguide%22%2C%22relevant-countries%22%3A%5B%22fr%22%5D%2C%22categories%22%3A%5B%22entertainment%22%5D%2C%22name%22%3A%22Domoguide%22%2C%22address%22%3A%226%20chemin%20de%20Baudin%2C%20B104%20%E2%80%93%2033320%20Le%20Taillan-M%C3%A9doc%22%2C%22email%22%3A%22admin%40domoguide.com%22%2C%22web%22%3A%22https%3A%2F%2Fwww.domoguide.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.domoguide.com%2Fconditions-generales-dutilisation%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1058%22%5D%2C%22needs-id-document%22%3Afalse%2C%22suggested-transport-medium%22%3A%22email%22%2C%22quality%22%3A%22verified%22%7D)**
> Add 'Domoguide' (community contribution)

- companies/vrbank.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22vrbank%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22finance%22%5D%2C%22name%22%3A%22VR%20Bank%20Rhein-Neckar%20eG%22%2C%22address%22%3A%22Augustaanlage%2061%5Cn68165%20Mannheim%22%2C%22phone%22%3A%220621%201282%2019999%22%2C%22fax%22%3A%220621%201282-12820%22%2C%22email%22%3A%22Datenschutz%40vrbank.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.vrbank.de%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.vrbank.de%2Fservice%2Frechtliche-hinweise%2Fdatenschutzhinweis-zur-website.html%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1100%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22quality%22%3A%22verified%22%7D)**
> Add 'VR Bank Rhein-Neckar eG' (community contribution)

- companies/energiemanufaktur.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22energiemanufaktur%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22utility%22%5D%2C%22name%22%3A%22DREWAG%20-%20Stadtwerke%20Dresden%20GmbH%22%2C%22address%22%3A%22Friedrich-List-Platz%202%5Cn01069%20Dresden%22%2C%22email%22%3A%22drewag-datenschutz%40SachsenEnergie.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.energiemanufaktur.net%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.energiemanufaktur.net%2Fdatenschutz%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1101%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22quality%22%3A%22verified%22%7D)**
> Add 'DREWAG - Stadtwerke Dresden GmbH' (community contribution)

- companies/outbrain.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22outbrain%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22ads%22%5D%2C%22name%22%3A%22Outbrain%2C%20Inc.%22%2C%22runs%22%3A%5B%22Outbrain%20Amplify%22%5D%2C%22address%22%3A%2239%20West%2013th%20Street%5Cn3rd%20floor%5CnNew%20York%5CnNY%2010011%5CnUnited%20States%20of%20America%22%2C%22web%22%3A%22https%3A%2F%2Fwww.outbrain.com%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.outbrain.com%2Flegal%2Fprivacy%23privacy-policy%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1109%22%5D%2C%22custom-access-template%22%3A%22access-tracking%22%2C%22suggested-transport-medium%22%3A%22email%22%2C%22quality%22%3A%22verified%22%7D)**
> Update 'Outbrain, Inc.' (community contribution)

- companies/alibaba.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22alibaba%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22commerce%22%5D%2C%22name%22%3A%22Alibaba.com%20Singapore%20E-Commerce%20Private%20Limited%22%2C%22address%22%3A%228%20Shenton%20Way%5Cn%2345-01%5CnAxa%20Tower%5CnSingapore%20068811%5CnRepublic%20of%20Singapore%22%2C%22email%22%3A%22dataprotection%40service.alibaba.com%22%2C%22web%22%3A%22https%3A%2F%2Fwww.alibaba.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Frule.alibaba.com%2Frule%2Fdetail%2F2034.htm%22%2C%22https%3A%2F%2Fopencorpdata.com%2Fsg%2F200720572D%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1113%22%5D%2C%22required-elements%22%3A%5B%7B%22desc%22%3A%22Name%22%2C%2 …
> Update 'Alibaba.com Singapore E-Commerce Private Limited' (community contribution)

- companies/pxn-digital.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22pxn-digital%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22telecommunication%22%5D%2C%22name%22%3A%22PXN%20GmbH%22%2C%22address%22%3A%22Leutragraben%201%5Cn07743%20Jena%5CnDeutschland%22%2C%22email%22%3A%22info%40pxn-digital.de%22%2C%22web%22%3A%22https%3A%2F%2Fpxn-digital.de%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fpxn-digital.de%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1110%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22quality%22%3A%22verified%22%7D)**
> Add 'PXN GmbH' (community contribution)

- companies/ing-diba.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22ing-diba%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22finance%22%5D%2C%22name%22%3A%22ING%20(ING-DiBa%20AG)%22%2C%22address%22%3A%22Theodor-Heuss-Allee%202%5Cn60486%20Frankfurt%20am%20Main%5CnDeutschland%22%2C%22phone%22%3A%22%2B49%2069%20342224%22%2C%22fax%22%3A%22%2B49%2069%202722227%22%2C%22email%22%3A%22datenschutz%40ing.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.ing.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.ing.de%2Fkundenservice%2Fsicherheit%2Fdatenschutz%2F%23!3430544%22%2C%22https%3A%2F%2Fwww.ing.de%2Fueber-uns%2Funternehmen%2Fimpressum%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1108%22%5D%2C%22required-eleme …
> Update 'ING (ING-DiBa AG)' (community contribution)

- companies/bold-company.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22bold-company%22%2C%22relevant-countries%22%3A%5B%22nl%22%5D%2C%22name%22%3A%22BOLD%20Company%22%2C%22address%22%3A%22Beursplein%2037%2C%20Rotterdam%2C%203011AA%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.boldcompany.nl%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1115%22%5D%2C%22quality%22%3A%22verified%22%7D)**
> Add 'BOLD Company' (community contribution)

- companies/takeaway-com.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22takeaway-com%22%2C%22relevant-countries%22%3A%5B%22bg%22%2C%22de%22%2C%22at%22%2C%22ro%22%2C%22lu%22%2C%22pt%22%2C%22pl%22%2C%22be%22%2C%22ch%22%2C%22nl%22%5D%2C%22name%22%3A%22Takeaway.com%20Group%20B.V.%22%2C%22runs%22%3A%5B%22%D0%91%D0%93%D0%BC%D0%B5%D0%BD%D1%8E%20%D0%95%D0%9E%D0%9E%D0%94%22%2C%22Lieferando%22%2C%22yd.yourdelivery%20GmbH%22%2C%22Hello%20Hungry%20SA%22%2C%22Takeaway.com%22%2C%22Pyszne.pl%22%2C%22Thuisbezorgd.nl%22%2C%2210bis%22%2C%22pizza.de%20(ehem.)%22%2C%22foodora.de%20(ehem.)%22%2C%22lieferservice.de%20(ehem.)%22%2C%22lieferheld.de%20(ehem.)%22%5D%2C%22address%22%3A%22Oosterdoksstraat%2080%5Cn1011%20DK%20Amsterdam%5CnNederland%22%2C%22phone%22%3A%22%2 …
> Update 'Takeaway.com Group B.V.' (community contribution)

- companies/gymnasium-sulingen.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22gymnasium-sulingen%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22public%20body%22%2C%22school%22%5D%2C%22name%22%3A%22Gymnasium%20Sulingen%22%2C%22address%22%3A%22Schmelingstra%C3%9Fe%2037%5Cn27232%20Sulingen%22%2C%22phone%22%3A%22%2B49%204271%2095340%22%2C%22fax%22%3A%22%2B49%204271%209534111%22%2C%22email%22%3A%22info%40gymnasium-sulingen.de%22%2C%22web%22%3A%22https%3A%2F%2Fgymnasium-sulingen.de%22%2C%22sources%22%3A%5B%22gymnasium-sulingen.de%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1123%22%5D%2C%22needs-id-document%22%3Atrue%2C%22suggested-transport-medium%22%3A%22email%22%2C%22quality%22%3A%22verified%22%7D)**
> Add 'Gymnasium Sulingen' (community contribution)

- companies/prd.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22prd%22%2C%22relevant-countries%22%3A%5B%22at%22%2C%22de%22%5D%2C%22categories%22%3A%5B%22school%22%5D%2C%22name%22%3A%22PR%26D%20%E2%80%93%20Public%20Relations%20f%C3%BCr%20Forschung%20%26%20Bildung%20GmbH%22%2C%22address%22%3A%22PR%26D%20Kommunikationsdienstleistungen%20GmbH%5CnKollersteig%2068%5Cn3400%20Klosterneuburg%5Cn%C3%96sterreich%22%2C%22phone%22%3A%22%2B43%20664%20226936%22%2C%22email%22%3A%22contact%40prd.at%22%2C%22web%22%3A%22https%3A%2F%2Fprd.at%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fprd.at%2Fkontakt-impressum%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1127%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22quality%22%3A% …
> Add 'PR&D – Public Relations für Forschung & Bildung GmbH' (community contribution)

- companies/vodafone-de.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22vodafone-de%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22telecommunication%22%5D%2C%22name%22%3A%22Vodafone%20GmbH%22%2C%22runs%22%3A%5B%22Vodafone%20Community%22%2C%22Vodafone%20Apps%22%2C%22Vodafone%20Deutschland%20GmbH%20(vormals%3A%20Vodafone%20Kabel%20Deutschland%20GmbH)%22%2C%22EDEKA%20mobil%20(www.edeka-mobil.de)%22%2C%22otelo%20(www.otelo.de)%22%5D%2C%22address%22%3A%22Ferdinand-Braun-Platz%201%5Cn40549%20D%C3%BCsseldorf%5CnDeutschland%22%2C%22phone%22%3A%22%2B49%20800%201721212%22%2C%22fax%22%3A%22%2B49%20211%205332200%22%2C%22email%22%3A%22datenschutz%40vodafone.com%22%2C%22web%22%3A%22https%3A%2F%2Fwww.vodafone.de%2F%22%2C%22sources%2 …
> Update 'Vodafone GmbH' (community contribution)

- companies/target-team-europe.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22target-team-europe%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22ads%22%5D%2C%22name%22%3A%22TARGET%20TEAM%20EUROPE%20S.L.%22%2C%22address%22%3A%22Madrazo%2027%2C%201a%20Planta%5Cn08006%20Barcelona%5CnSpain%22%2C%22email%22%3A%22service%40target-team-europe.com%22%2C%22web%22%3A%22http%3A%2F%2Fwww.target-team-europe.com%22%2C%22sources%22%3A%5B%22http%3A%2F%2Fwww.target-team-europe.com%2Fde%2Flegal%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F559%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1132%22%5D%2C%22required-elements%22%3A%5B%7B%22desc%22%3A%22Name%22%2C%22type%22%3A%22name%22%7D%2C%7B%22desc%2 …
> Update 'TARGET TEAM EUROPE S.L.' (community contribution)

- companies/ksk-koeln.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22ksk-koeln%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22name%22%3A%22Kreissparkasse%20K%C3%B6ln%22%2C%22address%22%3A%22Kreissparkasse%20K%C3%B6ln%5CnNeumarkt%2018-24%5Cn50667%20K%C3%B6ln%5CnDeutschland%5Cn%22%2C%22phone%22%3A%220221%20227-0%22%2C%22fax%22%3A%220221%20227-3920%20%22%2C%22email%22%3A%22info%40ksk-koeln.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.ksk-koeln.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.ksk-koeln.de%2Fde%2Fhome%2Ftoolbar%2Fdatenschutz.html%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1136%22%5D%2C%22needs-id-document%22%3Atrue%2C%22comments%22%3A%5B%22Datenschutzbeauftragter%5CnFrank-Stephan%20Esch%5CnNeumarkt%2018-24%5 …
> Add 'Kreissparkasse Köln' (community contribution)

- companies/covimedical.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22covimedical%22%2C%22relevant-countries%22%3A%5B%22de%22%2C%22es%22%5D%2C%22categories%22%3A%5B%22health%22%5D%2C%22name%22%3A%22CoviMedical%20GmbH%22%2C%22runs%22%3A%5B%22https%3A%2F%2F15minutentest.de%22%5D%2C%22address%22%3A%22c%2Fo%20Moos%20Datenschutzmanagement%20GmbH%5CnJulian%20Moos%5CnWilhelmstra%C3%9Fe%208%5Cn35683%20Dillenburg%5CnDeutschland%22%2C%22phone%22%3A%22%2B49%202771%2087040%22%2C%22email%22%3A%22datenschutz%40ds-moos.de%22%2C%22web%22%3A%22https%3A%2F%2Fcovimedical.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2F15minutentest.de%2Fde%2Fde%2Fdatenschutz%22%2C%22https%3A%2F%2Fcovimedical.de%2Fdatenschutzvereinbarungen%22%2C%22https%3A%2F%2Fgithub.com%2Fdat …
> Add 'CoviMedical GmbH' (community contribution)

- companies/epicgames.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22epicgames%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22ads%22%2C%22commerce%22%2C%22entertainment%22%5D%2C%22name%22%3A%22Epic%20Games%20International%20S.%C3%A0%20r.l.%22%2C%22runs%22%3A%5B%22Fortnite%22%2C%22Epic%20Games%2C%20Inc.%22%2C%22Epic%20Games%20Store%22%2C%22Battle%20Breaker%22%2C%22Spyjinx%22%5D%2C%22address%22%3A%22Atrium%20Business%20Park%5Cn33%20rue%20du%20Puits%20Romain%5CnL-8070%20Bertrange%5CnLuxembourg%22%2C%22email%22%3A%22dpo%40epicgames.com%22%2C%22web%22%3A%22https%3A%2F%2Fwww.epicgames.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.epicgames.com%2Fsite%2Fen-US%2Fprivacypolicy%22%2C%22https%3A%2F%2Fgithub.com%2Fdat …
> Update 'Epic Games International S.à r.l.' (community contribution)

- companies/freenode-ltd.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22freenode-ltd%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5Bnull%5D%2C%22name%22%3A%22Freenode%20Ltd.%22%2C%22address%22%3A%22%3F%22%2C%22sources%22%3A%5B%22%3F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1129%22%5D%2C%22quality%22%3A%22verified%22%7D)**
> Add 'Freenode Ltd.' (community contribution)

- companies/personio-gmbh.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22personio-gmbh%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22finance%22%5D%2C%22name%22%3A%22Personio%20GmbH%22%2C%22address%22%3A%22Rundfunkplatz%204%5Cn80335%20M%C3%BCnchen%5Cn%22%2C%22phone%22%3A%22%2B49%2089%2012501005%22%2C%22email%22%3A%22datenschutz%40personio.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.personio.de%2Fdatenschutzerklaerung%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1147%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22quality%22%3A%22verified%22%7D)**
> Add 'Personio GmbH' (community contribution)

- companies/vimeo.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22vimeo%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22entertainment%22%5D%2C%22name%22%3A%22Vimeo%2C%20Inc.%22%2C%22address%22%3A%22555%20West%2018th%20Street%5CnNew%20York%5CnNY%2010011%5CnUnited%20States%20of%20America%22%2C%22email%22%3A%22privacy%40vimeo.com%22%2C%22web%22%3A%22https%3A%2F%2Fvimeo.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fvimeo.com%2Fprivacy%22%2C%22https%3A%2F%2Fvimeo.com%2Fterms%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1152%22%5D%2C%22request-language%22%3A%22en%22%2C%22quality%22%3A%22verified%22%7D)**
> Update 'Vimeo, Inc.' (community contribution)

- companies/services-totalenergies.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22services-totalenergies%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22utility%22%5D%2C%22name%22%3A%22TOTAL%20Deutschland%20GmbH%22%2C%22runs%22%3A%5B%22TotalEnergies%22%2C%22heizoel.totaleergies.com%22%2C%22ELAN%22%2C%22MINOL%22%2C%22ACCESS%22%5D%2C%22address%22%3A%22Jean-Monnet-Str.%202%5Cn10557%20Berlin%22%2C%22phone%22%3A%2208008682533%22%2C%22fax%22%3A%22%2B49%2030%2020278833%22%2C%22email%22%3A%22kundenservice%40totalenergies.com%22%2C%22web%22%3A%22https%3A%2F%2Fwww.services.totalenergies.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.services.totalenergies.de%2Fimpressum%22%2C%22https%3A%2F%2Fwww.services.totalenergies.de%2Fzentraler …
> Add 'TOTAL Deutschland GmbH' (community contribution)

- companies/encliso.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22encliso%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22commerce%22%5D%2C%22name%22%3A%22encliso%20GmbH%22%2C%22address%22%3A%22Schillerstra%C3%9Fe%203%5Cn33415%20Verl%22%2C%22phone%22%3A%22%2B49%205246%209359199%22%2C%22email%22%3A%22info%40encliso.de%22%2C%22web%22%3A%22http%3A%2F%2Fwww.encliso.de%22%2C%22sources%22%3A%5B%22Registernummer%3A%20HRB%209168%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1162%22%5D%2C%22quality%22%3A%22verified%22%7D)**
> Add 'encliso GmbH' (community contribution)

- templates/de/access-bundesjustizamt.txt
- templates/de/access-bundespolizei.txt
- templates/de/access-default.txt
- templates/de/access-drk-brandenburg-datenleck.txt
- templates/de/access-evangelische-kirche.txt
- templates/de/access-katholische-kirche.txt
- templates/de/access-lka-nds.txt
- templates/de/access-tracking.txt
- templates/en/access-default.txt
- templates/en/access-tracking.txt
In the subject literature, there is a bit of a divide concerning the
relationship between Art. 15(1) and (3) GDPR. Basically, those are the
two differing opinions:
1. The "The controller shall provide a copy of the personal data
undergoing processing." from Art. 15(3) GDPR mandates how, in
particular, to give the data subject "access to the personal data"
according to Art. 15(1) GDPR.
As such, a request according to Art. 15(1) GDPR includes a request
for a copy.
2. Art. 15(1) and (3) GDPR are separate rights. A data subject that
wants a copy of their data explicitly has to request that according
to Art. 15(3) GDPR.
We believe that by requesting "all personal data concerning me that
you have stored", as we did until now in our access template, it is
obvious that we are in fact requesting a …
> Clarify that we are requesting a copy in access templates (DE + EN)

- companies/paydirekt.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22paydirekt%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22finance%22%5D%2C%22name%22%3A%22paydirekt%20GmbH%22%2C%22runs%22%3A%5B%22giropay%22%5D%2C%22address%22%3A%22Hamburger%20Allee%2026%20%E2%80%93%2028%5Cn60486%20Frankfurt%5CnDeutschland%22%2C%22phone%22%3A%22%2B49%2069%202475382200%22%2C%22email%22%3A%22datenschutz%40paydirekt.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.paydirekt.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.paydirekt.de%2Fagb%2Findex.html%22%2C%22https%3A%2F%2Fwww.paydirekt.de%2Fimpressum%2Findex.html%22%2C%22https%3A%2F%2Fwww.giropay.de%2Frechtliches%2Fdatenschutzerklaerung%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfrage …
> Update 'paydirekt GmbH' (community contribution)

- companies/condenast.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22condenast%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22entertainment%22%2C%22ads%22%5D%2C%22name%22%3A%22Cond%C3%A9%20Nast%20Holdings%20Limited%22%2C%22address%22%3A%22c%2Fo%20Data%20Protection%20Officer%5CnThe%20Adelphi%2C%201-11%20John%20Adam%20Street%5CnLondon%2C%20WC2N%206HT%5CnEngland%22%2C%22email%22%3A%22dpo%40condenast.com%22%2C%22web%22%3A%22https%3A%2F%2Fwww.condenast.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.condenast.com%2Fprivacy-policy%23notice-to-residents-of-the-european-economic-area%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1166%22%5D%2C%22needs-id-document%22%3Afalse%2C%22suggested-transport …
> Add 'Condé Nast Holdings Limited' (community contribution)

- companies/runtastic.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22runtastic%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22name%22%3A%22runtastic%22%2C%22address%22%3A%22runtastic%20GmbH%5CnPluskaufstra%C3%9Fe%207%20%C2%B7%20Business%20Center%5Cn4061%20Pasching%20bei%20Linz%20%2F%20Austria%20%22%2C%22fax%22%3A%22%2B43%207229%2023327%22%2C%22email%22%3A%22office%40runtastic.com%22%2C%22web%22%3A%22https%3A%2F%2Fwww.runtastic.com%2Fen%2Fprivacy-policy%22%2C%22needs-id-document%22%3Afalse%2C%22suggested-transport-medium%22%3A%22email%22%2C%22comments%22%3A%5B%22Diese%20Firma%20nimmt%20sich%20unfassbare%2030%20Tage%20zum%20L%C3%B6schen%20eines%20Accounts.%22%5D%2C%22quality%22%3A%22verified%22%2C%22sources%22%3A%5B%22https%3A%2F%2F …
> Add 'runtastic' (community contribution)

- companies/qnniu.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22qnniu%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22health%22%5D%2C%22name%22%3A%22Shenzhen%20Qingniu%20Software%20Co.%2C%20Ltd.%22%2C%22runs%22%3A%5B%22Feelfit-Health%20Fitness%20Tool%22%2C%22Megafit%22%2C%22VOFIT%22%2C%22Runcobo%22%2C%22Tikfit-Health%20Fitness%20Tool%22%2C%22BF%20Scale%20Health%20Fitness%20Tool%22%2C%22Runcobo%20note%22%5D%2C%22address%22%3A%22Room%20201-202%2C%20No.49-1%5CnDabao%20Road%2C%20Bao'an%5CnDistrict%20Shenzhen%5CnCity%20GuangDong%5CnChina%22%2C%22phone%22%3A%22%2B86%20400%20998%202913%22%2C%22email%22%3A%22service%40qnniu.com%22%2C%22web%22%3A%22http%3A%2F%2Fwww.qnniu.com%2F%22%2C%22sources%22%3A%5B%22https%3A% …
> Add 'Shenzhen Qingniu Software Co., Ltd.' (community contribution)

- companies/voxpark.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22voxpark%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22name%22%3A%22voxpark%20GmbH%22%2C%22address%22%3A%22voxpark%20GmbH%5CnGro%C3%9Fbeerenstra%C3%9Fe%202-10%5Cn12107%20Berlin%22%2C%22phone%22%3A%22030206143723%22%2C%22fax%22%3A%22030700108394%22%2C%22email%22%3A%22datenschutz%40voxpark.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.voxpark.de%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.voxpark.de%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1170%22%5D%2C%22suggested-transport-medium%22%3A%22fax%22%2C%22quality%22%3A%22verified%22%7D)**
> Add 'voxpark GmbH' (community contribution)

- companies/rsggroup.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22rsggroup%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22name%22%3A%22RSG%20Group%22%2C%22runs%22%3A%5B%22McFit%22%2C%22John%20Reed%22%2C%22weitere%22%5D%2C%22address%22%3A%22RSG%20Group%20GmbH%5CnTannenberg%204%5Cn96132%20Schl%C3%BCsselfeld%22%2C%22web%22%3A%22https%3A%2F%2Frsggroup.com%2Fen%2Fimprint%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Frsggroup.com%2Fen%2Fimprint%2F%22%2C%22https%3A%2F%2Fwww.mcfit.com%2Fde%2Fueber-mcfitcom%2Fimpressum%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1177%22%5D%2C%22quality%22%3A%22verified%22%7D)**
> Add 'RSG Group' (community contribution)

- companies/lime.json
> Update Lime Electric Ireland Limited

- companies/phoenixcontact.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22phoenixcontact%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22commerce%22%5D%2C%22name%22%3A%22Phoenix%20Contact%22%2C%22address%22%3A%22Flachsmarktstr.%208%20%C2%B7%2032825%20Blomberg%20%C2%B7%20%22%2C%22phone%22%3A%22%2B49%205235%20312000%22%2C%22fax%22%3A%22%2B49%205235%20312999%22%2C%22email%22%3A%22info%40phoenixcontact.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.phoenixcontact.com%2F%22%2C%22sources%22%3A%5B%22Amtsgericht%20Lemgo%3A%20HRB%207008%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1161%22%5D%2C%22quality%22%3A%22verified%22%7D)**
> Add 'Phoenix Contact' (community contribution)

- companies/spreadshirt.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22spreadshirt%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22commerce%22%5D%2C%22name%22%3A%22Spreadshirt%22%2C%22address%22%3A%22sprd.net%20AG%5CnGiesserstr.%2027%5Cn04229%20Leipzig%5CnGermany%22%2C%22phone%22%3A%22%2B49%20341%20594005900%22%2C%22fax%22%3A%22%2B49%20341%20594005499%22%2C%22email%22%3A%22privacy%40spreadshirt.net%22%2C%22web%22%3A%22https%3A%2F%2Fwww.spreadshirt.net%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.spreadshirt.de%2Fdatenschutz-C3928%22%2C%22https%3A%2F%2Fwww.spreadshirt.de%2Fimpressum-C1338%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1184%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%2 …
> Add 'Spreadshirt' (community contribution)

- companies/torquato.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22torquato%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22name%22%3A%22Torquato%20AG%22%2C%22runs%22%3A%5B%22torquato.de%22%5D%2C%22address%22%3A%22Am%20Spakenberg%2045%5Cn21500%20Geesthacht%5CnDeutschland%22%2C%22web%22%3A%22https%3A%2F%2Fwww.torquato.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.torquato.de%2Fimpressum%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1151%22%5D%2C%22quality%22%3A%22verified%22%7D)**
> Add 'Torquato AG' (community contribution)

- companies/vonza.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22vonza%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22name%22%3A%22Vonza%20HQ%22%2C%22address%22%3A%2212600%20Deerfield%20Pkwy%2C%20Suite%20100%20USA%22%2C%22phone%22%3A%228886402951%22%2C%22email%22%3A%22info%40vonza.com%22%2C%22web%22%3A%22https%3A%2F%2Fvonza.com%2F%22%2C%22quality%22%3A%22verified%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1171%22%5D%7D)**
> Add 'Vonza HQ' (community contribution)

- companies/fakespot.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22fakespot%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22name%22%3A%22Fakespot%20Inc%22%2C%22address%22%3A%22110%20Wall%20Street%5CnSuite%202-028%5CnNew%20York%20NY%2010005%5CnUnited%20States%20of%20America%20%22%2C%22email%22%3A%22contact%40fakespot.com%22%2C%22web%22%3A%22https%3A%2F%2Fwww.fakespot.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.fakespot.com%2Fprivacy-policy%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1193%22%5D%2C%22required-elements%22%3A%5B%7B%22desc%22%3A%22Email%22%2C%22type%22%3A%22name%22%2C%22optional%22%3Afalse%7D%5D%2C%22quality%22%3A%22verified%22%7D)**
> Add 'Fakespot Inc' (community contribution)

- companies/cyon.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22cyon%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22telecommunication%22%2C%22commerce%22%5D%2C%22name%22%3A%22cyon%20GmbH%22%2C%22address%22%3A%22Brunng%C3%A4sslein%2012%5Cn4052%20Basel%5CnSwitzerland%22%2C%22email%22%3A%22privacy%40cyon.ch%22%2C%22web%22%3A%22https%3A%2F%2Fwww.cyon.ch%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.cyon.ch%2Flegal%2Fdatenschutzerklaerung%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1194%22%5D%2C%22required-elements%22%3A%5B%7B%22desc%22%3A%22Name%22%2C%22type%22%3A%22name%22%2C%22optional%22%3Afalse%7D%2C%7B%22desc%22%3A%22Email%22%2C%22type%22%3A%22email%22%2C%22optional%22%3Afalse%7D%5D% …
> Add 'cyon GmbH' (community contribution)

- companies/fitbit.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22fitbit%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22name%22%3A%22Fitbit%22%2C%22address%22%3A%22Fitbit%20International%20Limited%5CnAttn%3A%20Legal%20Department%20(Privacy%20Policy)%5Cn76%20Lower%20Baggot%20Street%5CnDublin%202%2C%20Ireland%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.fitbit.com%2Fglobal%2Fus%2Flegal%2Fprivacy-policy%23contact-us%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1197%22%5D%2C%22comments%22%3A%5B%22Email%3A%20data-protection-office%40fitbit.com%22%5D%2C%22quality%22%3A%22verified%22%7D)**
> Add 'Fitbit' (community contribution)

- companies/abstimmung21.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22abstimmung21%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22nonprofit%22%5D%2C%22name%22%3A%22%20%20ABSTIMMUNG21%20e.V.%22%2C%22address%22%3A%22c%2Fo%20datenschutz%20nord%20GmbH%5CnNiederlassung%20Berlin%5CnKurf%C3%BCrstendamm%20212%5Cn10719%20Berlin%5CnDeutschland%22%2C%22email%22%3A%22office%40datenschutz-nord.de%22%2C%22web%22%3A%22https%3A%2F%2Fabstimmung21.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fabstimmung21.de%2Fdatenschutzerklaerung%2F%22%2C%22https%3A%2F%2Fabstimmung21.de%2Fimpressum%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1215%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22quality%22%3A%22 …
> Add '  ABSTIMMUNG21 e.V.' (community contribution)

- companies/adhese.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22adhese%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22name%22%3A%22Adhese%22%2C%22address%22%3A%22Dulle-grietlaan%201%2F0001%5Cn9050%20Gentbrugge%20-%20Belgium%20%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.adhese.eu%2Fadheseanddata.html%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1198%22%5D%2C%22quality%22%3A%22verified%22%7D)**
> Add 'Adhese' (community contribution)

- companies/adikteev.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22adikteev%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22name%22%3A%22Adikteev%22%2C%22runs%22%3A%5B%22SA%20%26%20Adikteev%20Inc%22%5D%2C%22address%22%3A%22ADIKTEEV%20SA%5CnAttn%3A%20Legal%20Department%20%5Cn29%20rue%20des%20Pyramides%2C%2075001%20Paris%2C%20France%22%2C%22email%22%3A%22dpo%40adikteev.com%22%2C%22web%22%3A%22https%3A%2F%2Fwww.adikteev.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.adikteev.com%2Fprivacy%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1199%22%5D%2C%22quality%22%3A%22verified%22%7D)**
> Add 'Adikteev' (community contribution)

- companies/adkernel.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22adkernel%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22name%22%3A%22Adkernel%20%22%2C%22address%22%3A%2230%20Montgomery%20St%5CnSuite%20440%5CnJersey%20City%5CnNJ%2007302%22%2C%22phone%22%3A%22%2B1%20888%20654%208826%22%2C%22email%22%3A%22contact%40adkernel.com%22%2C%22web%22%3A%22https%3A%2F%2Fadkernel.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fadkernel.com%2Fprivacy-policy%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1200%22%5D%2C%22quality%22%3A%22verified%22%7D)**
> Add 'Adkernel ' (community contribution)

- companies/adludio-limited.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22adludio-limited%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22name%22%3A%22Adludio%20Limited%22%2C%22address%22%3A%2210c%20Warner%20Street%2C%5CnLondon%2C%5CnEC1R%205HA%2C%5CnUnited%20Kingdom%22%2C%22email%22%3A%22privacy%40adludio.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.adludio.com%2Ftermsandconditions%23privacy%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1201%22%5D%2C%22quality%22%3A%22verified%22%7D)**
> Add 'Adludio Limited' (community contribution)

- companies/treatwell-dach-gmbh.json
- companies/treatwell-dach.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22treatwell-dach-gmbh%22%2C%22relevant-countries%22%3A%5B%22de%22%2C%22at%22%2C%22ch%22%5D%2C%22categories%22%3A%5B%22health%22%5D%2C%22name%22%3A%22Treatwell%20DACH%20GmbH%22%2C%22runs%22%3A%5B%22www.treatwell.de%22%2C%22www.treatwell.com%22%5D%2C%22address%22%3A%22Greifswalder%20Str.%20212%2C%2010405%20Berlin%2C%20Deutschland%22%2C%22email%22%3A%22koenigkunde%40treatwell.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.treatwell.de%2Finfo%2Fdatenschutz%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1202%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22quality%22%3A%22verified%22%7D)**
> Add 'Treatwell DACH GmbH' (community contribution)

- companies/it-talents-de.json
- companies/it-talents.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22it-talents%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5Bnull%5D%2C%22name%22%3A%22Talentzeit%20GmbH%22%2C%22runs%22%3A%5B%22IT-Talents%22%5D%2C%22address%22%3A%22Johanneswerkstra%C3%9Fe%204%2C%5Cn33611%20Bielefeld%22%2C%22phone%22%3A%22%2B49%20521%2091173050%22%2C%22fax%22%3A%22%2B49%20521%2091173051%22%2C%22email%22%3A%22datenschutz%40it-talents.de%22%2C%22web%22%3A%22https%3A%2F%2Fit-talents.de%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fit-talents.de%2Fimpressum%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1203%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22quality%22%3A%22verified%22%7D)**
> Add 'Talentzeit GmbH' (community contribution)

- companies/quizlet.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22quizlet%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22school%22%5D%2C%22name%22%3A%22Quizlet%2C%20Inc.%22%2C%22address%22%3A%22501%202nd%20Street%2C%20Suite%20500%5CnSan%20Francisco%2C%20CA%2094107%20USA%22%2C%22phone%22%3A%22%2B1%20510%20495%206550%22%2C%22email%22%3A%22privacy-eu%40quizlet.com%22%2C%22web%22%3A%22https%3A%2F%2Fquizlet.com%22%2C%22required-elements%22%3A%5B%7B%22desc%22%3A%22Name%22%2C%22type%22%3A%22name%22%2C%22optional%22%3Afalse%7D%2C%7B%22desc%22%3A%22Email%22%2C%22type%22%3A%22email%22%2C%22optional%22%3Afalse%7D%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22quality%22%3A%22verified%22%2C%22sources%22%3A%5 …
> Add 'Quizlet, Inc.' (community contribution)

- companies/lichtblick.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22lichtblick%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22utility%22%5D%2C%22name%22%3A%22LichtBlick%22%2C%22address%22%3A%22Zirkusweg%206%5Cn20359%20Hamburg%22%2C%22phone%22%3A%22%2B49%2040%2080803030%22%2C%22email%22%3A%22info%40lichtblick.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.lichtblick.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.lichtblick.de%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1211%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22quality%22%3A%22verified%22%7D)**
> Add 'LichtBlick' (community contribution)

- companies/purovivo.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22purovivo%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22entertainment%22%5D%2C%22name%22%3A%22PuroVivo%22%2C%22address%22%3A%22Rudolst%C3%A4dter%20Stra%C3%9Fe%2039%5Cn07745%20Jena%22%2C%22email%22%3A%22service%40purovivo.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.purovivo.de%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.purovivo.de%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1212%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22quality%22%3A%22verified%22%7D)**
> Add 'PuroVivo' (community contribution)

- companies/avm.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22avm%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22telecommunication%22%5D%2C%22name%22%3A%22AVM%20Computersysteme%20Vertriebs%20GmbH%22%2C%22address%22%3A%22Alt-Moabit%2095%5Cn10559%20Berlin%5CnDeutschland%22%2C%22phone%22%3A%22%2B49%2030%20399760%22%2C%22fax%22%3A%22%2B49%2030%2039976299%22%2C%22email%22%3A%22datenschutz%40avm.de%22%2C%22web%22%3A%22https%3A%2F%2Favm.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Favm.de%2Fdatenschutz%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1214%22%5D%2C%22quality%22%3A%22verified%22%7D)**
> Add 'AVM Computersysteme Vertriebs GmbH' (community contribution)

- companies/fressnapf-tiernahrungs-gmbh.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22fressnapf-tiernahrungs-gmbh%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22commerce%22%5D%2C%22name%22%3A%22Fressnapf%20Tiernahrungs%20GmbH%22%2C%22address%22%3A%22Fressnapf%20Tiernahrungs%20GmbH%5CnWestpreu%C3%9Fenstr.%2032-38%5CnD-47809%20Krefeld%5Cn%22%2C%22phone%22%3A%22%2B49%202151%204115760%22%2C%22email%22%3A%22info%40fressnapf.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.fressnapf.de%2Fimpressum%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1216%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22comments%22%3A%5B%22Bitte%20%C3%BCberpr%C3%BCfen%20Sie%20meine%20Angaben%20auf%20Korrektheit%22%5D%2C%22qua …
> Add 'Fressnapf Tiernahrungs GmbH' (community contribution)

- companies/postcode-lotterie.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22postcode-lotterie%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22entertainment%22%5D%2C%22name%22%3A%22Postcode%20Lotterie%20DT%20gGmbH%22%2C%22address%22%3A%22Martin-Luther-Platz%2028%5Cn40212%20D%C3%BCsseldorf%22%2C%22phone%22%3A%220211%E2%80%93%20942838%2021%20%22%2C%22email%22%3A%22datenschutz%40postcode-lotterie.de%20%22%2C%22web%22%3A%22https%3A%2F%2Fwww.postcode-lotterie.de%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.postcode-lotterie.de%2Fdatenschutz%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1217%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22quality%22%3A%22verified%22%7D)**
> Add 'Postcode Lotterie DT gGmbH' (community contribution)

- companies/schneebaer-berlin.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22schneebaer-berlin%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22commerce%22%5D%2C%22name%22%3A%22Schneeb%C3%A4r%20Winterdienst%20und%20Stra%C3%9Fenreinigung%20e.K.%22%2C%22address%22%3A%22Wittestra%C3%9Fe%2046-48%5Cn13509%20Berlin%5CnGermany%22%2C%22phone%22%3A%22030-403%2003%20556%22%2C%22fax%22%3A%22030-403%2003%20557%22%2C%22email%22%3A%22info%40schneebaer-berlin.de%22%2C%22web%22%3A%22http%3A%2F%2Fwww.schneebaer-berlin.de%2F%22%2C%22quality%22%3A%22verified%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1219%22%5D%7D)**
> Add 'Schneebär Winterdienst und Straßenreinigung e.K.' (community contribution)

- .github/config.yml
Can you install the bot as well? :D
> Configure first contrib bot

- companies/dialog-versicherung.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22dialog-versicherung%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22insurance%22%5D%2C%22name%22%3A%22Dialog%20Versicherung%20AG%22%2C%22address%22%3A%22Adenauerring%207%5Cn81737%20M%C3%BCnchen%22%2C%22phone%22%3A%22089%205121-%206680%22%2C%22email%22%3A%22service%40dialog-versicherung.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.dialog-versicherung.de%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.dialog-versicherung.de%2Fdsgvo%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1237%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22quality%22%3A%22verified%22%7D)**
> Add 'Dialog Versicherung AG' (community contribution)

- companies/pin-ag.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22pin-ag%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22name%22%3A%22PIN%20AG%22%2C%22runs%22%3A%5B%22PIN%20Logistik%20GmbH%20und%20PIN%20IT%20GmbH%22%5D%2C%22address%22%3A%22Alt-%20Moabit%2091%5Cn10559%20Berlin%5CnGermany%22%2C%22phone%22%3A%22030%20577978-184%22%2C%22web%22%3A%22https%3A%2F%2Fwww.pin-ag.de%2Fdatenschutz%22%2C%22quality%22%3A%22verified%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1220%22%5D%7D)**
> Add 'PIN AG' (community contribution)

- companies/wageningen-university.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22wageningen-university%22%2C%22relevant-countries%22%3A%5B%22nl%22%5D%2C%22name%22%3A%22Wageningen%20University%22%2C%22runs%22%3A%5B%22Wageningen%20Universiteit%22%5D%2C%22address%22%3A%22Droevendaalsesteeg%204%2C%206708PB%20Wageningen%22%2C%22sources%22%3A%5B%22wur.nl%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1230%22%5D%2C%22quality%22%3A%22verified%22%7D)**
> Add 'Wageningen University' (community contribution)

- companies/fonoa.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22fonoa%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22finance%22%5D%2C%22name%22%3A%22Fonoa%20Technologies%20Limited%22%2C%22address%22%3A%22Ground%20Floor%2C%2071%20Lower%20Baggot%20Street%2C%20Co.%20Dublin%5Cn%5CnDublin%2C%20D02%20P593%2C%20Ireland%22%2C%22email%22%3A%22info%40fonoatech.com%22%2C%22web%22%3A%22https%3A%2F%2Fwww.fonoa.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.fonoa.com%2Fprivacy-notice%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1232%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22quality%22%3A%22verified%22%7D)**
> Add 'Fonoa Technologies Limited' (community contribution)

- companies/ammerlaender-versicherung.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22ammerlaender-versicherung%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22insurance%22%5D%2C%22name%22%3A%22Ammerl%C3%A4nder%20Versicherung%20VVaG%22%2C%22address%22%3A%22Bahnhofstra%C3%9Fe%208%5Cn26655%20Westerstede%22%2C%22phone%22%3A%2204488%20%E2%80%93%2053737%20%E2%80%93%200%22%2C%22fax%22%3A%2204488%20%E2%80%93%2053737%20%E2%80%93%20100%22%2C%22email%22%3A%22datenschutz%40ammerlaender-versicherung.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.ammerlaender-versicherung.de%2F%22%2C%22suggested-transport-medium%22%3A%22email%22%2C%22quality%22%3A%22verified%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1238% …
> Add 'Ammerländer Versicherung VVaG' (community contribution)

- companies/funkemedien.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22funkemedien%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22entertainment%22%5D%2C%22name%22%3A%22FUNKE%20Mediengruppe%20GmbH%20%26%20Co.%20KGaA%22%2C%22address%22%3A%22Jakob-Funke-Platz%201%5Cn45127%20Essen%22%2C%22phone%22%3A%220800%20%2F%2060%2060%20760%22%2C%22email%22%3A%22datenschutz%40funkemedien.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.funkemedien.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.funkemedien.de%2Fde%2Fdatenschutz%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1240%22%5D%2C%22quality%22%3A%22verified%22%7D)**
> Add 'FUNKE Mediengruppe GmbH & Co. KGaA' (community contribution)

- companies/ionos.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22ionos%22%2C%22relevant-countries%22%3A%5B%22at%22%2C%22de%22%5D%2C%22categories%22%3A%5B%22telecommunication%22%5D%2C%22name%22%3A%22IONOS%20SE%22%2C%22address%22%3A%22Elgendorfer%20Stra%C3%9Fe%2057%5Cn56410%20Montabaur%22%2C%22phone%22%3A%22%2B49%20721%201705522%22%2C%22email%22%3A%22%20info%40ionos.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.ionos.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.ionos.de%2Fimpressum%22%2C%22https%3A%2F%2Fwww.ionos.de%2Fterms-gtc%2Fterms-privacy%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1242%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22comments%22%3A%5B%22Empfohlenes%20Medium%20f%C3%BCr%20Anfragen%20a …
> Add 'IONOS SE' (community contribution)

- companies/dogado.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22dogado%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22telecommunication%22%5D%2C%22name%22%3A%22dogado%20GmbH%20%22%2C%22address%22%3A%22Antonio-Segni-Stra%C3%9Fe%2011%5CnD-44263%20Dortmund%20%22%2C%22phone%22%3A%22%2B49%20231%202866200%22%2C%22email%22%3A%22info%40dogado.de%20%22%2C%22web%22%3A%22https%3A%2F%2Fwww.dogado.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.dogado.de%2Flegal%2Fimpressum%22%2C%22https%3A%2F%2Fwww.dogado.de%2Flegal%2Fdatenschutz%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1243%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22quality%22%3A%22verified%22%7D)**
> Add 'dogado GmbH ' (community contribution)

- companies/willytel.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22willytel%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22telecommunication%22%5D%2C%22name%22%3A%22willy.tel%20GmbH%22%2C%22address%22%3A%22Hinschenfelder%20Stieg%206%5Cn22041%20Hamburg%22%2C%22phone%22%3A%22040%2F696963-0%22%2C%22fax%22%3A%22040%2F696963-63%22%2C%22email%22%3A%22info%40willytel.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.willytel.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.willytel.de%2Fdatenschutz%22%2C%22https%3A%2F%2Fwww.willytel.de%2Fimpressum%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1244%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22quality%22%3A%22verified%22%7D)**
> Add 'willy.tel GmbH' (community contribution)

- companies/db-dialog.json
- companies/dbdialog.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22dbdialog%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22travel%22%5D%2C%22name%22%3A%22DB%20Dialog%20GmbH%22%2C%22address%22%3A%22Salzufer%206%5Cn10587%20Berlin%22%2C%22phone%22%3A%22030%20755453-444%22%2C%22email%22%3A%22info%40dbdialog.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.dbdialog.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.dbdialog.de%2Fdb-dialog-de%2FDBD_impressum-655312%22%2C%22https%3A%2F%2Fwww.dbdialog.de%2Fdb-dialog-de%2FDBD_Datenschutz-655348%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1245%22%5D%2C%22suggested-transport-medium%22%3A%22letter%22%2C%22comments%22%3A%5B%22Insbesondere%20bei%20der%20Aus%C3%B …
> Add 'DB Dialog GmbH' (community contribution)

- companies/haftpflichtkasse.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22haftpflichtkasse%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22insurance%22%5D%2C%22name%22%3A%22Die%20Haftpflichtkasse%20VVaG%22%2C%22address%22%3A%22Darmst%C3%A4dter%20Str.%20103%5Cn64380%20Ro%C3%9Fdorf%22%2C%22phone%22%3A%220%2061%2054%20%2F%206%2001-0%22%2C%22fax%22%3A%220%2061%2054%20%2F%206%2001-22%2088%22%2C%22email%22%3A%22info%40haftpflichtkasse.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.haftpflichtkasse.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.haftpflichtkasse.de%2Funternehmen%2Fimpressum%22%2C%22https%3A%2F%2Fwww.haftpflichtkasse.de%2Funternehmen%2Fdatenschutz%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull% …
> Add 'Die Haftpflichtkasse VVaG' (community contribution)

- companies/karma-response.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22karma-response%22%2C%22relevant-countries%22%3A%5B%22it%22%2C%22es%22%5D%2C%22name%22%3A%22Karma%20Response%22%2C%22address%22%3A%22Carrer%20Breton%20de%20los%20Herreros%209%5Cn08012%20Barcelona%5CnSPAIN%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.phishingmails.de%2Fitalienische-spam-der-karma-response-sl-aus-barcelona%2F%22%2C%22https%3A%2F%2Fwww.ripe.net%2Fmembership%2Findices%2Fdata%2Fes.karma.html%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1248%22%5D%2C%22quality%22%3A%22verified%22%7D)**
> Add 'Karma Response' (community contribution)

- companies/topmedia.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22topmedia%22%2C%22relevant-countries%22%3A%5B%22nl%22%5D%2C%22categories%22%3A%5B%22commerce%22%5D%2C%22name%22%3A%22Topmedia%20B.V.%22%2C%22address%22%3A%22Nijverheidsweg-Noord%2081%5Cn3812%20PL%2C%20Amersfoort%2C%20Utrecht%5CnThe%20Netherlands%22%2C%22email%22%3A%22privacy%40topmedia.nl%22%2C%22web%22%3A%22https%3A%2F%2Fwww.topmedia.nl%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.topmedia.nl%2Fprivacy-policy%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1250%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22quality%22%3A%22verified%22%7D)**
> Add 'Topmedia B.V.' (community contribution)

- companies/webmart.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22webmart%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5Bnull%2Cnull%5D%2C%22name%22%3A%22Team%20Centric%20Software%20GmbH%20%26%20Co.%20KG%22%2C%22address%22%3A%22Averhoffstra%C3%9Fe%2017%5Cn22085%20Hamburg%22%2C%22phone%22%3A%22%2B49%2089%20215581319%22%2C%22email%22%3A%22webmaster%40webmart.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.webmart.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.webmart.de%2Fweb%2Fprivacy%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1252%22%5D%2C%22comments%22%3A%5B%22Datenschutzbeauftragter%5CnStefan%20Kramer%5CnFachenfelder%20Weg%2084%5Cn21220%20Seevetal%5CnE-Mail%3A%20%22%5D%2C%22quality%22%3A%22ve …
> Add 'Team Centric Software GmbH & Co. KG' (community contribution)

- companies/wdr.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22wdr%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22entertainment%22%5D%2C%22name%22%3A%22Westdeutscher%20Rundfunk%20K%C3%B6ln%22%2C%22runs%22%3A%5B%22https%3A%2F%2Fwww.sportschau.de%22%5D%2C%22address%22%3A%22Appellhofplatz%201%5Cn50667%20K%C3%B6ln%5CnDeutschland%22%2C%22phone%22%3A%22%2B49%20221%202204207%22%2C%22fax%22%3A%22%2B49%20221%202208533%22%2C%22email%22%3A%22datenschutz%40wdr.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww1.wdr.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww1.wdr.de%2Fhilfe%2Fdatenschutz102.html%22%2C%22http%3A%2F%2Fwww.ard.de%2Fkinder%2FDatenschutz%2F3436692%2Findex.html%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2 …
> Update 'Westdeutscher Rundfunk Köln' (community contribution)

- companies/schweinske-de.json
- companies/schweinske.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22schweinske%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22name%22%3A%22SCHWEINSKE%20FRANCHISE%20GMBH%22%2C%22address%22%3A%22Alsterufer%2037%5CnD-20354%20Hamburg%22%2C%22phone%22%3A%22%2B49%2040%2087877890%22%2C%22fax%22%3A%22%2B49%2040%20878778999%22%2C%22email%22%3A%22%20info%40schweinske.de%22%2C%22web%22%3A%22https%3A%2F%2Fschweinske.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fschweinske.de%2Fdatenschutz%22%2C%22https%3A%2F%2Fschweinske.de%2Fdatenschutz%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1262%22%5D%2C%22quality%22%3A%22verified%22%7D)**
> Add 'SCHWEINSKE FRANCHISE GMBH' (community contribution)

- companies/s-broker.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22s-broker%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22finance%22%5D%2C%22name%22%3A%22S%20Broker%20AG%20%26%20Co.%20KG%22%2C%22address%22%3A%22Carl-Bosch-Stra%C3%9Fe%2010%5Cn65203%20Wiesbaden%5CnDeutschland%22%2C%22phone%22%3A%22%2B49%20611%2020441911%22%2C%22email%22%3A%22datenschutz%40sbroker.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.sbroker.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.sbroker.de%2Fsbl%2Fhome%2Fds%22%2C%22https%3A%2F%2Fwww.sbroker.de%2Fsbl%2Fhome%2Fimpressum%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1268%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22comments%22%3A%5B%22Auch%20Sparkas …
> Update 'S Broker AG & Co. KG' (community contribution)

- companies/fyfeweb.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22fyfeweb%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22telecommunication%22%5D%2C%22name%22%3A%22FyfeWeb%20Ltd%22%2C%22address%22%3A%2244%20Ashfield%20Park%5CnWhickham%5CnNewcastle%20Upon%20Tyne%5CnNE16%204SQ%5CnUnited%20Kingdom%22%2C%22email%22%3A%22privacy%40fyfeweb.com%22%2C%22web%22%3A%22https%3A%2F%2Ffyfeweb.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Ffyfeweb.com%2Fdownloads%2Fpolicies%2Fprivacy-policy.pdf%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F897%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1277%22%5D%2C%22required-elements%22%3A%5B%7B%22desc%22%3A%22Name%22%2C%22type%22%3A%22name%22%7D%2 …
> Update 'FyfeWeb Ltd' (community contribution)

- companies/wikimedia-foundation.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22wikimedia-foundation%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22nonprofit%22%5D%2C%22name%22%3A%22Wikimedia%20Foundation%2C%20Inc.%22%2C%22runs%22%3A%5B%22Wikipedia%22%2C%22Mediawiki%22%2C%22Wikimedia%20Commons%22%2C%22Wikispecies%22%2C%22Wikilivres%22%2C%22Wikidata%22%2C%22Wikimania%22%2C%22Wikinews%22%2C%22Wikiquote%22%2C%22Wikiversity%22%2C%22Wikivoyage%22%2C%22Wiktionary%22%2C%22meta.wikimedia.org%22%5D%2C%22address%22%3A%221%20Montgomery%20Street%5CnSuite%201600%5CnSan%20Francisco%2C%20CA%2094104%5CnUnited%20States%20of%20America%22%2C%22phone%22%3A%22%2B1%20415%20839%206885%22%2C%22fax%22%3A%22%2B1%20415%20882%200495%22%2C%22email% …
> Update 'Wikimedia Foundation, Inc.' (community contribution)

- companies/google.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22google%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22ads%22%2C%22commerce%22%2C%22entertainment%22%2C%22finance%22%2C%22social%20media%22%2C%22telecommunication%22%5D%2C%22name%22%3A%22Google%20LLC%22%2C%22runs%22%3A%5B%22Google%20Commerce%20Ltd.%22%2C%22Google%20Payment%20Corp.%22%2C%22Google%20Dialer%20Inc.%22%2C%22Android%22%2C%22Android%20Auto%22%2C%22Google%20Calendar%22%2C%22Google%20Chrome%22%2C%22Chrome%20Web%20Store%22%2C%22Chromecast%22%2C%22Google%20Contacts%22%2C%22Google%20Docs%22%2C%22Google%20Drive%22%2C%22Google%20Earth%22%2C%22Google%20Finance%22%2C%22Google%20Forms%22%2C%22Gboard%22%2C%22Gmail%22%2C%22Google%20Alerts%22%2C …
> Update 'Google LLC' (community contribution)

- companies/werbeartikel-copex.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22werbeartikel-copex%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22name%22%3A%22COPEX%20GmbH%22%2C%22address%22%3A%22Wichmannstr.%2027%5Cn30519%20Hannover%22%2C%22phone%22%3A%22%2B49%20511%2012359580%22%2C%22fax%22%3A%22%2B49%20511%20123595888%22%2C%22email%22%3A%22info%40werbeartikel-copex.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.werbeartikel-copex.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.werbeartikel-copex.de%2Fimpressum-38fc1e2a-4d57-5bbe-a69e-b5712285bb32.html%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1261%22%5D%2C%22quality%22%3A%22verified%22%7D)**
> Add 'COPEX GmbH' (community contribution)

- companies/miniatur-wunderland.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22miniatur-wunderland%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22entertainment%22%5D%2C%22name%22%3A%22Miniatur%20Wunderland%20Hamburg%20GmbH%22%2C%22runs%22%3A%5B%22http%3A%2F%2Fwww.knuffingen.de%22%5D%2C%22address%22%3A%22Kehrwieder%202%5CnBlock%20D%5Cn20457%20Hamburg%22%2C%22email%22%3A%22datenschutz%40miniatur-wunderland.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.miniatur-wunderland.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.miniatur-wunderland.de%2Fservice%2Fdatenschutz%2F%22%2C%22https%3A%2F%2Fwww.knuffingen.de%2Fdatenschutz%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1281%22%5D%2C%22quality%22%3A%22verified …
> Add 'Miniatur Wunderland Hamburg GmbH' (community contribution)

- companies/coca-cola-deutschland.json
- companies/coca-cola-fr.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22coca-cola-deutschland%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5Bnull%5D%2C%22name%22%3A%22NV%20Coca%E2%80%91Cola%20Services%20SA%22%2C%22runs%22%3A%5B%22https%3A%2F%2Fwww.coca-cola.de%22%5D%2C%22address%22%3A%22Chauss%C3%A9e%20de%20Mons%201424%5Cn1070%20Br%C3%BCssel%22%2C%22web%22%3A%22https%3A%2F%2Fwww.coca-cola-deutschland.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.coca-cola-deutschland.de%2Fdatenschutz%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1279%22%5D%2C%22comments%22%3A%5B%22Es%20ist%20davon%20auszugehen%2C%20dass%20der%20Anbieter%20zahlreiche%20weitere%20Webangebote%20betreibt.%22%5D%2C%22quality%22%3A%22 …
> Add 'NV Coca‑Cola Services SA' (community contribution)

- companies/seitwert.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22seitwert%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22name%22%3A%22Seitwert%20GmbH%22%2C%22address%22%3A%22Siegburger%20Stra%C3%9Fe%20215%5Cn50679%20K%C3%B6ln%5CnDeutschland%22%2C%22phone%22%3A%22%2B49%20221%20992020%22%2C%22email%22%3A%22info%40seitwert.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.seitwert.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.seitwert.de%2Fdatenschutz%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1264%22%5D%2C%22quality%22%3A%22verified%22%7D)**
> Add 'Seitwert GmbH' (community contribution)

- companies/world-of-smilies.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22world-of-smilies%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22name%22%3A%22World-of-Smilies%22%2C%22address%22%3A%22Sebastian%20Messerich%5CnHerrlichkeit%202%2C%2027283%20Verden%20%2F%20Aller%22%2C%22email%22%3A%22webmaster%40world-of-smilies.com%22%2C%22web%22%3A%22https%3A%2F%2Fwww.world-of-smilies.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.world-of-smilies.com%2Fimpressum.htm%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1266%22%5D%2C%22comments%22%3A%5Bnull%5D%2C%22quality%22%3A%22verified%22%7D)**
> Add 'World-of-Smilies' (community contribution)

- companies/nokia.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22nokia%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22telecommunication%22%5D%2C%22name%22%3A%22Nokia%20Corporation%22%2C%22address%22%3A%22Karakaari%207%5CnP.O.%20Box%20226%5CnFI-00045%20Nokia%20Group%5CnFinland%22%2C%22web%22%3A%22https%3A%2F%2Fwww.nokia.com%2Fde_int%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.nokia.com%2Fde_int%2Fprivacy%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1258%22%5D%2C%22comments%22%3A%5B%22Es%20ist%20keine%20Emailadresse%20angegeben.%20Das%20Kontaktformular%20ist%20auf%201000%20Zeichen%20begrenzt.%20Der%20Mustertext%20mus%20drastisch%20gek%C3%BCrzt%20werden.%20Die%20Webseite%20ist%20nic …
> Add 'Nokia Corporation' (community contribution)

- companies/simplify.json
- companies/vnr-verlag.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22simplify%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22school%22%2Cnull%5D%2C%22name%22%3A%22VNR%20Verlag%20f%C3%BCr%20die%20Deutsche%20Wirtschaft%20AG%22%2C%22address%22%3A%22Theodor-Heuss-Str.%202-4%5Cn53177%20Bonn%22%2C%22phone%22%3A%22%2B49%20228%20955066004%22%2C%22email%22%3A%22datenschutzbeauftragter%40vnr.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.simplify.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.simplify.de%2Fservice-rechtliches%2Fdatenschutz%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1251%22%5D%2C%22comments%22%3A%5B%22Verlag%20betreibt%20vernutlich%20noch%20weitere%20Angebote%20neben%20Sympily.%22%5D%2C% …
> Add 'VNR Verlag für die Deutsche Wirtschaft AG' (community contribution)

- companies/orf.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22orf%22%2C%22relevant-countries%22%3A%5B%22at%22%5D%2C%22name%22%3A%22%C3%96sterreichischen%20Rundfunk%20(ORF)%22%2C%22address%22%3A%22W%C3%BCrzburggasse%2030%5Cn1136%20Wien%5Cn%5Cn%22%2C%22email%22%3A%22datenschutz%40orf.at%22%2C%22web%22%3A%22https%3A%2F%2Fwww.orf.at%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.orf.at%2Fstories%2Fdatenschutz%2F%22%2C%22https%3A%2F%2Fwww.orf.at%2Fstories%2Fdatenschutz-rechte%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1273%22%5D%2C%22quality%22%3A%22verified%22%7D)**
> Add 'Österreichischer Rundfunk (ORF)' (community contribution)

- companies/jurpc-de.json
- companies/jurpc.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22jurpc%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22name%22%3A%22JurPC%22%2C%22address%22%3A%22Redaktion%20JurPC%5CnPatrickstra%C3%9Fe%2043%5Cn65191%20Wiesbaden%22%2C%22fax%22%3A%22%2B49%20611%209578228%22%2C%22email%22%3A%22mail%40jurpc.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.jurpc.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.jurpc.de%2Fwp%2Fdatenschutz%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1270%22%5D%2C%22quality%22%3A%22verified%22%7D)**
> Add 'JurPC' (community contribution)

- companies/caravan-owandner.json
**[Edit](https://company-json.netlify.com/#!doc=%7B%22slug%22%3A%22caravan-owandner%22%2C%22relevant-countries%22%3A%5B%22de%22%2C%22at%22%2C%22ch%22%2C%22it%22%2C%22fr%22%5D%2C%22categories%22%3A%5B%22travel%22%5D%2C%22name%22%3A%22Caravan%20Center%20J%C3%BCrgen%20Owandner%20e.K.%22%2C%22address%22%3A%22Caravan%20Center%20J%C3%BCrgen%20Owandner%20e.K.%5CnHerr%20J%C3%BCrgen%20Owandner%5CnHermann%20Neuner%20Str.%208%5Cn88299%20Leutkirch%22%2C%22phone%22%3A%2207561%2F9852780%22%2C%22fax%22%3A%2207561%2F9852788%22%2C%22email%22%3A%22cco-onlineshop%40gmx.de%22%2C%22web%22%3A%22https%3A%2F%2Fcaravan-owandner.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fcaravan-owandner.de%2Fdatenschutz%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2 …
> Add 'Caravan Center Jürgen Owandner e.K.' (community contribution)

- companies/dpunkt-de.json
- companies/dpunkt.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22dpunkt%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5Bnull%5D%2C%22name%22%3A%22dpunkt.verlag%20GmbH%22%2C%22address%22%3A%22Wieblinger%20Weg%2017%5Cn69123%20Heidelberg%22%2C%22phone%22%3A%22%2B49%206221%2014830%22%2C%22fax%22%3A%22%2B49%206221%20148399%22%2C%22email%22%3A%22datenschutz%40dpunkt.de%22%2C%22web%22%3A%22https%3A%2F%2Fdpunkt.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fdpunkt.de%2Fdatenschutzerklaerung%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1269%22%5D%2C%22quality%22%3A%22verified%22%7D)**
> Add 'dpunkt.verlag GmbH' (community contribution)

- companies/versandhaus-jung.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22versandhaus-jung%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22commerce%22%5D%2C%22name%22%3A%22Karlheinz%20Jung%20GmbH%22%2C%22runs%22%3A%5B%22Versandhaus%20Jung%22%5D%2C%22address%22%3A%22Remchinger%20Stra%C3%9Fe%201%5CnD%20-%2075196%20Remchingen%5Cn%5Cn%22%2C%22phone%22%3A%22%2B49%207232%2036540%22%2C%22fax%22%3A%22%2B49%207232%20365444%22%2C%22email%22%3A%22an%40versandhaus-jung.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.versandhaus-jung.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.versandhaus-jung.de%2FDatenschutz%22%2C%22https%3A%2F%2Fwww.versandhaus-jung.de%2FImpressum%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F …
> Add 'Karlheinz Jung GmbH' (community contribution)

- companies/eclipse-software.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22eclipse-software%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5Bnull%5D%2C%22name%22%3A%22Andreas%20Kollmer%22%2C%22runs%22%3A%5B%22https%3A%2F%2Fwww.neuverlieben.com%22%5D%2C%22address%22%3A%22Azuero%20Business%20Center%5CnSuite%20456%5CnAvenida%20Perez%20Chitre%5Cn0601-00395%20Panama%22%2C%22email%22%3A%22mail%40neuverlieben.com%22%2C%22web%22%3A%22http%3A%2F%2Fwww.eclipse-software.net%22%2C%22sources%22%3A%5B%22http%3A%2F%2Fwww.eclipse-software.net%22%2C%22https%3A%2F%2Fwww.neuverlieben.com%2Fimpressum.php%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1289%22%5D%2C%22comments%22%3A%5B%22Weitere%20Webseiten%20im%20Angebot%2C …
> Add 'Andreas Kollmer' (community contribution)

- companies/german-medical.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22german-medical%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22name%22%3A%22Fairpreis%20GmbH%22%2C%22runs%22%3A%5B%22German%20Medical%22%5D%2C%22address%22%3A%22Fairpreis%20GmbH%5CnKruppstra%C3%9Fe%207%5Cn47475%20Kamp-Lintfort%22%2C%22phone%22%3A%22%2B49%201573%203144515%22%2C%22email%22%3A%22thiel%40fairpreis-gmbh.de%22%2C%22web%22%3A%22https%3A%2F%2Fgerman-medical.nrw%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fgerman-medical.nrw%2Fdatenschutz%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1257%22%5D%2C%22quality%22%3A%22verified%22%7D)**
> Add 'Fairpreis GmbH' (community contribution)

- companies/psd-nuernberg.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22psd-nuernberg%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22finance%22%5D%2C%22name%22%3A%22PSD%20Bank%20N%C3%BCrnberg%20eG%22%2C%22address%22%3A%22Willy-Brandt-Platz%208%5Cn90402%20N%C3%BCrnberg%20%22%2C%22email%22%3A%22info%40psd-nuernberg.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.psd-nuernberg.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.psd-nuernberg.de%2Fservice%2Frechtliche-hinweise%2Fdatenschutzhinweis.html%22%2C%22https%3A%2F%2Fwww.psd-nuernberg.de%2Fservice%2Frechtliche-hinweise%2Fimpressum.html%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1295%22%5D%2C%22suggested-transport-medium%22%3A%22letter%22%2C%22qualit …
> Add 'PSD Bank Nürnberg eG' (community contribution)

- companies/rescuetime.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22rescuetime%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22entertainment%22%5D%2C%22name%22%3A%22RescueTime%22%2C%22phone%22%3A%22888-215-8635%22%2C%22email%22%3A%22dpo%40rescuetime.com%22%2C%22web%22%3A%22https%3A%2F%2Fwww.rescuetime.com%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fblog.rescuetime.com%2Fpersonal-data-gdpr%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1259%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22quality%22%3A%22verified%22%7D)**
> Add 'RescueTime' (community contribution)

- companies/winfuture.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22winfuture%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22name%22%3A%22WinFuture.de%22%2C%22address%22%3A%22Sebastian%20Kuhbach%5CnDudenstr.%2010%5Cn10965%20Berlin%5Cn%22%2C%22phone%22%3A%22%2B49%2030%2027908360%22%2C%22email%22%3A%22sk%40winfuture.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.winfuture.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.winfuture.de%2Fimpressum%22%2C%22https%3A%2F%2Fwww.winfuture.de%2Fimpressum%23datenschutz%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1265%22%5D%2C%22quality%22%3A%22verified%22%7D)**
> Add 'WinFuture.de' (community contribution)

- companies/feil-ra.json
- companies/recht-freundlich.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22recht-freundlich%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5Bnull%5D%2C%22name%22%3A%22Feil%20Rechtsanwaltsgesellschaft%20mbH%22%2C%22address%22%3A%22D%C3%B6hrbruch%2062%5Cn30559%5CnHanover%20%5Cn%5Cn%22%2C%22phone%22%3A%22%2B49%20511%204739060%22%2C%22email%22%3A%22kanzlei%40recht-freundlich.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.recht-freundlich.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.recht-freundlich.de%2Fdatenschutz%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1267%22%5D%2C%22quality%22%3A%22verified%22%7D)**
> Add 'Feil Rechtsanwaltsgesellschaft mbH' (community contribution)

- companies/delticom.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22delticom%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22commerce%22%5D%2C%22name%22%3A%22Delticom%20AG%22%2C%22runs%22%3A%5B%22Reifen-Online-Shop%20ReifenDirekt.de%22%2C%22Motorradreifen-Online-Shop%20MotorradreifenDirekt.de%22%2C%22Reifen-Testportal%20Reifentest.com%22%2C%22Komplettr%C3%A4der-Online-Shop%20Komplettraeder24.de%22%5D%2C%22address%22%3A%22Br%C3%BChlstra%C3%9Fe%2011%5Cn30169%20Hannover%5CnDeutschland%22%2C%22phone%22%3A%22%2B49%20511%2093634960%22%2C%22fax%22%3A%22%2B49%20511%2087989071%22%2C%22email%22%3A%22datenschutz%40delti.com%22%2C%22web%22%3A%22https%3A%2F%2Fwww.delti.com%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.re …
> Update 'Delticom AG' (community contribution)

- companies/accelevents.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22accelevents%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22school%22%2C%22utility%22%2C%22telecommunication%22%5D%2C%22name%22%3A%22Accelevents%22%2C%22address%22%3A%2210%20Post%20Office%20Sq%20Ste%20800%5CnBoston%20%E2%80%8B%2C%20MA%2C%2002109-4603%5CnUnited%20States%22%2C%22phone%22%3A%22857-254-8035%22%2C%22email%22%3A%22%20info%40accelevents.com%22%2C%22web%22%3A%22https%3A%2F%2Faccelevents.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.accelevents.com%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1278%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22quality%22%3A%22verified%22%7D)**
> Add 'Accelevents' (community contribution)

- companies/dtv-verlag.json
- companies/dtv.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22dtv%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22name%22%3A%22dtv%20Verlagsgesellschaft%20mbH%20%26%20Co.%20KG%22%2C%22address%22%3A%22Tumblingerstra%C3%9Fe%2021%5Cn80337%20M%C3%BCnchen%22%2C%22email%22%3A%22datenschutz%40dtv.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.dtv.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.dtv.de%2Fdatenschutz%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1274%22%5D%2C%22quality%22%3A%22verified%22%7D)**
> Add 'dtv Verlagsgesellschaft mbH & Co. KG' (community contribution)

- companies/digitalo.json
> feat: add digitalo

- companies/chefkoch-gmbh.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22chefkoch-gmbh%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22name%22%3A%22Chefkoch%20GmbH%22%2C%22address%22%3A%22Rheinwerk%203%5CnJoseph-Schumpeter-Allee%2033%5Cn53227%20Bonn%22%2C%22phone%22%3A%220228%2029977%20400%22%2C%22fax%22%3A%220228%2029977%20499%22%2C%22email%22%3A%22datenschutz%40chefkoch.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.chefkoch.de%2Fmagazin%2Fdatenschutz.html%22%2C%22https%3A%2F%2Fwww.chefkoch.de%2Fimpressum.php%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1344%22%5D%2C%22quality%22%3A%22verified%22%7D)**
> Add 'Chefkoch GmbH' (community contribution)

- companies/hoeffner.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22hoeffner%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22commerce%22%5D%2C%22name%22%3A%22H%C3%B6ffner%20Online%20GmbH%20%26%20Co.%20KG%22%2C%22address%22%3A%22Am%20Rondell%201%5Cn12529%20Sch%C3%B6nefeld%22%2C%22phone%22%3A%22%2B49%20(0)30%2037444%20-02%20%20und%20%2B49%20(0)39205%2061-333%20%22%2C%22fax%22%3A%22%2B49%2030%20374448700%22%2C%22email%22%3A%22%20onlineservice%40hoeffner.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.hoeffner.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.hoeffner.de%2Fimpressum%22%2C%22https%3A%2F%2Fwww.hoeffner.de%2Fdatenschutz%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1297%22%5D%2C%22quality%2 …
> Add 'Höffner Online GmbH & Co. KG' (community contribution)

- companies/porkbun.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22porkbun%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22telecommunication%22%5D%2C%22name%22%3A%22Porkbun%22%2C%22address%22%3A%2221370%20SW%20Langer%20Farms%20Parkway%2C%20Suite%20142-429%5CnSherwood%2C%20OR%2097140%2C%20US%22%2C%22email%22%3A%22abuse%40porkbun.com%22%2C%22web%22%3A%22https%3A%2F%2Fporkbun.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fporkbun.com%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1324%22%5D%2C%22required-elements%22%3A%5B%7B%22desc%22%3A%22Account%20E-Mail%20Address%22%2C%22type%22%3A%22email%22%2C%22optional%22%3Afalse%7D%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22quality%22%3A%22 …
> Add 'Porkbun' (community contribution)

- companies/tvinfo.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22tvinfo%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22entertainment%22%5D%2C%22name%22%3A%22TVinfo%20Internet%20GmbH%22%2C%22address%22%3A%22Kronprinzenstr.%2049%5Cn40217%20D%C3%BCsseldorf%22%2C%22phone%22%3A%22%2B49%20211%2097262990%22%2C%22fax%22%3A%22%2B49%20211%2097262999%22%2C%22email%22%3A%22support%40tvinfo.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.tvinfo.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.tvinfo.de%2Fimpressum%22%2C%22https%3A%2F%2Fwww.tvinfo.de%2Fdatenschutz%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1325%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22quality%22%3A%22verified%22%7D)**
> Add 'TVinfo Internet GmbH' (community contribution)

- companies/haspa.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22haspa%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22finance%22%5D%2C%22name%22%3A%22Hamburger%20Sparkasse%20AG%22%2C%22address%22%3A%22Ecke%20Adolphsplatz%20%2F%20Gr.%20Burstah%5Cn20457%20Hamburg%22%2C%22email%22%3A%22haspa%40haspa.de%22%2C%22web%22%3A%22https%3A%2F%2Fhaspa.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.haspa.de%2Fde%2Fhome%2Ffooter%2Fimpressum.html%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1304%22%5D%2C%22quality%22%3A%22verified%22%7D)**
> Add 'Hamburger Sparkasse AG' (community contribution)

- companies/contentfleet.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22contentfleet%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22name%22%3A%22Content%20Fleet%20GmbH%22%2C%22runs%22%3A%5B%22einfachtierisch.de%22%5D%2C%22address%22%3A%22Kehrwieder%208%5Cn20457%20Hamburg%22%2C%22email%22%3A%22datenschutz%40contentfleet.com%22%2C%22web%22%3A%22https%3A%2F%2Fwww.contentfleet.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Feinfachtierisch.de%2Fp%2Fimpressum%22%2C%22https%3A%2F%2Feinfachtierisch.de%2Fp%2Fdatenschutz%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1340%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22quality%22%3A%22verified%22%7D)**
> Add 'Content Fleet GmbH' (community contribution)

- companies/moebel-kraft.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22moebel-kraft%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22commerce%22%5D%2C%22name%22%3A%22M%C3%B6bel-Kraft%20Online%20GmbH%20%26%20Co.%20KG%22%2C%22address%22%3A%22Am%20Rondell%201%5Cn12529%20Sch%C3%B6nefeld%20%22%2C%22phone%22%3A%2249%20(0)4551%20%2F%2050%20-1%22%2C%22email%22%3A%22onlineservice%40moebel-kraft.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.moebel-kraft.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.moebel-kraft.de%2Fimpressum%22%2C%22https%3A%2F%2Fwww.moebel-kraft.de%2Fdatenschutz%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1298%22%5D%2C%22quality%22%3A%22verified%22%7D)**
> Add 'Möbel-Kraft Online GmbH & Co. KG' (community contribution)

- companies/nic-at-gmbh.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22nic-at-gmbh%22%2C%22relevant-countries%22%3A%5B%22at%22%5D%2C%22categories%22%3A%5B%22telecommunication%22%5D%2C%22name%22%3A%22nic.at%20GmbH%22%2C%22address%22%3A%22Jakob-Haringer-Stra%C3%9Fe%208%2FV%5Cn5020%20Salzburg%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.nic.at%2Fde%2Fimpressum%22%2C%22https%3A%2F%2Fwww.nic.at%2Fde%2Fwissenswertes%2Frechtliche-hintergruende%2Fdatenschutzerklaerung%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1305%22%5D%2C%22quality%22%3A%22verified%22%7D)**
> Add 'nic.at GmbH' (community contribution)

- companies/webgo-gmbh.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22webgo-gmbh%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22name%22%3A%22webgo%20GmbH%22%2C%22address%22%3A%22Heidenkampsweg%2081%5Cn20097%20Hamburg%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.webgo.de%2Fimpressum%2F%22%2C%22https%3A%2F%2Fwww.webgo.de%2Fdatenschutz%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1309%22%5D%2C%22quality%22%3A%22verified%22%7D)**
> Add 'webgo GmbH' (community contribution)

- companies/cameo.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22cameo%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22entertainment%22%5D%2C%22name%22%3A%22Baron%20App%2C%20Inc.%22%2C%22runs%22%3A%5B%22Cameo%22%5D%2C%22address%22%3A%222045%20West%20Grand%20Avenue%2C%20Suite%20B%5CnPMB%2071534%5CnChicago%20IL%2060612-1577%5CnUnited%20States%20of%20America%22%2C%22phone%22%3A%22%2B1%20800%20243%201739%22%2C%22email%22%3A%22dataprotection%40cameo.com%22%2C%22web%22%3A%22https%3A%2F%2Fwww.cameo.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.cameo.com%2Fprivacy%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1379%22%5D%2C%22required-elements%22%3A%5B%7B%22desc%22%3A%22Email%22%2C%22type%22%3 …
> Add 'Baron App, Inc.' (community contribution)

- companies/kmcomputer.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22kmcomputer%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22commerce%22%5D%2C%22name%22%3A%22K%26M%20Computer%20GmbH%20%26%20Co.KG%22%2C%22address%22%3A%22Nordendstra%C3%9Fe%2023%5Cn80801%20M%C3%BCnchen%5CnDeutschland%22%2C%22email%22%3A%22datenschutz%40kmcomputer.de%22%2C%22web%22%3A%22http%3A%2F%2Fwww.kmcomputer.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.kmcomputer.de%2Fcustom%2Findex%2FsCustom%2F79%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1351%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22quality%22%3A%22verified%22%7D)**
> Add 'K&M Computer GmbH & Co.KG' (community contribution)

- companies/ratp.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22ratp%22%2C%22relevant-countries%22%3A%5B%22fr%22%5D%2C%22categories%22%3A%5B%22travel%22%5D%2C%22name%22%3A%22RATP%22%2C%22address%22%3A%22D%C3%A9l%C3%A9gu%C3%A9%20%C3%A0%20la%20protection%20des%20donn%C3%A9es%20de%20la%20RATP%2C%20185%20rue%20de%20Bercy%2C%20LT73%2C%2075012%20Paris%22%2C%22email%22%3A%22protection-donnees%40ratp.fr%22%2C%22web%22%3A%22https%3A%2F%2Fratp.fr%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.ratp.fr%2Fen%2Fratp-general-privacy-policy%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1373%22%5D%2C%22required-elements%22%3A%5B%7B%22desc%22%3A%22Name%22%2C%22type%22%3A%22name%22%2C%22optional%22%3Afalse%7D%2C%7B%22desc%22%3A%22Ema …
> Add 'RATP' (community contribution)

- companies/deka.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22deka%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22finance%22%5D%2C%22name%22%3A%22DekaBank%20-%20Deutsche%20Girozentrale%22%2C%22runs%22%3A%5Bnull%5D%2C%22address%22%3A%22Mainzer%20Landstra%C3%9Fe%2016%5Cn60325%20Frankfurt%20am%20Main%22%2C%22email%22%3A%22datenschutz%40deka.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.deka.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.deka.de%2Fprivatkunden%2Fimpressum%22%2C%22https%3A%2F%2Fwww.deka.de%2Fprivatkunden%2Fdatenschutz%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1377%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22quality%22%3A%22verified%22%7D)**
> Add 'DekaBank - Deutsche Girozentrale' (community contribution)

- companies/cogora.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22cogora%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22ads%22%2C%22health%22%5D%2C%22name%22%3A%22Cogora%20Group%20Ltd.%22%2C%22address%22%3A%22Cogora%20Group%20Limited%5Cn140%20London%20Wall%5CnLondon%2C%20EC2Y%205DN%5CnUnited%20Kingdom%22%2C%22phone%22%3A%22%2B44%2020%207214%200500%22%2C%22email%22%3A%22data%40cogora.com%22%2C%22web%22%3A%22https%3A%2F%2Fwww.cogora.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.cogora.com%2Fprivacy-policy%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1349%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22quality%22%3A%22verified%22%7D)**
> Add 'Cogora Group Ltd.' (community contribution)

- companies/mailhardener.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22mailhardener%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22name%22%3A%22Mailhardener%22%2C%22address%22%3A%22Caballero%20Fabriek%20-%20unit%2018%5CnThe%20Hague%5CnNetherlands%22%2C%22email%22%3A%22privacy%40mailhardener.com%22%2C%22web%22%3A%22https%3A%2F%2Fwww.mailhardener.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.mailhardener.com%2Fprivacy-statement%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1380%22%5D%2C%22required-elements%22%3A%5B%7B%22desc%22%3A%22Email%22%2C%22type%22%3A%22name%22%2C%22optional%22%3Afalse%7D%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22quality%22%3A%22verified%22%7D)**
> Add 'Mailhardener' (community contribution)

- companies/report-uri.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22report-uri%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22name%22%3A%22Report-URI%20Ltd%22%2C%22address%22%3A%2222%20Shireburn%20Avenue%5CnClitheroe%5CnLancashire%5CnBB7%202PN%5CnUnited%20Kingdom%22%2C%22email%22%3A%22dpa%40report-uri.com%22%2C%22web%22%3A%22https%3A%2F%2Freport-uri.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Ffind-and-update.company-information.service.gov.uk%2Fcompany%2F10943557%22%2C%22https%3A%2F%2Fcdn.report-uri.com%2Fpdf%2FReport%2520URI%2520-%2520DPA%2520(2v0).pdf%22%2C%22https%3A%2F%2Fcdn.report-uri.com%2Fpdf%2FReport%2520URI%2520-%2520Data%2520Protection%2520(0v4).pdf%22%2C%22https%3A%2F%2Freport-uri.com%2Fhome%2Fprivacy_policy%22%2C%22h …
> Add 'Report-URI Ltd' (community contribution)

- companies/clockwise-inc.json
- companies/getclockwise.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22getclockwise%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22utility%22%5D%2C%22name%22%3A%22Clockwise%20Inc%22%2C%22address%22%3A%222021%20Fillmore%20St%2C%20%23126%2C%20San%20Francisco%2C%20CA%2094115%22%2C%22phone%22%3A%22888-720-9788%22%2C%22email%22%3A%22support%40getclockwise.com%22%2C%22web%22%3A%22https%3A%2F%2Fwww.getclockwise.com%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.getclockwise.com%2Fprivacy%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1383%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22quality%22%3A%22verified%22%7D)**
> Add 'Clockwise Inc' (community contribution)

- companies/bbbank.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22bbbank%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22finance%22%5D%2C%22name%22%3A%22BBBank%20eG%22%2C%22address%22%3A%22Herrenstra%C3%9Fe%202-10%5Cn76133%20Karlsruhe%22%2C%22phone%22%3A%2207%2021%20141-0%22%2C%22fax%22%3A%2207%2021%20141-497%22%2C%22email%22%3A%22info%40bbbank.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.bbbank.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.bbbank.de%2Fservice%2Fdatenschutz.html%22%2C%22https%3A%2F%2Fwww.bbbank.de%2Fservice%2Fbbbank-impressum.html%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1294%22%5D%2C%22suggested-transport-medium%22%3A%22letter%22%2C%22quality%22%3A%22verified%22%7D)**
> Add 'BBBank eG' (community contribution)

- companies/dzbank.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22dzbank%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22finance%22%5D%2C%22name%22%3A%22DZ%20BANK%20AG%22%2C%22address%22%3A%22Platz%20der%20Republik%5Cn60325%20Frankfurt%20am%20Main%22%2C%22phone%22%3A%22069%207447-01%22%2C%22fax%22%3A%22069%207447-16%2085%22%2C%22email%22%3A%22mail%40dzbank.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.dzbank.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.dzbank.de%2Fcontent%2Fdzbank%2Fde%2Fhome%2Ffooter%2Fdialog%2Fkontakt.html%22%2C%22https%3A%2F%2Fwww.dzbank.de%2Fcontent%2Fdzbank%2Fde%2Fhome%2Ffooter%2Frechtliche-hinweise%2Fimpressum.html%22%2C%22https%3A%2F%2Fwww.dzbank.de%2Fcontent%2Fdzbank%2Fde%2Fhome%2Ffoot …
> Add 'DZ BANK AG' (community contribution)

- companies/fileee.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22fileee%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22name%22%3A%22fileee%20GmbH%22%2C%22address%22%3A%22Windthorststra%C3%9Fe%2068%5Cn48143%20M%C3%BCnster%5CnDeutschland%22%2C%22phone%22%3A%22%2B49%20251%2032368309%22%2C%22email%22%3A%22datenschutz%40fileee.com%22%2C%22web%22%3A%22https%3A%2F%2Fwww.fileee.com%2Fdatenschutzbestimmungen%22%2C%22sources%22%3A%5B%22Website%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1522%22%5D%2C%22quality%22%3A%22verified%22%7D )**
> Add 'fileee GmbH' (community contribution)

- companies/nativo.json
> Restore Nativo Email as it's working again 

- companies/deutscher-motoryachtverband-e-v-dmyv.json
- companies/deutscher-motoryachtverband.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22deutscher-motoryachtverband-e-v-dmyv%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22school%22%2C%22nonprofit%22%2C%22public%20body%22%2C%22travel%22%2C%22entertainment%22%5D%2C%22name%22%3A%22Deutscher%20Motoryachtverband%20e.V.%20(DMYV)%22%2C%22address%22%3A%22Vinckeufer%2012-14%5Cn47119%20Duisburg%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.dmyv.de%2Fimpressum%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1481%22%5D%2C%22quality%22%3A%22verified%22%7D)**
> Add 'Deutscher Motoryachtverband e.V. (DMYV)' (community contribution)

- companies/ftm-freizeit-und-trendmarketing-gmbh-co-kg.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22ftm-freizeit-und-trendmarketing-gmbh-co-kg%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22travel%22%5D%2C%22name%22%3A%22FTM%20Freizeit-%20und%20Trendmarketing%20GmbH%20%26%20Co.%20KG%22%2C%22runs%22%3A%5B%22Daydreams%20(www.daydreams.de)%22%5D%2C%22address%22%3A%22Postfach%201223%5Cn77602%20Offenburg%5CnDeutschland%22%2C%22phone%22%3A%22%2B49%20781%206396100%22%2C%22fax%22%3A%22%2B49%20781%206396101%22%2C%22email%22%3A%22ftm%40datenschutzanfrage.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.daydreams.de%2Fdatenschutz%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1482%22%5D%2C%22suggested-transport-medium%22%3A%22email%22 …
> Add 'FTM Freizeit- und Trendmarketing GmbH & Co. KG' (community contribution)

- companies/arnold-demmerer.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22arnold-demmerer%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22addresses%22%2C%22ads%22%5D%2C%22name%22%3A%22Arnold%2C%20Demmerer%20%26%20Partner%20GmbH%22%2C%22runs%22%3A%5B%22www.zielgruppenmarketing.de%22%5D%2C%22address%22%3A%22AP%3A%20Frau%20Anita%20Demmerer%5CnMotorstr.%2025%5Cn70499%20Stuttgart%5CnDeutschland%22%2C%22phone%22%3A%22%2B49%20711%208871310%22%2C%22email%22%3A%22demmerer%40arnold-demmerer.de%22%2C%22web%22%3A%22http%3A%2F%2Fwww.arnold-demmerer.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fzielgruppenmarketing.de%2F%3Fid%3D116%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1483%22%5D%2C%22suggested-transport- …
> Add 'Arnold, Demmerer & Partner GmbH' (community contribution)

- companies/nrjmobile.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22nrjmobile%22%2C%22relevant-countries%22%3A%5B%22fr%22%5D%2C%22categories%22%3A%5B%22telecommunication%22%5D%2C%22name%22%3A%22NRJ%20Mobile%22%2C%22runs%22%3A%5B%22Bouygues%20Telecom%20Business%20-%20Distribution%22%5D%2C%22address%22%3A%2212%20rue%20Gaillon%20%5Cn75002%20Paris%5CnFrance%22%2C%22phone%22%3A%220969360200%22%2C%22email%22%3A%22informatiquelibertes%40mail.btbd.fr%22%2C%22web%22%3A%22https%3A%2F%2Fwww.nrjmobile.fr%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.nrjmobile.fr%2Ffr%2Finfos_legales.html%22%2C%22https%3A%2F%2Fwww.btbd.fr%2Ffr%2Finfos-legales.html%22%2C%22https%3A%2F%2Fwww.nrjmobile.fr%2Ffr%2Fpdf_v30%2FPolitiqueDonneesPersonnelles_NRJmobile.pdf%2 …
> Add 'NRJ Mobile' (community contribution)

- companies/profil-hannover.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22profil-hannover%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22school%22%5D%2C%22name%22%3A%22PROFIL%20GmbH%22%2C%22address%22%3A%22Gerhardtstra%C3%9Fe%203%5Cn30167%20Hannover%5CnDeutschland%22%2C%22phone%22%3A%22%2B49%20511%201316853%22%2C%22email%22%3A%22rh%40profil-hannover.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.profil-hannover.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.profil-hannover.de%2Fdatenschutz.html%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1492%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22quality%22%3A%22verified%22%7D)**
> Add 'PROFIL GmbH' (community contribution)

- companies/deezer.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22deezer%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22entertainment%22%5D%2C%22name%22%3A%22Deezer%20S.A.%22%2C%22address%22%3A%2224%20rue%20de%20Calais%5Cn75009%20Paris%5CnFrance%22%2C%22phone%22%3A%22%2B33%201%2084%2025%2025%2000%22%2C%22email%22%3A%22privacy%40deezer.com%22%2C%22web%22%3A%22http%3A%2F%2Fwww.deezer.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.deezer.com%2Flegal%2Flegal%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F718%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1493%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22quality%22%3A%22verified%22%7D)**
> Update 'Deezer S.A.' (community contribution)

- companies/jobcenter-consulting.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22jobcenter-consulting%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5Bnull%5D%2C%22name%22%3A%22Jobcenter%20Consulting%20GmbH%22%2C%22runs%22%3A%5B%22JobNETZWERK%20(www.jobnetzwerk.de)%22%5D%2C%22address%22%3A%22Harkortstra%C3%9Fe%205%5Cn04107%20Leipzig%5CnDeutschland%22%2C%22phone%22%3A%22%2B49%20341%202171794%22%2C%22email%22%3A%22datenschutz%40jobnetzwerk.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.jobcenter-consulting.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.jobnetzwerk.de%2Fjobnet%2Fpt%2Fjnw%2Fdatenschutz.php%3Fsid%3Djnw%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1494%22%5D%2C%22suggested-transport-medium%22%3A%22ema …
> Add 'Jobcenter Consulting GmbH' (community contribution)

- companies/bergische-volksbank.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22bergische-volksbank%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22finance%22%5D%2C%22name%22%3A%22Volksbank%20im%20Bergischen%20Land%20eG%22%2C%22address%22%3A%22Volksbank%20im%20Bergischen%20Land%20eG%5CnTenter%20Weg%201-3%5Cn42897%20Remscheid%20%5CnGermany%22%2C%22phone%22%3A%22%2002191699111%22%2C%22fax%22%3A%2202191699372%22%2C%22email%22%3A%22dialogteam%40voba-ibl.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.bergische-volksbank.de%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.bergische-volksbank.de%2Fservice%2Frechtliche-hinweise%2Fimpressum.html%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1499%22%5D%2C%22suggested-tr …
> Add 'Volksbank im Bergischen Land eG' (community contribution)

- companies/t3n.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22t3n%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22entertainment%22%5D%2C%22name%22%3A%22yeebase%20media%20GmbH%22%2C%22runs%22%3A%5B%22t3n%20%E2%80%93%20Magazin%20f%C3%BCr%20digitales%20Business%20(t3n.de)%22%5D%2C%22address%22%3A%22Kriegerstra%C3%9Fe%2040%5Cn30161%20Hannover%5CnDeutschland%22%2C%22phone%22%3A%22%2B49%205221%208549690%22%2C%22fax%22%3A%22%2B49%205221%208549699%22%2C%22email%22%3A%22datenschutz%40yeebase.com%22%2C%22web%22%3A%22https%3A%2F%2Fwww.yeebase.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Ft3n.de%2Fdatenschutz%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1507%22%5D%2C%22suggested-transport-mediu …
> Update 'yeebase media GmbH' (community contribution)

- companies/energieversorgung-gera-gmbh.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22energieversorgung-gera-gmbh%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22utility%22%5D%2C%22name%22%3A%22Energieversorgung%20Gera%20GmbH%22%2C%22address%22%3A%22De-Smit-Stra%C3%9Fe%2018%5Cn07545%20Gera%22%2C%22fax%22%3A%22%2B49%20365%208561199%22%2C%22quality%22%3A%22verified%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1528%22%5D%7D )**
> Add 'Energieversorgung Gera GmbH' (community contribution)

- companies/ikk-gesund-plus.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22ikk-gesund-plus%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22insurance%22%5D%2C%22name%22%3A%22IKK%20gesund%20plus%22%2C%22address%22%3A%22IKK%20gesund%20plus%5CnUmfassungsstra%C3%9Fe%2085%5Cn39124%20Magdeburg%22%2C%22fax%22%3A%220391%202806-6839%22%2C%22email%22%3A%22info%40ikk-gesundplus.de%22%2C%22quality%22%3A%22verified%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1529%22%5D%7D )**
> Add 'IKK gesund plus' (community contribution)

- companies/telepizza.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22telepizza%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22commerce%22%5D%2C%22name%22%3A%22TELE%20PIZZA%20AG%22%2C%22address%22%3A%22Wittenberger%20Weg%20103%5Cn40593%20D%C3%BCsseldorf%22%2C%22phone%22%3A%22%2B49%20211%20996066%22%2C%22fax%22%3A%22%2B49%20211%209960676%22%2C%22email%22%3A%22info%40telepizza.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.telepizza.de%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.telepizza.de%2Fimpressum%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1532%22%5D%2C%22quality%22%3A%22verified%22%7D )**
> Add 'TELE PIZZA AG' (community contribution)

- templates/en/access-default.txt
- templates/en/access-tracking.txt
- templates/en/admonition.txt
- templates/en/erasure-default.txt
- templates/en/objection-default.txt
- templates/en/rectification-default.txt
Very small improvements to the English wording
> minor English improvements

- companies/oskar-de-gmbh.json
- companies/oskar-de.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22oskar-de-gmbh%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22finance%22%5D%2C%22name%22%3A%22Oskar.de%20GmbH%22%2C%22address%22%3A%22Gartenstra%C3%9Fe%2067%5Cn76135%20Karlsruhe%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.oskar.de%2Fimpressum%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1535%22%5D%2C%22quality%22%3A%22verified%22%7D )**
> Add 'Oskar.de GmbH' (community contribution)

- companies/ttt48.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22ttt48%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22commerce%22%2C%22health%22%5D%2C%22name%22%3A%22TTT-Filmservice%20GmbH%22%2C%22address%22%3A%22R%C3%B6ntgentra%C3%9Fe%204%5Cn67133%20Maxdorf%5CnDeutschland%22%2C%22phone%22%3A%2207131%20-%203828%20998%22%2C%22fax%22%3A%2207131-20392-29%22%2C%22email%22%3A%22shop%40ttt48.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.ttt48.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.ttt48.de%2Fdatenschutz.html%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1544%22%5D%2C%22quality%22%3A%22verified%22%7D )**
> Add 'TTT-Filmservice GmbH' (community contribution)

- companies/clevervital.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22clevervital%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22health%22%5D%2C%22name%22%3A%22Clever%20Vital%22%2C%22address%22%3A%22Eiswerderstra%C3%9Fe%2020%20A%2C%2013585%20Berlin%2C%20Germany%22%2C%22phone%22%3A%22%2B49%2030%2098362968%22%2C%22email%22%3A%22rosemaryy708%40gmail.com%22%2C%22web%22%3A%22https%3A%2F%2Fwww.clevervital.com%2F%22%2C%22sources%22%3A%5B%22Google%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1557%22%5D%2C%22quality%22%3A%22verified%22%7D )**
> Add 'Clever Vital' (community contribution)

- companies/trade-republic-bank-gmbh.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22trade-republic-bank-gmbh%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22name%22%3A%22Trade%20Republic%20Bank%20GmbH%22%2C%22address%22%3A%22Trade%20Republic%20Bank%20GmbH%5CnKastanienallee%2032%5Cn10435%20Berlin%22%2C%22sources%22%3A%5B%22https%3A%2F%2Ftraderepublic.com%2Fde-de%2Fimprint%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1537%22%5D%2C%22quality%22%3A%22verified%22%7D )**
> Add 'Trade Republic Bank GmbH' (community contribution)

- companies/finanzen-net-zero-gmbh.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22finanzen-net-zero-gmbh%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22name%22%3A%22finanzen.net%20zero%20GmbH%22%2C%22address%22%3A%22Gartenstra%C3%9Fe%2067%5CnD-76135%20Karlsruhe%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.finanzen.net%2Fzero%2Fimpressum%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1536%22%5D%2C%22quality%22%3A%22verified%22%7D )**
> Add 'finanzen.net zero GmbH' (community contribution)

- companies/entega-medianet-gmbh.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22entega-medianet-gmbh%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22name%22%3A%22ENTEGA%20Medianet%20GmbH%22%2C%22address%22%3A%22Frankfurter%20Stra%C3%9Fe%20100%5Cn64293%20Darmstadt%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.entega.de%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1541%22%5D%2C%22quality%22%3A%22verified%22%7D )**
> Add 'ENTEGA Medianet GmbH' (community contribution)

- companies/swissad.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22swissad%22%2C%22relevant-countries%22%3A%5B%22ch%22%2C%22de%22%5D%2C%22name%22%3A%22swissad%20GmbH%22%2C%22address%22%3A%22St.%20Gallerstra%C3%9Fe%2049%5Cn9100%20Herisau%5CnSchweiz%22%2C%22phone%22%3A%22%2B41%2071%20886%2030%2020%22%2C%22email%22%3A%22datenschutz%40swissad.net%22%2C%22web%22%3A%22https%3A%2F%2Fswissad.net%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fswissad.net%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1546%22%5D%2C%22quality%22%3A%22verified%22%7D )**
> Add 'swissad GmbH' (community contribution)

- companies/abn-amro.json
- companies/moneyou.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22moneyou%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22finance%22%5D%2C%22name%22%3A%22ABN%20AMRO%20Bank%20N.V.%22%2C%22address%22%3A%22ABN%20AMRO%20Bank%20N.V.%5CnChief%20Privacy%20Officer%5CnGustav%20Mahlerlaan%2010%5Cn1082%20PP%20Amsterdam%5CnNiederlande%22%2C%22email%22%3A%22privacy.office%40nl.abnamro.com%22%2C%22web%22%3A%22https%3A%2F%2Fwww.moneyou.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.moneyou.de%2Fdatenschutz%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1554%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22comments%22%3A%5B%22Moneyou%22%5D%2C%22quality%22%3A%22verified%22%7D )**
> Add 'ABN AMRO Bank N.V.' (community contribution)

- companies/wolt-de.json
- companies/wolt.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_wolt_1638709817846%2Fcompanies%2Fwolt.json )**
> Add 'Wolt Enterprises Deutschland GmbH' (community contribution)

- companies/washingtonpost.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_washingtonpost_1638751503118%2Fcompanies%2Fwashingtonpost.json )**
> Update 'WP Company LLC' (community contribution)

- companies/vivento.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_vivento_1638939216338%2Fcompanies%2Fvivento.json )**
> Update 'Deutsche Telekom AG' (community contribution)

- companies/tier-mobility-de.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_tier-mobility-de_1638787481525%2Fcompanies%2Ftier-mobility-de.json )**
> Update 'Tier Mobility GmbH' (community contribution)

- companies/au-schein-de.json
- companies/au-schein.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22au-schein%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22health%22%5D%2C%22name%22%3A%22Dr.%20Ansay%20AU-Schein%20GmbH%22%2C%22address%22%3A%22Hartungstra%C3%9Fe%2014%5Cn20146%20Hamburg%22%2C%22phone%22%3A%22%2B49%2040%20445589%22%2C%22email%22%3A%22info%40au-schein.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.au-schein.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.dransay.com%2Fdatenschutz%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1551%22%5D%2C%22quality%22%3A%22verified%22%7D )**
> Add 'Dr. Ansay AU-Schein GmbH' (community contribution)

- companies/exclusiv-marketing-gmbh.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22exclusiv-marketing-gmbh%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22entertainment%22%5D%2C%22name%22%3A%22EXCLUSIV%20Marketing%20GmbH%22%2C%22runs%22%3A%5B%22KioskPresse.de%22%5D%2C%22address%22%3A%22Kistlerhofstr.%20170%5Cn81379%20M%C3%BCnchen%5CnDeutschland%22%2C%22phone%22%3A%22%2B49%2089%2021129188%22%2C%22email%22%3A%22datenschutz%40exclusiv-marketing.com%22%2C%22web%22%3A%22https%3A%2F%2Fkioskpresse.de%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fkioskpresse.de%2F_downloads%2F2018-06-28-Datenschutzerklaerung-KP.pdf%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fissues%2F524%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2 …
> Update 'EXCLUSIV Marketing GmbH' (community contribution)

- companies/1blu.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_1blu_1639477995332%2Fcompanies%2F1blu.json )**
> Update '1blu AG' (community contribution)

- companies/burgerking-de.json
- companies/burgerking.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_burgerking_1639766976870%2Fcompanies%2Fburgerking.json )**
> Add 'Burger King' (community contribution)

- companies/monday-com.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_monday-com_1639140411141%2Fcompanies%2Fmonday-com.json )**
> Add 'Monday.com' (community contribution)

- companies/hackclub.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22hackclub%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22school%22%2C%22nonprofit%22%5D%2C%22name%22%3A%22The%20Hack%20Foundation%22%2C%22runs%22%3A%5B%22Hack%20Club%22%5D%2C%22address%22%3A%22The%20Hack%20Foundation%5Cn8605%20Santa%20Monica%20Blvd%20%2386294%5CnWest%20Hollywood%2C%20CA%2090069%22%2C%22web%22%3A%22https%3A%2F%2Fhackclub.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fhackfoundation.org%22%2C%22https%3A%2F%2Fhackclub.com%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1542%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22quality%22%3A%22verified%22%7D )**
> Add 'The Hack Foundation' (community contribution)

- companies/marley-spoon.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_marley-spoon_1638967264955%2Fcompanies%2Fmarley-spoon.json )**
> Add 'Marley Spoon' (community contribution)

- companies/uphold.json
- companies/upwork.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_upwork_1639815751253%2Fcompanies%2Fupwork.json )**
> Update 'Uphold Europe Limited (Uphold group)' (community contribution)

- companies/upwork.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_upwork_1639866679184%2Fcompanies%2Fupwork.json )**
> Add 'Upwork Global Inc.' (community contribution)

- companies/greencell.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_greencell_1639847974892%2Fcompanies%2Fgreencell.json )**
> Add 'CSG S.A.' (community contribution)

- companies/meteor-leserservice.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22meteor-leserservice%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22commerce%22%5D%2C%22name%22%3A%22Helmut%20Silbernagel%20e.K.%22%2C%22runs%22%3A%5B%22Meteor%20Leserservice%22%2C%22Meteor-Verlag%22%5D%2C%22address%22%3A%22Helmut%20Silbernagel%20e.K.%5CnSchirmerweg%202a%5Cn81245%20M%C3%BCnchen%22%2C%22phone%22%3A%22089%20820%2020%20400%22%2C%22fax%22%3A%22089%20820%2020%20405%22%2C%22email%22%3A%22info%40meteor-leserservice.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.meteor-leserservice.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.meteor-leserservice.de%2Fimpressum%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1547%22%5D …
> Add 'Helmut Silbernagel e.K.' (community contribution)

- companies/intan.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22intan%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22commerce%22%5D%2C%22name%22%3A%22intan%20media%20services%20GmbH%22%2C%22address%22%3A%22Blumenhaller%20Weg%2088%2C%2049078%20Osnabr%C3%BCck%22%2C%22phone%22%3A%22%2B49%20541%2040840%22%2C%22fax%22%3A%22%2B49%20541%204084137%22%2C%22email%22%3A%22info%40intan.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.intan.de%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.intan.de%2Fimpressum%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1548%22%5D%2C%22quality%22%3A%22verified%22%7D )**
> Add 'intan media services GmbH' (community contribution)

- companies/moneyfarm-de.json
- companies/moneyfarm.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22moneyfarm%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22finance%22%5D%2C%22name%22%3A%22MFM%20Investment%20GmbH%22%2C%22runs%22%3A%5B%22vaamo%22%2C%22Moneyfarm%22%5D%2C%22address%22%3A%22Mainzer%20Landstra%C3%9Fe%20250-254%5Cn60326%20Frankfurt%20am%20Main%5CnDEUTSCHLAND%22%2C%22phone%22%3A%22%2B49%2069%2038076632%22%2C%22email%22%3A%22service%40moneyfarm.de%22%2C%22web%22%3A%22https%3A%2F%2Fwww.moneyfarm.com%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fwww.moneyfarm.com%2Fde%2Fdatenschutzerklaerung%2F%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1556%22%5D%2C%22suggested-transport-medium%22%3A%22email%22%2C%22quality%22%3A%22 …
> Add 'MFM Investment GmbH' (community contribution)

- companies/kollmann-informatik-gmbh.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22kollmann-informatik-gmbh%22%2C%22relevant-countries%22%3A%5B%22de%22%5D%2C%22categories%22%3A%5B%22credit%20agency%22%5D%2C%22name%22%3A%22Kollmann%20Informatik%20GmbH%22%2C%22address%22%3A%22Brookkehre%2034%5Cn21029%20%20Hamburg%22%2C%22phone%22%3A%22040%2F72410310%22%2C%22fax%22%3A%22040%2F72410311%22%2C%22quality%22%3A%22verified%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F1558%22%5D%7D )**
> Add 'Kollmann Informatik GmbH' (community contribution)

- companies/kirche-jesu-christi-der-heiligen-der-letzten-tage.json
- companies/the-church-of-jesus-christ-of-latter-day-saints.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen%2Fdata%2Fsuggest_kirche-jesu-christi-der-heiligen-der-letzten-tage_1638626271659%2Fcompanies%2Fkirche-jesu-christi-der-heiligen-der-letzten-tage.json.json )**
> Add 'Kirche Jesu Christi der Heiligen der Letzten Tage' (community contribution)

- companies/rossmann.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_rossmann_1639590738806%2Fcompanies%2Frossmann.json )**
> Add 'Rossmann Drogeriemarkt' (community contribution)

- companies/v-partei.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_v-partei_1639663810888%2Fcompanies%2Fv-partei.json )**
> Update 'Partei für Veränderung, Vegetarier und Veganer (V-Partei³)' (community contribution)

- companies/trading212.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_trading212_1639778373099%2Fcompanies%2Ftrading212.json )**
> Add 'Trading 212 Ltd' (community contribution)

- companies/kirchengemeinde-st-lukas-salzgitter-lebenstedt.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_kirchengemeinde-st-lukas-salzgitter-lebenstedt_1639920513408%2Fcompanies%2Fkirchengemeinde-st-lukas-salzgitter-lebenstedt.json )**
> Update 'Kirchengemeinde St. Lukas Salzgitter-Lebenstedt' (community contribution)

- companies/lendermarket.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_lendermarket_1640129156353%2Fcompanies%2Flendermarket.json )**
> Add 'LenderMarket Limited' (community contribution)

- companies/weltbett-de.json
- companies/weltbett.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_weltbett_1640702884349%2Fcompanies%2Fweltbett.json )**
> Add 'Weltbett GmbH' (community contribution)

- companies/bumble.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_bumble_1639999083062%2Fcompanies%2Fbumble.json )**
> Add 'Bumble' (community contribution)

- companies/jobomi.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_jobomi_1640045933910%2Fcompanies%2Fjobomi.json )**
> Add 'Jobomi UG (haftungsbeschränkt)' (community contribution)

- companies/mintos.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_mintos_1640129484484%2Fcompanies%2Fmintos.json )**
> Add 'AS Mintos Marketplace' (community contribution)

- companies/vivobarefoot.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_vivobarefoot_1640174188029%2Fcompanies%2Fvivobarefoot.json )**
> Add 'EOD European Online Distribution GmbH' (community contribution)

- companies/cleverreach.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_cleverreach_1640251502838%2Fcompanies%2Fcleverreach.json )**
> Add 'CleverReach GmbH & Co. KG' (community contribution)

- companies/bet365.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_bet365_1640132510922%2Fcompanies%2Fbet365.json )**
> Add 'Hillside (Sports) ENC' (community contribution)

- companies/shapr3d.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_shapr3d_1641382414344%2Fcompanies%2Fshapr3d.json )**
> Add 'Shapr3D Zrt.' (community contribution)

- companies/pinnacle.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_pinnacle_1640131240965%2Fcompanies%2Fpinnacle.json )**
> Add 'PinBet Malta Ltd' (community contribution)

- companies/invoice-2go.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_invoice-2go_1641382795851%2Fcompanies%2Finvoice-2go.json )**
> Add 'Invoice2go, Inc.' (community contribution)

- companies/nero.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_nero_1640935993242%2Fcompanies%2Fnero.json )**
> Add 'Nero AG' (community contribution)

- companies/gdpr-goflink-com.json
- companies/goflink-com.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_gdpr-goflink-com_1641622806714%2Fcompanies%2Fgdpr-goflink-com.json )**
> Add 'goflink.com' (community contribution)

- companies/biomaris.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_biomaris_1642256335744%2Fcompanies%2Fbiomaris.json )**
> Add 'BIOMARIS GmbH & Co. KG' (community contribution)

- companies/saz.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_saz_1642238848206%2Fcompanies%2Fsaz.json )**
> Add 'SAZ Services AG' (community contribution)

- companies/gartner.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_gartner_1642502503966%2Fcompanies%2Fgartner.json )**
> Add 'Gartner' (community contribution)

- companies/neatnik.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_neatnik_1642553147564%2Fcompanies%2Fneatnik.json )**
> Update 'Neatnik LLC' (community contribution)

- companies/adressen-kaufen.json
- companies/neatnik.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_adressen-kaufen_1642499252188%2Fcompanies%2Fadressen-kaufen.json )**
> Add 'Adressen-kaufen.cc' (community contribution)

- companies/meinvz.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_meinvz_1641973309781%2Fcompanies%2Fmeinvz.json )**
> Add 'poolworks (Germany) Ltd.' (community contribution)

- companies/directscouts.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_directscouts_1641549493517%2Fcompanies%2Fdirectscouts.json )**
> Add 'Direct Scouts GmbH' (community contribution)

- companies/joinclubhouse.json
**[Edit](https://company-json.datenanfragen.de/#!doc=%7B%22slug%22%3A%22joinclubhouse%22%2C%22relevant-countries%22%3A%5B%22all%22%5D%2C%22categories%22%3A%5B%22social%20media%22%5D%2C%22name%22%3A%22Alpha%20Exploration%20Co.%22%2C%22runs%22%3A%5B%22Clubhouse%22%5D%2C%22address%22%3A%22548%20Market%20St%5CnPMB%2072878%5CnSan%20Francisco%2C%20California%2094104-5401%5CnUnited%20States%20of%20America%22%2C%22email%22%3A%22support%40clubhouse.com%22%2C%22web%22%3A%22https%3A%2F%2Fwww.joinclubhouse.com%2F%22%2C%22sources%22%3A%5B%22https%3A%2F%2Fprivacy.clubhouse.com%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F934%22%2C%22https%3A%2F%2Fgithub.com%2Fdatenanfragen%2Fdata%2Fpull%2F937%22%2C%22https%3A%2F%2Fgithub.com%2Fdatena …
> Update 'Alpha Exploration Co.' (community contribution)

- companies/wattpad.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_wattpad_1642821179931%2Fcompanies%2Fwattpad.json )**
> Add 'Wattpad Corp.' (community contribution)

- companies/envivas.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_envivas_1642772424311%2Fcompanies%2Fenvivas.json )**
> Add 'Envivas Krankenversicherung AG' (community contribution)

- companies/mheducation.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_mheducation_1643162581980%2Fcompanies%2Fmheducation.json )**
> Add 'McGraw Hill LLC' (community contribution)

- companies/plastische-chirurgie-muenchen-ms.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_plastische-chirurgie-muenchen-ms_1643060538166%2Fcompanies%2Fplastische-chirurgie-muenchen-ms.json )**
> Add 'Dr. Susanne Morath & Dr. Hendrik Schöll - Plastische und Ästhetische Chirurgie' (community contribution)

- companies/cabify.json
- companies/typeform.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_typeform_1643416209843%2Fcompanies%2Ftypeform.json )**
> Add 'TYPEFORM, S.L.' (community contribution)

- companies/clicksco.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_clicksco_1643275482594%2Fcompanies%2Fclicksco.json )**
> Update 'Clicksco Digital Limited' (community contribution)

- companies/drkrug-nuernberg.json
- companies/drkrug.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_drkrug_1643058879719%2Fcompanies%2Fdrkrug.json )**
> Add 'Dr. Krug & Kollegen' (community contribution)

- companies/trellis-law.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_trellis-law_1644604694040%2Fcompanies%2Ftrellis-law.json )**
> Update 'Trellis Research Inc.' (community contribution)

- companies/vpeh-org.json
- companies/vpeh.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_vpeh_1644247614099%2Fcompanies%2Fvpeh.json )**
> Add 'Verband der privaten Erste Hilfe Schulen e. V.' (community contribution)

- companies/weirauch-org.json
- companies/weirauch.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_weirauch_1643059789550%2Fcompanies%2Fweirauch.json )**
> Add 'Zahnarztpraxis Dres. Weirauch' (community contribution)

- companies/vonmaehlen.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_vonmaehlen_1644393264137%2Fcompanies%2Fvonmaehlen.json )**
> Add 'Vonmählen GmbH' (community contribution)

- companies/stuzubi.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_stuzubi_1644430795030%2Fcompanies%2Fstuzubi.json )**
> Add 'Stuzubi GmbH' (community contribution)

- companies/deutsche-messe.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_deutsche-messe_1644439624643%2Fcompanies%2Fdeutsche-messe.json )**
> Update 'Deutsche Messe AG' (community contribution)

- companies/nextbike.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_nextbike_1644529487275%2Fcompanies%2Fnextbike.json )**
> Add 'nextbike' (community contribution)

- companies/is-its.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_is-its_1644625052098%2Fcompanies%2Fis-its.json )**
> Add 'isits AG International School of IT Security' (community contribution)

- companies/hs-albsig.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_hs-albsig_1644622191990%2Fcompanies%2Fhs-albsig.json )**
> Add 'Hochschule Albstadt- Sigmaringen' (community contribution)

- companies/bondora.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_bondora_1644254307652%2Fcompanies%2Fbondora.json )**
> Add 'Bondora Capital OÜ' (community contribution)

- companies/avira.json
- companies/nortonlifelock.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_nortonlifelock_1645973459337%2Fcompanies%2Fnortonlifelock.json )**
> Add 'NortonLifeLock Inc.' (community contribution)

- companies/best-relations-digital.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_best-relations-digital_1644693794041%2Fcompanies%2Fbest-relations-digital.json )**
> Add 'Best Relations Digital GmbH' (community contribution)

- companies/aseag.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_aseag_1645936000984%2Fcompanies%2Faseag.json )**
> Add 'Aachener Straßenbahn- und Energieversorgungs-AG (ASEAG)' (community contribution)

- companies/grovercom.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_grovercom_1646602548855%2Fcompanies%2Fgrovercom.json )**
> Update 'Grover Group GmbH' (community contribution)

- companies/tinc.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_tinc_1646709912725%2Fcompanies%2Ftinc.json )**
> Add 'The Infrastructure Company GmbH' (community contribution)

- companies/careerbuilder-germany-gmbh.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_careerbuilder-germany-gmbh_1646683913327%2Fcompanies%2Fcareerbuilder-germany-gmbh.json )**
> Add 'CareerBuilder Germany GmbH' (community contribution)

- companies/tidal.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_tidal_1647097158024%2Fcompanies%2Ftidal.json )**
> Add 'Aspiro AB' (community contribution)

- companies/boulderhaus.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_boulderhaus_1644831129516%2Fcompanies%2Fboulderhaus.json )**
> Add 'boulderhaus GmbH' (community contribution)

- companies/better-mail-media.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_better-mail-media_1647253113888%2Fcompanies%2Fbetter-mail-media.json )**
> Update 'Better Mail Media GmbH' (community contribution)

- companies/boulderhaus-darmstadt.json
- companies/boulderhaus.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_boulderhaus_1644831273139%2Fcompanies%2Fboulderhaus.json )**
> Add 'proseil GmbH' (community contribution)

- companies/prevhelp.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_prevhelp_1644831814605%2Fcompanies%2Fprevhelp.json )**
> Add 'sevDesk GmbH' (community contribution)

- companies/decathlon-de.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_decathlon-de_1646674806979%2Fcompanies%2Fdecathlon-de.json )**
> Update 'DECATHLON Deutschland SE & Co. KG' (community contribution)

- companies/verti.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_verti_1645049788477%2Fcompanies%2Fverti.json )**
> Add 'Verti Versicherung AG' (community contribution)

- companies/gebouw-t.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_gebouw-t_1645088566525%2Fcompanies%2Fgebouw-t.json )**
> Add 'Gebouw-T' (community contribution)

- companies/dud-de.json
AZDirect informed me that they got the address from this data broker („Abt. Customer Service” – if you want to add this for a possible letter), so obviously following the data trail would be great here…
As it si clearly a data broker, you may even consider adding it to the list of suggested companies.
> Add Dun & Bradstreet Deutschland GmbH

- companies/telekom-de.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_telekom-de_1645091571838%2Fcompanies%2Ftelekom-de.json )**
> Update 'Telekom Deutschland GmbH' (community contribution)

- companies/bfs-finance.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_bfs-finance_1645300404250%2Fcompanies%2Fbfs-finance.json )**
> Update 'BFS finance GmbH' (community contribution)

- companies/reico-vital.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_reico-vital_1645571631036%2Fcompanies%2Freico-vital.json )**
> Add 'Reico & Partner Vertriebs GmbH' (community contribution)

- companies/iff-gmbh.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_iff-gmbh_1645604332487%2Fcompanies%2Fiff-gmbh.json )**
> Add 'Otto IFF GmbH' (community contribution)

- companies/jumio.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_jumio_1645704690610%2Fcompanies%2Fjumio.json )**
> Add 'Jumio Corporation' (community contribution)

- companies/fast-data-cover-s-l.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_fast-data-cover-s-l_1646223588800%2Fcompanies%2Ffast-data-cover-s-l.json )**
> Add 'Fast Data Cover S.L.' (community contribution)

- companies/praxis-hoehne.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_praxis-hoehne_1646385893466%2Fcompanies%2Fpraxis-hoehne.json )**
> Add 'Praxis Höhne für Kinder- und Jugendpsychiatrie und Psychotherapie' (community contribution)

- companies/proptop.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_proptop_1646602542966%2Fcompanies%2Fproptop.json )**
> Add 'proptop GmbH' (community contribution)

- companies/deutsche-post.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_deutsche-post_1646624307124%2Fcompanies%2Fdeutsche-post.json )**
> Update 'Deutsche Post AG' (community contribution)

- src/checks/record/suggested-medium-exists.ts
> Test if suggested transport medium is defined in the record.

- companies/nationwide-building-society.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_nationwide-building-society_1649336732839%2Fcompanies%2Fnationwide-building-society.json )**
> Add 'Nationwide Building Society' (community contribution)

- companies/zoominfo.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_zoominfo_1649524117773%2Fcompanies%2Fzoominfo.json )**
> Add 'ZoomInfo' (community contribution)

- companies/cognosphere.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_cognosphere_1649582210282%2Fcompanies%2Fcognosphere.json )**
> Add 'Cognosphere Pte. Ltd.' (community contribution)

- companies/solit-kapital.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_solit-kapital_1650704346853%2Fcompanies%2Fsolit-kapital.json )**
> Add 'SOLIT Management GmbH' (community contribution)

- companies/katjes-fassin-gmbh-co-kg.json
- companies/katjes.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_katjes-fassin-gmbh-co-kg_1649658818858%2Fcompanies%2Fkatjes-fassin-gmbh-co-kg.json )**
> Add 'Katjes Fassin GmbH + Co. KG' (community contribution)

- companies/aboalarm.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_aboalarm_1650221601680%2Fcompanies%2Faboalarm.json )**
> Add 'Aboalarm GmbH' (community contribution)

- companies/netgemacht-event-ug-haftungsbeschr-nkt.json
- companies/netgemacht-event.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_netgemacht-event-ug-haftungsbeschr-nkt_1651067955184%2Fcompanies%2Fnetgemacht-event-ug-haftungsbeschr-nkt.json )**
> Add 'NETgemacht EVENT UG (haftungsbeschränkt)' (community contribution)

- companies/digitalriver.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_digitalriver_1651215663451%2Fcompanies%2Fdigitalriver.json )**
> Add 'Digital River Inc.' (community contribution)

- companies/codeanywhere.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_codeanywhere_1651763130856%2Fcompanies%2Fcodeanywhere.json )**
> Add 'Codeanywhere, Inc.' (community contribution)

- companies/kliemannsland.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_kliemannsland_1652131802809%2Fcompanies%2Fkliemannsland.json )**
> Add 'Kliemannsland GmbH' (community contribution)

- companies/padsquad.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_padsquad_1652300192229%2Fcompanies%2Fpadsquad.json )**
> Add 'PadSquad' (community contribution)

- companies/rp-online.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_rp-online_1652417989115%2Fcompanies%2Frp-online.json )**
> Add 'Rheinische Post Verlagsgesellschaft mbH' (community contribution)

- companies/sgd.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_sgd_1652448898698%2Fcompanies%2Fsgd.json )**
> Update 'Studiengemeinschaft Werner Kamprath Darmstadt GmbH' (community contribution)

- companies/apotheke-zur-rose.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_apotheke-zur-rose_1652951412485%2Fcompanies%2Fapotheke-zur-rose.json )**
> Add 'Apotheke Zur Rose' (community contribution)

- companies/slovnaftbajk.json
Hello,
another company suggestion.
Cheers,
Richard
> New company suggestion: Slovnaft Mobility Services, s. r. o.

- companies/bigpoint.json
Hello,
I did not find the Bigpoint GmbH on your list.
Cheers,
Richard
> New company suggestion: Bigpoint GmbH

- companies/consorsfinanz.json
Also, they use a Nextcloud instance for providing that data, but I guess that's not relevant here…
> BNP Paribas: Add explanation on the further progress

- src/checks/record/pass-schema.ts
This did not work on Windows before.
> make path prefix check OS agnostic

- companies/prevhelp.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_prevhelp_1654500463830%2Fcompanies%2Fprevhelp.json )**
> Update 'sevDesk GmbH' (community contribution)

- companies/vvs-de.json
- companies/vvs.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_vvs_1654625313095%2Fcompanies%2Fvvs.json )**
> Add VVS (community contribution)

- companies/autopartservice86.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_autopartservice86_1656487412773%2Fcompanies%2Fautopartservice86.json )**
> Add 'autopartservice86' (community contribution)

- companies/mdr.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_mdr_1653466151176%2Fcompanies%2Fmdr.json )**
> Update 'Mitteldeutscher Rundfunk' (community contribution)

- companies/radio-de.json
- companies/radio.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_radio_1653396068772%2Fcompanies%2Fradio.json )**
> Add 'radio.de GmbH' (community contribution)

- companies/ventla.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_ventla_1653461229890%2Fcompanies%2Fventla.json )**
> Add 'Ventla' (community contribution)

- companies/wise.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_wise_1660061865685%2Fcompanies%2Fwise.json )**
> Update 'Wise Europe SA' (community contribution)

- companies/bag-selection.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_bag-selection_1658986948230%2Fcompanies%2Fbag-selection.json )**
> Add 'Bag Selection' (community contribution)

- companies/conviction-org.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_conviction-org_1659453157127%2Fcompanies%2Fconviction-org.json )**
> Add 'Conviction' (community contribution)

- companies/zap-hosting.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_zap-hosting_1660159474878%2Fcompanies%2Fzap-hosting.json )**
> Add 'ZAP-Hosting GmbH & Co. KG' (community contribution)

- companies/yvolve.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_yvolve_1658752309236%2Fcompanies%2Fyvolve.json )**
> Add 'yvolve GmbH' (community contribution)

- companies/verivox.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_verivox_1661496662603%2Fcompanies%2Fverivox.json )**
> Update 'Verivox GmbH' (community contribution)

- companies/etoro.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_etoro_1661008183064%2Fcompanies%2Fetoro.json )**
> Add 'eToro' (community contribution)

- companies/pradeo.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_pradeo_1661931252076%2Fcompanies%2Fpradeo.json )**
> Add 'https://pradeo.com/' (community contribution)

- companies/linkedin.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_linkedin_1655335307511%2Fcompanies%2Flinkedin.json )**
> Update 'LinkedIn Ireland Unlimited Company' (community contribution)

- companies/rosettastone.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_rosettastone_1658678777317%2Fcompanies%2Frosettastone.json )**
> Add 'Rosetta Stone' (community contribution)

- companies/razer.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_razer_1658680433642%2Fcompanies%2Frazer.json )**
> Add 'Razer' (community contribution)

- companies/dnsimple.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_dnsimple_1662293415859%2Fcompanies%2Fdnsimple.json )**
> Add 'DNSimple Corporation' (community contribution)

- companies/ada-health.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_ada-health_1661965725277%2Fcompanies%2Fada-health.json )**
> Update 'Ada Health GmbH' (community contribution)

- companies/linode.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_linode_1664536494520%2Fcompanies%2Flinode.json )**
> Add 'Linode, LLC' (community contribution)

- companies/mach-co.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_mach-co_1664546990122%2Fcompanies%2Fmach-co.json )**
> Add 'Mach recruitment' (community contribution)

- companies/slotozilla.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_slotozilla_1664215747901%2Fcompanies%2Fslotozilla.json )**
> Add 'Slotozilla' (community contribution)

- companies/springer-nature.json
Add "requested-language": "en"
and mark as "tested"
> Update 'Springer Nature'

- companies/smp-gmbh-co-kg.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_smp-gmbh-co-kg_1665577936396%2Fcompanies%2Fsmp-gmbh-co-kg.json )**
> Update 'SMP GmbH & Co. KG' (community contribution)

- companies/gitlab-com.json
**[Edit in company JSON generator](https://company-json.datenanfragen.de/#!url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatenanfragen-community-edits%2Fdata%2Fsuggest_gitlab-com_1665914508295%2Fcompanies%2Fgitlab-com.json )**
> Update 'GitLab B.V.' (community contribution)
